objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ACV_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACV User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

classes/PreventAssigningWorkToBadResourcesTest.cls
@isTest
public class PreventAssigningWorkToBadResourcesTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account a = TestUtility.createAccount();
        a.Dealership_ID__c = '1';
        insert a;

        Contact c = TestUtility.createContact( a );
        insert c;

        FSL.GlobalAPIS.addStatusTransition( 'New', 'Scheduled' );
        FSLTestUtility.createData( a, 1 );

        ServiceResource testSR = FSLTestUtility.makeResourceData(c);

        ServiceTerritory st = [ SELECT Id, OperatingHoursId FROM ServiceTerritory LIMIT 1 ];
        ServiceTerritoryMember stm = new ServiceTerritoryMember(
            OperatingHoursId = st.OperatingHoursId, 
            ServiceTerritoryId = st.Id, 
            ServiceResourceId = testSR.Id,
            EffectiveStartDate = Date.today().addDays(-1), 
            TerritoryType = 'P'
        );
        insert stm;
    } 

    @IsTest
    static void assignSAToBadResource(){
        ServiceResource srTest = [ SELECT Id FROM ServiceResource LIMIT 1 ];
        ServiceAppointment saTest = [ SELECT Id FROM ServiceAppointment LIMIT 1 ];

        DateTime now = DateTime.now().addMinutes(5);
        saTest.SchedStartTime = now;
        saTest.SchedEndTime = now.addMinutes(30);
        update saTest;

        Boolean checkError = FALSE;
        Test.startTest();
            Contact c = [ SELECT Id, Email FROM Contact LIMIT 1 ];
            c.ACV_User__c = null;
            update c;

            try {
                insert new AssignedResource(
                    ServiceResourceId = srTest.Id,
                    ServiceAppointmentId = saTest.Id
                );
            } catch ( exception e ) {        
                if ( e.getMessage().contains( PreventAssigningWorkToBadResources.INVALID_RESOURCE_CONFIG_ERROR ) ) {
                    checkError = TRUE;
                }
            }
        Test.stopTest();
        
        System.assertEquals( TRUE, checkError );
    }
}