objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Last_90_Days_Bought__c</fullName>
        <description>Field to be deprecated. - MM 11/8/21</description>
        <label>xLast 90 Days Bought</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_90_Days_Sold__c</fullName>
        <description>Field to be deprecated. - MM 11/8/21</description>
        <label>xLast 90 Days Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountSalesPurchasesBatch.cls
global class AccountSalesPurchasesBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Buyer_Dealership__c, Seller_Dealership__C FROM Auction__C WHERE Status__c LIKE \'%_Accepted\' AND (End_Time__c = LAST_N_DAYS:90) ';
        System.debug(query); 
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Auction__C> auctionList = (List<Auction__C>)scope;
		system.debug(auctionList);

        Set<Id> sellerIDs = new Set<Id> ();
        Set<Id> buyerIDs= new Set<Id> ();

        for(Auction__c a : auctionList){
            if (a.Buyer_Dealership__c != null) {
                buyerIDs.add(a.Buyer_Dealership__c);
            }
            if (a.Seller_Dealership__c != null) {
                sellerIDs.add(a.Seller_Dealership__c);
            }
        }

        //Update all the sales made by the seller accounts using the sellerIDs set
        List<Account> sellerList = [SELECT Id, Last_90_Days_Sold__C FROM Account WHERE Id IN :sellerIDs ]; 
        Map<Id, Integer> auctionTotals = new Map<Id, Integer>();

        for(Id x : sellerIDs){
            List<Auction__c> amt = [SELECT Id, Seller_Dealership__C 
                                    FROM Auction__C 
                                    WHERE Status__c LIKE '%_Accepted' 
                                    AND (end_time__c = LAST_N_DAYS:90) 
                                    AND (seller_dealership__C = :x)];
            auctionTotals.put(x,amt.size());
        }
		
        for(Account a : sellerList){
            a.Last_90_Days_Sold__C = auctionTotals.get(a.id); 
        }
        // system.debug(auctionTotals);
        // system.debug(sellerList);
        update sellerList;

        //Update all the purchases over the last 90 days for the dealers in the buyerIds
        List<Account> buyerAccountList = [SELECT Id, Last_90_Days_Bought__c FROM Account WHERE Id IN :buyerIDs ]; 
        Map<Id, Integer> buyerAuctionTotals = new Map<Id, Integer>();

        for(Id x : buyerIDs){
            List<Auction__c> amt = [SELECT Id, Buyer_Dealership__c 
                                    FROM Auction__c 
                                    WHERE Status__c LIKE '%_Accepted'  
                                    AND (end_time__c = LAST_N_DAYS:90) 
                                    AND (buyer_dealership__C = :x)];
            buyerAuctionTotals.put(x,amt.size());
        }

        for(Account a : buyerAccountList){
            a.Last_90_Days_Bought__c = buyerAuctionTotals.get(a.id); 
        }
        // system.debug(buyerAuctionTotals);
        // system.debug(buyerAccountList);
        update buyerAccountList;
    }

    global void finish(Database.BatchableContext BC){
        
    }
}