objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Condition Report ID
This field is populated through the integration. It looks up to the condition report using the unique external Saved Auction Id</description>
        <inlineHelpText>Lookup Field to Condition Report object.</inlineHelpText>
        <label>Condition Report ID</label>
        <referenceTo>Condition_Report__c</referenceTo>
        <relationshipLabel>Auctions</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <description>Pulls down the Dealer ID from Accounts for List view criteria on Auction Obj</description>
        <formula>Seller_Dealership__r.Dealership_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <formula>IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;1&apos; ,&apos;Franchise&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;2&apos; ,&apos;Independent&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;4&apos; ,&apos;Independent - ACV Certified&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;3&apos; ,&apos;Wholesaler&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;Dealer Group (Parent Account)&apos;,&apos;Dealer Group (Parent Account)&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;5&apos; ,&apos;Commercial&apos;,
 &apos;&apos;) 

)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Life_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated with the Inventory Life Cycle the Auction is related to</description>
        <label>Inventory Life Cycle</label>
        <referenceTo>Inventory_Life_Cycle__c</referenceTo>
        <relationshipLabel>Auctions</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Auction__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is used to mark the auction as being the most recent auction for a specific VIN.</description>
        <label>Most Recent Auction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Dealer_ID__c</fullName>
        <formula>Seller_Dealership__r.Dealership_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seller Dealer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Report__c.object
<CustomObject>
    <description>This object receives fields from the condition_report, condition_report_document and saved_auctions tables in ACV Tools.</description>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CR_Doc_CreateDate__c</fullName>
        <description>condition_report_document.created</description>
        <label>CR Doc CreateDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealer_Id__c</fullName>
        <description>Holds the Dealer Id of the Dealership attached</description>
        <formula>Dealership__r.Dealership_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>This holds the API name of the Dealership&apos;s Dealer Type</description>
        <formula>TEXT(Dealership__r.Dealer_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is brought in through integration with acv-api, it is the dealer_id associated with the Saved_Auction_id</description>
        <label>Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory_Life_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated with the Inventory Life Cycle record this CR Relates to.</description>
        <label>Inventory Life Cycle</label>
        <referenceTo>Inventory_Life_Cycle__c</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <description>saved_auctions.vin</description>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report</label>
    <nameField>
        <label>Condition Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inventory_Life_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Id__c</fullName>
        <description>Holds the Dealer Id of the Client</description>
        <formula>Client__r.Dealership_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>This field translates the API Name into the type name. Will need to be updated if the Account field is updated.</description>
        <formula>CASE( TEXT(Client__r.Dealer_Type__c) , 
&apos;1&apos;,&apos;Franchise&apos;,
&apos;2&apos;,&apos;Independent&apos;,
&apos;4&apos;,&apos;Independent - ACV Certified&apos;,
&apos;3&apos;,&apos;Wholesaler&apos;,
&apos;5&apos;,&apos;Commercial&apos;,
TEXT(Client__r.Dealer_Type__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the most recent Auction that the car has been listed under. This helps populate some formula fields on Inventory Life Cycle.</description>
        <label>Most Recent Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Inventory Life Cycles</relationshipLabel>
        <relationshipName>Inventory_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Condition_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will stay consistent with the CR related to the Auction. If no Auction yet, this will be the Most Recent CR created</description>
        <inlineHelpText>This field will stay consistent with the CR related to the Auction. If no Auction yet, this will be the Most Recent CR created</inlineHelpText>
        <label>Most Recent Condition Report</label>
        <referenceTo>Condition_Report__c</referenceTo>
        <relationshipLabel>Inventory Life Cycles</relationshipLabel>
        <relationshipName>Inventory_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Work_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is linked to the most recent Work Order Line Item for an Inventory Life Cycle</description>
        <label>Most Recent Work Order Line Item</label>
        <referenceTo>WorkOrderLineItem</referenceTo>
        <relationshipLabel>Inventory Life Cycles</relationshipLabel>
        <relationshipName>Inventory_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <description>Vin Number of the Vehicle. This will be populated either when a WOLI is created or a Vehicle is created.</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Inventory Life Cycles</relationshipLabel>
        <relationshipName>Inventory_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Life Cycle</label>
    <nameField>
        <label>Inventory Life Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Life Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Dealer_Id__c</fullName>
        <description>Holds the Dealer Id from the Work Order&apos;s Account.</description>
        <formula>WorkOrder.Account.Dealership_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>Holds the Dealer Type API Name from Account</description>
        <formula>TEXT(WorkOrder.Account.Dealer_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Life_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated with the Inventory Life Cycle that it relates to.</description>
        <label>Inventory Life Cycle</label>
        <referenceTo>Inventory_Life_Cycle__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Work Type Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InventoryLifeCycleHelperTest.cls
@isTest
/**
 * Test class logic for InventoryLifeCycleHelperTest
 * @author James Andre LaCour
 */
public class InventoryLifeCycleHelperTest{
    /****************Class Variables************************/
    public static final Id STANDARD_ACCOUNT_RTID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Standard').getRecordTypeId();
    public static final String ACCOUNT_WITH_DEALER_ID_NAME = 'Test Dealership With DealerId';
    public static final String TEST_VIN = '1234abcdVINtest';
    public static final string TEST_DEALER_ID = 'dealerId123';
    /****************Test Setup****************************/
    /**
     * Creates Test Data
     * @return void
     */
    @TestSetup
    public static void createData(){
        List<Account> accountList = New List<Account>();
        Account acct = TestUtility.createAccount();
        acct.Name = ACCOUNT_WITH_DEALER_ID_NAME;
        acct.RecordTypeId = STANDARD_ACCOUNT_RTID;
        acct.Dealership_Id__c = TEST_DEALER_ID;
        acct.Dealer_Type__c = InventoryLifeCycleHelper.DEALER_TYPE_LABEL_TO_API_NAME_MAP_TO_PROCESS.values()[0];
        acct.Legal_Name__c = ACCOUNT_WITH_DEALER_ID_NAME;

        accountList.add(acct);
        insert accountList;
        
        Vehicle__c v = new Vehicle__c();
        v.VIN__c = TEST_VIN;
        insert v;

        FSLTestUtility.createAllStructureWithParentST( 'Buffalo' , '14209' );

        WorkType wt = [SELECT Id, Work_Type_Unique_ID__c, EstimatedDuration FROM WorkType WHERE Work_Type_Unique_ID__c = 'inspection' LIMIT 1];

        WorkOrder wo = new WorkOrder (AccountId = accountList[0].id, status = 'New', WorkTypeId = wt.id);
        insert wo;

        WorkOrderLineItem woli = new WorkOrderLineItem();
        woli.WorkTypeId = wt.Id;
        woli.WorkOrderId = wo.Id;
        woli.VIN__c = TEST_VIN;
        woli.Vehicle__c = v.Id;
        woli.Duration = 30.0;
        woli.DurationType = 'Minutes';
        insert woli;

        Condition_Report__c cr = new Condition_Report__c();
        cr.Dealership__c = acct.Id;
        cr.VIN__c = TEST_VIN;
        cr.Vehicle__c = v.Id;
        insert cr;

        Auction__c auc = new Auction__c();
        auc.Seller_Dealership__c = acct.Id;
        auc.VIN__c = TEST_VIN;
        auc.Condition_Report_ID__c = cr.Id;
        auc.Vehicle_id__c = v.Id;
        insert auc;

        cr.Auction__c = auc.Id;
        update cr;        
    }
    /****************Test Methods***************************/
    /**
     * Expecting an organized Map of Key to ILC based
     * @return void
     */
    public static testMethod void createILCKeyMap(){
        List<Inventory_Life_Cycle__c> ilc = [ SELECT Id, Key__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 1, ilc.size(), 'Only 1 Inventory Life Cycle should be created' );
        String key = TEST_DEALER_ID + TEST_VIN;
        Map<String,Inventory_Life_Cycle__c> ilcMap = InventoryLifeCycleHelper.createILCKeyMap( ilc );
        System.assertEquals( 1, ilcMap.size(), 'Map should only have 1 value in it' );
        System.assertEquals( ilcMap.get(key), ilc[0], 'Key value not found' );
    }
    /**
     * Expecting Inventory Life Cycle Records with the
     * updated values via the map and an Id attached
     * @return void
     */
    public static testMethod void updateExistingILCs(){
        List<Condition_Report__c> cr = [ SELECT Id, Dealer_Id__c, Vehicle__c, Dealership__c, Auction__c, VIN__c, Inventory_Life_Cycle__c FROM Condition_Report__c ];
        System.assertEquals( 1, cr.size(), 'Only one Condition Report should be found' );
        List<Inventory_Life_Cycle__c> ilcList = InventoryLifeCycleHelper.updateExistingILCs( new Map<Id,Condition_Report__c>(cr), 'Inventory_Life_Cycle__c','CR_Doc_CreateDate__c' );
        System.assertEquals( 1, ilcList.size(), 'Only one ILC should be returned');
        for( String ilcField : InventoryLifeCycleHelper.CR_FIELD_MAP.keySet() ){
            System.assertEquals( cr[0].get(InventoryLifeCycleHelper.CR_FIELD_MAP.get(ilcField)), ilcList[0].get(ilcField), ilcField + ' did not properly map from ' + InventoryLifeCycleHelper.CR_FIELD_MAP.get(ilcField) );
        }
        System.assertEquals( cr[0].Inventory_Life_Cycle__c, ilcList[0].Id, 'The ILC Id should be attached as we are updating it');
    }
    /**
     * Expecting a list of Inventory Life Cycle Records based
     * on the mappings
     * @return void
     */
    public static testMethod void createNewILCs(){
        List<Condition_Report__c> cr = [ SELECT Id, Dealer_Id__c, Vehicle__c, Dealership__c, Auction__c, VIN__c FROM Condition_Report__c ];
        System.assertEquals( 1, cr.size(), 'Only one Condition Report should be found' );
        List<Inventory_Life_Cycle__c> ilcList = InventoryLifeCycleHelper.createNewILCs( cr );
        System.assertEquals( 1, ilcList.size(), 'Only one ILC should be returned');
        for( String ilcField : InventoryLifeCycleHelper.CR_FIELD_MAP.keySet() ){
            System.assertEquals( cr[0].get(InventoryLifeCycleHelper.CR_FIELD_MAP.get(ilcField)), ilcList[0].get(ilcField), ilcField + ' did not properly map from ' + InventoryLifeCycleHelper.CR_FIELD_MAP.get(ilcField) );
        }
    }
    /**
     * Expecting a single Inventory Life Cycle Record based
     * on the mappings
     * @return void
     */
    public static testMethod void createILC(){
        List<Condition_Report__c> cr = [ SELECT Id, Vehicle__c, Dealer_Id__c, Dealership__c, Auction__c, VIN__c FROM Condition_Report__c ];
        System.assertEquals( 1, cr.size(), 'Only one Condition Report should be found' );
        String key = TEST_DEALER_ID + TEST_VIN;
        Inventory_Life_Cycle__c ilc = InventoryLifeCycleHelper.createILC( cr[0], key );
        for( String ilcField : InventoryLifeCycleHelper.CR_FIELD_MAP.keySet() ){
            System.assertEquals( cr[0].get(InventoryLifeCycleHelper.CR_FIELD_MAP.get(ilcField)), ilc.get(ilcField), ilcField + ' did not properly map from ' + InventoryLifeCycleHelper.CR_FIELD_MAP.get(ilcField) );
        }
    }
    /**
     * Expecting the correct Key returned from the function
     * dependent on what sobject is passed in
     * @return void
     */
    public static testMethod void getKey(){
        String key = TEST_DEALER_ID + TEST_VIN;
        List<Auction__c> auc = [ SELECT Id, Seller_Dealer_Id__c, VIN__c FROM Auction__c ];
        List<Condition_Report__c> cr = [ SELECT Id, VIN__c, Dealer_Id__c FROM Condition_Report__c ];
        List<WorkOrderLineItem> woli = [ SELECT Id, VIN__c, Dealer_Id__C FROM WorkOrderLineItem ];
        List<Inventory_Life_Cycle__c> ilc = [ SELECT Id, Key__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 1, auc.size(), 'Only 1 Auction should be created' );
        System.assertEquals( 1, cr.size(), 'Only 1 Condition Report should be created' );
        System.assertEquals( 1, woli.size(), 'Only 1 WorkOrderLineItem should be created' );
        System.assertEquals( 1, ilc.size(), 'Only 1 Inventory Life Cyle should be created' );
        System.assertEquals( key, InventoryLifeCycleHelper.getKey(auc[0]), 'Incorrect Key returned for Auction' );
        System.assertEquals( key, InventoryLifeCycleHelper.getKey(cr[0]), 'Incorrect Key returned for Condition Report' );
        System.assertEquals( key, InventoryLifeCycleHelper.getKey(woli[0]), 'Incorrect Key returned for Work Order Line Item' );
        System.assertEquals( key, InventoryLifeCycleHelper.getKey(ilc[0]), 'Incorrect Key returned for Inventory Life Cycle' );
    }
    /**
     * Expecting the population of the Invetory Life Cycle field
     * on the SObject with the existing ILC
     * @return void
     */
    public static testMethod void processCurrentRecordPopulation(){
        List<Condition_Report__c> crList = [ SELECT Id, Dealership__c, VIN__c, Inventory_Life_Cycle__c FROM Condition_Report__c ];
        System.assertEquals( 1, crList.size(), 'A Condition Report was not found' );
        Id ilcId = crList[0].Inventory_Life_Cycle__c;
        for( Condition_Report__c cr: crList ){
            cr.Inventory_Life_Cycle__c = null;
        }
        update crList;
        Map<Id,Account> acctMap = new Map<Id,Account>( [ SELECT Id, Dealership_Id__c FROM Account ] );
        Map<String,List<SObject>> groupedRecordsMap = InventoryLifeCycleHelper.groupIlcKeyToSObjectList(crList, acctMap, 'Dealership__c', 'VIN__c');
        List<SObject> recordsUpdated = InventoryLifeCycleHelper.processCurrentRecordPopulation(groupedRecordsMap, 'Inventory_Life_Cycle__c' );
        System.assertEquals( 1, recordsUpdated.size(), 'One record should\'ve been updated');
        System.assertEquals( ilcId, recordsUpdated[0].get('Inventory_Life_Cycle__c'), 'Condition Report ILC field should\'ve been populated with the ILC');
    }
    /**
     * Expecting a grouped Map of Key to List of records associated with that key
     * @return void
     */
    public static testMethod void groupIlcKeyToSObjectList(){
        String key = TEST_DEALER_ID + TEST_VIN;
        List<Condition_Report__c> crList = [ SELECT Id, Dealership__c, VIN__c FROM Condition_Report__c ];
        Map<Id,Account> acctMap = new Map<Id,Account>( [ SELECT Id, Dealership_Id__c FROM Account ] );
        Map<String,List<SObject>> groupedRecordsMap = InventoryLifeCycleHelper.groupIlcKeyToSObjectList(crList, acctMap, 'Dealership__c', 'VIN__c');
        System.assertEquals( 1, groupedRecordsMap.size(), 'The map should only have one value' );
        System.assertEquals( 1, groupedRecordsMap.get(key).size(), 'For our key, there should only be one value in the list returned' );
    }
    /**
     * Expecting the correct API name of the ilc most recent field
     * based on what sobj is passed in
     * @return void
     */
    public static testMethod void getMostRecentAPINameField(){
        List<Auction__c> auc = [ SELECT Id, Seller_Dealer_Id__c, VIN__c FROM Auction__c ];
        List<Condition_Report__c> cr = [ SELECT Id, VIN__c, Dealer_Id__c FROM Condition_Report__c ];
        List<WorkOrderLineItem> woli = [ SELECT Id, VIN__c, Dealer_Id__C FROM WorkOrderLineItem ];
        System.assertEquals( 1, auc.size(), 'Only 1 Auction should be created' );
        System.assertEquals( 1, cr.size(), 'Only 1 Condition Report should be created' );
        System.assertEquals( 1, woli.size(), 'Only 1 WorkOrderLineItem should be created' );
        System.assertEquals( 'Most_Recent_Auction__c', InventoryLifeCycleHelper.getMostRecentAPINameField(auc[0]), 'Incorrect Key returned for Auction' );
        System.assertEquals( 'Most_Recent_Condition_Report__c', InventoryLifeCycleHelper.getMostRecentAPINameField(cr[0]), 'Incorrect Key returned for Condition Report' );
        System.assertEquals( 'Most_Recent_Work_Order_Line_Item__c', InventoryLifeCycleHelper.getMostRecentAPINameField(woli[0]), 'Incorrect Key returned for Work Order Line Item' );
    }
}