objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <description>The most recent resale number for the account.</description>
        <label>Permit/Resale Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Docs_Uploaded__c</fullName>
        <description>The date/time that all required docs were uploaded for this account.</description>
        <label>Required Docs Uploaded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <label>Permit/Resale Number</label>
        <type>TextArea</type>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State_Abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

classes/DealerDocTimeStampBatchTest.cls
@isTest
public class DealerDocTimeStampBatchTest {
    public static final Id licenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id resaleId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();

    public static DateTime utcToEST(DateTime utcCreatedDate) {
        Integer Day = utcCreatedDate.Day();
        Integer Month = utcCreatedDate.Month();
        Integer Year = utcCreatedDate.Year();
        Integer Hour = utcCreatedDate.Hour(); //so this is showing up as the EST hour, but the value in the field at the end is UTC still
        Integer estHour = Hour - 5; //i don't know how this works, but it works
        Integer Minute = utcCreatedDate.Minute();
        Integer Second = utcCreatedDate.Second();
        DateTime correctedDateTime = DateTime.newInstance(Year, Month, Day, estHour, Minute, Second); //so when it creates the new instance, it makes it UTC. fun.
        //System.debug(correctedDateTime);
        return correctedDateTime;
    }

    @TestSetup
    static void makeData(){
        Account newAcct = new Account(Name = 'Test', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Test', Dealer_Type__c='1');
        insert newAcct;
    }

    @isTest
    static void licenseInSpecialState() { //making sure the date of the license is stamped correctly and code isn't looking for a resale cert
        Account testAcct = [SELECT Id FROM Account];
        Date expDate = System.Today().addMonths(5);
        Dealer_Docs__c testDoc = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '11111', Expiration_Date__c = expDate));
        insert testDoc;

        //run batch
        Test.startTest();
            SchedulableContext sc = null;
            DealerDocTimeStampBatch batch = new DealerDocTimeStampBatch();
            Batch.execute(sc);
        Test.stopTest();

        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account];
        System.assertNotEquals(null, testAcct.Required_Docs_Uploaded__c);
    }

    @isTest
    static void licenseAndResaleNotSpecial() { //making sure the code takes the date of the more recent doc
        Account testAcct = [SELECT Id FROM Account];
        Date expDate = System.Today().addMonths(5);
        DateTime createdDate = System.Now().addHours(-3);
        Dealer_Docs__c testDoc1 = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'FL', License_Number__c = '11111', Expiration_Date__c = expDate));
        insert testDoc1;
        Test.setCreatedDate(testDoc1.Id, createdDate); //can i do this?
        Dealer_Docs__c testDoc2 = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '22222', Expiration_Date__c = expDate));
        insert testDoc2; //doing two inserts so the created dates will be slightly different

        //run batch
        Test.startTest();
            SchedulableContext sc = null;
            DealerDocTimeStampBatch batch = new DealerDocTimeStampBatch();
            Batch.execute(sc);
        Test.stopTest();

        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account];
        testDoc1 = [SELECT Id, CreatedDate FROM Dealer_Docs__c WHERE RecordType.DeveloperName = 'Dealer_License'];
        System.assertNotEquals(null, testAcct.Required_Docs_Uploaded__c);
        System.assertEquals(true, (testAcct.Required_Docs_Uploaded__c > utcToEst(testDoc1.CreatedDate)));
    }

    @isTest
    static void onlyAResale() { //making sure the code doesn't stamp a date because the other doc is missing
        Account testAcct = [SELECT Id FROM Account];
        Date expDate = System.Today().addMonths(5);
        Dealer_Docs__c testDoc = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '22222', Expiration_Date__c = expDate));
        insert testDoc;

        //run batch
        Test.startTest();
            SchedulableContext sc = null;
            DealerDocTimeStampBatch batch = new DealerDocTimeStampBatch();
            Batch.execute(sc);
        Test.stopTest();

        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account];
        System.assertEquals(null, testAcct.Required_Docs_Uploaded__c);
    }

    @isTest
    static void multiplesOfBothDocs() { //making sure the code takes the date of the first doc of its kind, but the second of the two required (that makes no sense)
        Account testAcct = [SELECT Id FROM Account];
        Date expDate = System.Today().addMonths(5);
        DateTime createdDate1 = System.Now().addHours(-6);
        DateTime createdDate2 = System.Now().addHours(-4);
        DateTime createdDate3 = System.Now().addHours(-2);
        Dealer_Docs__c testDoc1 = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'FL', License_Number__c = '11111', Expiration_Date__c = expDate));
        insert testDoc1;
        Test.setCreatedDate(testDoc1.Id, createdDate1);
        Dealer_Docs__c testDoc2 = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '22222', Expiration_Date__c = expDate));
        insert testDoc2;
        Test.setCreatedDate(testDoc2.Id, createdDate2);
        Dealer_Docs__c testDoc3 = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'FL', License_Number__c = '33333', Expiration_Date__c = expDate));
        insert testDoc3;
        Test.setCreatedDate(testDoc3.Id, createdDate3);
        Dealer_Docs__c testDoc4 = (new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '44444', Expiration_Date__c = expDate));
        insert testDoc4; // doing four inserts so the created dates are all different

        //run batch
        Test.startTest();
            SchedulableContext sc = null;
            DealerDocTimeStampBatch batch = new DealerDocTimeStampBatch();
            Batch.execute(sc);
        Test.stopTest();

        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account];
        testDoc1 = [SELECT Id, CreatedDate FROM Dealer_Docs__c WHERE RecordType.DeveloperName = 'Dealer_License' AND License_Number__c = '11111'];
        testDoc3 = [SELECT Id, CreatedDate FROM Dealer_Docs__c WHERE RecordType.DeveloperName = 'Dealer_License' AND License_Number__c = '33333'];
        System.assertNotEquals(null, testAcct.Required_Docs_Uploaded__c);
        System.assertEquals(true, (testAcct.Required_Docs_Uploaded__c > utcToEST(testDoc1.CreatedDate))); //greater than the created date of the first doc
        System.assertEquals(true, (testAcct.Required_Docs_Uploaded__c < utcToEST(testDoc3.CreatedDate))); //less than the created date of the third doc
    }
}