objects/Account.object
<CustomObject
     >
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Relaunch_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Auction ID for the relaunched auction</description>
        <label>Auction Relaunch ID</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases (Auction Relaunch ID)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/AccountMergeDependentRecordError.cls
public class AccountMergeDependentRecordError extends TriggerInterface {


    Id orgRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();

    public override void beforeDelete(Map<Id,SObject> incomingMap) {

        Map<Id, Account> mergeAccMap = (Map<Id, Account>)incomingMap;
        Map<Id, Account> accCheckMap = new Map<Id, Account>([Select Id, RecordTypeId, (Select Id From Auctions__r), (Select Id From BuyerAuctions__r), (Select Id From Cases), (Select Id From Cases1__r) 
        From Account Where Id In :mergeAccMap.keyset()]);
        
        for (Account a : accCheckMap.values()) {
            if (a.RecordTypeId == orgRecordTypeId && AccountMergeDependentRecordCheck.AccountMergeDependentRecordCheck(a)) {
                mergeAccMap.get(a.id).adderror('This Account has an Auction or Case record associated with it and cannot be merged.');
            }
        }
    }
}