objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <description>The most recent resale number for the account.</description>
        <label>Permit/Resale Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IST_Account_Manager_Email__c</fullName>
        <description>Email of the IST Account Manager</description>
        <formula>Account.IST_Account_Owner__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IST Account Manager Email</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IST_Account_Manager_Email__c</fullName>
        <description>IST Account Manager&apos;s email</description>
        <label>IST Account Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <label>Permit/Resale Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TM_Email__c</fullName>
        <label>TM Email</label>
        <type>Email</type>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State_Abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NY</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

classes/ISTAccountEmailBatchTest.cls
@isTest
public class ISTAccountEmailBatchTest {
    public static final Id licenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id resaleId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();

    @isTest
    static void batchTestIST() {
        //will i need a user? or can i fudge with like test@test.com for an email?
        //need some accounts - 4? one with multiple docs, two with one doc, one correct and one not, and one account with no docs
        List<Account> accountList = new List<Account>();
        accountList.add(new Account(Name = 'Account1', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account1', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Name = 'Account2', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account2', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Name = 'Account3', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account3', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Name = 'Account4', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account4', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        insert accountList;

        Contact c = TestUtility.createContact(accountList[0]);
        insert c;

        List<Affiliation__c> affList = new List<Affiliation__c>();
        Affiliation__c aff = TestUtility.createAffiliation( accountList[0], c );
        affList.add( aff );
        Affiliation__c aff1 = TestUtility.createAffiliation( accountList[1], c );
        affList.add( aff1 );
        Affiliation__c aff2 = TestUtility.createAffiliation( accountList[2], c );
        affList.add( aff2 );
        Affiliation__c aff3 = TestUtility.createAffiliation( accountList[3], c );
        affList.add( aff3 );
        insert affList;
        //make four dates - i'm literally only doing this so i have a way to order the docs at the end
        Date expDate7 = System.Today().addMonths(7);
        Date expDate6 = System.Today().addMonths(6);
        Date expDate5 = System.Today().addMonths(5);
        Date expDate4 = System.Today().addMonths(4);
        //4 docs
        List<Dealer_Docs__c> docList = new List<Dealer_Docs__c>();
        //need some docs for one of the accounts with the correct IST account email, one without
        docList.add(new Dealer_Docs__c(Account__c = accountList[0].Id, RecordTypeId = licenseId, Document_State__c = 'FL', License_Number__c = '11111', Expiration_Date__c = expDate7, Compliant__c = true));
        docList.add(new Dealer_Docs__c(Account__c = accountList[0].Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '22222', Expiration_Date__c = expDate6, Compliant__c = true));
        //need a doc for an account that will be correct
        docList.add(new Dealer_Docs__c(Account__c = accountList[1].Id, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '33333', Expiration_Date__c = expDate5, Compliant__c = true));
        //need a doc for an account that will be incorrect
        docList.add(new Dealer_Docs__c(Account__c = accountList[2].Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '44444', Expiration_Date__c = expDate4, Compliant__c = true));
        insert docList;
        //will have to try and update the email field to the incorrect info after because it will auto-populate correctly
        for (Dealer_Docs__c d : docList) {
            if (d.License_Number__c == '11111' || d.Permit_Resale_Number__c == '44444') {
                d.IST_Account_Manager_Email__c = 'test@test.com'; //going to try this to see if i can get away with not creating a test user
            }
        }
        //update docs
        update docList;

        //run batch
        //start test
        Test.startTest();
        //run batch
            SchedulableContext sc = null;
            ISTAccountEmailBatch batch = new ISTAccountEmailBatch();
            Batch.execute(sc);
        //stop test
        Test.stopTest();

        //query
        List<Dealer_Docs__c> checkDocList = [SELECT Id, RecordTypeId, License_Number__c, Permit_Resale_Number__c, IST_Account_Manager_Email__c, TM_Email__c FROM Dealer_Docs__c ORDER BY Expiration_Date__c DESC];
        //system.asserts
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[0].IST_Account_Manager_Email__c);
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[1].IST_Account_Manager_Email__c);
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[2].IST_Account_Manager_Email__c);
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[3].IST_Account_Manager_Email__c);
    }

    @isTest
    static void batchTestTM() {
        //will i need a user? or can i fudge with like test@test.com for an email?
        //need some accounts - 4? one with multiple docs, two with one doc, one correct and one not, and one account with no docs
        List<Account> accountList = new List<Account>();
        accountList.add(new Account(Name = 'Account1', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account1', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Name = 'Account2', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account2', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Name = 'Account3', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account3', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Name = 'Account4', IST_Account_Owner__c = UserInfo.getUserId(), legal_name__c='Account4', Dealer_Type__c='1', phone='1234567890', BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        insert accountList;

        Contact c = TestUtility.createContact(accountList[0]);
        insert c;

        List<Affiliation__c> affList = new List<Affiliation__c>();
        Affiliation__c aff = TestUtility.createAffiliation( accountList[0], c );
        affList.add( aff );
        Affiliation__c aff1 = TestUtility.createAffiliation( accountList[1], c );
        affList.add( aff1 );
        Affiliation__c aff2 = TestUtility.createAffiliation( accountList[2], c );
        affList.add( aff2 );
        Affiliation__c aff3 = TestUtility.createAffiliation( accountList[3], c );
        affList.add( aff3 );
        insert affList;
        //make four dates - i'm literally only doing this so i have a way to order the docs at the end
        Date expDate7 = System.Today().addMonths(7);
        Date expDate6 = System.Today().addMonths(6);
        Date expDate5 = System.Today().addMonths(5);
        Date expDate4 = System.Today().addMonths(4);
        //4 docs
        List<Dealer_Docs__c> docList = new List<Dealer_Docs__c>();
        //need some docs for one of the accounts with the correct IST account email, one without
        docList.add(new Dealer_Docs__c(Account__c = accountList[0].Id, RecordTypeId = licenseId, Document_State__c = 'FL', License_Number__c = '11111', Expiration_Date__c = expDate7, Compliant__c = true));
        docList.add(new Dealer_Docs__c(Account__c = accountList[0].Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '22222', Expiration_Date__c = expDate6, Compliant__c = true));
        //need a doc for an account that will be correct
        docList.add(new Dealer_Docs__c(Account__c = accountList[1].Id, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '33333', Expiration_Date__c = expDate5, Compliant__c = true));
        //need a doc for an account that will be incorrect
        docList.add(new Dealer_Docs__c(Account__c = accountList[2].Id, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '44444', Expiration_Date__c = expDate4, Compliant__c = true));
        insert docList;
        //will have to try and update the email field to the incorrect info after because it will auto-populate correctly
        for (Dealer_Docs__c d : docList) {
            if (d.License_Number__c == '11111' || d.Permit_Resale_Number__c == '44444') {
                d.TM_Email__c = 'test@test.com'; //going to try this to see if i can get away with not creating a test user
            }
        }
        //update docs
        update docList;

        //run batch
        //start test
        Test.startTest();
        //run batch
            SchedulableContext sc = null;
            ISTAccountEmailBatch batch = new ISTAccountEmailBatch();
            Batch.execute(sc);
        //stop test
        Test.stopTest();

        //query
        List<Dealer_Docs__c> checkDocList = [SELECT Id, RecordTypeId, License_Number__c, Permit_Resale_Number__c, IST_Account_Manager_Email__c, TM_Email__c FROM Dealer_Docs__c ORDER BY Expiration_Date__c DESC];
        //system.asserts
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[0].TM_Email__c);
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[1].TM_Email__c);
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[2].TM_Email__c);
        System.assertEquals(UserInfo.getUserEmail(), checkDocList[3].TM_Email__c);
    }

    //@isTest
    static void bulkTest() {
        //create a date
        Date past = System.Today().addMonths(-5);
        //create some accounts
        List<Account> accountList = new List<Account>();
        for (Integer i = 0; i < 50; i ++) {
            accountList.add(new Account(Name = 'Account' + i, legal_Name__c='Account' + i, dealer_type__c='1',phone='1234567890',IST_Account_Owner__c = UserInfo.getUserId(), Dealership_Id__c = '1' + i, Active__c = true,BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='1421' + i, BillingCountry='US'));
        }
        //insert account
        insert accountList;
        //create 200 dealer docs
        List<Dealer_Docs__c> bulkDocs = new List<Dealer_Docs__c>();
        for (Integer i = 0; i < 50; i ++) {
            bulkDocs.add(new Dealer_Docs__c(Account__c = accountList[i].Id, Expiration_Date__c = past, RecordTypeId = resaleId, Document_State__c = 'FL', Permit_Resale_Number__c = '11111'));
        }
        //insert docs
        insert bulkDocs;
        //update docs to have incorrect email data
        for (Dealer_Docs__c d : bulkDocs) {
            d.TM_Email__c = 'test@test.com';
            d.IST_Account_Manager_Email__c = 'test@test.com';
        }
        update bulkDocs;
        //run through batch
        //start test
        Test.startTest();
        //run batch
            SchedulableContext sc = null;
            ISTAccountEmailBatch batch = new ISTAccountEmailBatch();
            Batch.execute(sc);
        //stop test
        Test.stopTest();
        //test "pass" condition is: no errors thrown
    }

    // @isTest
    // static void errorCheck() {
    //     Account newAccount = new Account(Name = 'Account1', IST_Account_Owner__c = UserInfo.getUserId());
    //     insert newAccount;
    //     Date expDate = System.Today().addMonths(5);
    //     Dealer_Docs__c newDoc = new Dealer_Docs__c(Account__c = newAccount.Id, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '33333', Expiration_Date__c = expDate, Compliant__c = true);
    //     insert newDoc;
    //     //run through batch with an error
    //     //start test
    //     Test.startTest();
    //     //run batch
    //         SchedulableContext sc = null;
    //         ISTAccountEmailBatch ISTbatch = new ISTAccountEmailBatch();
    //         ISTbatch.errorList.add('error');
    //         ISTbatch.execute(sc);
    //     //stop test
    //     Test.stopTest();
    // }
}