objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Halt_True360_Appointments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manually controlled field to prevent the creation of any more True360 Service Appointments.</description>
        <inlineHelpText>Manually controlled field to prevent the creation of any more True360 Service Appointments.</inlineHelpText>
        <label>Halt True360 Appointments</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Day__c</fullName>
        <description>When Every is 1, select what day of the week for the occurrence</description>
        <label>Day of the Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>weekday</fullName>
                </value>
                <value>
                    <fullName>weekend day</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End time of the occurrence</description>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Every__c</fullName>
        <description>Space between the frequency. Every # frequency.</description>
        <label>Every</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency that the event occurs</description>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time of the occurrence</description>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Timeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The revolving appointment that this occurrence appears on</description>
        <label>Revolving Appointment</label>
        <referenceTo>Timeline__c</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timeline__c.object
<CustomObject>
    <description>Object for defining a time period for creating recurring records</description>
    <label>Revolving Appointment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revolving Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/tracRecurringEventController.cls
/**
 * @description apex controller for the tracRecurringEvent component
 * @name tracRecurringEventController
 * @author Daniel Labonte, Traction on Demand
 * @date 2019-08-22
 */

public class tracRecurringEventController {
    private final static Integer MAX_RESULTS = 5;

    
    /**
     * @description finds territories based on string
     * @param searchTerm string to search
     * @param selectedIds list of ids to exclude from the search
     * @return list of lookup results
     */
    /*@AuraEnabled
    public static List<LookupSearchResult> getTerritories(String searchTerm, List<String> selectedIds) {
        // Prepare query paramters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
                ServiceTerritory (Id, Name WHERE id NOT IN :selectedIds) LIMIT :MAX_RESULTS];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Accounts & convert them into LookupSearchResult
        String icon = 'standard:service_territory_location';
        ServiceTerritory [] serviceTerritories = ((List<ServiceTerritory>) searchResults[0]);
        for (ServiceTerritory st : serviceTerritories) {
            results.add(new LookupSearchResult(st.Id, 'ServiceTerritory', icon, st.Name, ''));
        }

        return results;
    }*/

    @AuraEnabled
    public static String getOperatingHours( String acctId ) {      
        Account acct = [ SELECT Id, OperatingHoursId, Billinglongitude, BillingLatitude FROM Account WHERE Id = :acctId LIMIT 1 ];
        OperatingHoursRange returnData = new OperatingHoursRange();
        if ( acct.OperatingHoursId != null ) {
            returnData = processOperatingHours(
                getTimeSlots( acct.OperatingHoursId ), 
                returnData
            );
        }

        if ( acct.Billinglongitude != null && acct.BillingLatitude != null ) {
            Id serviceTerritoryId = FSL.PolygonUtils.getTerritoryIdByPolygons( Double.valueOf( acct.Billinglongitude ), Double.valueOf( acct.BillingLatitude ) );
            if ( serviceTerritoryId != null ) {
                ServiceTerritory st = [ SELECT Id, OperatingHoursId FROM ServiceTerritory WHERE Id = :serviceTerritoryId LIMIT 1 ];
                returnData = processOperatingHours(
                    getTimeSlots( st.OperatingHoursId ), 
                    returnData
                );
            }
        }
        return JSON.serialize( returnData );
    }

    @AuraEnabled
    public static String getUpdatedOperatingHours( String optHourRange, String serviceResourceId, String providedAcctId ) {     
        OperatingHoursRange returnRangeData = (OperatingHoursRange) JSON.deserialize( optHourRange, OperatingHoursRange.class );
        if ( !String.isBlank( serviceResourceId ) ) {
            Account providedAcct = [ SELECT Id, BillingLongitude, BillingLatitude FROM Account WHERE Id = :providedAcctId LIMIT 1 ];
            if ( providedAcct.Billinglongitude != null && providedAcct.BillingLatitude != null ) {
                Id territoryId = FSL.PolygonUtils.getTerritoryIdByPolygons( Double.valueOf( providedAcct.Billinglongitude ), Double.valueOf( providedAcct.BillingLatitude ) );
                if ( territoryId != null ) {
                    ServiceTerritoryMember stmRec = [ SELECT Id, OperatingHoursId FROM ServiceTerritoryMember WHERE ServiceResourceId = :serviceResourceId 
                                                        AND ServiceTerritoryId = :territoryId AND ( EffectiveEndDate = null OR EffectiveEndDate > :Date.today() ) ];
                    if ( stmRec != null ) {
                        returnRangeData = processOperatingHours(
                            getTimeSlots( stmRec.OperatingHoursId ), 
                            returnRangeData
                        );
                    }
                }
            }
        }

        return JSON.serialize( returnRangeData );
    }

    private static List<TimeSlot> getTimeSlots( Id operatingHoursId ) {
        return [ SELECT StartTime, EndTime FROM TimeSlot WHERE OperatingHoursId = :operatingHoursId ];
    }

    private static OperatingHoursRange processOperatingHours( List<TimeSlot> tsLst, OperatingHoursRange optRange ) {
        for ( TimeSlot tsRec : tsLst ) {
            if ( optRange.startingHour == null || ( optRange.startingHour != null && tsRec.StartTime > optRange.startingHour ) ) {
                optRange.startingHour = tsRec.StartTime;
            }
            if ( optRange.closingHour == null || ( optRange.closingHour != null && tsRec.EndTime < optRange.closingHour ) ) {
                optRange.closingHour = tsRec.EndTime;
            }
        }

        return optRange;
    }

    public class OperatingHoursRange {
        public Time startingHour;
        public Time closingHour;
    }

    /**
     * @description finds territories based on string
     * @param searchTerm string to search
     * @param selectedIds list of ids to exclude from the search
     * @return list of lookup results
     */
    // @AuraEnabled
    // public static List<LookupSearchResult> getResources(String searchTerm, List<String> selectedIds) {
    //     // Prepare query paramters
    //     searchTerm += '*';
    //     System.debug('selectedIds'+selectedIds);
    //     // Execute search query
    //     List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
    //             ServiceResource (Id, Name WHERE id NOT IN :selectedIds) LIMIT :MAX_RESULTS];

    //     // Prepare results
    //     List<LookupSearchResult> results = new List<LookupSearchResult>();

    //     // Extract Accounts & convert them into LookupSearchResult
    //     String icon = 'standard:service_resource';
    //     ServiceResource [] serviceResources = ((List<ServiceResource>) searchResults[0]);
    //     for (ServiceResource st : serviceResources) {
    //         results.add(new LookupSearchResult(st.Id, 'ServiceResource', icon, st.Name, ''));
    //     }

    //     return results;
    // }


    /**
     * @description get child occurrences from a timeline
     * @param recordId timeline id
     * @return list of occurrences
     */
    @AuraEnabled(Cacheable=false)
    public static List<Occurrence__c> getOccurrences(String recordId) {
        return [SELECT Day__c,End_Time__c,Every__c,Frequency__c,Id,Start_Time__c,Timeline__c
                FROM Occurrence__c WHERE Timeline__c = :recordId];
    }

    /**
     * @description get account from record Id
     * @param recordId account Id
     * @return Account
     */
    @AuraEnabled
    public static Account getAccountAddress(String recordId) {
        return [SELECT BillingStreet,BillingCity,BillingState,BillingCountry,BillingPostalCode,Halt_True360_Appointments__c 
                FROM Account WHERE Id = :recordId];
    }

    /**
     * @description deletes a timeline record
     * @param recordId id of the timeline to delete
     */
    @AuraEnabled
    public static void deleteTimeline(String recordId) {
        delete new Timeline__c(Id=recordId);
    }
}