objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Receive_Push__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating if this member should receive mobile push notifications.</description>
        <label>Receive Push</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the date that the Affiliation began.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;admin&quot;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>rep</fullName>
                </value>
                <value>
                    <fullName>admin</fullName>
                    <default>true</default>
                    <label>admin</label>
                </value>
                <value>
                    <fullName>backoffice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>primary_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live_Appraisal_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate this Service Appointment is for a Live Appraisal Event.</description>
        <label>Live Appraisal Event</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/liveAppraisalControllerTest.cls
@IsTest
public with sharing class liveAppraisalControllerTest {
    
    @TestSetup
    static void createTerritory() {

        FSL.GlobalAPIS.addStatusTransition( 'New', 'Scheduled' );

        Account a = TestUtility.createAccount();
        insert a;

        Contact c = TestUtility.createContact( a );
        insert c;

        Affiliation__c aff = new Affiliation__c(
            Account__c=a.id, Contact__c=c.id, Active__c=true, Receive_Push__c = true,
            Primary_Contact__c = true, Start_Date__c = Date.today().addDays(-7),
            type__c='rep'
        );
        insert aff;
        FSLTestUtility.createAllStructureWithParentST( 'Buffalo', '14209' );

        ServiceResource sr = FSLTestUtility.makeResourceData();

        ServiceTerritory st = [SELECT id FROM ServiceTerritory LIMIT 1];

        OperatingHours optHour = [ SELECT Id FROM OperatingHours LIMIT 1 ];
        ServiceTerritoryMember stm = new ServiceTerritoryMember(
            ServiceResourceId = sr.id, ServiceTerritoryId = st.id, EffectiveStartDate = DateTime.now().addDays(-1), TerritoryType = 'P',
            OperatingHoursId = optHour.Id
        );
        insert stm;
    }

    @isTest
    static void createLiveAppraisal(){
        ServiceTerritory st = [SELECT id FROM ServiceTerritory LIMIT 1];
        String workOrderJSON = '{"city":"Buffalo","state":"NY","zip":"14203","country":"United States","street":"101 Main Street","NotificationRequest":false,"accountName":"';

        Account acct = [ SELECT Id, Name FROM Account LIMIT 1 ];
        workOrderJSON += acct.Name;

        workOrderJSON +='","serviceTerritory":"'+st.Id+'","contact":null,"accountId":"';
        workOrderJSON += acct.Id;
        workOrderJSON += '","WSCount":"0","AVCount":"0","T360Count":"0","date":"';

        workOrderJSON += System.today().year() + '-' + System.today().month() + '-' + System.today().day();

        workOrderJSON += '","time":"Later","notes":"Inspection Notes Here",';

        ServiceResource sr = [SELECT id, relatedRecordId FROM ServiceResource Limit 1];

        workOrderJSON +='"userId":"';
        workOrderJSON += sr.relatedRecordId;
        workOrderJSON += '","SXMCount":"0","BSUCheck":false,"timeSelection":"Live Appraisal","startTime":"12:00:00.000","endTime":"15:00:00.000"}';

        List<String> serviceResourceIds = new List<String>();
        serviceResourceIds.add(sr.Id);
        Test.startTest();
        liveAppraisalController.submitWorkOrders( workOrderJSON, serviceResourceIds );
        Test.stopTest();

        List<ServiceAppointment> saList = new List<ServiceAppointment>([SELECT id, status, Live_Appraisal_Event__c, SchedStartTime FROM ServiceAppointment]);
        System.Assert(saList.size() == 1 , saList.size() + ' service appointments created. Expected 1 to be created');
        System.Assert(saList[0].status == 'Scheduled', 'Expected Service Appointment to have a status of \'Scheduled\', status was ' + saLIst[0].status + ' instead');
        System.Assert(true , saList[0].Live_Appraisal_Event__c + 'Service Appointment is not a Live Appraisal Event.');
        System.assertEquals(DateTime.newInstance(System.date.today(), Time.newInstance(12, 0, 0, 0)), saList[0].SchedStartTime, 'Service Appointment Start Time is incorrect.');
        List<AssignedResource> arList = new List<AssignedResource>([SELECT ServiceResourceId, ServiceAppointmentId FROM AssignedResource]);
        System.Assert(arList.size() == 1, arList.size() + ' assigned resource records created. Expected 1 to be created');
        System.Assert(arList[0].ServiceResourceId == sr.Id, 'Incorrect service resource assigned to service appointment');
        System.Assert(arList[0].ServiceAppointmentId == saList[0].id, 'Service Resource assigned to incorrect Service Appointment');
    }

    @isTest
    static void searchServiceResources(){
        ServiceResource sr = [SELECT id, Name, relatedRecordId FROM ServiceResource Limit 1];
        
		Id [] fixedSearchResults= new Id[1];
       	fixedSearchResults[0] = sr.Id;
       	Test.setFixedSearchResults(fixedSearchResults);
        
        List<LookupSearchResult> returnLst = liveAppraisalController.getServiceResources( sr.Name, new List<String>() );

        System.assertEquals( 1, returnLst.size(), 'The wrong number of Service Resources were returned.' );
    }
}