objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Make__c</fullName>
        <description>Set by Process Builder automation.</description>
        <label>Make</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vehicle_Make</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winning_Bid_Price__c</fullName>
        <label>High Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>floor_price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record for the buyer, person who will get delivery of vehicle</description>
        <label>Buyer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Buyer Dealership)</relationshipLabel>
        <relationshipName>Buyer_Transportation_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_Case_Status_Under_Review__c</fullName>
        <description>Captures the Date/Time the case status is changed to &quot;Under Review&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date/Time Case Status Under Review</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <description>Field on unwind case layout to set a floor price</description>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseTriggerFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>CaseTriggerFlag</label>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>make__c</fullName>
        <description>The make (manufacturer) of the vehicle.</description>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/CaseCRReviewProcessesTest.cls
@isTest
public class CaseCRReviewProcessesTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        insert new CaseTriggerFlag__c(Name='Default', Enabled__c = true);
        List<Account> accountList = New List<Account>();
        accountList.add(new Account(Name='seller',IST_Account_Owner__c =UserInfo.getUserId()));
        accountList.add(new Account(Name='buyer',IST_Account_Owner__c = UserInfo.getUserId()));
        insert accountList;
        List<Contact> contactList = new List<Contact>();
        contactList.add(new Contact(FirstName='seller', LastName='seller', accountId=accountList[0].id));
        contactList.add(new Contact(FirstName='buyer', LastName='buyer', accountId=accountList[1].id));
        insert contactList;
        vehicle__c newCar = new vehicle__c(year__c='2009',make__c='test make', model__c='test model', vin__c = '1234567890102030');
        insert newCar;
        vehicle__c newCar1 = new vehicle__c(year__c='2010',make__c='test make', model__c='test model', vin__c = '1234567890102031');
        insert newCar1;
        auction__c newAuction = new auction__c(status__c = 'Active', end_time__c = System.Now(),Buyer_Dealership__c = accountList[1].id, 
        Seller_Dealership__c = accountList[0].id,Floor_Price__c = 500, Winning_Bid_Price__c = 450, vehicle_id__c = newCar.id);
        insert newAuction;
        Id arbRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Arbitration Claim').getRecordTypeId();
        Case newCase = new Case(accountId = accountList[0].id,RecordTypeId = arbRecordType, Vehicle__c = newCar.id);
        insert newCase;
    }

    

    //Process test: Date/Time stamp on Case Reviews. DONE
    @isTest 
    static void dateTimeStamponCase() {
        Test.startTest();
        //These status values can only be picked with CR Review or Arbitration Claims
        Id arbRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CR Review').getRecordTypeId();
        Auction__c a = [SELECT id FROM Auction__c LIMIT 1 ];
        case newCase = new case(RecordTypeId = arbRecordType, Status = 'New', Auction_Number__c = a.Id);
        insert newCase;

        newCase = [select status, Date_Time_Case_Status_Under_Review__c from case where Id = : newCase.Id limit 1 ];
        System.assertEquals( null , newCase.Date_Time_Case_Status_Under_Review__c);
        CaseCRReviewProcesses.beforeUpdateToggle();
        newCase.status = 'Under Review';
        update newCase;
        newCase = [select status, Date_Time_Case_Status_Under_Review__c from case where Id = : newCase.Id limit 1 ];
        System.assertNotEquals( null , newCase.Date_Time_Case_Status_Under_Review__c);


        System.Debug('dateTimeStamponCase CPU Time: ' + String.valueOf(Limits.getCpuTime()));
        Test.stopTest();
    }
    @isTest
    static void testToggles(){
        Boolean foo = false;
        CaseCRReviewProcesses.beforeInsertToggle();
        CaseCRReviewProcesses.beforeInsertToggle(foo);
        CaseCRReviewProcesses.afterInsertToggle();
        CaseCRReviewProcesses.afterInsertToggle(foo);
        CaseCRReviewProcesses.beforeUpdateToggle();
        CaseCRReviewProcesses.beforeUpdateToggle(foo);
        CaseCRReviewProcesses.afterUpdateToggle();
        CaseCRReviewProcesses.afterUpdateToggle(foo);
    }
}