objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Maps_TM_Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for relating Salesforce Maps Assignment Plans for the TMs and Sales Territories</description>
        <label>Maps TM Assignment Rule</label>
        <referenceTo>maps__AssignmentRule__c</referenceTo>
        <relationshipLabel>Accounts (Maps TM Assignment Rule)</relationshipLabel>
        <relationshipName>Accounts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Name__c</fullName>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maps__AssignmentRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maps Assignment Rule</label>
        <referenceTo>maps__AssignmentRule__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/maps__AssignmentRule__c.object
<CustomObject>
    <fields>
        <fullName>maps__ShapeLayer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maps Shape Layer</label>
        <referenceTo>maps__ShapeLayer__c</referenceTo>
        <relationshipLabel>Assignment Rules</relationshipLabel>
        <relationshipName>AssignmentRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maps Assignment Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Maps Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/maps__ShapeLayer__c.object
<CustomObject>
    <fields>
        <fullName>maps__ShapeLayer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shape Layer</label>
        <referenceTo>maps__ShapeLayer__c</referenceTo>
        <relationshipLabel>Shape Layers</relationshipLabel>
        <relationshipName>ShapeLayers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maps Shape Layer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps Shape Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FillTerritoryOnAccount.cls
public class FillTerritoryOnAccount extends TriggerInterface {

    public override void beforeUpdate( Map<Id, sObject> oldMap, Map<Id, sObject> newMap ) {
        List<Account> acctLst = new List<Account>();
        Set<Id> assignmentRuleSet = new Set<Id>();

        for ( Account acct : (List<Account>) newMap.values() ) { Account oldAcct = (Account) oldMap.get( acct.Id ); if ( acct.Maps_TM_Assignment_Rule__c != oldAcct.Maps_TM_Assignment_Rule__c ) { acctLst.add( acct ); if ( acct.Maps_TM_Assignment_Rule__c != null ) { assignmentRuleSet.add( acct.Maps_TM_Assignment_Rule__c ); } } }

        updateMapTerritory( acctLst, assignmentRuleSet );
    }

    private static void updateMapTerritory( List<Account> acctLst, Set<Id> assignmentRuleSet ) {
        if ( acctLst != null && !acctLst.isEmpty() ) { Map<Id, maps__AssignmentRule__c> thingMap = new Map<Id, maps__AssignmentRule__c>( [ SELECT Id, maps__ShapeLayer__c, maps__ShapeLayer__r.Name FROM maps__AssignmentRule__c WHERE Id IN :assignmentRuleSet ] ); for ( Account acct : acctLst ) { if ( acct.Maps_TM_Assignment_Rule__c != null && thingMap.get( acct.Maps_TM_Assignment_Rule__c ) != null && thingMap.get( acct.Maps_TM_Assignment_Rule__c ).maps__ShapeLayer__c != null ) { acct.Territory_Name__c = thingMap.get( acct.Maps_TM_Assignment_Rule__c ).maps__ShapeLayer__r.Name; } } }
    }
}