objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <formula>IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;1&apos; ,&apos;Franchise&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;2&apos; ,&apos;Independent&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;4&apos; ,&apos;Independent - ACV Certified&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;3&apos; ,&apos;Wholesaler&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;Dealer Group (Parent Account)&apos;,&apos;Dealer Group (Parent Account)&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;5&apos; ,&apos;Commercial&apos;,
 &apos;&apos;) 

)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Life_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated with the Inventory Life Cycle the Auction is related to</description>
        <label>Inventory Life Cycle</label>
        <referenceTo>Inventory_Life_Cycle__c</referenceTo>
        <relationshipLabel>Auctions</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Auction__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is used to mark the auction as being the most recent auction for a specific VIN.</description>
        <label>Most Recent Auction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>start_time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inventory_Life_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Life Cycles (Client)</relationshipLabel>
        <relationshipName>Inventory_Life_Cycles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>This field translates the API Name into the type name. Will need to be updated if the Account field is updated.</description>
        <formula>CASE( TEXT(Client__r.Dealer_Type__c) , 
&apos;1&apos;,&apos;Franchise&apos;,
&apos;2&apos;,&apos;Independent&apos;,
&apos;4&apos;,&apos;Independent - ACV Certified&apos;,
&apos;3&apos;,&apos;Wholesaler&apos;,
&apos;5&apos;,&apos;Commercial&apos;,
TEXT(Client__r.Dealer_Type__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated with the most recent Auction that the car has been listed under. This helps populate some formula fields on Inventory Life Cycle.</description>
        <label>Most Recent Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Inventory Life Cycles</relationshipLabel>
        <relationshipName>Inventory_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <description>Vin Number of the Vehicle. This will be populated either when a WOLI is created or a Vehicle is created.</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Inventory Life Cycle</label>
    <nameField>
        <label>Inventory Life Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Life Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

classes/InventoryLifeCycleAuctionTest.cls
@isTest
/**
 * This is the Test class for the Trigger InventoryLifeCycleAuction
 * @author James Andre LaCour
 */
public class InventoryLifeCycleAuctionTest{
    /****************Class Variables************************/
    public static final Id STANDARD_ACCOUNT_RTID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Standard').getRecordTypeId();
    public static final String ACCOUNT_WITH_DEALER_ID_NAME = 'Test Dealership With DealerId';
    public static final String ACCOUNT_WITHOUT_DEALER_ID_NAME = 'Test Dealership without DealerId';
    /****************Test Setup****************************/
    /**
     * Creates Test Data
     * @return void
     */
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account acct = new Account();
        acct.Name = ACCOUNT_WITH_DEALER_ID_NAME;
        acct.RecordTypeId = STANDARD_ACCOUNT_RTID;
        acct.Dealership_Id__c = 'dealerId123';
        acct.Dealer_Type__c = InventoryLifeCycleHelper.DEALER_TYPE_LABEL_TO_API_NAME_MAP_TO_PROCESS.values()[0];
        acct.Legal_Name__c = ACCOUNT_WITH_DEALER_ID_NAME;
        Account acct2 = new Account();
        acct2.Name = ACCOUNT_WITHOUT_DEALER_ID_NAME;
        acct2.RecordTypeId = STANDARD_ACCOUNT_RTID;
        acct2.Dealer_Type__c = InventoryLifeCycleHelper.DEALER_TYPE_LABEL_TO_API_NAME_MAP_TO_PROCESS.values()[0];
        List<Account> acctsToInsert = new List<Account>{acct,acct2};
        insert acctsToInsert;
    }
    /****************Test Methods***************************/
    /**
     * Expecting Successful Creation of Inventory Life Cycle
     * @return void
     */
    public static testMethod void successfulCreation(){
        //Gather Data
        List<Account> acct = [ SELECT Id, Dealership_Id__c FROM Account WHERE Name = :ACCOUNT_WITH_DEALER_ID_NAME LIMIT 1 ];
        System.assertEquals( 1, acct.size(), 'No Account Found from Creation' );
        String vin = '1234abcdVINTest';
        //Create Data
        Test.startTest();
            Auction__c auc = new Auction__c();
            auc.Seller_Dealership__c = acct[0].Id;
            auc.VIN__c = vin;
            insert auc;
        Test.stopTest();
        //System Asserts
        List<Inventory_Life_Cycle__c> ilcToCheck = [ SELECT Id, Most_Recent_Auction__c, Most_Recent_Auction__r.Inventory_Life_Cycle__c, VIN__c, Client__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 1, ilcToCheck.size(), 'Only one Inventory Life Cycle record should be created' );
        System.assertEquals( vin, ilcToCheck[0].VIN__c, 'VIN value was not correctly populated on the Inventory Life Cycle Record' );
        System.assertEquals( auc.Id, ilcToCheck[0].Most_Recent_Auction__c, 'Most Recent Auction should be populated with auc created in test' );
        System.assertEquals( acct[0].Id, ilcToCheck[0].Client__c, 'Client should be populated with Account created in testSetup' );
        System.assertEquals( ilcToCheck[0].Id, ilcToCheck[0].Most_Recent_Auction__r.Inventory_Life_Cycle__c, 'Inventory Life Cycle value should be created with ILC created from logic' );
    }
    /**
     * Expecting No Inventory Life Cycle because VIN Code is not populated
     * @return void
     */
    public static testMethod void noVinCode(){
        //Gather Data
        List<Account> acct = [ SELECT Id, Dealership_Id__c FROM Account WHERE Name = :ACCOUNT_WITH_DEALER_ID_NAME LIMIT 1 ];
        System.assertEquals( 1, acct.size(), 'No Account Found from Creation' );
        //Create Data
        Test.startTest();
            Auction__c auc = new Auction__c();
            auc.Seller_Dealership__c = acct[0].Id;
            insert auc;
        Test.stopTest();
        //System Asserts
        List<Inventory_Life_Cycle__c> ilcToCheck = [ SELECT Id, Most_Recent_Auction__c, Most_Recent_Auction__r.Inventory_Life_Cycle__c, VIN__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 0, ilcToCheck.size(), 'No Inventory Life Cycle record should be created' );
    }
    /**
     * Expecting no Inventory Life Cycle because the Dealer Id on Account isn't populated
     * @return void
     */
    public static testMethod void noDealerId(){
        //Gather Data
        List<Account> acct = [ SELECT Id, Dealership_Id__c FROM Account WHERE Name = :ACCOUNT_WITHOUT_DEALER_ID_NAME LIMIT 1 ];
        System.assertEquals( 1, acct.size(), 'No Account Found from Creation' );
        String vin = '1234abcdVINTest';
        //Create Data
        Test.startTest();
            Auction__c auc = new Auction__c();
            auc.Seller_Dealership__c = acct[0].Id;
            auc.VIN__c = vin;
            insert auc;
        Test.stopTest();
        //System Asserts
        List<Inventory_Life_Cycle__c> ilcToCheck = [ SELECT Id, Most_Recent_Auction__c, Most_Recent_Auction__r.Inventory_Life_Cycle__c, VIN__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 0, ilcToCheck.size(), 'No Inventory Life Cycle record should be created' );
    }
    /**
     * Expecting that the Inventory Life Cycle record is reparented to the next 
     * newest Auction due to the current one being deleated
     * @return void
     */
    public static testMethod void deletionReparent(){
        //Gather Data
        List<Account> acct = [ SELECT Id, Dealership_Id__c FROM Account WHERE Name = :ACCOUNT_WITH_DEALER_ID_NAME LIMIT 1 ];
        System.assertEquals( 1, acct.size(), 'No Account Found from Creation' );
        String vin = '1234abcdVINTest';
        Auction__c auc = new Auction__c();
        auc.Seller_Dealership__c = acct[0].Id;
        auc.VIN__c = vin;
        insert auc;
        //Create Data
        Test.startTest();
            Auction__c newAuc = new Auction__c();
            newAuc.Seller_Dealership__c = acct[0].Id;
            newAuc.VIN__c = vin;
            newAuc.name = 'Second Auc';
            insert newAuc;
            List<Inventory_Life_Cycle__c> ilcToCheck = [ SELECT Id, Most_Recent_Auction__c, Most_Recent_Auction__r.Inventory_Life_Cycle__c, VIN__c FROM Inventory_Life_Cycle__c ];
            System.assertEquals( 1, ilcToCheck.size(), 'Only 1 Inventory Life Cycle should be created' );
            System.assertEquals( newAuc.Id, ilcToCheck[0].Most_Recent_Auction__c, 'Most Recent Auction should be attached to the new Auc' );
            delete newAuc;
        Test.stopTest();
        //System Asserts
        ilcToCheck = [ SELECT Id, Most_Recent_Auction__c, Most_Recent_Auction__r.Inventory_Life_Cycle__c, VIN__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 1, ilcToCheck.size(), 'Only 1 Inventory Life Cycle should be created' );
        System.assertEquals( auc.Id, ilcToCheck[0].Most_Recent_Auction__c, 'Most Recent Auction should be attached to the old Auc after new one was deleted' );
    }
    /**
     * Test for a bug where theres already an ILC created and multiple Auctions's
     * come in at the same time
     * @return void
     */
    public static testMethod void multipleAucSameKeyAlreadyCreatedILC(){
        //Gather Data
        List<Account> acct = [ SELECT Id, Dealership_Id__c FROM Account WHERE Name = :ACCOUNT_WITH_DEALER_ID_NAME LIMIT 1 ];
        System.assertEquals( 1, acct.size(), 'No Account Found from Creation' );
        String vin = '1234abcdVINTest';
        String dealerId = 'dealerId123';
        Inventory_Life_Cycle__c ilc = new Inventory_Life_Cycle__c();
        ilc.key__c = dealerID + vin;
        ilc.Client__c = acct[0].Id;
        insert ilc;
        //Create Data
        Test.startTest();
            Auction__c auc1 = new Auction__c();
            auc1.Seller_Dealership__c = acct[0].Id;
            auc1.VIN__c = vin;
            auc1.start_time__c = Datetime.Now();
            Auction__c auc2 = new Auction__c();
            auc2.Seller_Dealership__c = acct[0].Id;
            auc2.VIN__c = vin;
            auc2.start_time__c = Datetime.now().addDays(1);
            insert new List<Auction__c>{auc1,auc2};
        Test.stopTest();
        //System Asserts
        List<Inventory_Life_Cycle__c> ilcToCheck = [ SELECT Id, Most_Recent_Auction__c, Most_Recent_Auction__r.Inventory_Life_Cycle__c, VIN__c, Client__c FROM Inventory_Life_Cycle__c ];
        System.assertEquals( 1, ilcToCheck.size(), 'Only one Inventory Life Cycle record should be created' );
        System.assertEquals( vin, ilcToCheck[0].VIN__c, 'VIN value was not correctly populated on the Inventory Life Cycle Record' );
        System.assertEquals( auc2.Id, ilcToCheck[0].Most_Recent_Auction__c, 'Most Recent Auction should be populated with CR created in test' );
        System.assertEquals( acct[0].Id, ilcToCheck[0].Client__c, 'Client should be populated with Account created in testSetup' );
        System.assertEquals( ilcToCheck[0].Id, ilcToCheck[0].Most_Recent_Auction__r.Inventory_Life_Cycle__c, 'Inventory Life Cycle value should be created with ILC created from logic' );
    }
}