objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Service Territory this Account is related to, if all related Work Orders should fall under the same Territory.</description>
        <label>Service Territory</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ServiceTerritory.ParentTerritoryId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Data_Schedule__c.object
<CustomObject>
    <description>Object that uses the trigger to create and delete cron apex jobs for the recurring data generator</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Schedule that is active. Only one record can be active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>Day that the data generation should occur</description>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>How often does the data batch run</description>
        <label>Frequency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Horizon_Length__c</fullName>
        <description>How many x in the future to generate data</description>
        <label>Horizon Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Horizon_Type__c</fullName>
        <description>Number of &quot;type&quot; in the future</description>
        <label>Horizon Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Weeks</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Email_On_Success__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Email will send when batch runs successfully when checked. Emails will always send when the batch fails.</inlineHelpText>
        <label>Send Email On Success</label>
        <type>Checkbox</type>
    </fields>
    <label>Data Schedule</label>
    <nameField>
        <displayFormat>Sch{000}</displayFormat>
        <label>Data Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Date_of_Last_Generation__c</fullName>
        <description>Old field with not up to date information</description>
        <inlineHelpText>Do not use this field</inlineHelpText>
        <label>Date of Last Generation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>When Every is 1, select what day of the week for the occurrence</description>
        <label>Day of the Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>weekday</fullName>
                </value>
                <value>
                    <fullName>weekend day</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End time of the occurrence</description>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Every__c</fullName>
        <description>Space between the frequency. Every # frequency.</description>
        <label>Every</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency that the event occurs</description>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether this Occurrence is still active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time of the occurrence</description>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Timeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The revolving appointment that this occurrence appears on</description>
        <label>Revolving Appointment</label>
        <referenceTo>Timeline__c</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <label>Week Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>first</fullName>
                </value>
                <value>
                    <fullName>second</fullName>
                </value>
                <value>
                    <fullName>third</fullName>
                </value>
                <value>
                    <fullName>fourth</fullName>
                </value>
                <value>
                    <fullName>fifth</fullName>
                </value>
                <value>
                    <fullName>last</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timeline__c.object
<CustomObject>
    <description>Object for defining a time period for creating recurring records</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Timelines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Average_Number_Cars__c</fullName>
        <description>Field for user to capture average number of cars for the visit</description>
        <label>Average Number of Cars</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date that the timeline ends. This can be left null for an indefinite timeline</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this Timeline Currently Active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <formula>Account__r.Service_Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Territory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Day that the timeline begins</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Revolving Appointment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revolving Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/tracRecurringGenerationBatch.cls
/**
 * @description ${DESCRIPTION}
 * @name tracRecurringGenerationBatch
 * @author Daniel Labonte, Traction on Demand
 * @date 2019-08-28
 */

global with sharing class tracRecurringGenerationBatch implements Database.Batchable<SObject>, Database.Stateful  {
    public static final Datetime NOW = (Datetime) System.today();
    public static final String DAY_OF_THE_WEEK = NOW.format('EEEE');
    public static final String DAY_OF_THE_MONTH = NOW.format('d');

    global Data_Schedule__c schedule;

    global List<String> debug = new List<String>{'THIS IS THE DEBUG'};
    global Integer batchCount = 0;
    global Boolean hasError = false;

    global Date future;

    String occurrenceQuery =    'SELECT ' +
                                'Id, Frequency__c,' +
                                'Week_Number__c,' +
                                'Every__c,' +
                                'Day__c,' +
                                'Timeline__c,' +
                                'Timeline__r.Account__c,' +
                                'Timeline__r.Account__r.BillingCity,' +
                                'Timeline__r.Account__r.BillingCountry,' +
                                'Timeline__r.Account__r.BillingLatitude,' +
                                'Timeline__r.Account__r.BillingLongitude,' +
                                'Timeline__r.Account__r.BillingPostalCode,' +
                                'Timeline__r.Account__r.BillingState,' +
                                'Timeline__r.Account__r.BillingStreet,' +
                                'Timeline__r.End_Date__c,' +
                                'Timeline__r.Start_Date__c,' +
                                'Timeline__r.Account__r.Service_Territory__c,' +
                                'Timeline__r.Average_Number_Cars__c,' +
                                'Start_Time__c,End_Time__c,' +
                                'Date_of_Last_Generation__c ' +
                            'FROM Occurrence__c ' +
                            'WHERE Is_Active__c = TRUE ' +
                            'AND Timeline__c != NULL ' +
                            'AND (Timeline__r.End_Date__c = NULL OR Timeline__r.End_Date__c >= TODAY ) ' +
                            'AND (Date_of_Last_Generation__c < :future OR Date_of_Last_Generation__c = NULL)';


    /**
     * @description build query for the active data schedule
     * @param bc batchable context
     * @return query
     */
    global Database.QueryLocator start (Database.BatchableContext bc) {
        try{

            schedule = [
                    SELECT Id, Horizon_Type__c, Horizon_Length__c, Frequency__c, Send_Email_On_Success__c, Debug_Email__c
                    FROM Data_Schedule__c
                    WHERE Active__c = TRUE
                    LIMIT 1];
    
            // stop batch if data schedule record doesnt match with today
            if (!tracRecurringGenerationManual.overrideDataSchedule) {
                if (!Test.isRunningTest() && !(isDaily(schedule) || isWeeklyToday(schedule) || isMonthlyToday(schedule))) {
                    return null;
                }
            }
    
            future = getFutureDate(schedule);
    
            
    
            debug.add('--------------------------------');
            debug.add('PRE-BATCH DATA REMOVAL');
            debug.addAll(tracGenerate.deleteChangedRecords());  // delete generated data for changed or deleted occurrences
            debug.addAll(tracGenerate.removeInactiveRecords());  // delete timelines and occurrences that are inactive or past
        }
        catch(Exception e){
            debug.addAll(new List<String>{'**EXCEPTION THROWN IN START OF BATCH**', e.getMessage(), e.getStackTraceString()});
            hasError = true;
        }
        
        return Database.getQueryLocator(occurrenceQuery);
    }


    /**
     * @description execute the batch
     * @param bc batchable context
     * @param scope list of records from query
     */
    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        if (scope == null) return;

        List<String> thisDebug = new List<String>();
        thisDebug.add('--------------------------------');
        thisDebug.add('EXECUTING BATCH #' + ++batchCount);
        try {
            thisDebug.addAll(tracGenerate.generate((List<Occurrence__c>)scope,future));  // generate data for all future active timeline and occurrences
        }
        catch(Exception e) {
            thisDebug.addAll(new List<String>{'**EXCEPTION THROWN**',e.getMessage(),e.getStackTraceString()});
            hasError = true;
        }
        debug.addAll(thisDebug);
    }


    /**
     * @description actions to perform on batch completion
     * @param bc batchable context
     */
    global void finish(Database.BatchableContext bc) {
        debug.add('------------------------');
        debug.add('PROCESSING COMPLETE' + (hasError?' WITH ERRORS':''));
        if(!Test.isRunningTest() && schedule.Debug_Email__c != null && (schedule.Send_Email_On_Success__c || hasError)) {
            tracConstants.sendMail(schedule.Debug_Email__c, 'Batch Finish Report', String.join(debug, '\n<br>'));
        }
    }



    /************ HELPER METHODS ************/
    public static Date getFutureDate(Data_Schedule__c thisSchedule) {
        Date today = Date.today();
        Date futureDate;
        if (thisSchedule.Horizon_Type__c == tracConstants.DATA_HORIZON_DAYS) {
            futureDate = today.addDays(Integer.valueOf(thisSchedule.Horizon_Length__c));
        } else if (thisSchedule.Horizon_Type__c == tracConstants.DATA_HORIZON_WEEKS) {
            futureDate = today.addDays(Integer.valueOf(thisSchedule.Horizon_Length__c)*7);
        } else if (thisSchedule.Horizon_Type__c == tracConstants.DATA_HORIZON_MONTHS) {
            futureDate = today.addMonths(Integer.valueOf(thisSchedule.Horizon_Length__c));
        }
        return futureDate;
    }

    public static Boolean isDaily(Data_Schedule__c ds) {
        return ds.Frequency__c == tracConstants.DATA_FREQUENCY_DAILY;
    }

    public static Boolean isWeeklyToday(Data_Schedule__c ds) {
        return ds.Frequency__c == tracConstants.DATA_FREQUENCY_WEEKLY
                && DAY_OF_THE_WEEK == ds.Day__c;
    }

    public static Boolean isMonthlyToday(Data_Schedule__c ds) {
        return ds.Frequency__c == tracConstants.DATA_FREQUENCY_MONTHLY
                && DAY_OF_THE_MONTH == ds.Day__c;
    }

}