objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>Unique Id in ACV databases - used for integration purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Dealership Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AssociatedLocation.object
<CustomObject>
    <fields>
        <fullName>Alternate_Address_Name__c</fullName>
        <description>Provides an alternative Address name for the associated location</description>
        <inlineHelpText>This Location Name will show on the release slip instead of Dealer Name if this address is selected for Transportation</inlineHelpText>
        <label>Alternate Address Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inherited_Address_Id__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will populate when an address is being changed (ie: old associatedLocation is being de-activated and Org Address ID/guid is being transferred) creating a NEW associatedLocation with the org Address ID/guid of the old associatedLocation</description>
        <label>Inherited Address Id</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes related to the relationship between this Account and the Address association</description>
        <label>Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Organization_Address_Guid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique Guid associated with an Organization and an address, along with the unique address type</description>
        <externalId>true</externalId>
        <label>Organization Address Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Organization_Address_Id__c</fullName>
        <description>This field is the unique Id between the Organizaition and the Address associated with it, along with the unique Address type</description>
        <externalId>true</externalId>
        <label>Organization Address Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Guid__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealership_Contact_Id__c</fullName>
        <description>Indicates the unique Dealership Contact Id for this Contact record. This field will be populated only for the Dealership Contact Record types</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Dealership Contact Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountMergeProcess.cls
public class AccountMergeProcess extends TriggerInterface {

    public override void beforeDelete(Map<Id,SObject> incomingMap){ 
        

        Map<Id, Affiliation__c> deletedAffiliation = new Map<Id, Affiliation__c>([Select id, id__c, Account__c, Account__r.Dealership_Id__c, 
        Contact__c, Contact__r.id__c, Contact__r.RecordTypeId, LastModifiedBy.Email From Affiliation__c Where Account__c IN: incomingMap.keyset()]);

        List<Affiliation__c> deletedAffiliationList = new List<Affiliation__c>();

        if(deletedAffiliation.size() > 0){
            for(Affiliation__c aff : deletedAffiliation.values()){
                deletedAffiliationList.add(aff);
            }
        }
        if(deletedAffiliationList.size() > 0){
            // Line below is used to turn off validation rule that does not allow Affiliation to be deleted in a beforeDelete
            AffiliationPrimaryorAdminChangeCheck.validationEnabled = false;
            delete deletedAffiliationList;
            // Line below is used to turn the validation rule back on that does not allow Affiliation to be deleted in a beforeDelete
            AffiliationPrimaryorAdminChangeCheck.validationEnabled = true;
        }

        Map<Id, Contact> deletedContact = new Map<Id, Contact>([Select id, AccountId, Account.Dealership_Id__c, LastModifiedBy.Email, RecordTypeId, Contact_Guid__c, Dealership_Contact_Id__c
        From Contact Where AccountId IN: incomingMap.keyset()]);

        List<Contact> deletedContactList = new List<Contact>();

        if(deletedContact.size() > 0){
            for(Contact con : deletedContact.values()){
                deletedContactList.add(con);
            }
        }
        if(deletedContactList.size() > 0){
            // Line below is used to turn off validation rule that does not allow Contact to be deleted in a beforeDelete
            AffiliationPrimaryorAdminChangeCheck.validationEnabled = false;
            delete deletedContactList;
            // Line below is used to turn the validation rule back on that does not allow Contact to be deleted in a beforeDelete
            AffiliationPrimaryorAdminChangeCheck.validationEnabled = true;
        }

        Map<Id, AssociatedLocation> deletedAddress = new Map<Id, AssociatedLocation>([Select id, Type, Notes__c, Organization_Address_Id__c, Inherited_Address_Id__c, ActiveTo,
        Organization_Address_Guid__c, LocationId, Location.VisitorAddressId, Location.VisitorAddress.Street, Location.VisitorAddress.City, Alternate_Address_Name__c,  
        Location.VisitorAddress.PostalCode, Location.VisitorAddress.State, Location.VisitorAddress.Country, Location.VisitorAddress.Address_Guid__c, ParentRecord.Dealership_Id__c,
        LastModifiedBy.Email            
        From AssociatedLocation Where ParentRecordId IN: incomingMap.keyset()]);

        List<AssociatedLocation> deletedAddressList = new List<AssociatedLocation>();

        if(deletedAddress.size() > 0){
            for(AssociatedLocation ass : deletedAddress.values()){
                deletedAddressList.add(ass);
            }
        }
        if(deletedAddressList.size() > 0){
            delete deletedAddressList;
        }



    }

}