objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>External_Invoice_Id__c</fullName>
        <label>External Invoice Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Work Type Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvoiceCancelAPITest.cls
@isTest
public class InvoiceCancelAPITest {
    private static final string INVOICE_NUM = '1';
    private static final string ZIP = '14209';

    @TestSetup
    static void createTerritory() {
        Account a = TestUtility.createAccount();
        insert a;

        FSLTestUtility.createAllStructureWithParentST( 'Buffalo', ZIP );
    }

    @IsTest
    static void cancelExistingInvoiceWithItem() {
        FSL.GlobalAPIS.addStatusTransition( 'New', 'Canceled' );

        RestResponse res = new RestResponse();
        RestContext.response = res;

        Account acctRec = [ SELECT Id, Name FROM Account LIMIT 1 ];
        ServiceTerritory stRec = [ SELECT Id FROM ServiceTerritory LIMIT 1 ];
        WorkType assetWT = [ SELECT Id, Name, DurationType, EstimatedDuration FROM WorkType WHERE Work_Type_Unique_ID__c = 'verification' ];
        
        WorkOrder workRec = FSLTestUtility.createWorkOrder( assetWT, acctRec, ZIP, stRec, null );
        insert workRec;
        WorkOrderLineItem woliRec = FSLTestUtility.createWorkOrderLineItem( workRec, assetWT, 1 );
        woliRec.External_Invoice_Id__c = INVOICE_NUM;
        insert woliRec;

        Test.startTest();
            InvoiceCancelAPI.CancelStruct newCancelRec = new InvoiceCancelAPI.CancelStruct();
            newCancelRec.invoiceId = INVOICE_NUM;

            InvoiceCancelAPI.cancelInvoice( new List<InvoiceCancelAPI.CancelStruct>{ newCancelRec } );
        Test.stopTest();

        system.debug( RestContext.response );

        System.assertEquals( 200, RestContext.response.statusCode, 'The status code resulted in an error when hitting the API' );

        Invoice__c systemInvoice = [ SELECT Id, Status__c FROM Invoice__c LIMIT 1 ];
        System.assertEquals(  'Closed', systemInvoice.Status__c, 'The Invoice was not properly closed as expected' );

        woliRec = [ SELECT Id, Status FROM WorkOrderLineItem LIMIT 1 ];
        System.assertEquals( 'Canceled', woliRec.Status, 'The Work Order Line Item was not properly canceled as expected' );
    }

    @IsTest
    static void cancelExistingInvoice() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        Account acctRec = [ SELECT Id FROM Account LIMIT 1 ];
        insert CapitalTestUtility.createInvoice( INVOICE_NUM, acctRec.Id );

        Test.startTest();
            InvoiceCancelAPI.CancelStruct newCancelRec = new InvoiceCancelAPI.CancelStruct();
            newCancelRec.invoiceId = INVOICE_NUM;

            InvoiceCancelAPI.cancelInvoice( new List<InvoiceCancelAPI.CancelStruct>{ newCancelRec } );
        Test.stopTest();

        system.debug( RestContext.response );

        System.assertEquals( 200, RestContext.response.statusCode, 'The status code resulted in an error when hitting the API' );

        Invoice__c systemInvoice = [ SELECT Id, Status__c FROM Invoice__c LIMIT 1 ];
        System.assertEquals(  'Closed', systemInvoice.Status__c, 'The Invoice was not properly closed as expected' );
    }

    @IsTest
    static void cancelNoInvoice() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        Test.startTest();
            InvoiceCancelAPI.CancelStruct newCancelRec = new InvoiceCancelAPI.CancelStruct();
            newCancelRec.invoiceId = INVOICE_NUM;

            InvoiceCancelAPI.cancelInvoice( new List<InvoiceCancelAPI.CancelStruct>{ newCancelRec } );
        Test.stopTest();

        system.debug( RestContext.response );

        System.assertEquals( 400, RestContext.response.statusCode, 'The status code resulted in an error when hitting the API' );
    }

    @IsTest
    static void cancelMissingOneInvoice() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        Account acctRec = [ SELECT Id FROM Account LIMIT 1 ];
        insert CapitalTestUtility.createInvoice( INVOICE_NUM, acctRec.Id );

        Test.startTest();
            InvoiceCancelAPI.CancelStruct newCancelRec = new InvoiceCancelAPI.CancelStruct();
            newCancelRec.invoiceId = INVOICE_NUM;

            InvoiceCancelAPI.CancelStruct missingCancelRec = new InvoiceCancelAPI.CancelStruct();
            missingCancelRec.invoiceId = '2';

            InvoiceCancelAPI.cancelInvoice( new List<InvoiceCancelAPI.CancelStruct>{ newCancelRec,missingCancelRec } );
        Test.stopTest();

        system.debug( RestContext.response );

        System.assertEquals( 207, RestContext.response.statusCode, 'The status code resulted in an error when hitting the API' );

        Invoice__c systemInvoice = [ SELECT Id, Status__c FROM Invoice__c LIMIT 1 ];
        System.assertEquals(  'Closed', systemInvoice.Status__c, 'The Invoice was not properly closed as expected' );
    }

    @IsTest
    static void cancelExistingInvoiceWithItemError() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        Account acctRec = [ SELECT Id, Name FROM Account LIMIT 1 ];
        ServiceTerritory stRec = [ SELECT Id FROM ServiceTerritory LIMIT 1 ];
        WorkType assetWT = [ SELECT Id, Name, DurationType, EstimatedDuration FROM WorkType WHERE Work_Type_Unique_ID__c = 'verification' ];
        
        WorkOrder workRec = FSLTestUtility.createWorkOrder( assetWT, acctRec, ZIP, stRec, null );
        insert workRec;
        WorkOrderLineItem woliRec = FSLTestUtility.createWorkOrderLineItem( workRec, assetWT, 1 );
        woliRec.External_Invoice_Id__c = INVOICE_NUM;
        insert woliRec;

        Test.startTest();
            InvoiceCancelAPI.CancelStruct newCancelRec = new InvoiceCancelAPI.CancelStruct();
            newCancelRec.invoiceId = INVOICE_NUM;

            InvoiceCancelAPI.cancelInvoice( new List<InvoiceCancelAPI.CancelStruct>{ newCancelRec } );
        Test.stopTest();

        system.debug( RestContext.response );

        System.assertEquals( 400, RestContext.response.statusCode, 'The status code resulted in an error when hitting the API' );
    }
}