objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>ACV_Anywhere_Registration_Date__c</fullName>
        <label>ACV Anywhere Registration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Inactive_Sub_Status__c</fullName>
        <description>Inactive Reason set when the Active flag is set to False. Do not update this without updating the datahub schema and MySQL tables associated with it in the organizations domain</description>
        <label>Inactive Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Dealership_Inactive_Sub_status</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

globalValueSets/Dealership_Inactive_Sub_status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Incomplete</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Out of Business</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Suspended</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Blacklisted</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Non-payment</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Dealer Docs Out of Compliance</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Selling Arb Offender</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Duplicate</label>
    </customValue>
    <masterLabel>Dealership Inactive Sub-status</masterLabel>
</GlobalValueSet>

classes/FslAcvAnywhereOnboardingControllerTest.cls
@isTest
public class FslAcvAnywhereOnboardingControllerTest {

    private class FslAcvAnywhereOnboardingMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {

            HTTPResponse res = new HTTPResponse();
            res.setBody('{"ErrorId": "200", "Message": "Success", "ReturnCode": 0, "ACV_OrgID": "73802", "ASI_Org_Code": "1456", "ASI_Org_ID": "126114", "ASI_Org_Name": "Customer Wow"}');
            res.setStatusCode(200);
            return res;

        }
    }

        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account acct = TestUtility.createAccount();
        acct.Active__c = true;
        acct.Dealership_ID__c = '12345';
        insert acct;
    }

    @IsTest
    static void successfulRegistration(){
        Test.setMock(HttpCalloutMock.class, new FslAcvAnywhereOnboardingMock());

        Account acc = [SELECT Id, ACV_Anywhere_Registration_Date__c FROM Account LIMIT 1];
        system.assert(acc.ACV_Anywhere_Registration_Date__c == null);

        test.startTest();
        FslAcvAnywhereOnboardingController.RegistrationResponse res = FslAcvAnywhereOnboardingController.acvAnywhereRegistrationRequest(acc.Id);
        test.stopTest();

        System.assertEquals(200,res.errorId);
        System.assertEquals('Success', res.message);

        Account updatedAccount = [SELECT Id, ACV_Anywhere_Registration_Date__c FROM Account LIMIT 1];
        system.assert(updatedAccount.ACV_Anywhere_Registration_Date__c != null);
    }

    @IsTest
    static void isEligible(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        FslAcvAnywhereOnboardingController.EligibilityResponse res = FslAcvAnywhereOnboardingController.checkEligibility(acc.Id);

        System.assert(res.isAlreadyRegistered == false);
        System.assert(res.isActiveDealer == true);

    }

    @IsTest
    static void isAlreadyRegistered(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        acc.ACV_Anywhere_Registration_Date__c = System.now();
        update acc;

        FslAcvAnywhereOnboardingController.EligibilityResponse res = FslAcvAnywhereOnboardingController.checkEligibility(acc.Id);

        System.assert(res.isAlreadyRegistered == true);
        System.assert(res.isActiveDealer == true);

    }

    @IsTest
    static void noDealerId(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        acc.Active__c = false;
        acc.Inactive_Sub_Status__c = '2';
        update acc;

        FslAcvAnywhereOnboardingController.EligibilityResponse res = FslAcvAnywhereOnboardingController.checkEligibility(acc.Id);

        System.assert(res.isAlreadyRegistered == false);
        System.assert(res.isActiveDealer == false);

    }

}