objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>This will be the same as Auction Number (Name), but is marked as an external ID for integration purposes.</description>
        <externalId>true</externalId>
        <label>Auction ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>Field used for integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Arbitration ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Title__c.object
<CustomObject>
    <description>Hold fields specifically related to Physical &amp; Digital Titles.</description>
    <fields>
        <fullName>Buyer_Organization_Id__c</fullName>
        <description>Buyer Account Id - populated by the backed (engineering team) using SF TitleService.</description>
        <inlineHelpText>Buyer Account Id - populated by the backed (engineering team) using SF TitleService.</inlineHelpText>
        <label>Buyer Organization Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buyer_User_Id__c</fullName>
        <description>Buyer Contact Id - populated by the backed (engineering team).</description>
        <inlineHelpText>Buyer Contact Id - populated by the backed (engineering team).</inlineHelpText>
        <label>Buyer User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Pending_Related_Info__c</fullName>
        <defaultValue>false</defaultValue>
        <description>We only create shell Case &amp; Title records when we get a &apos;created&apos; event in TitleService. A batch file is run separately to populate related salesforce ids to avoid Row Lock error. This field is set to False by the batch file that populates the related salesforce ids in Case &amp; Title records.</description>
        <label>Is Pending Related Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Auction_Id__c</fullName>
        <description>Auction Id - populated by the backed (engineering team) using SF TitleService.</description>
        <inlineHelpText>Auction Id - populated by the backed (engineering team) using SF TitleService.</inlineHelpText>
        <label>Legacy Auction Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Organization_Id__c</fullName>
        <description>Seller Account Id - populated by the backed (engineering team) using SF TitleService.</description>
        <inlineHelpText>Seller Account Id - populated by the backed (engineering team) using SF TitleService.</inlineHelpText>
        <label>Seller Organization Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_User_Id__c</fullName>
        <description>Seller Contact Id - populated by the backed (engineering team) using SF TitleService.</description>
        <inlineHelpText>Seller Contact Id - populated by the backed (engineering team) using SF TitleService.</inlineHelpText>
        <label>Seller User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <description>Vehicle Id - populated by the backed (engineering team) using SF TitleService.</description>
        <inlineHelpText>Vehicle Id - populated by the backed (engineering team) using SF TitleService.</inlineHelpText>
        <label>VIN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <description>acv_prod id found on the users table used to identify internal users</description>
        <externalId>true</externalId>
        <inlineHelpText>This corresponds to the User&apos;s ACV Tools ID</inlineHelpText>
        <label>ACV User Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>id__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle ID</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TitleServicePopulateRelatedDataBatch.cls
/**
 * @description A batch process to populate missing Related records on Cases.
 * 				A shell Case record is created in TitleService to avoid ROW LOCK error. This batch process populated the missing related info on Cases where
 * 				Title__c.Is_Pending_Related_Info__c is True (i.e. related info missing).
 * 
 * @author Manmeet Vaseer
 * @date 04/27/2022
 * 
 * @history
 * 		04/27/2022 Manmeet Vaseer - Initial.
 * 
 */
global with sharing class TitleServicePopulateRelatedDataBatch extends SchedulingInterface implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {

    public Integer totalRecsReceived = 0;
    public Integer totalRecsProcessed = 0;
    
   /**
     * Intiliaze the Batch Job.
     * 
     */
    public TitleServicePopulateRelatedDataBatch()	{
    }

    public override void executeScheduledLogic() {
        TitleServicePopulateRelatedDataBatch batchClass = new TitleServicePopulateRelatedDataBatch();
		database.executebatch( batchClass, 20 ); // lower batch size to reduce the probability of the Row Lock error.
    }

    
    /**
     * Find all Titles with missing data.
     * 
     * @param BC Batch Context
     * @return  `Database.QueryLocator` All Titles where Is_Pending_Related_Info__c=true.
     */
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(getQuery());
    }
    
    /**
     * Populate missing Case & Title data.
     * 
     * @param BC Batch Context
     * @param titles A batch of new titles that will be processed to populate missing related data.
     */
    global void execute(Database.BatchableContext BC, List<Title__c> titles){
        try	{
            totalRecsReceived = totalRecsReceived + titles.size();
            populateMissingRelatedData(titles);
            totalRecsProcessed = totalRecsProcessed + titles.size();
        }
        catch(Exception e)	{
            String logMsg = 'Found Error while Processing Batch: ' + e.getMessage();
			makeSplunkLog(null, ACVUtility.currentLineNumber(), logMsg, e.getStackTraceString(), SplunkHelper.LOGLEVEL.ERROR);
        }
    }
    
    /**
     * Log into Splunk when the batch is finished.
     * 
     * @param BC Batch Context
     */
    global void finish(Database.BatchableContext BC){
        List<Title__c> leftToBeProcessed = [SELECT Id FROM Title__c WHERE Is_Pending_Related_Info__c = true];
        String msg = 'Title records Processed/Received: ' + totalRecsProcessed + '/' + totalRecsReceived + '\n';
        msg = msg + 'Title records left to be processed in Title__c: ' + leftToBeProcessed.size() + '\n';
        msg = msg + 'TitleServicePopulateRelatedDataBatch Finished.\n';
        
        makeSplunkLog(null, 0, msg, '', SplunkHelper.LOGLEVEL.INFO);
        
        //
        // Usually, related info should be populated by this batch process within a day. We want to know if the related info is not populated within a day
        // so that we can send alert on channel.
        // 
        List<Title__c> olderTitlesNotProcessedYet = [SELECT Id, CreatedDate FROM Title__c WHERE Is_Pending_Related_Info__c = true AND CreatedDate < TODAY];
        if(olderTitlesNotProcessedYet != null && olderTitlesNotProcessedYet.size() > 0)	{
            String warnMsg = 'Warning: These titles should have been processed as they are older than a day: ' + olderTitlesNotProcessedYet.size();
        	makeSplunkLog(null, 0, warnMsg, '', SplunkHelper.LOGLEVEL.WARN);            
        }
    } 

    /**
     * Fetch all Titles where Related Record Info are missing.
     * 
     * @return Query String
     */
    public String getQuery()	{
        String query = 'SELECT Id, Is_Pending_Related_Info__c, Case__c, Buyer_User_Id__c, Seller_User_Id__c, Buyer_Organization_Id__c, Seller_Organization_Id__c, VIN__c, Legacy_Auction_Id__c FROM Title__c ' + 
            'WHERE Is_Pending_Related_Info__c = true';

		return query;        
    }
    
    public void populateMissingRelatedData(List<Title__c> titles)	{
        List<Case> updatedCases = new List<Case>();
        List<Title__c> updatedTitles = new List<Title__c>();
        
        // Load various maps in bulk - it is mostly used to load Salesforce Ids.
        IdMaps variousMaps = mapAllIds(titles);
        
        for(Title__c aTitle : titles)	{
            // Find various Salesforce Ids from the maps.
            String buyerContactId = variousMaps.userIdContactIdMap.get(aTitle.Buyer_User_Id__c);
            String sellerContactId = variousMaps.userIdContactIdMap.get(aTitle.Seller_User_Id__c);
            String buyerAcctId = variousMaps.dealerIdAccountIdMap.get(aTitle.Buyer_Organization_Id__c);
            String sellerAcctId = variousMaps.dealerIdAccountIdMap.get(aTitle.Seller_Organization_Id__c);
            String vehicleId = variousMaps.vinVehicleIdMap.get(aTitle.VIN__c);
            String auctionId = variousMaps.auctionNumberAuctionIdMap.get(aTitle.Legacy_Auction_Id__c);
            
            // Create a new case record.
            Case updateCase = new Case (
                Id = aTitle.Case__c,
                AccountId = buyerAcctId,
                ContactId = buyerContactId,
                Seller_Dealership__c = sellerAcctId,
                Seller_Contact__c = sellerContactId,
                //Vehicle_Id__c = vehicleId,
                Vehicle__c = vehicleId,
                Auction_Number__c = auctionId
            );
            
            updatedCases.add(updateCase);
            
            aTitle.Is_Pending_Related_Info__c = false; // Related Records Ids are populated.
            updatedTitles.add(aTitle);
        } // for
        
        if(updatedCases.size() > 0) {
            update updatedCases;
            update updatedTitles;
        }
    }
    
    /**
     * Create mapping between Salesforce Ids and various fields in the Event.
     * 
     * @titleList A list of titles records/events that will be mapped.
     * 
     */
    private static IdMaps mapAllIds(List<Title__c> titleList)	{        
		List<String> dealerIds = new List<String>();
        List<String> userIds = new List<String>();
        List<String> vins = new List<String>();
        List<String> auctionIds = new List<String>();
        
        // Collect all values from the events of specific types.
        for(Title__c aTitle : titleList)	{
            if(aTitle.Seller_User_Id__c != null) userIds.add(aTitle.Seller_User_Id__c);
            if(aTitle.Buyer_User_Id__c != null) userIds.add(aTitle.Buyer_User_Id__c);
            
            if(aTitle.Seller_Organization_Id__c != null) dealerIds.add(aTitle.Seller_Organization_Id__c);
            if(aTitle.Buyer_Organization_Id__c != null) dealerIds.add(aTitle.Buyer_Organization_Id__c);
            
            if(aTitle.VIN__c != null) vins.add(aTitle.VIN__c);
            
            if(aTitle.Legacy_Auction_Id__c != null) auctionIds.add(aTitle.Legacy_Auction_Id__c);
        }
        
        // A collection of maps
        IdMaps variousMaps = new IdMaps();
        
        // Fetch all the Salesforce Id for the corresponding Dealer Ids in the events.
		List<Account> accts = [SELECT Id, Dealership_ID__c FROM Account WHERE Dealership_ID__c IN :dealerIds FOR UPDATE];
        for(Account a : accts)	{
            variousMaps.dealerIdAccountIdMap.put(a.Dealership_ID__c, a.Id);
        }
        
        // Fetch all the Salesforce Id for the corresponding buyer/seller User Ids in the events.
		List<Contact> conts = [SELECT Id, ID__c FROM Contact WHERE ID__c IN :userIds FOR UPDATE];
        for(Contact c : conts)	{
            variousMaps.userIdContactIdMap.put(c.ID__c, c.Id);
        }

        // Fetch all the Salesforce Id for the corresponding Vehicle VIN in the events.
		List<Vehicle__c> vehicles = [SELECT Id, Name FROM Vehicle__c WHERE Name IN :vins FOR UPDATE];
        for(Vehicle__c v : vehicles)	{
            variousMaps.vinVehicleIdMap.put(v.Name, v.Id);
        }

        // Fetch all the Salesforce Id for the corresponding Auction Number in the events.
		List<Auction__c> auctions = [SELECT Id, Name FROM Auction__c WHERE Name IN :auctionIds FOR UPDATE];
        for(Auction__c v : auctions)	{
            variousMaps.auctionNumberAuctionIdMap.put(v.Name, v.Id);
        }
        
        return variousMaps;
    }

    public static void makeSplunkLog(Object anyObj, Integer lineNumber, String message, String stackTrace, SplunkHelper.LOGLEVEL LogLevel)	{
        SplunkHelper.Log infoLog = new SplunkHelper.Log();
        infoLog.componentName = 'TitleServicePopulateRelatedDataBatch';
        if(anyObj != null) infoLog.sfObject = JSON.serialize(anyObj);
        infoLog.domainSet = new Set<SplunkHelper.DOMAIN>{ SplunkHelper.DOMAIN.ENTERPRISE_APPS};
        infoLog.location = 'TitleServicePopulateRelatedDataBatch: '+ lineNumber;
        infoLog.logLevel = LogLevel;
        infoLog.message = message;
        infoLog.stackTrace = stackTrace;
        infoLog.version = 'v1';
        infoLog.setContext(SplunkHelper.CONTEXT_TYPE.BATCH);
        
        if(!Test.isRunningTest())	SplunkHelper.processLog(infoLog);
    }
    
    /**
     * A collection of Maps
     */
    public class IdMaps	{
        public Map<String,String> dealerIdAccountIdMap = new Map<String,String>();
        public Map<String,String> userIdContactIdMap = new Map<String,String>();
        public Map<String,String> vinVehicleIdMap = new Map<String,String>();
        public Map<String,String> auctionNumberAuctionIdMap = new Map<String,String>();        
        public Map<String,String> acvTitleExtIdTitleMap = new Map<String,String>();        
    }
 

}