objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateDealerDocHandler.cls
public with sharing class CreateDealerDocHandler {
    public static final Id licenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    private final static Integer MAX_RESULTS = 5;
    
    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getLookupInfo(String searchTerm){ //, List<String> selectedIds - removed because it's not used
        // Prepare query paramters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
        Dealer_Docs__c (Id, Account__r.Name, License_Number__c WHERE RecordTypeId = :licenseId) //Id NOT IN :selectedIds AND - removed because it's not used
        LIMIT :MAX_RESULTS];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Accounts & convert them into LookupSearchResult
        String icon = 'standard:note';
        Dealer_Docs__c [] docList = ((List<Dealer_Docs__c>) searchResults[0]);
        for (Dealer_Docs__c d : docList) {
            results.add(new LookupSearchResult(d.Id, 'Dealer Doc', icon, d.License_Number__c, 'Account • '+ d.Account__r.Name));
        }

        return results;
    }

    @AuraEnabled
    public static String getLicenseNumber(Id relLicId){
        //need to auto-populate the license number
        System.debug(relLicId);
        Dealer_Docs__c licDoc = [SELECT Id, License_Number__c FROM Dealer_Docs__c WHERE Id = :relLicId];
        String licNum = licDoc.License_Number__c;
        return licNum;
    }
}