objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Email_Notification__c.object
<CustomObject>
    <description>Object containing records of emails sent to users who have subscribed.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup to the account the user has subscribed to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Email Notifications</relationshipLabel>
        <relationshipName>Email_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealership_Id__c</fullName>
        <description>The tools Id of the dealership the user has subscribed to.</description>
        <label>Dealership Id</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Email_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_VINs__c</fullName>
        <description>The list of VINs from all WOLIs associated with the Work Order the Email Notification record is being created for.</description>
        <label>Work Order VINs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Email Notification</label>
    <nameField>
        <displayFormat>EN-{000000}</displayFormat>
        <label>Email Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Email_Notification_Subscription__c.object
<CustomObject>
    <description>The subscription records for email notifications to be sent to users.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account a user has subscribed to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Email Notification Subscriptions</relationshipLabel>
        <relationshipName>Email_Notification_Subscriptions_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_User_on_Work_Order_Completion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the user should be emailed when a work order for the account has been completed.</description>
        <label>Email User on Work Order Completion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user associated with the subscription record.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Email_Notification_Subscriptions_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The specific Work Order that this Email Notification Subscription is for.</description>
        <inlineHelpText>The specific Work Order that this Email Notification Subscription is for.</inlineHelpText>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Email Notification Subscriptions</relationshipLabel>
        <relationshipName>Email_Notification_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Notification Subscription</label>
    <nameField>
        <displayFormat>ENS-{000000}</displayFormat>
        <label>Email Notification Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Notification Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>Holds the Dealer Type API Name from Account</description>
        <formula>TEXT(WorkOrder.Account.Dealer_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Work Type Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkOrderEmailAlertsTest.cls
@isTest
public class WorkOrderEmailAlertsTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        //need an account
        List<Account> acctList = new List<Account>();
        
        Account acct1 = TestUtility.createAccount('Test1');
        acct1.Dealership_Id__c = '11111';
        acct1.legal_Name__c='Test1';
        acct1.dealer_type__c='1';
        acctList.add(acct1);

        Account acct2 = TestUtility.createAccount('Test2');
        acct2.Dealership_Id__c = '22222';
        acct2.legal_Name__c='Test2';
        acct2.dealer_type__c='1';
        acctList.add(acct2);

        Account acct3 = TestUtility.createAccount('Test3');
        acct3.Dealership_Id__c = '33333';
        acct3.legal_Name__c='Test3';
        acct3.dealer_type__c='1';
        acctList.add(acct3);

        Account acct4 = TestUtility.createAccount('Test4');
        acct4.Dealership_Id__c = '44444';
        acct4.legal_Name__c='Test4';
        acct4.dealer_type__c='1';
        acctList.add(acct4);
        
        Account acct5 = TestUtility.createAccount('Test5');
        acct5.Dealership_Id__c = '55555';
        acct5.legal_Name__c='Test5';
        acct5.dealer_type__c='1';
        acctList.add(acct5);

        insert acctList;

        FSLTestUtility.createAllStructureWithParentST( 'Buffalo', '14209' );
        WorkType wt = [ SELECT Id FROM WorkType WHERE Work_Type_Unique_ID__c = 'inspection' LIMIT 1 ];
        ServiceTerritory st = [ SELECT Id FROM ServiceTerritory LIMIT 1 ];
        
        //need a work order for that account (Account, Priority, Service Territory)
        List<WorkOrder> woList = new List<WorkOrder>();
        woList.add(new WorkOrder(AccountId = acctList[0].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        woList.add(new WorkOrder(AccountId = acctList[1].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        woList.add(new WorkOrder(AccountId = acctList[2].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        woList.add(new WorkOrder(AccountId = acctList[3].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        woList.add(new WorkOrder(AccountId = acctList[3].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        woList.add(new WorkOrder(AccountId = acctList[4].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        woList.add(new WorkOrder(AccountId = acctList[4].Id, ServiceTerritoryId = st.Id, Priority = 'Low', Status = 'New', WorkTypeId = wt.Id));
        insert woList;

        //need some line items
        List<WorkOrderLineItem> woliList = new List<WorkOrderLineItem>();
        woliList.add(new WorkOrderLineItem(WorkOrderId = woList[2].Id, Status = 'New', VIN__c = '1234567890', WorkTypeId = wt.Id));
        woliList.add(new WorkOrderLineItem(WorkOrderId = woList[2].Id, Status = 'New', VIN__c = '0987654321', WorkTypeId = wt.Id));
        insert woliList;

        //need a record of the subscription
        List<Email_Notification_Subscription__c> ensList = new List<Email_Notification_Subscription__c>();
        ensList.add(new Email_Notification_Subscription__c(User__c = UserInfo.getUserId(),Account__c = acctList[0].Id, Email_User_on_Work_Order_Completion__c = true));
        ensList.add(new Email_Notification_Subscription__c(User__c = UserInfo.getUserId(),Account__c = acctList[2].Id, Email_User_on_Work_Order_Completion__c = true));
        ensList.add(new Email_Notification_Subscription__c(User__c = UserInfo.getUserId(),Account__c = acctList[3].Id, Email_User_on_Work_Order_Completion__c = true, Work_Order__c = woList[4].Id));
        ensList.add(new Email_Notification_Subscription__c(User__c = UserInfo.getUserId(),Account__c = acctList[4].Id, Email_User_on_Work_Order_Completion__c = true));
        ensList.add(new Email_Notification_Subscription__c(User__c = UserInfo.getUserId(),Account__c = acctList[4].Id, Email_User_on_Work_Order_Completion__c = true, Work_Order__c = woList[6].Id));
        insert ensList;
    }

    @isTest
    static void workOrderCompletedForAccountWithSubs() {
        //query work order and set status to completed
        WorkOrder wo = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test1' LIMIT 1];
        wo.Status = 'Completed';
        update wo;
        //check that a email notification record has been created
        List<Email_Notification__c> en = [SELECT Id FROM Email_Notification__c];
        System.assertEquals(true, en.size() > 0);
    }

    @isTest
    static void workOrderNotCompleted() {
        //query work order and set status to anything but completed
        WorkOrder wo = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test1' LIMIT 1];
        wo.Status = 'In Progress';
        update wo;
        //make sure that no email notification record has been created
        List<Email_Notification__c> en = [SELECT Id FROM Email_Notification__c];
        System.assertEquals(true, en.size() < 1);
    }

    @isTest
    static void workOrderCompletedForAccountWithNoSubs() {
        //query for work order for the second account
        WorkOrder wo = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test2' LIMIT 1];
        wo.Status = 'Completed';
        update wo;
        //make sure that no email notification record has been created
        List<Email_Notification__c> en = [SELECT Id FROM Email_Notification__c];
        System.assertEquals(true, en.size() < 1);
    }

    @isTest
    static void multipleWorkOrdersUpdated() {
        //get both work orders
        List<WorkOrder> woList = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test1' OR Account.Name = 'Test2' OR Account.Name = 'Test3'];
        for (WorkOrder w : woList) {
            w.Status = 'Completed';
        }
        update woList;
        //make sure only 2 email notification records were created
        List<Email_Notification__c> en = [SELECT Id FROM Email_Notification__c];
        System.assertEquals(true, en.size() == 2);
    }

    @isTest
    static void workOrderCompletedWithWOLIs() {
        //testing new VIN field in email notification record
        //query for work orders for the third account
        WorkOrder wo = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test3' LIMIT 1];
        wo.Status = 'Completed';
        update wo;
        //check that a email notification record has been created
        List<Email_Notification__c> en = [SELECT Id, Work_Order_VINs__c FROM Email_Notification__c];
        System.assertEquals(true, en.size() > 0);
        System.assertEquals(true, en[0].Work_Order_VINs__c != null);
    }

    @isTest
    static void workOrderCompletedForSpecificWorkOrder() {
        //query for work order for the second account
        List<WorkOrder> woList = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test4'];
        System.assertEquals(2, woList.size());
        for(WorkOrder wo : woList) {
            wo.Status = 'Completed';
        }
        update woList;
        //make sure that one email notification record has been created for the two work orders
        List<Email_Notification__c> en = [SELECT Id FROM Email_Notification__c];
        System.assertEquals(1, en.size());
    }

    @isTest
    static void workOrderCompletedForSpecificAndGeneralEmailSubscription() {
        //query for work order for the second account
        List<WorkOrder> woList = [SELECT Id, Status FROM WorkOrder WHERE Account.Name = 'Test4' OR Account.Name = 'Test5'];
        System.assertEquals(4, woList.size());
        for(WorkOrder wo : woList) {
            wo.Status = 'Completed';
        }
        update woList;
        //make sure that one email notification record has been created for the two work orders
        List<Email_Notification__c> en = [SELECT Id FROM Email_Notification__c];
        System.assertEquals(3, en.size());
    }
}