objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Receive_Push__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating if this member should receive mobile push notifications.</description>
        <label>Receive Push</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the date that the Affiliation began.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;admin&quot;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>rep</fullName>
                </value>
                <value>
                    <fullName>admin</fullName>
                    <default>true</default>
                    <label>admin</label>
                </value>
                <value>
                    <fullName>backoffice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>primary_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Appt_Date_Range_by_Work_Type__mdt.object
<CustomObject>
    <description>Default Date Ranges for the Service Appointment&apos;s Earliest Start Permitted to the Due Date based on Work Type.</description>
    <fields>
        <fullName>Date_Range__c</fullName>
        <description>The number of says between the Service Appointment&apos;s Earliest Start Permitted field and the Due Date field.</description>
        <inlineHelpText>The number of says between the Service Appointment&apos;s Earliest Start Permitted field and the Due Date field.</inlineHelpText>
        <label>Date Range</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Appt Date Range by Work Type</label>
    <pluralLabel>Service Appt Date Ranges by Work Type</pluralLabel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateServiceAppointmentTest.cls
@isTest
public class CreateServiceAppointmentTest {

    final static String TERRITORY_NAME = 'Buffalo';
    final static String ZIPCODE = '14209';
    final static String INSPECTION = 'Standard Inspection';
    final static String UNWIND = 'Unwind Inspection';
    final static String ARBITRATION = 'Arbitration Inspection';

    @TestSetup
    static void createTerritory() {
        Account a = TestUtility.createAccount();
        insert a;

        Contact c = TestUtility.createContact( a );
        insert c;

        Affiliation__c aff = new Affiliation__c(
            Account__c=a.id, Contact__c=c.id, Active__c=true, Receive_Push__c = true, 
            Primary_Contact__c = true, Start_Date__c = Date.today().addDays(-7),
            type__c='rep'
        );
        insert aff;

        FSLTestUtility.createAllStructureWithParentST( TERRITORY_NAME, ZIPCODE );
    }

    @IsTest
    static void createStandardWorkOrder(){
        Service_Appt_Date_Range_by_Work_Type__mdt dateRangeRec = [SELECT Label, Date_Range__c FROM Service_Appt_Date_Range_by_Work_Type__mdt WHERE Label = 'Default' LIMIT 1];
        Account testAcct = [ SELECT Id, Name FROM Account LIMIT 1 ];
        ServiceTerritory stRec = [ SELECT Id FROM ServiceTerritory WHERE Name = :TERRITORY_NAME LIMIT 1 ];

        WorkType wtRec = [ SELECT Id, Name, EstimatedDuration, DurationType FROM WorkType WHERE Name = :INSPECTION LIMIT 1 ];
        
        Test.StartTest();
            FSLTestUtility.WorkStruct workReturn = FSLTestUtility.generateWork( wtRec, wtRec, testAcct, ZIPCODE, stRec, 1 );
        Test.StopTest();

        System.assert( workReturn.wo.Id != null, 'The Id of the Work Order was not set' );

        List<ServiceAppointment> serApptList = new List<ServiceAppointment>([ SELECT Id, EarliestStartTime, DueDate FROM ServiceAppointment WHERE ParentRecordId = :workReturn.wo.Id ]);
        System.assertEquals( 1, serApptList.size(), 'There was an unexpected amount of Service Appointments in the system' );
        System.assertEquals(serApptList[0].DueDate, serApptList[0].EarliestStartTime.addDays((Integer) dateRangeRec.Date_Range__c), 'DueDate is 7 days from start date.');
    }

    @IsTest
    static void createUnwindWorkOrder(){
        Account testAcct = [ SELECT Id, Name FROM Account LIMIT 1 ];
        ServiceTerritory stRec = [ SELECT Id FROM ServiceTerritory WHERE Name = :TERRITORY_NAME LIMIT 1 ];

        WorkType wtRec = [ SELECT Id, Name, EstimatedDuration, DurationType FROM WorkType WHERE Name = :UNWIND LIMIT 1 ];
        CreateServiceAppointment.currentDT = DateTime.newInstance(2022, 1, 14, 12, 0, 0);
        
        Test.StartTest();
            FSLTestUtility.WorkStruct workReturn = FSLTestUtility.generateWork( wtRec, wtRec, testAcct, ZIPCODE, stRec, 1 );
        Test.StopTest();

        System.assert( workReturn.wo.Id != null, 'The Id of the Work Order was not set' );

        List<ServiceAppointment> serApptList = new List<ServiceAppointment>([ SELECT Id, EarliestStartTime, DueDate FROM ServiceAppointment WHERE ParentRecordId = :workReturn.wo.Id ]);
        System.assertEquals( 1, serApptList.size(), 'There was an unexpected amount of Service Appointments in the system' );
        System.assert(serApptList[0].DueDate.Date() == Date.newInstance(2022, 1, 18), 'DueDate is not 2 business days from start date.');
        System.assert(serApptList[0].DueDate.time() == serApptList[0].EarliestStartTime.time(), 'DueDate time is not the same as the EarliestStartDates time.');
    }

    @IsTest
    static void createArbitrationWorkOrder(){
        Account testAcct = [ SELECT Id, Name FROM Account LIMIT 1 ];
        ServiceTerritory stRec = [ SELECT Id FROM ServiceTerritory WHERE Name = :TERRITORY_NAME LIMIT 1 ];

        WorkType wtRec = [ SELECT Id, Name, EstimatedDuration, DurationType FROM WorkType WHERE Name = :ARBITRATION LIMIT 1 ];
        CreateServiceAppointment.currentDT = DateTime.newInstance(2022, 1, 14, 12, 0, 0);
        
        Test.StartTest();
            FSLTestUtility.WorkStruct workReturn = FSLTestUtility.generateWork( wtRec, wtRec, testAcct, ZIPCODE, stRec, 1 );
        Test.StopTest();

        System.assert( workReturn.wo.Id != null, 'The Id of the Work Order was not set' );

        List<ServiceAppointment> serApptList = new List<ServiceAppointment>([ SELECT Id, EarliestStartTime, DueDate FROM ServiceAppointment WHERE ParentRecordId = :workReturn.wo.Id ]);
        System.assertEquals( 1, serApptList.size(), 'There was an unexpected amount of Service Appointments in the system' );
        System.assert(serApptList[0].DueDate.Date() == Date.newInstance(2022, 1, 18), 'DueDate is not 2 business days from start date.');
        System.assert(serApptList[0].DueDate.time() == serApptList[0].EarliestStartTime.time(), 'DueDate time is not the same as the EarliestStartDates time.');
    }
}