objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Customer_Success_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Success Advocate - replacing the Title Consultant field</description>
        <inlineHelpText>Please reach out to the Customer Success Advocate for title statuses of “New” and “48 Hour Notice”. Customer Success Advocate has replaced the Title Consultant field.</inlineHelpText>
        <label>Customer Success Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts73Aq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the Title Specialist that works with the Account</inlineHelpText>
        <label>Title Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record for the buyer, person who will get delivery of vehicle</description>
        <label>Buyer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Buyer Dealership)</relationshipLabel>
        <relationshipName>Buyer_Transportation_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Customer_Inquiry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that the CI is related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Inquiries</relationshipLabel>
        <relationshipName>Customer_Inquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+Ops_Case__r.Auction_Number__c,  Ops_Case__r.Auction_Number__r.Name, &quot;_parent&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Related Customer Inquiries</relationshipLabel>
        <relationshipName>Related_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Bucket__c</fullName>
        <description>The bucket that the call falls into.</description>
        <label>Call Bucket</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Buyer Shipment</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Helpdesk</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Titles</fullName>
                </value>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>ACV Transport</fullName>
                </value>
                <value>
                    <fullName>Resolutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Count__c</fullName>
        <description>The number of times that the customers have called about a specific inquiry.</description>
        <label>Call Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <description>The notes from the call.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <description>The subset of Call Bucket, further defines what the dealer is calling about.</description>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Call_Bucket__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Release Slip</fullName>
                </value>
                <value>
                    <fullName>Payment Not Selected</fullName>
                </value>
                <value>
                    <fullName>NSF</fullName>
                </value>
                <value>
                    <fullName>Buyer Payment Status</fullName>
                </value>
                <value>
                    <fullName>Seller Payment Status</fullName>
                </value>
                <value>
                    <fullName>Default Payment Update</fullName>
                </value>
                <value>
                    <fullName>ACV Capital</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Pickup Issue</fullName>
                </value>
                <value>
                    <fullName>Cancel Transport</fullName>
                </value>
                <value>
                    <fullName>Dealmaker</fullName>
                </value>
                <value>
                    <fullName>Make an Offer</fullName>
                </value>
                <value>
                    <fullName>False Proxy</fullName>
                </value>
                <value>
                    <fullName>Goodwill Request</fullName>
                </value>
                <value>
                    <fullName>Multi-Store Buyer</fullName>
                </value>
                <value>
                    <fullName>Ghost Bid</fullName>
                </value>
                <value>
                    <fullName>Account/Contact Update</fullName>
                </value>
                <value>
                    <fullName>User Login Support</fullName>
                </value>
                <value>
                    <fullName>Deactivation</fullName>
                </value>
                <value>
                    <fullName>Good Experience</fullName>
                </value>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Titles</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Unwind</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Valid Business Reason</fullName>
                </value>
                <value>
                    <fullName>Called No Answer, Try Again</fullName>
                </value>
                <value>
                    <fullName>App Education</fullName>
                </value>
                <value>
                    <fullName>Buyer Reported Problem</fullName>
                </value>
                <value>
                    <fullName>Buyer Title Status</fullName>
                </value>
                <value>
                    <fullName>48 Hour Notice Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact related to the CI</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Inquiries</relationshipLabel>
        <relationshipName>Customer_Inquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <formula>IF( ISBLANK(TEXT(Call_Type__c)) , HYPERLINK( &quot;/&quot; + Id,  &quot;Historic Record&quot;, &quot;_self&quot;), HYPERLINK( &quot;/&quot; + Id,  TEXT(Call_Type__c), &quot;_self&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Inquiry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>This is the external id for CI records coming from the Report a Problem process in tools. It is a concatenated id made up of the auction_issues table id and the auction_issues_note table id.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Displays which process a CI record was created by.</description>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>48 Hr Notice Tab</fullName>
                </value>
                <value>
                    <fullName>Log an Interaction</fullName>
                </value>
                <value>
                    <fullName>Report a Problem</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority of the inquiry.</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+Ops_Case__r.Vehicle__c, Ops_Case__r.Vehicle__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle</label>
        <type>Text</type>
    </fields>
    <label>Customer Inquiry</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Customer Inquiry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inquiry_Comment__c.object
<CustomObject>
    <description>Comments made related to each individual Inquiry record on a Support Case.</description>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related auction to the inquiry.</description>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Inquiry Comments</relationshipLabel>
        <relationshipName>Inquiry_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the Customer Inquiry record.</description>
        <label>Customer Inquiry</label>
        <referenceTo>Customer_Inquiry__c</referenceTo>
        <relationshipLabel>Inquiry Comments</relationshipLabel>
        <relationshipName>Inquiry_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inquiry Comment</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Inquiry Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiry Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomerInquiryReportAProblemHandlerTest.cls
@isTest
public class CustomerInquiryReportAProblemHandlerTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        //need two accounts (one with specialist and CSA populated, one without) - think i will set the running user as both of these fields. instead of creating a new user
        List<Account> acctList = new List<Account>();
        acctList.add(TestUtility.createAccount('Test 1'));
        Account a = TestUtility.createAccount('Test 2');
            a.Title_Specialist__c = UserInfo.getUserId();
            a.Customer_Success_Advocate__c = UserInfo.getUserId();
        acctList.add(a);
        insert acctList;
        //need two contacts
        List<Contact> conList = new List<Contact>();
        conList.add(TestUtility.createContact(acctList[0]));
        conList.add(TestUtility.createContact(acctList[1]));
        insert conList;
        //need a vehicle
        Vehicle__c v = TestUtility.createVehicle();
        insert v;
        //need two auctions - switch which account is the buyer and seller
        List<Auction__c> aucList = new List<Auction__c>();
        aucList.add(TestUtility.createAuctionWithUniqueId(acctList[0], conList[0], v));
        aucList.add(TestUtility.createAuctionWithUniqueId(acctList[1], conList[1], v));
        insert aucList;
        //need two title cases - status' should be different
        List<Case> caseList = new List<Case>();
        Case no1 = TestUtility.createTitleCase(aucList[0], acctList[0], conList[0]);
            no1.Status = 'New';
        caseList.add(no1);
        Case no2 = TestUtility.createTitleCase(aucList[1], acctList[1], conList[1]);
            no2.Status = 'Problem';
        caseList.add(no2);
        insert caseList;
    }

    //normal functionality - correct information is provided and CI is created and assigned to the correct people
    @isTest
    static void testNormalBeforeInsertFunction() {
        Account a = [SELECT Id, Title_Specialist__c FROM Account WHERE Title_Specialist__c != null];
        Auction__c au = [SELECT Id FROM Auction__c WHERE Buyer_Dealership__c = :a.Id];
        Contact c = [SELECT Id FROM Contact WHERE AccountId = :a.Id];
        Case ca = [SELECT Id FROM Case WHERE Auction_Number__c = :au.Id];
        Customer_Inquiry__c ci = new Customer_Inquiry__c(
            Account__c = a.Id,
            Auction__c = au.Id,
            Contact__c = c.Id,
            External_Id__c = '1234_1234',
            Origin__c = 'Report a Problem',
            Priority__c = 'Low',
            Call_Count__c = 1,
            Call_Bucket__c = 'Titles',
            Call_Type__c = 'Buyer Title Status',
            Call_Notes__c = 'test notes'
        );
        Test.startTest();
            insert ci;
        Test.stopTest();

        ci = [SELECT Id, Ops_Case__c, Assigned_To__c, Initial_Inquiry_Comment__c FROM Customer_Inquiry__c WHERE Account__c = :a.Id];
        System.assert(ci != null);
        System.assertEquals(ca.Id, ci.Ops_Case__c);
        //System.assertEquals(a.Title_Specialist__c, ci.Assigned_To__c);
        System.assertEquals('test notes', ci.Initial_Inquiry_Comment__c);
    }

    //test assigned to if certain information is missing
    // @isTest
    // static void testMissingSpcialistAndConsultant() {
    //     Account a = [SELECT Id, Title_Specialist__c FROM Account WHERE Title_Specialist__c = null];
    //     Auction__c au = [SELECT Id FROM Auction__c WHERE Buyer_Dealership__c = :a.Id];
    //     Contact co = [SELECT Id FROM Contact WHERE AccountId = :a.Id];
    //     Customer_Inquiry__c ci = new Customer_Inquiry__c(
    //         Account__c = a.Id,
    //         Auction__c = au.Id,
    //         Contact__c = co.Id,
    //         External_Id__c = '1234_1234',
    //         Origin__c = 'Report a Problem',
    //         Priority__c = 'Low',
    //         Call_Count__c = 1,
    //         Call_Bucket__c = 'Titles',
    //         Call_Type__c = 'Buyer Reported Problem',
    //         Call_Notes__c = 'test notes'
    //     );
    //     Test.startTest();
    //         insert ci;
    //     Test.stopTest();

    //     ci = [SELECT Id, Assigned_To__c, Should_Assign_To__c FROM Customer_Inquiry__c WHERE Account__c = :a.Id];
    //     System.assert(ci != null);
    //     System.assertEquals(null, ci.Assigned_To__c);
    //     System.assertEquals('Specialist', ci.Should_Assign_To__c);
    // }

    //test no errors thrown if there are multiple title cases - creates a CI with the most recent case record - can add another case in the beginning of the test
    @isTest
    static void testMultipleTitleCases() {
        //add a new titles case - have to query for the other records first
        Account a = [SELECT Id, Title_Specialist__c FROM Account WHERE Title_Specialist__c = null];
        Auction__c au = [SELECT Id FROM Auction__c WHERE Buyer_Dealership__c = :a.Id];
        Contact co = [SELECT Id FROM Contact WHERE AccountId = :a.Id];
        Case c1 = TestUtility.createTitleCase(au, a, co);
            c1.CreatedDate = System.Today().addDays(-5);
        insert c1;
        
        Customer_Inquiry__c ci = new Customer_Inquiry__c(
            Account__c = a.Id,
            Auction__c = au.Id,
            Contact__c = co.Id,
            External_Id__c = '1234_1234',
            Origin__c = 'Report a Problem',
            Priority__c = 'Low',
            Call_Count__c = 1,
            Call_Bucket__c = 'Titles',
            Call_Type__c = 'Buyer Title Status',
            Call_Notes__c = 'test notes'
        );
        Test.startTest();
            insert ci;
        Test.stopTest();

        Case c2 = [SELECT Id FROM Case WHERE CreatedDate = TODAY AND AccountId = :a.Id]; //should get the other one, hopefully
        ci = [SELECT Id, Ops_Case__c FROM Customer_Inquiry__c WHERE Account__c = :a.Id];
        System.assert(ci != null);
        System.assertEquals(c2.Id, ci.Ops_Case__c);
    }

    //normal functionality - correct information is provided and IC is created
    @isTest
    static void testNormalAfterInsertFunction() {
        Account a = [SELECT Id, Title_Specialist__c FROM Account WHERE Title_Specialist__c != null];
        Auction__c au = [SELECT Id FROM Auction__c WHERE Buyer_Dealership__c = :a.Id];
        Contact co = [SELECT Id FROM Contact WHERE AccountId = :a.Id];
        Customer_Inquiry__c ci = new Customer_Inquiry__c(
            Account__c = a.Id,
            Auction__c = au.Id,
            Contact__c = co.Id,
            External_Id__c = '1234_1234',
            Origin__c = 'Report a Problem',
            Priority__c = 'Low',
            Call_Count__c = 1,
            Call_Bucket__c = 'Titles',
            Call_Type__c = '48 Hour Notice Request', //48 Hour Submit
            Call_Notes__c = 'this is a test note'
        );
        Test.startTest();
            insert ci;
        Test.stopTest();

        ci = [SELECT Id, Assigned_To__c FROM Customer_Inquiry__c WHERE Account__c = :a.Id];
        System.assertEquals(null, ci.Assigned_To__c);
        Inquiry_Comment__c ic = [SELECT Id, Customer_Inquiry__c, Inquiry_Notes__c FROM Inquiry_Comment__c]; //maybe i should add a where clause here? but should only be one
        System.assert(ic != null);
        System.assertEquals(ci.Id, ic.Customer_Inquiry__c);
        System.assertEquals('this is a test note', ic.Inquiry_Notes__c);
    }
}