objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>All_Time_Arbs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>All Time Arbs</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Most_Recent_Arb__c</fullName>
        <label>Date Most Recent Arb</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_First_Buy__c</fullName>
        <label>Date of First Purchase</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Purchase__c</fullName>
        <label>Date of Last Purchase</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchases_All_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>All Time Purchases</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Make__c</fullName>
        <description>Set by Process Builder automation.</description>
        <label>Make</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vehicle_Make</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winning_Bid_Price__c</fullName>
        <label>High Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>floor_price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_Confusion__c</fullName>
        <inlineHelpText>Select “Yes” if buyer brings up confusion over green light policy</inlineHelpText>
        <label>Buyer Confusion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buyer_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record for the buyer, person who will get delivery of vehicle</description>
        <label>Buyer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Buyer Dealership)</relationshipLabel>
        <relationshipName>Buyer_Transportation_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <description>Field on unwind case layout to set a floor price</description>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseTriggerFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>CaseTriggerFlag</label>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>make__c</fullName>
        <description>The make (manufacturer) of the vehicle.</description>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/AccountUpdateLogisticsFromCaseTest.cls
@isTest
public class AccountUpdateLogisticsFromCaseTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        
        insert new CaseTriggerFlag__c(Name='Default', Enabled__c = true);
        List<Account> accountList = new List<Account>();
        accountList.add(new Account(Name = 'seller', IST_Account_Owner__c = UserInfo.getUserId()));
        accountList.add(new Account(Name = 'buyer', IST_Account_Owner__c = UserInfo.getUserId(), Purchases_All_Time__c = 2));
        Vehicle__c newCar = new Vehicle__c(Year__c='2009',Make__c='test make', Model__c='test model', VIN__c = '1234567890102030');
        insert newCar;
        insert accountList;
        Date firstDate = System.Today().addDays(-3);
        Date secondDate = System.Today().addDays(-2);
        Date thirdDate = System.Today().addDays(-1);

        Vehicle__c car = [SELECT Id FROM Vehicle__c LIMIT 1];

        Auction__c newAuction = new Auction__c(Status__c = 'Ended_Accepted', End_Time__c = secondDate, Buyer_Dealership__c = accountList[1].Id, 
                                                Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 500, Winning_Bid_Price__c = 450, Vehicle_Id__c = car.Id);
        insert newAuction;

        Auction__c caseAuc = [SELECT Id FROM Auction__c LIMIT 1];
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Arbitration Claim').getRecordTypeId();
        List<Case> caseList = new List<Case>();
        Case testArb = new Case(Status = 'Closed', RecordTypeId = recordTypeId, AccountId = accountList[1].Id, Seller_Dealership__c = accountList[0].Id, Origin = 'Phone',
                                                    CreatedDate = firstDate, ClosedDate = secondDate, Buyer_Confusion__c = 'No', Auction_Number__c = caseAuc.Id);
        caseList.add(testArb);
        Case testArb2 = new Case(Status = 'Closed', RecordTypeId = recordTypeId, AccountId = accountList[1].Id, Seller_Dealership__c = accountList[0].Id, Origin = 'Phone',
                                                    CreatedDate = firstDate, ClosedDate = thirdDate, Buyer_Confusion__c = 'No', Auction_Number__c = caseAuc.Id);
        caseList.add(testArb2);
        Case testArb3 = new Case(Status = 'New', RecordTypeId = recordTypeId, AccountId = accountList[1].Id, Seller_Dealership__c = accountList[0].Id, Origin = 'Phone',
                                                    CreatedDate = firstDate, Buyer_Confusion__c = 'No', Auction_Number__c = caseAuc.Id);
        caseList.add(testArb3);
        insert caseList;
        // AccountUpdateLogisticsFromCase.toggle();
        // update caseList;
    }

    @isTest
    static void mainTest() {
        List<Case> caseList = [SELECT Id FROM CASE];
        update caseList;
        List<Account> buyerAccount = [SELECT Id, Name, All_Time_Arbs__c, Date_Most_Recent_Arb__c, Date_of_Last_Purchase__c, Date_of_First_Buy__c FROM Account WHERE Name = 'buyer'];
        List<Account> sellerAccount = [SELECT Id, Name FROM Account WHERE Name = 'seller'];
        Date thirdDate = System.Today().addDays(-1);

        System.debug('All Time Arbs: ' + buyerAccount[0].All_Time_Arbs__c);
        System.debug('Date of Most Recent Arb: ' + buyerAccount[0].Date_Most_Recent_Arb__c);
        System.debug('Date of Last Purchase: ' + buyerAccount[0].Date_of_Last_Purchase__c);
        System.debug('Date of First Purchase: ' + buyerAccount[0].Date_of_First_Buy__c);

        System.assertEquals(3, buyerAccount[0].All_Time_Arbs__c);
        System.assertEquals(thirdDate, buyerAccount[0].Date_Most_Recent_Arb__c);
    }

    @isTest
    static void selfReferenceTest() {
        List<Case> caseList = [SELECT Id FROM CASE];
        update caseList;
        //Account buyerAccount = [SELECT Id, Name, All_Time_Arbs__c, Date_Most_Recent_Arb__c, IST_Account_Owner__c FROM Account WHERE Name = 'buyer'];
        Account sellerAccount = [SELECT Id, Name FROM Account WHERE Name = 'seller'];
        User newUser = [SELECT Id FROM User WHERE Name LIKE 'Paul%' LIMIT 1];
        //buyerAccount.IST_Account_Owner__c = newUser.Id;
        sellerAccount.IST_Account_Owner__c = newUser.Id;
        //update buyerAccount;
        update sellerAccount;
    }
}