objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>primary_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Seller_Contact_Email__c</fullName>
        <description>This field is auto-populated via apex code to stamp the selling dealership&apos;s primary contact&apos;s email. Coed done by Manmeet Vasser</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Seller Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Title_Information</fullName>
        <active>true</active>
        <businessProcess>Title Information Process</businessProcess>
        <description>Use this record type to process a title.</description>
        <label>Title Information</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/SetTitleContactEmail.cls
/**
 * @description https://acvauctions.atlassian.net/browse/TDO-292
 * 
 * @author Manmeet Vaseer
 * @date 09/03/2021
 * 
 */
public class SetTitleContactEmail extends TriggerInterface {

    public static String TITLE_INFO_RT = 'Title_Information';
    
    public override void beforeInsert( List<SObject> newList ){
        processCaseList( (List<Case>) newList, new Map<Id, Case>() );
    }

    public override void beforeUpdate( Map<Id,SObject> oldMap, Map<Id,SObject> newMap ){
        processCaseList( (List<Case>) newMap.values(), (Map<Id, Case>) oldMap );
    }

    private void processCaseList( List<Case> newCaseLst, Map<Id, Case> oldMap ) {
        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(TITLE_INFO_RT).getRecordTypeId();
        
        List<Id> sellerAccountIds = new List<Id>();
        List<Case> titleCaseList = new List<Case>();
        for ( Case caseRec : newCaseLst ) {
            // Only apply this logic to Title Information record type.
            if(caseRec.RecordTypeId == titlesRecordType)	{
                titleCaseList.add( caseRec );
                if(caseRec.Seller_Dealership__c != null) sellerAccountIds.add(caseRec.Seller_Dealership__c);
            }
        }

        if ( !titleCaseList.isEmpty() && !sellerAccountIds.isEmpty() ) {
            setTitleContactEmails( sellerAccountIds, titleCaseList);
        }
    }
    
    private void setTitleContactEmails(List<Id> sellerAccountIds, List<Case> newCaseList){        
        // Affiliations related to all Cases
        List<Affiliation__c> relatedAffiliations = [SELECT Id, Account__c, Contact__c, Contact__r.Email FROM Affiliation__c WHERE Account__c IN :sellerAccountIds AND Primary_Contact__c = true];
        Map<Id, Affiliation__c> sellerAcctIdAffiliationMap = new Map<Id, Affiliation__c>();
        for(Affiliation__c aff : relatedAffiliations)	{
            sellerAcctIdAffiliationMap.put(aff.Account__c, aff);
        }
        
        for(Case caseRec : newCaseList)	{
            if(sellerAcctIdAffiliationMap.get(caseRec.Seller_Dealership__c) != null) caseRec.Seller_Contact_Email__c = sellerAcctIdAffiliationMap.get(caseRec.Seller_Dealership__c)?.Contact__r?.Email;
            else caseRec.Seller_Contact_Email__c = null; // if the related seller account not set/found in the Case
        }        
    }
}