objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Guid__c</fullName>
        <description>This is the unique Organization Guid for Standard Dealership Accounts</description>
        <externalId>true</externalId>
        <label>Organization Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Federal Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cell__c</fullName>
        <label>Dealer Phone (cell)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>dba_trade_name__c</fullName>
        <description>Doing Business As</description>
        <label>DBA Trade Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the date that the Affiliation began.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;admin&quot;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>rep</fullName>
                </value>
                <value>
                    <fullName>admin</fullName>
                    <default>true</default>
                    <label>admin</label>
                </value>
                <value>
                    <fullName>backoffice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>Unique Id in ACV databases - used for integration purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Dealership Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>primary_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <description>acv_prod id found on the users table used to identify internal users</description>
        <externalId>true</externalId>
        <inlineHelpText>This corresponds to the User&apos;s ACV Tools ID</inlineHelpText>
        <label>ACV User Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/IdentityServiceCreateDealerWithContact.cls
@RestResource(urlMapping='/IdentityService/Registration/createDealerWithContact')
global with sharing class IdentityServiceCreateDealerWithContact {

    private static final Map<String, String> AccountTypeMap = new Map<String,String>{'unknown'=>'0', 'franchise'=>'1', 'independent'=>'2', 'wholesaler'=>'3', 'acv certified independent'=>'4', 'commercial'=>'5'};
    private static final string standardAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Standard').getRecordTypeId();

    @HTTPPost
    global static void createDealerWithContact(CreateDealerRequest newDealer){
        ACVAPIHelper.SFResponse identityResult = new ACVAPIHelper.SFResponse(newDealer, '', 200);
        identityResult.originalRequest = newDealer;
        String endpointURL = URL.getSalesforceBaseUrl().toExternalForm()+'/apex/services/IdentityService/Registration/createDealerWithContact';
        Map<String, String> headerMap = new Map<String, String>();
        headerMap.put('Content-Type', 'application/json');

        List<Contact> conList = [select id, Id__c, AccountId from Contact where Id__c = :newDealer.User_Id];
        if(conList.isEmpty()){
            identityResult.message = 'User Not Found';
            identityResult.statusCode = 409;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', 'IdentityService.createDealerWithContact Line: '+ACVUtility.currentLineNumber(), SplunkHelper.LOGLEVEL.ERROR, 409);
            identityResult.generateResponse(headerMap);
            return;
        }

        String sanitizedLegalName= String.IsBlank(newDealer.Legal_Name)? '' : newDealer.Legal_Name.replaceAll('`','\'');
        List<Account> accList = [select id from Account where legal_name__c = :sanitizedLegalName and BillingStreet=:newDealer.Street 
                                    and BillingCity=:newDealer.City];
        if(!String.isBlank(sanitizedLegalName) && !accList.isEmpty()){
            identityResult.message = 'Duplicate dealer found';
            identityResult.statusCode = 409;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', 'IdentityService.createDealerWithContact Line: '+ACVUtility.currentLineNumber(), SplunkHelper.LOGLEVEL.ERROR, 409);
            identityResult.generateResponse(headerMap);
            return;
        }
        //Phone validator will need updated in the future for country codes
        if(!String.isBlank(newDealer.Cell) && !ACVUtility.isValidPhone(newDealer.Cell)){
            identityResult.message = 'Invalid Phone Format for Cell';
            identityResult.statusCode = 400;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', 'IdentityService.createDealerWithContact Line: '+ACVUtility.currentLineNumber(), SplunkHelper.LOGLEVEL.ERROR, 400);
            identityResult.generateResponse(headerMap);
            return;
        }
        if(!String.isBlank(newDealer.Phone) && !ACVUtility.isValidPhone(newDealer.Phone)){
            identityResult.message = 'Invalid Phone Format for Phone';
            identityResult.statusCode = 400;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', 'IdentityService.createDealerWithContact Line: '+ACVUtility.currentLineNumber(), SplunkHelper.LOGLEVEL.ERROR, 400);
            identityResult.generateResponse(headerMap);
            return;
        }
 
        Account newAccount = new Account();
        Savepoint sp = Database.setSavepoint();
        try{
            String compondPhone = String.isBlank(newDealer.phoneExt) ? newDealer.Phone : newDealer.Phone+';'+newDealer.phoneExt;
            String sanitizedDBATradeName= String.IsBlank(newDealer.DBA_Trade_Name)? '' : newDealer.DBA_Trade_Name.replaceAll('`','\'');
            String namePlaceHolder = String.isBlank(sanitizedDBATradeName) ? sanitizedLegalName : sanitizedDBATradeName;
            newAccount = new Account(recordTypeId = standardAccountRecordTypeId, Active__c = false, dba_trade_name__c = sanitizedDBATradeName, 
                            Name = namePlaceHolder, cell__c = newDealer.Cell, Phone = compondPhone, Status__c = '3', legal_name__c = sanitizedLegalName, 
                            Dealer_Type__c = AccountTypeMap.get(newDealer.Dealership_Type.toLowerCase()), Organization_Guid__c = ACVUtility.NewGuid(),
                            BillingStreet= newDealer.Street, BillingCity= newDealer.City, BillingState= newDealer.State, BillingPostalCode= newDealer.Zip_code,
                            Tax_Id__c= newDealer.Federal_Tax_ID, License_Number__c= newDealer.License_Number);
            insert newAccount;
        }
        catch(Exception e){
            identityResult.message = 'Error Generating Account';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', e.getStackTraceString()+':'+e.getMessage(), SplunkHelper.LOGLEVEL.ERROR, 500);
            identityResult.generateResponse(headerMap);
            Database.rollback( sp );
            return;
        }
        newAccount = [SELECT Id, Name, Status__c, Organization_Guid__c, Dealer_Type__c, legal_name__c, cell__c, dba_trade_name__c, Active__c, Phone, Dealership_ID__c FROM Account WHERE Id = :newAccount.Id limit 1];
        conList[0].AccountId = newAccount.Id;

        try{
            update conList;
            
        }
        catch(Exception e){
            identityResult.message = 'Error Relating Contact or Associating Location';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', e.getStackTraceString()+':'+e.getMessage(), SplunkHelper.LOGLEVEL.ERROR, 500);
            identityResult.generateResponse(headerMap);
            Database.rollback( sp );
            return;
        }

        if(!String.isBlank(newDealer.Street))
        {
                AddressHelper.AddressWrapper aw = new AddressHelper.AddressWrapper();
                aw.Street =  newDealer.Street;
                aw.City =  newDealer.City;
                aw.State = newDealer.State;
                aw.PostalCode =  newDealer.Zip_code;
                aw.Country = 'US'; 
                aw.type = 'billing';
               
            try {
                insert AddressHelper.generateAddressStack(aw, newAccount.Id);
            } 
            catch(Exception e){
                identityResult.message = 'Error Generating Associated Location';
                identityResult.statusCode = 500;
                IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', e.getStackTraceString(), SplunkHelper.LOGLEVEL.ERROR, 500);
                identityResult.generateResponse(headerMap);
                Database.rollback( sp );
                return;
            }
        }
        Affiliation__c newAff = new Affiliation__c();
        newAff.Account__c = newAccount.Id;
        newAff.Contact__c = conList[0].Id;
        newAff.Active__c = True;
        newAff.primary_contact__c = True;
        newAff.type__c = 'admin';
        newAff.id__c = IdentityHelper.createAffiliationId(newAccount.Dealership_ID__c, conList[0].ID__c);
        newAff.Start_Date__c = System.today();

        try{
            insert newAff;
        }
        catch(Exception e){
            identityResult.message = 'Error Generating Affiliation';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PUT', e.getStackTraceString(), SplunkHelper.LOGLEVEL.ERROR, 500);
            identityResult.generateResponse(headerMap);
            Database.rollback( sp );
            return;
        }

        CreateDealerResponse dcr = new CreateDealerResponse();
        dcr.Dealer_Id = newAccount.Dealership_ID__c;
        dcr.Affiliation_Id = newAff.id__c;
        dcr.Dealer_GUID = newAccount.Organization_Guid__c;
        dcr.Sanitized_Legal_Name= newAccount.legal_name__c;
        dcr.Sanitized_DBA_Name= newAccount.dba_trade_name__c;
        identityResult.message = 'Account Created';
        identityResult.statusCode = 201;
        identityResult.apiResponse = dcr;
        IdentityHelper.makeLog(newDealer, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'POST', 'IdentityService.createDealerWithContact Line: '+ACVUtility.currentLineNumber(), SplunkHelper.LOGLEVEL.INFO, 201);
        identityResult.generateResponse(headerMap);
    }

    global class CreateDealerRequest{
        global String DBA_Trade_Name;
        global String Legal_Name;
        global String User_Id;
        global String Phone;
        global String phoneExt;
        global String Cell;
        global String Dealership_Type;
        public string Street;
        public string City;
        public string State;
        public string Zip_code;
        public string Federal_Tax_ID;
        public string License_Number;
        
    }

    global class CreateDealerResponse{
        global String Dealer_Id;
        global String Dealer_GUID;
        global String Affiliation_Id;
        global String Sanitized_Legal_Name;
        global String Sanitized_DBA_Name;
    }
}