objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>IST_Last_Call_Date__c</fullName>
        <description>The date of the last Log a Call on the Support Case</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Automatically set by Log a Call entries on this Support Case, reflecting last saved record.</inlineHelpText>
        <label>IST Last Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Follow_Up__c</fullName>
        <description>Written from the Follow Up Date from Log A Call</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Automatically set by data entered on Log a Call. Should only be manually overwritten if decision to alter date is not a result of conversation with dealer.</inlineHelpText>
        <label>Next Follow Up</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ops_Last_Call_Date__c</fullName>
        <description>The date of the last Log a Call on the Title Case</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Automatically set by Log a Call entries on the Title Case, reflecting last saved record.</inlineHelpText>
        <label>Ops Last Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>Support Case</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Customer_Inquiry__c.object
<CustomObject>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Related Customer Inquiries</relationshipLabel>
        <relationshipName>Related_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <formula>IF( ISBLANK(TEXT(Call_Type__c)) , HYPERLINK( &quot;/&quot; + Id,  &quot;Historic Record&quot;, &quot;_self&quot;), HYPERLINK( &quot;/&quot; + Id,  TEXT(Call_Type__c), &quot;_self&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Inquiry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ops_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ops Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Related Support Cases</relationshipLabel>
        <relationshipName>Related_Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the inquiry.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>AM Follow Up</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inquiry Resolved</fullName>
                    <isActive>false</isActive>
                    <label>Inquiry Resolved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+Ops_Case__r.Vehicle__c, Ops_Case__r.Vehicle__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle</label>
        <type>Text</type>
    </fields>
    <label>Customer Inquiry</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Customer Inquiry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inquiry_Comment__c.object
<CustomObject>
    <description>Comments made related to each individual Inquiry record on a Support Case.</description>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related auction to the inquiry.</description>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Inquiry Comments</relationshipLabel>
        <relationshipName>Inquiry_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the Customer Inquiry record.</description>
        <label>Customer Inquiry</label>
        <referenceTo>Customer_Inquiry__c</referenceTo>
        <relationshipLabel>Inquiry Comments</relationshipLabel>
        <relationshipName>Inquiry_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feed_Task_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feed Task Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inquiry_Notes__c</fullName>
        <description>Notes related to the Inquiry in the Customer Inquiry lookup field.</description>
        <label>Inquiry Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ops_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related ops case. ie: titles, arb, etc.</description>
        <label>Ops Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Inquiry Comments (Ops Case)</relationshipLabel>
        <relationshipName>Inquiry_Comments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the CI record.</description>
        <formula>TEXT(Customer_Inquiry__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Inquiry Comment</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Inquiry Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiry Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetFollowUpDatesTest.cls
@isTest
public class SetFollowUpDatesTest {
    
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account a = TestUtility.createAccount();
        insert a;
        Contact c = TestUtility.createContact(a);
        insert c;
        Vehicle__c v = TestUtility.createVehicle();
        insert v;
        Auction__c au = TestUtility.createAuction(v);
        insert au;

        List<Case> titleCases = new List<Case>();
        List<Case> allCases = new List<Case>();
        Case titleCase = TestUtility.createTitleCase(au, a, c);
        allCases.add(titleCase);
        Case openSupportCase = TestUtility.createSupportCase(a);
        allCases.add(openSupportCase);
        Case closedSupportCase = TestUtility.createSupportCase(a);
        closedSupportCase.Status = 'Closed';
        allCases.add(closedSupportCase);
        Case arbCase = TestUtility.createCase(au,v,a,c);
        allCases.add(arbCase);
        insert allCases;

        titleCases.add(titleCase);
        List<Customer_Inquiry__c> inquiries = new List<Customer_Inquiry__c>();
        inquiries.addAll(TestUtility.createRelatedCasesCaseContext(titleCases,openSupportCase));
        inquiries.addAll(TestUtility.createRelatedCasesCaseContext(titleCases,closedSupportCase));
        insert inquiries;
    }

    @isTest
    static void testNextFollowLoggedOnTitleCaseByTitleUser(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Titles'];
        User titleUser = TestUtility.createUser(p.Id);

        Case titleCase = [SELECT Id FROM Case WHERE Subject = 'Title Testing'];
        Test.startTest();
        System.runAs(titleUser){
            Task loggedCall = new Task();
            loggedCall.Call_On_Title_Case__c = true;
            loggedCall.WhatId = titleCase.Id;
            loggedCall.Reason_for_Outreach__c = 'Aged Title';
            loggedCall.Reason_For_Title_Delay__c = 'DMV Delay';
            loggedCall.Follow_Up_Date__c = System.today().addDays(2);
            insert loggedCall;
        }
        Test.stopTest();

        titleCase = [SELECT Id, Next_Follow_Up__c, Ops_Last_Call_Date__c FROM Case WHERE Subject = 'Title Testing'];
        System.assertEquals(System.today().addDays(2),titleCase.Next_Follow_Up__c, 'Next follow up date should equal follow up date on logged call');
        System.assertEquals(System.today(),titleCase.Ops_Last_Call_Date__c, 'Ops Last Call up date should be set to today');
    }

    @isTest
    static void testNextFollowLoggedOnTitleCaseByNonTitleUser(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Territory Manager'];
        User territoryManager = TestUtility.createUser(p.Id);

        Case titleCase = [SELECT Id FROM Case WHERE Subject = 'Title Testing'];
        Test.startTest();
        System.runAs(territoryManager){
            Task loggedCall = new Task();
            loggedCall.Call_On_Title_Case__c = true;
            loggedCall.WhatId = titleCase.Id;
            loggedCall.Reason_for_Outreach__c = 'Other';
            insert loggedCall;
        }
        Test.stopTest();

        titleCase = [SELECT Id, Next_Follow_Up__c, Ops_Last_Call_Date__c FROM Case WHERE Subject = 'Title Testing'];
        System.assertEquals(null,titleCase.Next_Follow_Up__c, 'Next follow up date should equal follow up date on logged call');
        System.assertEquals(null,titleCase.Ops_Last_Call_Date__c, 'Ops Last Call up date should be set to today');
    }

    @isTest
    static void testLastFollowOnRelatedSupportCase(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Title Manager'];
        User titleUser = TestUtility.createUser(p.Id);

        Case titleCase = [SELECT Id FROM Case WHERE Subject = 'Title Testing'];
        Test.startTest();
        System.runAs(titleUser){
            Task loggedCall = new Task();
            loggedCall.Call_On_Title_Case__c = true;
            loggedCall.WhatId = titleCase.Id;
            loggedCall.Description = 'Here are the comments';
            loggedCall.Follow_Up_Date__c = System.Today().addDays(3);
            loggedCall.Reason_For_Title_Delay__c = 'Unable to Reach';
            loggedCall.Reason_for_Outreach__c = 'Other';
            insert loggedCall;
        }
        Test.stopTest();

        Task callLogged = [SELECT Id, Description, Reason_For_Title_Delay__c FROM Task WHERE WhatId = :titleCase.Id];
        List<Inquiry_Comment__c> comments = [SELECT Id, Feed_Task_Created__c, Inquiry_Notes__c FROM Inquiry_Comment__c WHERE Customer_Inquiry__r.Ops_Case__c = :titleCase.Id];
        for(Inquiry_Comment__c ic : comments){
            System.assertEquals(true,ic.Feed_Task_Created__c, 'When Inquiry comment is created by log a call on ops case, Feed_Task_Created__c should set to true');
            System.assert(ic.Inquiry_Notes__c.contains(callLogged.Description), 'When Inquiry comment is created by log a call description should populate in Inquiry Notes');
            System.assert(ic.Inquiry_Notes__c.contains(callLogged.Reason_For_Title_Delay__c), 'When Inquiry comment is created by log a call reason for title delay should populate in Inquiry Notes');
        }
    }

    @isTest
    static void testCallLoggedNoUpdateToClosedInquiry(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Title Manager'];
        User titleUser = TestUtility.createUser(p.Id);

        Case titleCase = [SELECT Id FROM Case WHERE Subject = 'Title Testing'];
        List<Customer_Inquiry__c> ciList = [SELECT Id, Status__c FROM Customer_Inquiry__c];
        for (Customer_Inquiry__c ci : ciList) {
            ci.Status__c = 'Closed';
        }
        update ciList;

        Test.startTest();
        System.runAs(titleUser){
            Task loggedCall = new Task();
            loggedCall.Call_On_Title_Case__c = true;
            loggedCall.WhatId = titleCase.Id;
            loggedCall.Description = 'Here are the comments';
            loggedCall.Follow_Up_Date__c = System.Today().addDays(3);
            loggedCall.Reason_For_Title_Delay__c = 'Unable to Reach';
            loggedCall.Reason_for_Outreach__c = 'Other';
            insert loggedCall;
        }
        Test.stopTest();

        System.assertEquals(0, [SELECT Count() FROM Inquiry_Comment__c], 'Inquiry comments should only be logged on open Customer Inquries');
    }

    @isTest
    static void testNonTitleCallLogged(){ 
        Case titleCase = [SELECT Id FROM Case WHERE Subject = 'Title Testing'];
        Test.startTest();
        Task loggedCall = new Task();
        loggedCall.WhatId = titleCase.Id;
        loggedCall.Follow_Up_Date__c = System.today().addDays(3);
        insert loggedCall;
        Test.stopTest();

        titleCase = [SELECT Id, Next_Follow_Up__c, Ops_Last_Call_Date__c FROM Case WHERE Subject = 'Title Testing'];
        System.assertEquals(null,titleCase.Next_Follow_Up__c, 'Next follow up date should not be populated if Task is not created with Call On Title Case set to true');
        System.assertEquals(null,titleCase.Ops_Last_Call_Date__c, 'Ops Last Call up date should not be populated if Task is not created with Call On Title Case set to true');
    }

    @isTest
    static void testCallLoggedOnSupportCaseWithISTUser(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Inside Sales - Activation'];
        User istUser = TestUtility.createUser(p.Id);

        Id supportRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Case supportCase = [SELECT Id FROM Case WHERE RecordTypeId = :supportRecordTypeId limit 1];
        Test.startTest();
        System.runAs(istUser){
            Task loggedCall = new Task();
            loggedCall.WhatId = supportCase.Id;
            insert loggedCall;
        }
        Test.stopTest();

        supportCase = [SELECT Id, IST_Last_Call_Date__c FROM Case WHERE Id = :supportCase.Id];
        System.assertEquals(System.today(),supportCase.IST_Last_Call_Date__c, 'IST Last Call should be updated to today when on a support case that has a call logged on it');
    }

    @isTest
    static void testCallLoggedOnSupportCaseWithOutISTUser(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Territory Manager'];
        User territoryManager = TestUtility.createUser(p.Id);

        Id supportRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Support').getRecordTypeId();
        Case supportCase = [SELECT Id FROM Case WHERE RecordTypeId = :supportRecordTypeId limit 1];
        Test.startTest();
        System.runAs(territoryManager){
            Task loggedCall = new Task();
            loggedCall.WhatId = supportCase.Id;
            insert loggedCall;
        }
        Test.stopTest();

        supportCase = [SELECT Id, IST_Last_Call_Date__c FROM Case WHERE Id = :supportCase.Id];
        System.assertEquals(null,supportCase.IST_Last_Call_Date__c, 'IST Last Call should not be updated when not done by IST User profile');
    }

    @isTest
    static void testCallLoggedWithWhoId(){ 
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Test.startTest();
        Task loggedCall = new Task();
        loggedCall.WhoId = con.Id;
        insert loggedCall;
        Test.stopTest();

        System.assertEquals(1,[SELECT COUNT() FROM Task LIMIT 1], 'Task should create without WhatId and with a WhoId');
    }

    @isTest
    static void testCallLoggedWithOutWhatId(){ 
        Test.startTest();
        Task loggedCall = new Task();
        insert loggedCall;
        Test.stopTest();

        System.assertEquals(1,[SELECT COUNT() FROM Task LIMIT 1], 'Task should create without WhatId');
    }

    @isTest
    static void testCallLoggedOnArbitrationCase(){ 
        Id arbitrationRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Arbitration Claim').getRecordTypeId();
        Case arbCase = [SELECT Id FROM Case WHERE RecordTypeId = :arbitrationRecordTypeId limit 1];
        Test.startTest();
        Task loggedCall = new Task();
        loggedCall.WhatId = arbCase.Id;
        insert loggedCall;
        Test.stopTest();

        arbCase = [SELECT Id, IST_Last_Call_Date__c FROM Case WHERE Id = :arbCase.Id];
        System.assertEquals(null,arbCase.IST_Last_Call_Date__c, 'IST Last Call should not be updated on arbitration Case');
    }
}