objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <description>The most recent resale number for the account.</description>
        <label>Permit/Resale Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Docs_Uploaded__c</fullName>
        <description>The date/time that all required docs were uploaded for this account.</description>
        <label>Required Docs Uploaded</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <label>Permit/Resale Number</label>
        <type>TextArea</type>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State_Abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

classes/DealerDocInsertTimeStampForAcctTest.cls
@isTest
public class DealerDocInsertTimeStampForAcctTest {
    public static final Id licenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id resaleId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();

    @TestSetup
    static void makeData() {
        List<Account> acctList = new List<account>();
        DateTime testDate = System.Today().addDays(-5);
        acctList.add(new Account(Name = 'Test 1', IST_Account_Owner__c = UserInfo.getUserId()));
        acctList.add(new Account(Name = 'Test 2', IST_Account_Owner__c = UserInfo.getUserId(), Required_Docs_Uploaded__c = testDate));
        insert acctList;
    }
    
    @isTest
    static void licenseInSpecialStateTest() {
        //need an account
        Account testAcct = [SELECT Id FROM Account WHERE Name = 'Test 1'];
        //expDate
        Date expDate = System.Today().addMonths(5);
        //need a license in a special state
        Dealer_Docs__c testDoc = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '11111', Expiration_Date__c = expDate);
        insert testDoc;

        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account WHERE Name = 'Test 1'];
        System.assertNotEquals(null, testAcct.Required_Docs_Uploaded__c, 'Field did not populate correctly (License in special state)');
    }

    @isTest
    static void licenseWithResaleInSystem() {
        //need an account
        Account testAcct = [SELECT Id FROM Account WHERE Name = 'Test 1'];
        //expDate
        Date expDate = System.Today().addMonths(5);
        //insert resale doc
        Dealer_Docs__c resale = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'LA', Permit_Resale_Number__c = '11111', Expiration_Date__c = expDate);
        insert resale;
        //start test and insert license
        Dealer_Docs__c license = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'LA', License_Number__c = '22222', Expiration_Date__c = expDate);
        Test.startTest();
            insert license;
        //stop test
        Test.stopTest();
        //system.assert
        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account WHERE Name = 'Test 1'];
        System.assertNotEquals(null, testAcct.Required_Docs_Uploaded__c, 'Field did not populate correctly (License not in special state)');
    }

    @isTest
    static void resaleWithLicenseInSystem() {
        //need an account
        Account testAcct = [SELECT Id FROM Account WHERE Name = 'Test 1'];
        //expDate
        Date expDate = System.Today().addMonths(5);
        //insert license
        Dealer_Docs__c license = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'LA', License_Number__c = '22222', Expiration_Date__c = expDate);
        insert license;
        //start test and insert resale
        Dealer_Docs__c resale = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'LA', Permit_Resale_Number__c = '11111', Expiration_Date__c = expDate);
        Test.startTest();
            insert resale;
        //stop test
        Test.stopTest();
        //system.assert
        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account WHERE Name = 'Test 1'];
        System.assertNotEquals(null, testAcct.Required_Docs_Uploaded__c, 'Field did not populate correctly (Resale not in special state)');
    }

    @isTest
    static void onlyLicense() {
        //need an account
        Account testAcct = [SELECT Id FROM Account WHERE Name = 'Test 1'];
        //expDate
        Date expDate = System.Today().addMonths(5);
        //insert license not in a special state
        Dealer_Docs__c license = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'LA', License_Number__c = '22222', Expiration_Date__c = expDate);
        insert license;
        //should not populate the field
        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account WHERE Name = 'Test 1'];
        //system.assert
        System.assertEquals(null, testAcct.Required_Docs_Uploaded__c, 'Field populated with only one doc (License)');
    }

    @isTest
    static void onlyResale() {
        //need an account
        Account testAcct = [SELECT Id FROM Account WHERE Name = 'Test 1'];
        //expDate
        Date expDate = System.Today().addMonths(5);
        //insert resale doc
        Dealer_Docs__c resale = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = resaleId, Document_State__c = 'LA', Permit_Resale_Number__c = '11111', Expiration_Date__c = expDate);
        insert resale;
        //should not populate a field
        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account WHERE Name = 'Test 1'];
        //system.assert
        System.assertEquals(null, testAcct.Required_Docs_Uploaded__c, 'Field populated with only one doc (Resale)');
    }

    @isTest
    static void dateFieldPopulated() {
        //need an account
        Account testAcct = [SELECT Id FROM Account WHERE Name = 'Test 2'];
        //expDate
        Date expDate = System.Today().addMonths(5);
        DateTime checkTime = System.Now().addHours(-2); //two hours earlier
        //insert license in special state
        Dealer_Docs__c testDoc = new Dealer_Docs__c(Account__c = testAcct.Id, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '11111', Expiration_Date__c = expDate);
        insert testDoc;
        //should not update the date field
        testAcct = [SELECT Id, Required_Docs_Uploaded__c FROM Account WHERE Name = 'Test 2'];
        //system.assert
        System.assert(testAcct.Required_Docs_Uploaded__c < checkTime, 'Overwrote old uploaded date with new uploaded date.'); //make sure the date has not been updated to the new createdDate
    }
}