objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Group_Affiliation__c.object
<CustomObject>
    <description>Junction object between the many to many relationship of the Account and Group objects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Associated Account for this Group Affiliation</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organization Group Affiliations</relationshipLabel>
        <relationshipName>Group_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Checkbox indicating if the Group Affiliation between an Account and a Group is active or not. This will allow for history tracking of group members</description>
        <inlineHelpText>This field indicates if the Affiliation between the Dealership and Group is live. By unchecking this box you will remove the Dealership from the Group.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Relationship between this junction object and the Group object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Group_Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Affiliation__c</fullName>
        <description>Field used to prevent duplication by concatenating the Ids of the Group and Account associated with this Affiliation</description>
        <label>Unique Affiliation</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Organization Group Affiliation</label>
    <nameField>
        <displayFormat>GA-{00000}</displayFormat>
        <label>Group Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Group Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Integration_Result__c.object
<CustomObject>
    <fields>
        <fullName>Request_Message__c</fullName>
        <label>Request Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Result</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

classes/GroupAffiliationUniqueIdGenerationTest.cls
@istest
public with sharing class GroupAffiliationUniqueIdGenerationTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        List<Account> accountList = New List<Account>();
        accountList.add(new Account(Dealership_ID__c = '456', Name='seller',legal_Name__c='seller', dealer_type__c='1',IST_Account_Owner__c =UserInfo.getUserId(),BillingStreet='158 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account(Dealership_ID__c = '123', Name='buyer',legal_Name__c='buyer', dealer_type__c='1',IST_Account_Owner__c = UserInfo.getUserId(),BillingStreet='123 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        accountList.add(new Account( Name='noID',IST_Account_Owner__c = UserInfo.getUserId(),BillingStreet='123 main st', BillingState='NY', BillingCity='Buffalo', BillingPostalCode='14214', BillingCountry='US'));
        insert accountList;
        List<Group__c> groupList = new List<Group__c>();
        groupList.add(new Group__c(Name='TEST GROUP 1', Active__c=true));
        insert groupList;
        List<Group_Affiliation__c> groupAffList = new List<Group_Affiliation__c>();
        groupAffList.add(new Group_Affiliation__c(Account__c=accountList[0].id, Group__c=groupList[0].id, Active__c=true));
        insert groupAffList;
        delete [Select id, Status_Code__c, Request_Message__c From Integration_Result__c ];

    }
    public static testMethod void TestGroupAffIdGenerationUponInsert(){
        //Generate a unique group_account id upon creation of a Group Affiliation
        Group_Affiliation__c newGrpAff = new Group_Affiliation__c();
        newGrpAff = [SELECT ID, Unique_Affiliation__c FROM Group_Affiliation__c LIMIT 1];
        // insert newGrpAff;
        System.debug(newGrpAff);
        System.assert(newGrpAff.Unique_Affiliation__c != null, 'Unique Id for Group Affiliation is Null when it shouldnt be');      
    }
    public static testMethod void TestGroupAffIdGenerationUponUpdate(){
        //Generate a unique group_account id upon update of a group Affiliation if one does not already exist
        Group_Affiliation__c newGrpAff = new Group_Affiliation__c();
        newGrpAff = [SELECT ID, Unique_Affiliation__c FROM Group_Affiliation__c Limit 1];
        
        newGrpAff.Unique_Affiliation__c = null;
        update newGrpAff;
        newGrpAff = [SELECT ID, Unique_Affiliation__c FROM Group_Affiliation__c LIMIT 1];
        
        System.debug(newGrpAff);
        System.assert(newGrpAff.Unique_Affiliation__c != null, 'Unique Id for Group Affiliation is Null when it shouldnt be');      
    }
    public static testMethod void TestGroupAffIdDuplicateErrorUponInsert(){
        //Check for Error message when attempting to Insert a new Group affiliation with an already existing combination of group_account
        system.debug([Select id, account__c, group__c From group_affiliation__c]);
        Account ac = [Select id From Account Where Name='seller'];
        Group__c gr = [Select id From Group__c Limit 1];
        Group_Affiliation__c newGrpAff = new Group_Affiliation__c();
        newGrpAff = (new Group_Affiliation__c(Account__c=ac.id, Group__c=gr.id));

        //Should see a Duplicate_value error message becasuse the Unique_Affiliation__c field is a unique field
        Boolean goterror = false;
            try{
                insert newGrpAff;
            }catch(Exception exc){
                if(exc.getMessage().contains('DUPLICATE_VALUE')){
                    goterror = true;
                }        
            }
        System.assert(goterror, 'Duplicate Value check has failed allowing two duplicate Group Affiliations to be created');   
    }        
    public static testMethod void TestGroupAffIdAccountChangeErrorUponInsert(){
        //Check an error message will fire when attempting to Change the Account field on an already exisitng group affiliation
        Account acOld = [Select id From Account Where Name='seller'];
        Account acNew = [Select id From Account Where Name='buyer'];
        Group_Affiliation__c newGrpAff = new Group_Affiliation__c();
        newGrpAff = [SELECT ID, Unique_Affiliation__c, Account__c, Group__c FROM Group_Affiliation__c Where Account__c=:acOld.id];
        // insert newGrpAff;
        system.debug(acOld);
        system.debug(acNew);
        system.debug(newGrpAff);
        //Check that GroupAffiliationAccountChangeError fires when attempting ot change an Account field
        Boolean goterror = false;
            try{
                newGrpAff.Account__c=acNew.id;
                update newGrpAff;
                system.debug(newGrpAff);
            }catch(Exception exc){
                if(exc.getMessage().contains('Cannot change Group Affiliation account after creation')){
                    goterror = true;
                }        
            }
        System.assert(goterror, 'Validation Rule to prevent Account record change on Group Affiliation has failed');   
    }
}