objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Account_Management_Next_Steps__c</fullName>
        <description>Used to track the next steps needed on this account.  Is populated/overwritten each time a retention &amp; ignition record is logged on an account</description>
        <label>Account Management Next Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Retention_Ignition__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Retention</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Call_Direction__c</fullName>
        <description>How was contact made with this customer.</description>
        <label>Call Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Retention</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Comments__c</fullName>
        <label>Dealer Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Latest_ACV_Experience__c</fullName>
        <label>Latest ACV Experience</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buy Fee</fullName>
                </value>
                <value>
                    <fullName>Good experience with ACV</fullName>
                </value>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Titles</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Unwind</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Valid Business Reason</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Steps__c</fullName>
        <description>The next steps to be taken on this retention record.  When a new retention record is created via the dealer outreach pop up, this value is written here and overwrites the value of the Next_Step_Issues_or_Objections__c field on the related account.</description>
        <label>Next Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>No_Answer__c</fullName>
        <label>No Answer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No answer</fullName>
                </value>
                <value>
                    <fullName>Declined call</fullName>
                </value>
                <value>
                    <fullName>Number Disconnected</fullName>
                </value>
                <value>
                    <fullName>Left voicemail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type of Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buy Fee Task</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Ignition</fullName>
                </value>
                <value>
                    <fullName>Introduction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retention &amp; Ignition</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Retention/Ignition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retentions &amp; Ignitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DealerOutreachControllerTest.cls
@isTest
public class DealerOutreachControllerTest {
    
    @isTest
    static void testCreateRetention() {
        Account acc = TestUtility.createAccount('Test');
        insert acc;
        Contact con = TestUtility.createContact(acc);
        insert con;

        String jsonString = '{"account":"' + acc.Id + '","contact":"' + con.Id + '","comments":"test comments","direction":"Outbound","noAnswer":"No answer","callType":"Retention","experience":["Arbitration","Payments"],"nextSteps":"test"}';
        
        Test.startTest();
        DealerOutreachController.createRetention(jsonString);
        Test.stopTest();

        Retention_Ignition__c retentionRecord = [SELECT Id, AccountName__c, ContactName__c, Dealer_Comments__c, Call_Direction__c, No_Answer__c, Type__c, Latest_ACV_Experience__c, Next_Steps__c FROM Retention_Ignition__c];
        System.assertEquals(acc.Id, retentionRecord.AccountName__c);
        System.assertEquals(con.Id, retentionRecord.ContactName__c);
        System.assertEquals('test comments', retentionRecord.Dealer_Comments__c);
        System.assertEquals('Outbound', retentionRecord.Call_Direction__c);
        System.assertEquals('No answer', retentionRecord.No_Answer__c);
        System.assertEquals('Retention', retentionRecord.Type__c);
        System.assertEquals('Arbitration;Payments', retentionRecord.Latest_ACV_Experience__c);
        System.assertEquals('test', retentionRecord.Next_Steps__c);

        acc = [SELECT Id, Account_Management_Next_Steps__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals('test', acc.Account_Management_Next_Steps__c);
    }

    @isTest
    static void testErrorOnCreate() {

        TestingUtility.SingleRequestMock splunkRes = new TestingUtility.SingleRequestMock(200,'OK','{ success }',null);
        Map<String,HttpCalloutMock> multiCall = new Map<String,HttpCalloutMock>();
        multiCall.put('callout:Splunk/services/collector/event',splunkRes);
        Test.setMock(HttpCalloutMock.class, new TestingUtility.MultiRequestMock(multiCall));

        String jsonString = '{"accountId":"00111000025bz0fAAA","contactId":"0031100001noYw0AAE","comments":"test comments","direction":"Outbound","noAnswer":"No answer","callType":"Retention","experience":["Arbitration","Payments"]}';
        
        Test.startTest();
        DealerOutreachController.createRetention(jsonString);
        Test.stopTest();

        System.assertEquals(0, [SELECT Count() FROM Retention_Ignition__c]);
    }

    @isTest
    static void testRetentionCreateAccessCustomerSuccessUser(){ 
        String uniqueUserName = 'user' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Customer Success Team'];
        User customerSuccessUser = TestUtility.createUser(p.Id);
        Boolean hasAccess;

        Test.startTest();
        System.runAs(customerSuccessUser){
            hasAccess = DealerOutreachController.checkRetentionCreateAccess();
        }
        Test.stopTest();

        System.assertEquals(false,hasAccess, 'Customer Success users do not have access to create Retention_Ignition__c records');
    }

    @isTest
    static void testCheckAffiliationCreateAccessAdmin(){ 
        Test.startTest();
            Boolean hasAccess = DealerOutreachController.checkRetentionCreateAccess();
        Test.stopTest();

        System.assertEquals(true,hasAccess, 'System Admin should have access to create Retention_Ignition__c records');
    }

}