objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Appointment_Offer__c.object
<CustomObject>
    <label>Appointment Offer</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>Appointment Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FSL__Scheduling_Policy__c.object
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OperatingHours.object
<CustomObject>
    <fields>
        <fullName>Unique_Work_Hours__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used to associate for the OffersAPI to get unique hours, often associated with specific hours for a particular type of work</description>
        <inlineHelpText>Used to associate for the OffersAPI to get unique hours, often associated with specific hours for a particular type of work</inlineHelpText>
        <label>Unique Work Hours</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Setting__mdt.object
<CustomObject>
    <description>This holds small Custom Metadata values that we wish are configurable but are not enough to have its own Custom Metadata Type.</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>value that will be used in Apex or wherever this metadata record is used</description>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>Salesforce Setting</label>
    <pluralLabel>Salesforce Settings</pluralLabel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <description>Work Type Unique ID for the Work Order linked to this Service Appointment.</description>
        <formula>Work_Order__r.WorkType.Work_Type_Unique_ID__c</formula>
        <label>Work Type Unique ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>External_Record_guid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Record guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Work Type Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OffersAPITest.cls
@isTest
public class OffersAPITest {
    private final static String WORK_TYPE_UNIQUE_NAME = 'inspection';
    private final static String TIME_ZONE = 'America/New_York';
    private final static Set<String> DAY_OF_WEEK_SET = new Set<String>{ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday' };
    private final static Integer STARTING_HOUR = 8;
    private final static Integer ENDING_HOUR = 17;
    
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account a = TestUtility.createAccount();
        a.Dealership_ID__c = '1';
        insert a;

        FSL__Scheduling_Policy__c newPolicy = new FSL__Scheduling_Policy__c(
            Name = [ SELECT Value__c FROM Salesforce_Setting__mdt WHERE Label = 'Main Scheduling Policy Name' LIMIT 1 ][0].Value__c
        );
        insert newPolicy;

        FSLTestUtility.createData( a, 1 );

        OperatingHours specialHours = new OperatingHours(
            Name = WORK_TYPE_UNIQUE_NAME + ' Special EST Hours', TimeZone = TIME_ZONE,
            Unique_Work_Hours__c = WORK_TYPE_UNIQUE_NAME + ':' + TIME_ZONE
        );
        insert specialHours;

        List<TimeSlot> timeSlotLst = new List<TimeSlot>();
        for ( String dayOfWeek : DAY_OF_WEEK_SET ) {
            timeSlotLst.add( new TimeSlot(
                DayOfWeek = dayOfWeek,
                OperatingHoursId = specialHours.Id,
                StartTime = Time.newInstance( STARTING_HOUR, 0, 0, 0 ),
                EndTime = Time.newInstance( 12, 30, 0, 0 )
            ) );
            timeSlotLst.add( new TimeSlot(
                DayOfWeek = dayOfWeek,
                OperatingHoursId = specialHours.Id,
                StartTime = Time.newInstance( 12, 30, 0, 0 ),
                EndTime = Time.newInstance( ENDING_HOUR, 0, 0, 0 )
            ) );
        }
        insert timeSlotLst;

        ServiceTerritory st = [ SELECT Id FROM ServiceTerritory LIMIT 1 ];
        st.OperatingHoursId = specialHours.Id;
        update st;

        ServiceResource testSR = FSLTestUtility.makeResourceData();

        ServiceTerritoryMember stm = new ServiceTerritoryMember(
            OperatingHoursId = st.OperatingHoursId, 
            ServiceTerritoryId = st.Id, 
            ServiceResourceId = testSR.Id,
            EffectiveStartDate = Date.today().addDays(-1), 
            TerritoryType = 'P'
        );
        insert stm;
    }

    private static void debug( String restBody ) {
        Integer index = 0;
        system.debug( '----------------------------- Start of Current REST Body -----------------------------' );
        do {
            if ( index + 250 >= restBody.length() ) {
                system.debug( restBody.subString( index, restBody.length() ) );
            } else { 
                system.debug( restBody.subString( index, index + 250 ) );
            }
            index += 250;       
        } while ( index < restBody.length() );
        system.debug( '----------------------------- End of Current REST Body -----------------------------' );
    }

    @IsTest
    static void getOffer() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/Offers';

        WorkOrderLineItem woliTestRec = [ SELECT Id, External_Record_Guid__c FROM WorkOrderLineItem LIMIT 1 ];

        Date futureDate = Date.today().addDays( 3 );
        Date furtherFutureDate = futureDate.addDays( 6 );
        req.addParameter( 'startDateTime', '' + futureDate.month() + '/' + futureDate.day() + '/' + futureDate.year() + ' 12:00 PM' );
        req.addParameter( 'endDateTime', '' + furtherFutureDate.month() + '/' + furtherFutureDate.day() + '/' + furtherFutureDate.year() + ' 12:00 PM' );
        req.addParameter( 'externalUUID', woliTestRec.External_Record_Guid__c );

        RestContext.request = req;

        Test.startTest();
            OffersAPI.getOffers();
        Test.stopTest();
        
        debug( res.responseBody.toString() );
    }

    @IsTest
    static void setOfferInJeopardy() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        StaticResource singleRequestRes = [ SELECT Id, Body FROM StaticResource WHERE Name = 'WorkAPITest_SingleValidRequest' LIMIT 1 ];
        WorkObject workReq = ((List<WorkObject>) JSON.deserialize( singleRequestRes.body.toString(), List<WorkObject>.class ))[0];
        workReq.workDetail.isInJeopardy = String.valueOf( TRUE );
        
        DateTime startTime = DateTime.now().addDays( 1 );
        DateTime endTime = DateTime.now().addDays( 1 ).addMinutes( 60 );

        Test.startTest();
            OfferedAppointment offerAppt = new OfferedAppointment();
            offerAppt.workRec = workReq;
            offerAppt.startTime = startTime;
            offerAppt.endTime = endTime;

            OffersAPI.saveOffer( offerAppt );
        Test.stopTest();

        debug( res.responseBody.toString() );
    }

    @IsTest
    static void setOffer() {
        FSL.GlobalAPIS.addStatusTransition( 'New', 'Scheduled' );
        RestResponse res = new RestResponse();
        RestContext.response = res;

        StaticResource singleRequestRes = [ SELECT Id, Body FROM StaticResource WHERE Name = 'WorkAPITest_SingleValidRequest' LIMIT 1 ];
        WorkObject workReq = ((List<WorkObject>) JSON.deserialize( singleRequestRes.body.toString(), List<WorkObject>.class ))[0];
        workReq.workDetail.isInJeopardy = String.valueOf( FALSE );
        
        DateTime startTime = DateTime.now().addDays( 1 );
        DateTime endTime = DateTime.now().addDays( 1 ).addMinutes( 60 );

        ServiceResource sr = [ SELECT Id FROM ServiceResource LIMIT 1 ];
        ServiceAppointment sa = [ SELECT Id FROM ServiceAppointment LIMIT 1 ];
        insert OffersAPI.createSavedOffer( sr.Id, startTime, endTime, 100.0, sa, startTime, startTime, endTime );

        Test.startTest();
            OfferedAppointment offerAppt = new OfferedAppointment();
            offerAppt.workRec = workReq;
            offerAppt.startTime = startTime;
            offerAppt.endTime = endTime;

            OffersAPI.saveOffer( offerAppt );
        Test.stopTest();

        debug( res.responseBody.toString() );
    }

    @IsTest
    static void setOfferWithNoGivenOffers() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        StaticResource singleRequestRes = [ SELECT Id, Body FROM StaticResource WHERE Name = 'WorkAPITest_SingleValidRequest' LIMIT 1 ];
        WorkObject workReq = ((List<WorkObject>) JSON.deserialize( singleRequestRes.body.toString(), List<WorkObject>.class ))[0];
        workReq.workDetail.isInJeopardy = String.valueOf( FALSE );
        
        DateTime startTime = DateTime.now().addDays( 1 );
        DateTime endTime = DateTime.now().addDays( 1 ).addMinutes( 60 );

        Test.startTest();
            OfferedAppointment offerAppt = new OfferedAppointment();
            offerAppt.workRec = workReq;
            offerAppt.startTime = startTime;
            offerAppt.endTime = endTime;

            OffersAPI.saveOffer( offerAppt );
        Test.stopTest();

        debug( res.responseBody.toString() );
    }

    @IsTest
    static void setOfferWithBadID() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        StaticResource singleRequestRes = [ SELECT Id, Body FROM StaticResource WHERE Name = 'WorkAPITest_SingleValidRequest' LIMIT 1 ];
        WorkObject workReq = ((List<WorkObject>) JSON.deserialize( singleRequestRes.body.toString(), List<WorkObject>.class ))[0];
        
        DateTime startTime = DateTime.now().addDays( 1 );
        DateTime endTime = DateTime.now().addDays( 1 ).addMinutes( 60 );

        Test.startTest();
            OfferedAppointment offerAppt = new OfferedAppointment();
            offerAppt.workRec = workReq;
            offerAppt.startTime = startTime;
            offerAppt.endTime = endTime;

            OffersAPI.saveOffer( offerAppt );
        Test.stopTest();

        debug( res.responseBody.toString() );
    }

    @IsTest
    static void setOfferWithMissingFields() {
        RestResponse res = new RestResponse();
        RestContext.response = res;

        StaticResource singleRequestRes = [ SELECT Id, Body FROM StaticResource WHERE Name = 'WorkAPITest_SingleInvalidRequest' LIMIT 1 ];
        WorkObject workReq = ((List<WorkObject>) JSON.deserialize( singleRequestRes.body.toString(), List<WorkObject>.class ))[0];

        DateTime startTime = DateTime.now().addDays( 1 );
        DateTime endTime = DateTime.now().addDays( 1 ).addMinutes( 60 );

        Test.startTest();
            OfferedAppointment offerAppt = new OfferedAppointment();
            offerAppt.workRec = workReq;
            offerAppt.startTime = startTime;
            offerAppt.endTime = endTime;

            OffersAPI.saveOffer( offerAppt );
        Test.stopTest();

        debug( res.responseBody.toString() );
    }

    @isTest
    static void createSavedOffer() {
        ServiceResource sr = [ SELECT Id FROM ServiceResource LIMIT 1 ];
        ServiceAppointment sa = [ SELECT Id FROM ServiceAppointment LIMIT 1 ];
        DateTime now = DateTime.now();
        DateTime afterNow = now.addMinutes(60);
        Test.startTest();
            OffersAPI.createSavedOffer( sr.Id, now, afterNow, 100.0, sa, now, now, afterNow );
        Test.stopTest();
    }

    @IsTest
    static void checkForNewOffer(){
        OfferSlotObject oso = new OfferSlotObject( 100, DateTime.now().addHours(1), DateTime.now().addHours(2) );

        Test.startTest();
            String key = OffersAPI.makeSlotMapKey( oso.startTime, oso.endTime );
            Map<String, OfferSlotObject> testMap = new Map<String, OfferSlotObject>();
            testMap.put( key, oso );

            System.assertEquals( FALSE, OffersAPI.isNewOffer( testMap, oso ), 'The offer was incorrectly identified' );

            OfferSlotObject oso2 = new OfferSlotObject( 100, DateTime.now().addHours(2), DateTime.now().addHours(3) );
            System.assertEquals( TRUE, OffersAPI.isNewOffer( testMap, oso2 ), 'The offer was incorrectly identified' );
        Test.stopTest();
    }

    @IsTest
    static void processNormalSlot(){
        ServiceAppointment sa = [ SELECT Id,
                                        WorkType.Work_Type_Unique_Id__c,
                                        ServiceTerritory.OperatingHours.TimeZone,
                                        WorkType.EstimatedDuration
                                        FROM ServiceAppointment LIMIT 1 ];

        Date tomorrow = Date.today().addDays(1);

        FSLWorkProcessUtility.setupUniqueWorkHourStructs();
        OffersAPI.SlotProcessData processSlotData = new OffersAPI.SlotProcessData();
        processSlotData.savedOfferLst = new List<Appointment_Offer__c>();
        processSlotData.slotReturnMap = new Map<String, OfferSlotObject>();
        Timezone localUserTZ = UserInfo.getTimeZone();
        Integer offSet = ( localUserTZ.getOffset( DateTime.now() ) / 1000 ); // In Seconds

        Test.startTest();
            processSlotData = OffersAPI.processSlotData(
                localUserTZ,
                100,
                [ SELECT Id FROM ServiceResource LIMIT 1 ].Id,
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( STARTING_HOUR, 0, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),  
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( 12, 30, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),
                sa,
                processSlotData
            );
        Test.stopTest();

        system.assertEquals( TRUE, !processSlotData.savedOfferLst.isEmpty(), 'An offer was provided' );
        system.assertEquals( TRUE, !processSlotData.slotReturnMap.isEmpty(), 'A slot was provided' );
    }

    @IsTest
    static void processLargeSlot(){
        ServiceAppointment sa = [ SELECT Id,
                                        WorkType.Work_Type_Unique_Id__c,
                                        ServiceTerritory.OperatingHours.TimeZone,
                                        WorkType.EstimatedDuration
                                        FROM ServiceAppointment LIMIT 1 ];

        Date tomorrow = Date.today().addDays(1);

        FSLWorkProcessUtility.setupUniqueWorkHourStructs();
        OffersAPI.SlotProcessData processSlotData = new OffersAPI.SlotProcessData();
        processSlotData.savedOfferLst = new List<Appointment_Offer__c>();
        processSlotData.slotReturnMap = new Map<String, OfferSlotObject>();
        Timezone localUserTZ = UserInfo.getTimeZone();
        Integer offSet = ( localUserTZ.getOffset( DateTime.now() ) / 1000 ); // In Seconds

        Test.startTest();
            processSlotData = OffersAPI.processSlotData(
                localUserTZ,
                100,
                [ SELECT Id FROM ServiceResource LIMIT 1 ].Id,
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( ( STARTING_HOUR - 1 ), 0, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),  
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( ( 12 + 1 ), 30, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),
                sa,
                processSlotData
            );
        Test.stopTest();

        system.assertEquals( TRUE, !processSlotData.savedOfferLst.isEmpty(), 'An offer was provided' );
        system.assertEquals( TRUE, !processSlotData.slotReturnMap.isEmpty(), 'A slot was provided' );
    }

    @IsTest
    static void processSmallSlot(){
        ServiceAppointment sa = [ SELECT Id,
                                        WorkType.Work_Type_Unique_Id__c,
                                        ServiceTerritory.OperatingHours.TimeZone,
                                        WorkType.EstimatedDuration
                                        FROM ServiceAppointment LIMIT 1 ];

        Date tomorrow = Date.today().addDays(1);

        FSLWorkProcessUtility.setupUniqueWorkHourStructs();
        OffersAPI.SlotProcessData processSlotData = new OffersAPI.SlotProcessData();
        processSlotData.savedOfferLst = new List<Appointment_Offer__c>();
        processSlotData.slotReturnMap = new Map<String, OfferSlotObject>();
        Timezone localUserTZ = UserInfo.getTimeZone();
        Integer offSet = ( localUserTZ.getOffset( DateTime.now() ) / 1000 ); // In Seconds

        Test.startTest();
            processSlotData = OffersAPI.processSlotData(
                localUserTZ,
                100,
                [ SELECT Id FROM ServiceResource LIMIT 1 ].Id,
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( ( STARTING_HOUR + 1 ), 0, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),  
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( ( 12 - 1 ), 30, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),
                sa,
                processSlotData
            );
        Test.stopTest();

        system.assertEquals( TRUE, !processSlotData.savedOfferLst.isEmpty(), 'An offer was provided' );
        system.assertEquals( TRUE, !processSlotData.slotReturnMap.isEmpty(), 'A slot was provided' );
    }

    @IsTest
    static void processOverlapStartSlot(){
        ServiceAppointment sa = [ SELECT Id,
                                        WorkType.Work_Type_Unique_Id__c,
                                        ServiceTerritory.OperatingHours.TimeZone,
                                        WorkType.EstimatedDuration
                                        FROM ServiceAppointment LIMIT 1 ];

        Date tomorrow = Date.today().addDays(1);

        FSLWorkProcessUtility.setupUniqueWorkHourStructs();
        OffersAPI.SlotProcessData processSlotData = new OffersAPI.SlotProcessData();
        processSlotData.savedOfferLst = new List<Appointment_Offer__c>();
        processSlotData.slotReturnMap = new Map<String, OfferSlotObject>();
        Timezone localUserTZ = UserInfo.getTimeZone();
        Integer offSet = ( localUserTZ.getOffset( DateTime.now() ) / 1000 ); // In Seconds

        Test.startTest();
            processSlotData = OffersAPI.processSlotData(
                localUserTZ,
                100,
                [ SELECT Id FROM ServiceResource LIMIT 1 ].Id,
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( ( STARTING_HOUR - 1 ), 0, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),  
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( 12, 30, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),
                sa,
                processSlotData
            );
        Test.stopTest();

        system.assertEquals( TRUE, !processSlotData.savedOfferLst.isEmpty(), 'An offer was provided' );
        system.assertEquals( TRUE, !processSlotData.slotReturnMap.isEmpty(), 'A slot was provided' );
    }

    @IsTest
    static void processOverlapEndSlot(){
        ServiceAppointment sa = [ SELECT Id,
                                        WorkType.Work_Type_Unique_Id__c,
                                        ServiceTerritory.OperatingHours.TimeZone,
                                        WorkType.EstimatedDuration
                                        FROM ServiceAppointment LIMIT 1 ];

        Date tomorrow = Date.today().addDays(1);

        FSLWorkProcessUtility.setupUniqueWorkHourStructs();
        OffersAPI.SlotProcessData processSlotData = new OffersAPI.SlotProcessData();
        processSlotData.savedOfferLst = new List<Appointment_Offer__c>();
        processSlotData.slotReturnMap = new Map<String, OfferSlotObject>();
        Timezone localUserTZ = UserInfo.getTimeZone();
        Integer offSet = ( localUserTZ.getOffset( DateTime.now() ) / 1000 ); // In Seconds

        Test.startTest();
            processSlotData = OffersAPI.processSlotData(
                localUserTZ,
                100,
                [ SELECT Id FROM ServiceResource LIMIT 1 ].Id,
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( STARTING_HOUR, 0, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),  
                DateTime.newInstanceGMT( tomorrow, Time.newInstance( ( 12 + 1 ), 30, 0, 0 ).addSeconds( ((-1) * offSet ) ) ),
                sa,
                processSlotData
            );
        Test.stopTest();

        system.assertEquals( TRUE, !processSlotData.savedOfferLst.isEmpty(), 'An offer was provided' );
        system.assertEquals( TRUE, !processSlotData.slotReturnMap.isEmpty(), 'A slot was provided' );
    }
}