objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Creation_Source__c</fullName>
        <description>Field indicating how this record was created, used to filter records created through bulk creation processes to avoid mass email send outs</description>
        <label>Creation Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bulk Load</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Convert_Status__c</fullName>
        <label>Lead Convert Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Converting</fullName>
                </value>
                <value>
                    <fullName>Identity Id Endpoint Failed</fullName>
                </value>
                <value>
                    <fullName>Eula/Tos Endpoint Failed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetAccountRecordType.cls
public class SetAccountRecordType extends TriggerInterface {
    
    String accRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();

    public override void beforeInsert(List<sObject> objectList) {
    
        List<Account> newAccounts = (List<Account>) objectList;
        
            for ( Account newAcc : newAccounts ) {
                if (LeadConversion.isConverting) {
                    newAcc.RecordTypeId = accRTId;
                    newAcc.Active__c= false;
                    newAcc.Creation_Source__c= 'Registration';
                    newAcc.Lead_Convert_Status__c= 'Converting';
                }
            }
    }
    
}