objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_90_Days_Bought__c</fullName>
        <description>Field to be deprecated. - MM 11/8/21</description>
        <label>xLast 90 Days Bought</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_90_Days_Sold__c</fullName>
        <description>Field to be deprecated. - MM 11/8/21</description>
        <label>xLast 90 Days Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <formula>IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;1&apos; ,&apos;Franchise&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;2&apos; ,&apos;Independent&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;4&apos; ,&apos;Independent - ACV Certified&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;3&apos; ,&apos;Wholesaler&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;Dealer Group (Parent Account)&apos;,&apos;Dealer Group (Parent Account)&apos;,
IF(TEXT( Seller_Dealership__r.Dealer_Type__c )==&apos;5&apos; ,&apos;Commercial&apos;,
 &apos;&apos;) 

)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <description>Set by Process Builder automation.</description>
        <label>Make</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vehicle_Make</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winning_Bid_Price__c</fullName>
        <label>High Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>floor_price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>make__c</fullName>
        <description>The make (manufacturer) of the vehicle.</description>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/AccountSalesInfoTest.cls
@isTest
public class AccountSalesInfoTest {
    
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
      List<Auction__c> newAuctions = new List<Auction__c>();
      List<Account> AccountList = new List<Account>();
      accountList.add(new Account(Name='seller',IST_Account_Owner__c =UserInfo.getUserId(),legal_Name__c='seller', dealer_type__c='1'));
      accountList.add(new Account(Name='buyer',IST_Account_Owner__c = UserInfo.getUserId(),legal_Name__c='buyer', dealer_type__c='1'));
      vehicle__c newCar = new vehicle__c(year__c='2009',make__c='test make', model__c='test model', vin__c = '1234567890102030');
      insert newCar;
      insert accountList;
      
      vehicle__c car = [select id from vehicle__c limit 1];
        
      for(Integer i=0;i<100;i++){
          auction__c newAuction = new auction__c(status__c = 'Counter_Accepted', end_time__c = System.Now(),Buyer_Dealership__c = accountList[1].id, 
                                                   Seller_Dealership__c = accountList[0].id,Floor_Price__c = 500, Winning_Bid_Price__c = 450, vehicle_id__c = car.id);
          newAuctions.add(newAuction);   
      }
   
      insert newAuctions;    
    }

    @IsTest
    public static void testBatch(){
      
      test.startTest();
      id batchJob = Database.executeBatch(new AccountSalesPurchasesBatch(),200);
      test.stopTest();
      List<account> buyerAccount = [select id, Name, Last_90_Days_Sold__C, Last_90_Days_bought__C from Account where Name = 'buyer'];
      List<account> sellerAccount = [select id, Name, Last_90_Days_Sold__C, Last_90_Days_bought__C from Account where Name = 'seller'];
      //Integer numOfAuc = [SELECT ID FROM Auction__c].size();
      

      //System.assertEquals(numOfAuc,200);
      System.assertEquals(sellerAccount[0].Last_90_days_sold__c, 100);
      System.assertEquals(buyerAccount[0].Last_90_days_bought__c, 100);
     
    }

    @IsTest
    public static void testBatchSchedule(){
      test.startTest();
        AutoCloseDealmakerOpportunitiesScheduler batch = new AutoCloseDealmakerOpportunitiesScheduler();
        batch.executeScheduledLogic();
      test.stopTest();
      
      
    }
}