objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Territory_Name__c</fullName>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>maps__AssignmentRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maps Assignment Rule</label>
        <referenceTo>maps__AssignmentRule__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/maps__AssignmentRule__c.object
<CustomObject>
    <fields>
        <fullName>maps__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>maps__ShapeLayer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maps Shape Layer</label>
        <referenceTo>maps__ShapeLayer__c</referenceTo>
        <relationshipLabel>Assignment Rules</relationshipLabel>
        <relationshipName>AssignmentRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maps Assignment Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Maps Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps Assignment Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/maps__ShapeLayer__c.object
<CustomObject>
    <fields>
        <fullName>maps__ShapeLayer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shape Layer</label>
        <referenceTo>maps__ShapeLayer__c</referenceTo>
        <relationshipLabel>Shape Layers</relationshipLabel>
        <relationshipName>ShapeLayers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maps Shape Layer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps Shape Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FillTerritoryOnAccountTest.cls
@IsTest//(SeeAllData=TRUE)
public class FillTerritoryOnAccountTest {
    @IsTest
    static void updateAccountTerritory(){
        Account acct = new Account(
            Name = 'Smith Dealerships', legal_name__c='Smith Dealerships'
        );
        insert acct;

        acct.legal_name__c = 'John Smith Dealerships';
        update acct;

        /*maps__AssignmentRule__c rec = [ SELECT Id, maps__ShapeLayer__c, maps__ShapeLayer__r.Name FROM maps__AssignmentRule__c WHERE maps__Active__c = TRUE LIMIT 1 ];

        Test.startTest();

            acct.Maps_TM_Assignment_Rule_Territory_A_E__c = rec.Id;
            update acct;
            /*acct.Maps_TM_Assignment_Rule_Territory_F_O__c = rec.Id;
            update acct;
            acct.Maps_TM_Assignment_Rule_Territory_P_Z__c = rec.Id;
            update acct;

        Test.stopTest();

        acct = [ SELECT Id, Territory_Name__c FROM Account WHERE Id = :acct.Id LIMIT 1 ];
        system.assertEquals( rec.maps__ShapeLayer__r.Name, acct.Territory_Name__c, 'The Map Assignment Rule did not change as expected' );*/
    }
}