objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Account_Activity_Status__c</fullName>
        <description>P0: New Customer = Joined in last 60; P1: Lapsed = no activity last 30; P2: Declining = last 30 activity is less than half average 30 day activity; P3: Churned = no activity last 90; Normal = regular activity based on monthly average</description>
        <formula>IF(  (TODAY() - DATEVALUE(Date_Joined__c)) &lt; 60, &quot;P0: New Customer&quot;,
 IF(  ISBLANK(Date_of_Last_Sale__c) &amp;&amp;  ISBLANK(Date_of_Last_Purchase__c), &quot;&quot;, 
  IF( 
   OR(
    Date_of_Last_Sale__c &lt; (TODAY() - 90) &amp;&amp; Date_of_Last_Purchase__c &lt; (TODAY() - 90),
    Date_of_Last_Sale__c &lt; (TODAY() - 90) &amp;&amp; ISBLANK(Date_of_Last_Purchase__c),
    Date_of_Last_Purchase__c &lt; (TODAY() - 90) &amp;&amp; ISBLANK(Date_of_Last_Sale__c)
   ),
   &quot;P3: Churned&quot;,

   IF(
    OR(
    Date_of_Last_Sale__c &lt; (TODAY() - 30) &amp;&amp; Date_of_Last_Purchase__c &lt; (TODAY() - 30),
    Date_of_Last_Sale__c &lt; (TODAY() - 30) &amp;&amp; ISBLANK(Date_of_Last_Purchase__c),
    Date_of_Last_Purchase__c &lt; (TODAY() - 30) &amp;&amp; ISBLANK(Date_of_Last_Sale__c)
   ),
   &quot;P1: Lapsed&quot;,

    IF(
     (Last_30_Days_Bought__c + Actual_Rolling_30_Day_Sales_Volume__c) &lt; ((Purchases_All_Time__c + Wholesale_Units_Sold__c) / ((TODAY() - 
     DATEVALUE(Date_Joined__c)) / 30) / 2), 
     &quot;P2: Declining&quot;,

     &quot;Normal&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>P0: New Customer = Joined in last 60; 
P1: Lapsed = no activity last 30; 
P2: Declining = last 30 activity is less than half average 30 day activity; 
P3: Churned = no activity last 90; 
Normal = regular activity based on monthly average</inlineHelpText>
        <label>Account Activity Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Management_Next_Steps__c</fullName>
        <description>Used to track the next steps needed on this account.  Is populated/overwritten each time a retention &amp; ignition record is logged on an account</description>
        <label>Account Management Next Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Retention_Ignition__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Retention</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Call_Direction__c</fullName>
        <description>How was contact made with this customer.</description>
        <label>Call Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Retention</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateofCall__c</fullName>
        <label>Date of Call</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dealer_Comments__c</fullName>
        <label>Dealer Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Latest_ACV_Experience__c</fullName>
        <label>Latest ACV Experience</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buy Fee</fullName>
                </value>
                <value>
                    <fullName>Good experience with ACV</fullName>
                </value>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Titles</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Unwind</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Valid Business Reason</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Steps__c</fullName>
        <description>The next steps to be taken on this retention record.  When a new retention record is created via the dealer outreach pop up, this value is written here and overwrites the value of the Next_Step_Issues_or_Objections__c field on the related account.</description>
        <label>Next Steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>No_Answer__c</fullName>
        <label>No Answer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No answer</fullName>
                </value>
                <value>
                    <fullName>Declined call</fullName>
                </value>
                <value>
                    <fullName>Number Disconnected</fullName>
                </value>
                <value>
                    <fullName>Left voicemail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type of Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buy Fee Task</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Ignition</fullName>
                </value>
                <value>
                    <fullName>Introduction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Retention &amp; Ignition</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Retention/Ignition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retentions &amp; Ignitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Inside_Sales</fullName>
        <active>true</active>
        <label>Inside Sales</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DealerOutreachController.cls
public with sharing class DealerOutreachController {

    /**
     * Returns true or false based on ability for current user to create Retention_Ignition__c records
     * @return  `Boolean`    
     */
    @AuraEnabled
    public static Boolean checkRetentionCreateAccess(){
        return Retention_Ignition__c.sObjectType.getDescribe().isCreateable();
    }

    /**
     * Given an account, this will return true if account is locked in an approval process
     * @param accountId 
     * @return  `Boolean` 
     */
    @AuraEnabled
    public static Boolean checkForLockedAccount(Id accountId){
        return Approval.isLocked(accountId);
    }

    /**
     * Returns the recordtypeId for an Inside Sales task
     * @return  `Id`
     */
    @AuraEnabled
    public static Id getInsideSalesRecordTypeId(){
        return Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Inside_Sales').getRecordTypeId();
    }
    
    /**
     * Inserts a retention_ignition__c record from the dealerOutreach LWC
     * @param jsonString    The data that will be used to create retention_ignition__c record
     * @return  `Id`        Returns the ID of the record created
     */
    @AuraEnabled
    public static Id createRetention(String jsonString){
        try {
            NewRetentionIgnition retentionDetails = (NewRetentionIgnition)JSON.deserialize(jsonString, NewRetentionIgnition.class);
            String activityStatus = [SELECT Id, Account_Activity_Status__c FROM Account WHERE Id = :retentionDetails.account].Account_Activity_Status__c;
            Retention_Ignition__c retentionRecord = new Retention_Ignition__c
                (
                    AccountName__c = retentionDetails.account,
                    ContactName__c = retentionDetails.contact,
                    DateOfCall__c = System.today(),
                    Dealer_Comments__c = retentionDetails.comments,
                    Call_Direction__c = retentionDetails.direction,
                    No_Answer__c = retentionDetails.noAnswer,
                    Type__c = retentionDetails.callType,
                    Next_Steps__c = retentionDetails.nextSteps,
                    Latest_ACV_Experience__c = retentionDetails.experience,
                    Account_Activity_Status__c = activityStatus
                );
            insert retentionRecord;

            if(retentionDetails.nextSteps != null){
                update new Account(Id = retentionDetails.account, Account_Management_Next_Steps__c = retentionDetails.nextSteps);
            }
            return retentionRecord.Id;
            
        } 
        catch (Exception e) {
            SplunkHelper.buildAndProcessLog( createLog( SplunkHelper.LOGLEVEL.FATAL, e.getMessage(), e.getStackTraceString(), ACVUtility.currentLineNumber()) );
            return null;
        }
    }

    public class NewRetentionIgnition { //object for inbound data
        public String account;
        public String contact;
        public String comments;
        public String direction;
        public String noAnswer;
        public String callType;
        public String nextSteps;
        public String experience;
    }

    /**
     * Creates SplunkHelper Log
     * @param loglevel - ERROR, FATAL, INFO, DEBUG, WARN, or PERFORMANCE
     * @param message - error message
     * @param stackTrace - Full Detailed Stack Trace
     * @param lineNumber - Line Number that the error has happened on
     * @return SplunkHelper.log
     */
    public static SplunkHelper.Log createLog(SplunkHelper.LOGLEVEL loglevel, String message, String stackTrace, Integer lineNumber){
        SplunkHelper.Log log = new SplunkHelper.log();
        log.domainSet = new Set<SplunkHelper.DOMAIN>{SplunkHelper.DOMAIN.SALES};
        log.sfObject = 'Retention_Ignition__c';
        log.version = 'v1';
        log.componentName = 'LWC - DealerOutreach';
        log.location = 'DealerOutreachController Line #' + String.valueOf(lineNumber);
        log.message = message;
        log.stackTrace = stackTrace;
        log.logLevel = loglevel;
        log.setContext(SplunkHelper.CONTEXT_TYPE.LWC);
        return log;
    }
}