objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Director__c</fullName>
        <formula>Owner.Manager.FirstName + &quot; &quot; + Owner.Manager.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regional Sales Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <formula>Owner.FirstName &amp; &quot; &quot; &amp; Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Manager</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the program is active or not.</description>
        <inlineHelpText>Used to indicate if the program is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Rule_Logic__c</fullName>
        <description>User to enter the field logic criteria</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Rule Logic Eligibility</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <description>Used to find the sales team member for this Program</description>
        <inlineHelpText>Used to find the sales team member for this Program</inlineHelpText>
        <label>Sales Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IST_Account_Owner__c</fullName>
                    <label>Account Manager</label>
                </value>
                <value>
                    <fullName>OwnerId</fullName>
                    <label>Territory Manager</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to capture current status program.</description>
        <inlineHelpText>Used to capture current status program.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not eligible</fullName>
                </value>
                <value>
                    <fullName>In/under review by IST (use pre and post pending customer response)</fullName>
                </value>
                <value>
                    <fullName>Pending customer response (pending app completion) -In/under review by IST</fullName>
                </value>
                <value>
                    <fullName>Waiting on POA (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Verified by IST (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Under review by TM under review by RSD approved Rejected [with reasons] (do not call removes from eligibility)</fullName>
                </value>
                <value>
                    <fullName>TM will be reaching out to you soon Enrolled (start date)</fullName>
                </value>
                <value>
                    <fullName>Active (initiated at first sale)</fullName>
                </value>
                <value>
                    <fullName>Remove (for performance)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>To indicate status of Approval</description>
        <inlineHelpText>To indicate status of Approval</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Pending TM Approval</fullName>
                </value>
                <value>
                    <fullName>TM Approved</fullName>
                </value>
                <value>
                    <fullName>TM Rejected</fullName>
                </value>
                <value>
                    <fullName>RSD Approved</fullName>
                </value>
                <value>
                    <fullName>RSD Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IST_Sales_Rep_Email__c</fullName>
        <description>To store IST Sales Rep Email used for communication</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>To store IST Sales Rep Email used for communication</inlineHelpText>
        <label>IST Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Dealership_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the primary contact of the dealer.</description>
        <inlineHelpText>Used to store the primary contact of the dealer.</inlineHelpText>
        <label>Primary Dealership Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the user who is the regional sales director of the dealer / account</description>
        <inlineHelpText>Used to store the user who is the regional sales director of the dealer / account</inlineHelpText>
        <label>Regional Sales Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RSD_Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the user who is the manager of the dealer / account</description>
        <inlineHelpText>Used to store the user who is the manager of the dealer / account</inlineHelpText>
        <label>Sales Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not eligible</fullName>
                </value>
                <value>
                    <fullName>In/under review by IST (use pre and post pending customer response)</fullName>
                </value>
                <value>
                    <fullName>Pending customer response (pending app completion) -In/under review by IST</fullName>
                </value>
                <value>
                    <fullName>Waiting on POA (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Verified by IST (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Under review by TM under review by RSD approved Rejected [with reasons] (do not call removes from eligibility)</fullName>
                </value>
                <value>
                    <fullName>TM will be reaching out to you soon Enrolled (start date)</fullName>
                </value>
                <value>
                    <fullName>Active (initiated at first sale)</fullName>
                </value>
                <value>
                    <fullName>Remove (for performance)</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the user who is the territory manager of the dealer / account</description>
        <inlineHelpText>Used to store the user who is the territory manager of the dealer / account</inlineHelpText>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TM_Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PopulateDefaultsOnProgramEnrollmentTest.cls
/******************************************
*Author - Avinash Sharma(Saisystems) 
*Description - Test Class for PopulateDefaultsOnProgramEnrollment 
*Date - 28th Jan 2021
*******************************************/
@isTest
public class PopulateDefaultsOnProgramEnrollmentTest {
    @TestSetup
    static void makeData(){
        
        Account acc=TestUtility.createAccount();
        acc.IST_Account_Owner__c =UserInfo.getUserId();
        insert acc;
        
        Contact con = TestUtility.createContact(acc);
        insert con;
        acc.Primary_Contact__c=con.Id;
        update acc;
        
         List<Program__c> programList = New List<Program__c>();
        Program__c prog = new Program__c();
        prog.Name ='Program';
        Prog.Active__c =true;
        Prog.Sales_Contact__c='IST_Account_Owner__c';
        prog.Program_Rule_Logic__c='1 AND 2';
        Prog.Status__c ='Eligible';
        programList.add(Prog);
        
        Program__c Prog_1 = new Program__c();
        Prog_1.Name ='Program 1';
        Prog_1.Active__c =true;
        Prog_1.Sales_Contact__c='IST_Account_Owner__c';
        Prog_1.Program_Rule_Logic__c='1 AND 2';
        Prog_1.Status__c ='Eligible';
        programList.add(Prog_1);
        
        Program__c Prog_2 = new Program__c();
        Prog_2.Name ='Program 1';
        Prog_2.Active__c =true;
        Prog_2.Sales_Contact__c='IST_Account_Owner__c';
        Prog_2.Program_Rule_Logic__c='1 AND 2';
        Prog_2.Status__c ='Eligible';
        programList.add(Prog_2);
        insert programList;
        
        List<Program_Enrollment__c> programEnrollList = new List<Program_Enrollment__c>();
        Program_Enrollment__c progEnroll = new Program_Enrollment__c(Program__c =prog.Id, Account__c=acc.Id, Primary_Dealership_Contact__c=con.Id,Name ='Program enrollment', Status__c='Eligible', Approval_Status__c ='TM Rejected');
        programEnrollList.add(progEnroll);
        Program_Enrollment__c progEnroll1 = new Program_Enrollment__c(Program__c =Prog_1.Id, Account__c=acc.Id, Primary_Dealership_Contact__c=con.Id,Name ='Program enrollment1_1', Approval_Status__c ='RSD Rejected', Status__c='Eligible', IST_Sales_Rep_Email__c='abc@abc.com',Territory_Manager__c=UserInfo.getUserId(),Regional_Sales_Director__c=UserInfo.getUserId());
        programEnrollList.add(progEnroll1);
        Program_Enrollment__c progEnroll2 = new Program_Enrollment__c(Program__c =Prog_2.Id, Account__c=acc.Id, Primary_Dealership_Contact__c=null,Name ='Program enrollment1_2', Approval_Status__c ='TM Rejected', Status__c='Eligible');
        programEnrollList.add(progEnroll2);
        insert programEnrollList;
        programEnrollList[0].Name='Program Enrollment1';
        upsert programEnrollList;
                
        
    }
    @isTest
    static void TestbeforeInsert(){
        List<sObject> aclist =[Select Id, Name, Account.IST_Account_Owner__c, Account.OwnerId from Account];
        List<sObject> programlist = [SELECT Name, Id, Program__c.Sales_Contact__c from Program__c]; 
        List<Program_Enrollment__c> ProgramEnrollList =[Select Id, Name, Program_Enrollment__c.Account__c,Program_Enrollment__c.Primary_Dealership_Contact__c,Program_Enrollment__c.IST_Sales_Rep_Email__c,Program_Enrollment__c.Sales_Contact__c,Program_Enrollment__c.Program__c,Program_Enrollment__c.Status__c, Program_Enrollment__c.Approval_Status__c,Program_Enrollment__c.Territory_Manager__c,Program_Enrollment__c.Regional_Sales_Director__c  from Program_Enrollment__c];
        system.debug('ProgramEnrollList'+ProgramEnrollList);
        List<sObject> ProgramEnrollLists = new List<sObject>();
        for (Program_Enrollment__c pe : ProgramEnrollList){
            pe.Status__c = 'Rejected';
            pe.Approval_Status__c ='RSD Approved';
            //pe.Approval_Status__c ='TM Rejected';
            ProgramEnrollLists.add(pe);
        }
        update ProgramEnrollLists;
        
        List<Program_Enrollment__c> ProgramEnrollList1 =[Select Id, Name, Program_Enrollment__c.Account__c,Program_Enrollment__c.Primary_Dealership_Contact__c,Program_Enrollment__c.IST_Sales_Rep_Email__c,Program_Enrollment__c.Sales_Contact__c,Program_Enrollment__c.Program__c,Program_Enrollment__c.Status__c, Program_Enrollment__c.Approval_Status__c  from Program_Enrollment__c];
        List<sObject> ProgramEnrollLists1 = new List<sObject>();
        for (Program_Enrollment__c pe : ProgramEnrollList1){
            pe.Status__c = 'Rejected';
            //pe.Approval_Status__c ='RSD Approved';
            pe.Approval_Status__c ='TM Rejected';
            ProgramEnrollLists1.add(pe);
        }
        update ProgramEnrollLists1;
        
        
        PopulateDefaultsOnProgramEnrollment populatedefaultsonProgramenroll = new PopulateDefaultsOnProgramEnrollment();
        populatedefaultsonProgramenroll.beforeInsert(ProgramEnrollList);
        populatedefaultsonProgramenroll.afterUpdate(ProgramEnrollList, ProgramEnrollLists);
    	populatedefaultsonProgramenroll.beforeUpdate(ProgramEnrollList, ProgramEnrollLists);
        
        System.assertEquals(3, ProgramEnrollLists.size());
        System.assertEquals(ProgramEnrollList, ProgramEnrollLists);
        System.assertNotEquals(null, ProgramEnrollList[0].Approval_Status__c);
        System.assertNotEquals(null, ProgramEnrollList[0].Status__c);
        System.assertEquals('Rejected', ProgramEnrollList1[0].Status__c);
        System.assertEquals('RSD Approved', ProgramEnrollList[0].Approval_Status__c);
        System.assertEquals('TM Rejected', ProgramEnrollList1[0].Approval_Status__c);
    
    }

}