objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>IST_Account_Owner_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For use in the arbitration approval process</description>
        <label>IST Account Owner Lookup</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>Master</businessProcess>
        <description>Support Case</description>
        <label>Support</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Customer_Inquiry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that the CI is related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Inquiries</relationshipLabel>
        <relationshipName>Customer_Inquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user assigned to this inquiry</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Inquiries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <description>The subset of Call Bucket, further defines what the dealer is calling about.</description>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Call_Bucket__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Release Slip</fullName>
                </value>
                <value>
                    <fullName>Payment Not Selected</fullName>
                </value>
                <value>
                    <fullName>NSF</fullName>
                </value>
                <value>
                    <fullName>Buyer Payment Status</fullName>
                </value>
                <value>
                    <fullName>Seller Payment Status</fullName>
                </value>
                <value>
                    <fullName>Default Payment Update</fullName>
                </value>
                <value>
                    <fullName>ACV Capital</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Pickup Issue</fullName>
                </value>
                <value>
                    <fullName>Cancel Transport</fullName>
                </value>
                <value>
                    <fullName>Dealmaker</fullName>
                </value>
                <value>
                    <fullName>Make an Offer</fullName>
                </value>
                <value>
                    <fullName>False Proxy</fullName>
                </value>
                <value>
                    <fullName>Goodwill Request</fullName>
                </value>
                <value>
                    <fullName>Multi-Store Buyer</fullName>
                </value>
                <value>
                    <fullName>Ghost Bid</fullName>
                </value>
                <value>
                    <fullName>Account/Contact Update</fullName>
                </value>
                <value>
                    <fullName>User Login Support</fullName>
                </value>
                <value>
                    <fullName>Deactivation</fullName>
                </value>
                <value>
                    <fullName>Good Experience</fullName>
                </value>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Titles</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Unwind</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Valid Business Reason</fullName>
                </value>
                <value>
                    <fullName>Called No Answer, Try Again</fullName>
                </value>
                <value>
                    <fullName>App Education</fullName>
                </value>
                <value>
                    <fullName>Seller Title Status</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <formula>IF( ISBLANK(TEXT(Call_Type__c)) , HYPERLINK( &quot;/&quot; + Id,  &quot;Historic Record&quot;, &quot;_self&quot;), HYPERLINK( &quot;/&quot; + Id,  TEXT(Call_Type__c), &quot;_self&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Inquiry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ops_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ops Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Related Support Cases</relationshipLabel>
        <relationshipName>Related_Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the inquiry.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>AM Follow Up</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inquiry Resolved</fullName>
                    <isActive>false</isActive>
                    <label>Inquiry Resolved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Related Cases &amp; Auctions</relationshipLabel>
        <relationshipName>Related_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Inquiry</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Customer Inquiry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesAccountProcesses.cls
public class SalesAccountProcesses {
    public static void runBeforeInsert(List<SobJect> incomingList){
        
    }

    public static void runAfterInsert(Map<Id,SobJect> incomingNewMap, Map<Id,SobJect> incomingOldMap){
        
    }

    public static void runBeforeUpdate(Map<Id,SobJect> incomingNewMap, Map<Id,SobJect> incomingOldMap){
        updateCaseISTAccountOwnersOnChange((Map<Id,Account>) incomingNewMap, (Map<Id,Account>) incomingOldMap);
    }

    public static void runAfterUpdate(Map<Id,SobJect> incomingNewMap, Map<Id,SobJect> incomingOldMap){
        
    }

    public static void updateCaseISTAccountOwnersOnChange(Map<Id,Account> newMap, Map<Id,Account> oldMap){
        Set<Id> accountIdSet = new Set<Id>();

        for(Account a :newMap.values()){
            if(a.IST_Account_Owner__c != oldMap.get(a.id).IST_Account_Owner__c){
                accountIdSet.add(a.id);
            }
        }

        if(accountIdSet.size() > 0){ 
            User doNotCall = [SELECT Id FROM User WHERE FirstName = 'Do' AND LastName = 'Not Call'];
            List<Case> updatedCases= new List<Case>();
            Map<Id,Customer_Inquiry__c> updatedCIs = new Map<Id,Customer_Inquiry__c>();
            for (Case c : [SELECT Id, AccountId, IST_Account_Owner_Lookup__c, RecordType.DeveloperName, (SELECT Id, OwnerId, Assigned_To__c, CreatedById FROM Related_Cases__r WHERE Account__c IN :accountIdSet AND Status__c != 'Closed') FROM Case WHERE AccountId IN :accountIdSet AND isClosed = false]) {
                if(newMap.get(c.accountId) != null){
                    c.IST_Account_Owner_Lookup__c = newMap.get(c.accountId).IST_Account_Owner__c;
                    if(c.RecordType.DeveloperName == 'Support' && newMap.get(c.AccountId).IST_Account_Owner__c != null && newMap.get(c.AccountId).IST_Account_Owner__c != doNotCall.Id) {
                        c.OwnerId = newMap.get(c.AccountId).IST_Account_Owner__c;
                    }
                    updatedCases.add(c);
                }
                for(Customer_Inquiry__c ci : c.Related_Cases__r) {
                    if(newMap.get(c.AccountId).IST_Account_Owner__c != null && newMap.get(c.AccountId).IST_Account_Owner__c != doNotCall.Id) {
                        ci.OwnerId = newMap.get(c.AccountId).IST_Account_Owner__c;
                        if(ci.Assigned_To__c == ci.CreatedById){
                            ci.Assigned_To__c = newMap.get(c.AccountId).IST_Account_Owner__c;
                        }
                        updatedCIs.put(ci.Id,ci);
                    }
                }
            }

            for (Customer_Inquiry__c ci : [SELECT Id, Ops_Case__r.AccountId, Assigned_To__c FROM Customer_Inquiry__c WHERE Ops_Case__r.AccountId IN :accountIdSet AND Call_Type__c = 'Seller Title Status' AND Status__c != 'Closed' AND ID NOT IN :updatedCIs.keySet()]) {
                if(ci.Assigned_To__c == oldMap.get(ci.Ops_Case__r.AccountId).IST_Account_Owner__c && newMap.get(ci.Ops_Case__r.AccountId).IST_Account_Owner__c != null && newMap.get(ci.Ops_Case__r.AccountId).IST_Account_Owner__c != doNotCall.Id) {
                    ci.Assigned_To__c = newMap.get(ci.Ops_Case__r.AccountId).IST_Account_Owner__c;
                    updatedCIs.put(ci.Id,ci);
                }
            }

            if(updatedCases.size() > 0){
                update updatedCases;
            }
            if(updatedCIs.size() > 0){
                update updatedCIs.values();
            }
        }
    }
}