objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether this Occurrence is still active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Timeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The revolving appointment that this occurrence appears on</description>
        <label>Revolving Appointment</label>
        <referenceTo>Timeline__c</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timeline__c.object
<CustomObject>
    <description>Object for defining a time period for creating recurring records</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Timelines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Average_Number_Cars__c</fullName>
        <description>Field for user to capture average number of cars for the visit</description>
        <label>Average Number of Cars</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this Timeline Currently Active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is part of new implementation for Revolving Appointment where Revolving appointment UI will have field work type to get selected</description>
        <label>Work Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Revolving Appointments can only be assigned to select Work Types. Please ensure you are selecting an appropriate Work Type.</errorMessage>
            <filterItems>
                <field>WorkType.Allow_for_Revolving_Appointments__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Revolving Appointments</relationshipLabel>
        <relationshipName>Revolving_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Revolving Appointment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revolving Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RevAppActiveFieldTest.cls
@isTest
public class RevAppActiveFieldTest {
    @TestSetup
    public static void createTerritory() {
        Account a = new Account(
            Name = 'ACV Dealership', Dealership_Id__c = '1', BillingPostalCode = '14209', legal_Name__c='ACV Dealership', dealer_type__c='1'
        );
        insert a;

        FSLTestUtility.createAllStructureWithParentST( /*'Great Lakes',*/ 'Buffalo', '14209' );
        Id workTypeId = [SELECT Id FROM WorkType WHERE Name = :FSLTestUtility.INSPECTION LIMIT 1].Id;
        Timeline__c tl = new Timeline__c(
            Account__c = a.id,
            Is_Active__c = true,
            Average_Number_Cars__c = 1,
            Work_Type__c = workTypeId
        );
        insert tl;

        Occurrence__c occ1 = new Occurrence__c(
            timeline__c = tl.id,
            is_Active__c = true
        );
        insert occ1;

        Occurrence__c occ2 = new Occurrence__c(
            timeline__c = tl.id,
            Is_Active__c = true
        );
        insert occ2;

        Occurrence__c occ3 = new Occurrence__c(
            timeline__c = tl.id,
            Is_Active__c = true
        );
        insert occ3;
    }
    @isTest
    public static void deactivateRevolvingAppointment(){
        Timeline__c tl = [SELECT id, Is_Active__c FROM Timeline__c LIMIT 1];
        tl.Is_Active__c = false;
        update tl;


        List<Occurrence__c> occList = new List<Occurrence__c>([SELECT id, Is_Active__c FROM Occurrence__c WHERE Timeline__c = :tl.id]);
        for(Occurrence__c occ : occList){
            system.assert(occ.Is_Active__c == false);
        }
    }

}