objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Receive_Push__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating if this member should receive mobile push notifications.</description>
        <label>Receive Push</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the date that the Affiliation began.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;admin&quot;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>rep</fullName>
                </value>
                <value>
                    <fullName>admin</fullName>
                    <default>true</default>
                    <label>admin</label>
                </value>
                <value>
                    <fullName>backoffice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>primary_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether this Occurrence is still active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Timeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The revolving appointment that this occurrence appears on</description>
        <label>Revolving Appointment</label>
        <referenceTo>Timeline__c</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <description>Work Type Unique ID for the Work Order linked to this Service Appointment.</description>
        <formula>Work_Order__r.WorkType.Work_Type_Unique_ID__c</formula>
        <label>Work Type Unique ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timeline__c.object
<CustomObject>
    <description>Object for defining a time period for creating recurring records</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Timelines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Average_Number_Cars__c</fullName>
        <description>Field for user to capture average number of cars for the visit</description>
        <label>Average Number of Cars</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this Timeline Currently Active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Day that the timeline begins</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Work_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is part of new implementation for Revolving Appointment where Revolving appointment UI will have field work type to get selected</description>
        <label>Work Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Revolving Appointments can only be assigned to select Work Types. Please ensure you are selecting an appropriate Work Type.</errorMessage>
            <filterItems>
                <field>WorkType.Allow_for_Revolving_Appointments__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Revolving Appointments</relationshipLabel>
        <relationshipName>Revolving_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Revolving Appointment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revolving Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Occurrence record from the revolving appointment generator that generated this work order record</description>
        <label>Occurrence</label>
        <referenceTo>Occurrence__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Work Type Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpireRevolvingAppointmentsBatchTest.cls
@isTest
public class ExpireRevolvingAppointmentsBatchTest {
    @TestSetup
    static void createData() {
        
        Account a = TestUtility.createAccount();
        insert a;

        Contact c = TestUtility.createContact( a );
        insert c;

        Affiliation__c aff = new Affiliation__c(
            Account__c=a.id, Contact__c=c.id, Active__c=true, Receive_Push__c = true, 
            Primary_Contact__c = true, Start_Date__c = Date.today().addDays(-7),
            type__c='rep'
        );
        insert aff;
        FSLTestUtility.createData( a, 1 );

        List<ServiceAppointment> saLst = [ SELECT Id, EarliestStartTime, DueDate FROM ServiceAppointment ];
        for ( ServiceAppointment saRec : saLst ) {
            saRec.EarliestStartTime = Date.today().addDays(-1);
            saRec.dueDate = Date.today();
        }
        update saLst;

        FSL.GlobalAPIS.addStatusTransition( 'New', ExpireRevolvingAppointmentsBatch.STATUS_CHANGE );
    }

    @isTest
    static void runBatchWithoutRevolvingAppointment() {

        List<ServiceAppointment> saLst = [ SELECT Id, DueDate FROM ServiceAppointment ];
        for ( ServiceAppointment saRec : saLst ) {     
            System.assertEquals( Date.today(), saRec.DueDate, 'The Due Date was an unexpected Date of ' + saRec.DueDate );
        }

        Test.startTest();
            ExpireRevolvingAppointmentsBatch batch = new ExpireRevolvingAppointmentsBatch();
            batch.executeScheduledLogic();
        Test.stopTest();     
    }

    @isTest
    static void runBatchWithRevolvingAppointment() {

        Test.startTest();
        	Timeline__c timeRec = new Timeline__c(
                Account__c = [ SELECT Id FROM Account LIMIT 1 ].Id,
                Is_Active__c = TRUE,
                Start_Date__c = Date.today().addDays(-7),
                Average_Number_Cars__c = 1,
                Work_Type__c = [ SELECT Id FROM WorkType WHERE Work_Type_Unique_ID__c = 'inspection' LIMIT 1 ].Id
            );
            insert timeRec;
        
            Occurrence__c occRec = RevolvingTest.generateTestOcc( timeRec, 'TestName', 'Daily', 1, tracDateUtils.DAY, null );
            insert occRec;

            List<WorkOrder> woLst = [ SELECT Id FROM WorkOrder ];
            for ( WorkOrder woRec : woLst ) {
                woRec.Occurrence__c = occRec.Id;
            }
            update woLst;

            for ( ServiceAppointment saRec : [ SELECT Id, DueDate FROM ServiceAppointment ] ) {     
                System.assertEquals( Date.today(), saRec.DueDate, 'The Due Date was an unexpected Date of ' + saRec.DueDate );
            }

            ExpireRevolvingAppointmentsBatch batch = new ExpireRevolvingAppointmentsBatch();
            batch.executeScheduledLogic();
        Test.stopTest();     
    }

    @isTest
    static void runBatchWithRevolvingAppointmentForError() {

        Test.startTest();
        	Timeline__c timeRec = new Timeline__c(
                Account__c = [ SELECT Id FROM Account LIMIT 1 ].Id,
                Is_Active__c = TRUE,
                Start_Date__c = Date.today().addDays(-7),
                Average_Number_Cars__c = 1,
                Work_Type__c = [ SELECT Id FROM WorkType WHERE Work_Type_Unique_ID__c = 'inspection' LIMIT 1 ].Id
            );
            insert timeRec;
        
            Occurrence__c occRec = RevolvingTest.generateTestOcc( timeRec, 'TestName', 'Daily', 1, tracDateUtils.DAY, null );
            insert occRec;

            List<WorkOrder> woLst = [ SELECT Id FROM WorkOrder ];
            for ( WorkOrder woRec : woLst ) {
                woRec.Occurrence__c = occRec.Id;
            }
            update woLst;

            for ( ServiceAppointment saRec : [ SELECT Id, DueDate FROM ServiceAppointment ] ) {     
                System.assertEquals( Date.today(), saRec.DueDate, 'The Due Date was an unexpected Date of ' + saRec.DueDate );
            }

            ExpireRevolvingAppointmentsBatch batch = new ExpireRevolvingAppointmentsBatch();

            BatchUtilityClass.testingFlag = TRUE;
            batch.executeScheduledLogic();
        Test.stopTest();   
    }
}