objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Sales_Region_Formula__c</fullName>
        <description>The region of the account, pulled from Territory__c.</description>
        <formula>Maps_Sales_Region_Name__c</formula>
        <label>Sales Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_End_Date_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Auction End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_IST__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller IST</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DealmakerOpportunitiesSellerIST</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DealMakerView2Test.cls
@isTest
private class DealMakerView2Test {
    
    @TestSetup
    private static void makeData() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u1 = new User(Username = 'Testy1@Testington.test', LastName = 'McTesty1', Email ='Testy1@Testington.test', Alias = 'TESTBOY1', CommunityNickname = 'tEsT1', TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', ProfileId = p.Id, LanguageLocaleKey = 'en_US');
        insert u1;
        list<Account> actList = new list<Account>();
        actList.add(new Account(Name = 'Test Account'));
        //actList.add(new Account(Name = 'Test Account 2', Sales_Region_Formula__c = 'Great Lakes Region'));
        insert actList;
        Auction__c testAuc = new Auction__c(Name = '940938', status__c = 'counter_sent');
        insert testAuc;
        Datetime now = System.Now();
        date future = System.Today().addDays(30);
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Deal Maker').getRecordTypeId();
        List<Opportunity> oppList = new list<Opportunity>();
        oppList.add(new Opportunity(Auction_End_Date_Time__c = now, RecordTypeId = recordTypeId, Name = 'Test', CloseDate = future, StageName = 'New', AccountId = actList[0].Id, Auction__c = testAuc.Id, Seller_IST__c = u1.Id));
        oppList.add(new Opportunity(Auction_End_Date_Time__c = now, RecordTypeId = recordTypeId, Name = 'Test', CloseDate = future, StageName = 'New', AccountId = actList[0].Id, Auction__c = testAuc.Id));
        insert oppList;
    }

    @IsTest
    private static void testReturn(){
        String blank = '[]';
        List<Opportunity> oppList = DealMakerView2.getOpportunities(blank);
        System.assertEquals(2, oppList.size());
    }

    @IsTest
    private static void testSearch(){
        User testUser = [SELECT Id FROM User WHERE LastName = 'McTesty1'];
        Opportunity searchOpp = [SELECT Id, Seller_IST__c FROM Opportunity WHERE Seller_IST__c != null];
        List<Opportunity> oppList = DealMakerView2.getOpportunities('["'+testUser.Id+'"]');
        System.assertEquals(1, oppList.size());
        System.assertEquals(searchOpp.Id, oppList[0].Id);
    }

    @IsTest
    private static void nullTest(){
        List<Opportunity> oppList = DealMakerView2.getOpportunities('["User 3000"]');
        System.assertEquals(0, oppList.size());
    }

    @IsTest
    private static void lfListTest(){
        User testUser = [SELECT Id FROM User WHERE LastName = 'McTesty1'];
        List<LookupSearchResult> useList = DealMakerView2.searchTheTerm('Roxanne');
        System.assertEquals(0, useList.size());
    }

    @IsTest
    private static void loadFiltTest(){
        User testUser = [SELECT Id FROM User WHERE LastName = 'McTesty1'];
        list<String> testStrings = new List<String>();
        testStrings.add('McTesty1');
        DealMakerView2.filterSave(testStrings);
        List<LookupSearchResult> loadTest = DealMakerView2.loadFilterList();
        System.assertEquals(1, loadTest.size());
    }

}