objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance_Issues__c</fullName>
        <label>Compliance Issues</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Missing Signature</fullName>
                    <label>Missing signature</label>
                </value>
                <value>
                    <fullName>Incorrect State</fullName>
                    <label>Incorrect state</label>
                </value>
                <value>
                    <fullName>Document illegible</fullName>
                </value>
                <value>
                    <fullName>Incorrect document</fullName>
                </value>
                <value>
                    <fullName>Did not specify reason for exemption on MTC</fullName>
                </value>
                <value>
                    <fullName>State doesn&apos;t allow MTC for resale purpose</fullName>
                </value>
                <value>
                    <fullName>Resale not specified</fullName>
                </value>
                <value>
                    <fullName>Resale box not checked</fullName>
                </value>
                <value>
                    <fullName>Document expired</fullName>
                </value>
                <value>
                    <fullName>Missing Resale/Tax ID #</fullName>
                </value>
                <value>
                    <fullName>ACV Listed As Seller</fullName>
                    <label>ACV listed as seller</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Document Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_Expiration__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If a resale certificate does not have an expiration date (all states except AZ, MI, NE, WA and FL), you must check this box.</inlineHelpText>
        <label>No Expiration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Dealer_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used on the Confirmation Doc record type. This is the lookup to the license the confirmation doc is a renewal for.</description>
        <label>Related Dealer License</label>
        <referenceTo>Dealer_Docs__c</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <label>Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Review</fullName>
                    <default>true</default>
                    <label>Ready for Review</label>
                </value>
                <value>
                    <fullName>Requires BDR</fullName>
                    <label>Requires IST</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>License_Renewal_Confirmation</fullName>
        <active>true</active>
        <description>Record type for License Renewal Confirmation documents</description>
        <label>License Renewal Confirmation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State_Abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>OR</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

classes/DealerDocExpirationHandler.cls
global class DealerDocExpirationHandler extends SchedulingInterface implements Database.Batchable<sObject>, Database.Stateful {
    public static List<String> errorList = new List<String>();
    public static final Id licenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id resaleId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();
    public static final Id confirmationId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('License_Renewal_Confirmation').getRecordTypeId();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Expiration_Date__c, Document_Expired__c, Review_Status__c, RecordTypeId, Compliant__c, Compliance_Issues__c, Account__c, Account__r.Name, Document_State__c, Related_Dealer_License__c FROM Dealer_Docs__c WHERE (Expiration_Date__c <= TODAY AND Document_Expired__c = false AND No_Expiration__c = false)';
        //Account__r.IST_Account_Owner__r.Email, (pulling this out)
        //select (a bunch of fields) from Dealer Docs where:
        //expiration date is today or earlier,
        //document is not marked as expired yet,
        //and no expiration is not checked
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Dealer_Docs__c> scope) {
        Set<String> specialStates = new Set<String>{'NH', 'DE', 'OR', 'MT', 'AK'};
        Set<Id> cdocDealersToday = new Set<Id>();
        Set<Id> cdocRelatedLicToday = new Set<Id>();
        List<Dealer_Docs__c> expTwoWeeks = new List<Dealer_Docs__c>();
        Map<Id, List<Dealer_Docs__c>> confirmationDocsExpTwoWeeks = new Map<Id, List<Dealer_Docs__c>>();
        for (Dealer_Docs__c d : scope) {
            if (d.RecordTypeId == confirmationId) {
                cdocDealersToday.add(d.Account__c);
                cdocRelatedLicToday.add(d.Related_Dealer_License__c);
                d.Document_Expired__c = true;
                d.Compliant__c = false;
                d.Compliance_Issues__c = 'Document expired';
                d.Review_Status__c = null;
            }
            else {
                if (d.RecordTypeId == licenseId || d.RecordTypeId == resaleId) {
                    d.Document_Expired__c = true;
                    d.Compliant__c = false;
                    d.Compliance_Issues__c = 'Document expired';
                    d.Review_Status__c = null;
                }
            }
        }

        if (!cdocRelatedLicToday.isEmpty()) {
            ConfirmationDocExpirationLogic.handleExpiringToday(cdocDealersToday, cdocRelatedLicToday); //this will handle the license expiration
        }

        Database.SaveResult[] mesgList = Database.update(scope, false); //try to update docs
        for (Database.SaveResult upRes : mesgList) {
            if (!upRes.isSuccess()) {
                //error message
                Database.Error errors = upRes.getErrors()[0];
                String errMesg = 'ERROR on Id: ' + upRes.getId() + '<br/>With Status Code of: ' + errors.getStatusCode() + '<br/>And Error of: ' + errors.getMessage();
                DealerDocExpirationHandler.errorList.add(errMesg);
            }
        }
    }

    global void finish(Database.BatchableContext bc) {
        //finish
        if (DealerDocExpirationHandler.errorList.size() > 0) {
            AsyncApexJob a = [SELECT Id, Status, ExtendedStatus, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[]{'SF-DevAlerts@acvauctions.com'};
            //String[] toAddresses = new String[]{'kpriebe@acvauctions.com'};
            mail.setToAddresses(toAddresses);
            mail.setSubject('DealerDocExpirationHandler: ' + a.Status);
            String body = 'Results from DealerDocExpirationHandler Batch: <br/>' + 'Number of Items Processed: ' + a.JobItemsProcessed + '<br/>Number of Errors: ' + a.NumberOfErrors + '<br/>';
            body += String.join(DealerDocExpirationHandler.errorList, '<br/>');
            mail.setHtmlBody(body);
            if (!test.isRunningTest()) {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
        }
    }

    public override void executeScheduledLogic() {
        //schedule
        DealerDocExpirationHandler almb = new DealerDocExpirationHandler();
        Database.executeBatch(almb, 200);
    }
}