objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the date that the Affiliation began.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;admin&quot;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>rep</fullName>
                </value>
                <value>
                    <fullName>admin</fullName>
                    <default>true</default>
                    <label>admin</label>
                </value>
                <value>
                    <fullName>backoffice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>Unique Id in ACV databases - used for integration purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Dealership Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <description>acv_prod id found on the users table used to identify internal users</description>
        <externalId>true</externalId>
        <inlineHelpText>This corresponds to the User&apos;s ACV Tools ID</inlineHelpText>
        <label>ACV User Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/IdentityServiceCreateAffiliation.cls
/*
 * 
 * 10/11/2021 - Ravi Shukla (Anablock) - New value 'back office staff member' added for type field in condition.
 * 
*/

@RestResource(urlMapping='/IdentityService/affiliationcreate')
global class IdentityServiceCreateAffiliation {
 
    @HTTPPost
    global static void createAffiliation(affiliate affiliate){
        String affID = IdentityHelper.createAffiliationId(affiliate.dealerId, affiliate.userId);
        ACVAPIHelper.SFResponse identityResult = new ACVAPIHelper.SFResponse(affiliate, '', 200);
        identityResult.originalRequest = affiliate;
        String endpointURL = URL.getSalesforceBaseUrl().toExternalForm()+'/apex/services/identityservice/updatedealer';
        Map<String, String> headerMap = new Map<String, String>();
        headerMap.put('Content-Type', 'application/json');
        List<Account> accList = new List<Account>([SELECT ID FROM ACCOUNT WHERE Dealership_ID__c = :affiliate.dealerId]);
        List<Contact> conList = new List<Contact>([SELECT ID FROM CONTACT WHERE Id__c = :affiliate.userId]);


        if([Select Id From Affiliation__c WHERE id__c = :affId AND Active__c = TRUE].size() >= 1){
            identityResult.message = 'Active Affiliation Exists For Found For That UserId/DealerId Combination';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(affiliate, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'POST','IdentityServiceCreateAffiliation:'+identityResult.message, SplunkHelper.LOGLEVEL.FATAL, 500);
            identityResult.generateResponse(headerMap);
            return;
        }
        if(accList.size() == 0){
            identityResult.message = 'No Dealer Found with that Dealer Id';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(affiliate, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'POST', 'IdentityServiceCreateAffiliation:'+identityResult.message, SplunkHelper.LOGLEVEL.FATAL, 500);
            identityResult.generateResponse(headerMap);
            return;
        }
        if(conList.size() == 0){
            identityResult.message = 'No User Found with that User Id';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(affiliate, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'POST', 'IdentityServiceCreateAffiliation:'+identityResult.message, SplunkHelper.LOGLEVEL.FATAL, 500);
            identityResult.generateResponse(headerMap);
            return;
        }
        if(affiliate.type != 'rep' && affiliate.type != 'admin' && affiliate.type != 'backoffice'){
            identityResult.message = 'Only accepted Affiliate Types are "rep", "admin" and "backoffice"';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(affiliate, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'POST', 'IdentityServiceCreateAffiliation:'+identityResult.message, SplunkHelper.LOGLEVEL.FATAL, 500);
            identityResult.generateResponse(headerMap);
            return;
        }
        try{
            insert new Affiliation__c(type__c = affiliate.type, id__c = affID, Account__c = accList[0].id, Contact__c = conList[0].id, Active__c = true, Start_Date__c = System.Today());
        }
        catch(Exception e){
            identityResult.message = 'Error Creating new Affiliation';
            identityResult.statusCode = 500;
            IdentityHelper.makeLog(affiliate, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'POST', e.getStackTraceString()+':'+e.getMessage(), SplunkHelper.LOGLEVEL.FATAL, 500);
            identityResult.generateResponse(headerMap);
            return;
        }
        identityResult.message = 'Affiliation Created';
        identityResult.statusCode = 201;
        identityResult.apiResponse = affiliate;
        IdentityHelper.makeLog(affiliate, identityResult, ACVUtility.currentLineNumber(), endpointURL, 'PATCH', 'IdentityService.createAffiliation Line: '+ACVUtility.currentLineNumber(), SplunkHelper.LOGLEVEL.INFO, 201);
        identityResult.generateResponse(headerMap);
    }

    global class affiliate{
        global string userId;
        global string dealerId;
        global string type;
    }
}