objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>All_Time_Sales_Gross__c</fullName>
        <defaultValue>0</defaultValue>
        <description>gross count of a sellers sales</description>
        <label>All Time Sales (Gross)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchases_All_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>All Time Purchases</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the program is active or not.</description>
        <inlineHelpText>Used to indicate if the program is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Rule_Logic__c</fullName>
        <description>User to enter the field logic criteria</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Rule Logic Eligibility</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <description>Used to find the sales team member for this Program</description>
        <inlineHelpText>Used to find the sales team member for this Program</inlineHelpText>
        <label>Sales Contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IST_Account_Owner__c</fullName>
                    <label>Account Manager</label>
                </value>
                <value>
                    <fullName>OwnerId</fullName>
                    <label>Territory Manager</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to capture current status program.</description>
        <inlineHelpText>Used to capture current status program.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not eligible</fullName>
                </value>
                <value>
                    <fullName>In/under review by IST (use pre and post pending customer response)</fullName>
                </value>
                <value>
                    <fullName>Pending customer response (pending app completion) -In/under review by IST</fullName>
                </value>
                <value>
                    <fullName>Waiting on POA (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Verified by IST (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Under review by TM under review by RSD approved Rejected [with reasons] (do not call removes from eligibility)</fullName>
                </value>
                <value>
                    <fullName>TM will be reaching out to you soon Enrolled (start date)</fullName>
                </value>
                <value>
                    <fullName>Active (initiated at first sale)</fullName>
                </value>
                <value>
                    <fullName>Remove (for performance)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the user who is the manager of the dealer / account</description>
        <inlineHelpText>Used to store the user who is the manager of the dealer / account</inlineHelpText>
        <label>Sales Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_To_Compare_1__c</fullName>
        <description>Used to store api name of first field to compare</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Used to store api name of first field to compare</inlineHelpText>
        <label>Field To Compare 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Compare_2__c</fullName>
        <description>Used to store api name of second field to compare</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Used to store api name of second field to compare</inlineHelpText>
        <label>Field To Compare 2</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <description>Used to decide operator which can be used to compare fields</description>
        <inlineHelpText>Used to decide operator which can be used to compare fields</inlineHelpText>
        <label>Field Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>DATE</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>INTEGER</fullName>
                </value>
                <value>
                    <fullName>LOCATION</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>NUMBER</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>REFERENCE</fullName>
                </value>
                <value>
                    <fullName>STRING</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <isActive>false</isActive>
                    <label>Text</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_RHS_Static_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To indicate if RHS is static value</description>
        <inlineHelpText>To indicate if RHS is static value</inlineHelpText>
        <label>Is RHS Static Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>Used to store operator to compare field 1 and field 2</description>
        <inlineHelpText>Used to store operator to compare field 1 and field 2</inlineHelpText>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Field_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Rule_Operators</valueSetName>
        </valueSet>
    </fields>
    <label>Program Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Rules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Program_Rule__c</fullName>
        <label>Program Rule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Rule__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Rule__c</referenceTo>
        <relationshipLabel>Rule Assignment</relationshipLabel>
        <relationshipName>Rule_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Rule Assignment</relationshipLabel>
        <relationshipName>Rule_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Assignment</label>
    <nameField>
        <displayFormat>RA{00000000}</displayFormat>
        <label>Rule Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

globalValueSets/Rule_Operators.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>=</fullName>
        <label>Equals</label>
    </customValue>
    <customValue>
        <fullName>!=</fullName>
        <label>Not Equals</label>
    </customValue>
    <customValue>
        <fullName>&lt;</fullName>
        <label>Less Than</label>
    </customValue>
    <customValue>
        <fullName>&gt;</fullName>
        <label>Greater Than</label>
    </customValue>
    <customValue>
        <fullName>&lt;=</fullName>
        <label>Less Than Or Equal To</label>
    </customValue>
    <customValue>
        <fullName>&gt;=</fullName>
        <label>Greater Than Or Equal To</label>
    </customValue>
    <masterLabel>Rule Operators</masterLabel>
</GlobalValueSet>

classes/PopulateSalesContactOnProgramEnrollTest.cls
/******************************************
*Author - Avinash Sharma(Saisystems) 
*Description - Test Class for PopulateSalesContactOnProgramEnrollments 
*Date - 5 APR 2021
*******************************************/
@isTest
public class PopulateSalesContactOnProgramEnrollTest {
    @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account acc=TestUtility.createAccount();
        acc.IST_Account_Owner__c =UserInfo.getUserId();
        insert acc;
        
        Contact con = TestUtility.createContact(acc);
        insert con;
        
        List<Program_Rule__c> progRuleList=new List<Program_Rule__c>();
        Program_Rule__c programRule = new Program_Rule__c();
        programRule.Active__c =true;
        programRule.Field_To_Compare_1__c='Account.Purchases_All_Time__c';
        programRule.Operator__c = '>';
        programRule.Field_To_Compare_2__c ='Account.All_Time_Sales_Gross__c';
        programRule.Field_Type__c= 'INTEGER';
        programRule.Eligibility__c=true;
        progRuleList.add(programRule);
        
         Program_Rule__c programRule1 = new Program_Rule__c();
        programRule1.Active__c =true;
        programRule1.Field_To_Compare_1__c='Account.Active__c';
        programRule1.Operator__c = '=';
        programRule1.Field_To_Compare_2__c ='true';
        programRule1.Is_RHS_Static_Value__c=true;
        programRule1.Field_Type__c= 'BOOLEAN';
        programRule1.Eligibility__c=true;
        progRuleList.add(programRule1);
        insert progRuleList;
        
        List<Program__c> programList = New List<Program__c>();
        Program__c prog = new Program__c();
        prog.Name ='Program';
        Prog.Active__c =true;
        Prog.Sales_Contact__c='IST_Account_Owner__c';
        prog.Program_Rule_Logic__c='1 AND 2';
        Prog.Status__c ='Eligible';
        programList.add(Prog);
        
        Program__c Prog_1 = new Program__c();
        Prog_1.Name ='Program';
        Prog_1.Active__c =true;
        Prog_1.Sales_Contact__c='IST_Account_Owner__c';
        Prog_1.Program_Rule_Logic__c='1 AND 2';
        Prog_1.Status__c ='Eligible';
        programList.add(Prog_1);
        insert programList;
        
        //Prog.Sales_Contact__c='OwnerId';
        //update prog;
        
        
        
        List<Rule_Assignment__c> ruleAssignList = New List<Rule_Assignment__c>();
        Rule_Assignment__c ruleAssign = new Rule_Assignment__c();
        ruleAssign.Order__c = 1;
        ruleAssign.Program__c = prog.Id;
        ruleAssign.Program_Rule__c = programRule.Id;
        ruleAssignList.add(ruleAssign);
        
        Rule_Assignment__c ruleAssign1 = new Rule_Assignment__c();
        ruleAssign1.Order__c = 2;
        ruleAssign1.Program__c = prog.Id;
        ruleAssign1.Program_Rule__c = programRule1.Id;
        ruleAssignList.add(ruleAssign1);
        insert ruleAssignList;
        
        List<Program_Enrollment__c> programEnrollList = new List<Program_Enrollment__c>();        
        Program_Enrollment__c progEnroll = new Program_Enrollment__c(Program__c =prog.Id, Account__c=acc.Id, Primary_Dealership_Contact__c=con.Id,Name ='Program enrollment', Status__c='Rejected', Approval_Status__c ='TM Rejected');
        programEnrollList.add(progEnroll);
        Program_Enrollment__c progEnroll1 = new Program_Enrollment__c(Program__c =Prog_1.Id, Account__c=acc.Id, Primary_Dealership_Contact__c=con.Id,Name ='Program enrollment1', Status__c='Rejected', Approval_Status__c ='TM Rejected');
        programEnrollList.add(progEnroll1);
        insert programEnrollList;
        System.assertNotEquals(null, acc.IST_Account_Owner__c);
        System.assertEquals(UserInfo.getUserId(), acc.IST_Account_Owner__c);
        
    }
    @isTest
    static void TestafterUpdate(){
    	List<Program__c> programlist = [SELECT Name, Id, Program__c.Sales_Contact__c,Program__c.Program_Rule_Logic__c from Program__c];
        List<Program_Enrollment__c> programEnrollmentList =[SELECT Id, Name from Program_Enrollment__c];
        List<sObject> programlists = new List<sObject>();
        for (Program__c pe : programlist){
            pe.Name = 'Program1';
            pe.Sales_Contact__c='IST_Account_Owner__c';
            programlists.add(pe);
        }
        update programlists;
        PopulateSalesContactOnProgramEnrollments populatesalescontactonproramenroll = new PopulateSalesContactOnProgramEnrollments();
        populatesalescontactonproramenroll.afterUpdate(programlist,programlists);
        PopulateSalesContactOnProgramEnrollments.populateProgramEligibilityCriteria(programlists);
        System.assertEquals(programlist, programlists);        
		System.assertNotEquals(null, programlist[0].Sales_Contact__c);
        System.assertNotEquals(null, programlist);
        System.assertNotEquals(null, programlists);
	
    }
}