objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Report_Prescreen__c.object
<CustomObject>
    <fields>
        <fullName>CR_Review_Timeout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is checked if 30 minutes has elapsed since creation and no review has been completed.</description>
        <label>CR Review Timeout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CR_Update_by_pre_Screener__c</fullName>
        <description>Changes made to the CR by Pre-Screener field needs to be filled out to close the case. There is also a validation rule to verify this is filled in before closing the record.</description>
        <label>CR Update by pre-Screener</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VCI_Creator_Email__c</fullName>
        <description>Email address of the VCI Creator</description>
        <label>VCI Creator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>VCI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VCI</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Condition_Report_Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report Prescreen</label>
    <nameField>
        <displayFormat>CRR-{0000000}</displayFormat>
        <label>Condition Report Prescreen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Report Prescreen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CR_Question__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report_Prescreen__c</fullName>
        <label>Condition Report Prescreen</label>
        <referenceTo>Condition_Report_Prescreen__c</referenceTo>
        <relationshipLabel>CR Questions</relationshipLabel>
        <relationshipName>CR_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_Sub_Type__c</fullName>
        <label>Question Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Question_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Question_Sub_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Question_Type</valueSetName>
        </valueSet>
    </fields>
    <label>CR Question</label>
    <nameField>
        <displayFormat>CRQ-{0000}</displayFormat>
        <label>CR Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CR Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Prescreen_Reason__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report_Prescreen__c</fullName>
        <label>Condition Report Prescreen</label>
        <referenceTo>Condition_Report_Prescreen__c</referenceTo>
        <relationshipLabel>Prescreen Reasons</relationshipLabel>
        <relationshipName>Prescreen_Reasons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prescreen Reason</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Prescreen Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescreen Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Question_Sub_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>4x4 / 4WD / Drivetrain Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Abnormal Smoke from Exhaust</fullName>
    </customValue>
    <customValue>
        <fullName>Aftermarket Parts - Exterior</fullName>
    </customValue>
    <customValue>
        <fullName>Aftermarket Parts - Mechanical</fullName>
    </customValue>
    <customValue>
        <fullName>Aftermarket Rims / Tires</fullName>
    </customValue>
    <customValue>
        <fullName>Aftermarket Stereo Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Airbag Deployed</fullName>
    </customValue>
    <customValue>
        <fullName>Airbag Light</fullName>
    </customValue>
    <customValue>
        <fullName>Automatic Shifter</fullName>
    </customValue>
    <customValue>
        <fullName>Bad Amp</fullName>
    </customValue>
    <customValue>
        <fullName>Battery/Charging Light</fullName>
    </customValue>
    <customValue>
        <fullName>Blurry</fullName>
    </customValue>
    <customValue>
        <fullName>Brake/ABS Light</fullName>
    </customValue>
    <customValue>
        <fullName>Brake Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Branded Title</fullName>
    </customValue>
    <customValue>
        <fullName>Broken</fullName>
    </customValue>
    <customValue>
        <fullName>CA DMV Fees</fullName>
    </customValue>
    <customValue>
        <fullName>Carpet Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Catalytic Converters Missing</fullName>
    </customValue>
    <customValue>
        <fullName>Check Engine Light</fullName>
    </customValue>
    <customValue>
        <fullName>Chipped</fullName>
    </customValue>
    <customValue>
        <fullName>Climate Control Not Working</fullName>
    </customValue>
    <customValue>
        <fullName>Cracked</fullName>
    </customValue>
    <customValue>
        <fullName>Crank Windows</fullName>
    </customValue>
    <customValue>
        <fullName>Damaged</fullName>
    </customValue>
    <customValue>
        <fullName>Damaged Tires</fullName>
    </customValue>
    <customValue>
        <fullName>Damaged Wheels</fullName>
    </customValue>
    <customValue>
        <fullName>Dash/Instrument Panel Damage</fullName>
    </customValue>
    <customValue>
        <fullName>Dented</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Scratches</fullName>
    </customValue>
    <masterLabel>Question Sub-Type</masterLabel>
</GlobalValueSet>

classes/PrescreenEmailsSchedulerTest.cls
@isTest(isParallel=true)
private class PrescreenEmailsSchedulerTest {
    
    @testSetup static void initData(){
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Legal_Name__c = 'Test';
        acc.Dealer_Type__c = 'Franchise';
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Test';
        con.Email = 'test@test.com';
        con.AccountId = acc.Id;
        insert con;
        
        Condition_Report_Prescreen__c prescreen = new Condition_Report_Prescreen__c();
        prescreen.VCI__c = con.Id;
        prescreen.Status__c = 'New';
        prescreen.VCI_Creator_Email__c = 'test@test.com';
        insert prescreen;
        
        Prescreen_Reason__c reason = new Prescreen_Reason__c();
        reason.Name = 'Exotic';
        reason.Condition_Report_Prescreen__c = prescreen.Id;
        insert reason;
        
        CR_Question__c question = new CR_Question__c();
		question.Question_Type__c = 'Exterior';
        question.Question_Sub_Type__c = 'Scratches';
        question.Condition_Report_Prescreen__c = prescreen.Id;
        insert question;
    }
    
    @isTest static void crSentToPrescreen(){
        PrescreenEmailsScheduler scheduler = new PrescreenEmailsScheduler();
        Test.startTest();
        scheduler.executeScheduledLogic();
        Test.stopTest();
        
       	System.assertEquals(true, [SELECT Sent_To_Prescreen_Email__c FROM Condition_Report_Prescreen__c][0].Sent_To_Prescreen_Email__c);
    }
    
    @isTest static void crTimeout(){
        Condition_Report_Prescreen__c prescreen = [SELECT Id FROM Condition_Report_Prescreen__c][0];
        prescreen.CR_Review_Timeout__c = true;
        prescreen.Sent_To_Prescreen_Email__c = true;
        update prescreen;
        
        PrescreenEmailsScheduler scheduler = new PrescreenEmailsScheduler();
        Test.startTest();
        scheduler.executeScheduledLogic();
        Test.stopTest();
        
       	System.assertEquals(true, [SELECT Time_Out_Email__c FROM Condition_Report_Prescreen__c][0].Time_Out_Email__c);
    }
    
    @isTest static void crUnderReview(){
        Condition_Report_Prescreen__c prescreen = [SELECT Id FROM Condition_Report_Prescreen__c][0];
        prescreen.Status__c = 'Under Review';
        update prescreen;
        
        PrescreenEmailsScheduler scheduler = new PrescreenEmailsScheduler();
        Test.startTest();
        scheduler.executeScheduledLogic();
        Test.stopTest();
        
       	System.assertEquals(true, [SELECT Under_Review_Email__c FROM Condition_Report_Prescreen__c][0].Under_Review_Email__c);
    }
    
    @isTest static void closedWithChanges(){
        Condition_Report_Prescreen__c prescreen = [SELECT Id FROM Condition_Report_Prescreen__c][0];
        prescreen.Status__c = 'Closed';
        update prescreen;
                
        PrescreenEmailsScheduler scheduler = new PrescreenEmailsScheduler();
        Test.startTest();
        scheduler.executeScheduledLogic();
        Test.stopTest();
        
       	System.assertEquals(true, [SELECT Completed_Review_Changes_Email__c FROM Condition_Report_Prescreen__c][0].Completed_Review_Changes_Email__c);
    }
    
    @isTest static void closedWithChangesButNoQuestions(){
        Condition_Report_Prescreen__c prescreen = [SELECT Id FROM Condition_Report_Prescreen__c][0];
        prescreen.Status__c = 'Closed';
        prescreen.CR_Update_by_pre_Screener__c = 'Yes';
        update prescreen;
        
        delete [select id from CR_Question__c];
        
        PrescreenEmailsScheduler scheduler = new PrescreenEmailsScheduler();
        Test.startTest();
        scheduler.executeScheduledLogic();
        Test.stopTest();
        
       	System.assertEquals(true, [SELECT Completed_Review_Changes_Email__c FROM Condition_Report_Prescreen__c][0].Completed_Review_Changes_Email__c);
    }
    
    @isTest static void closedWithoutChanges(){
        Condition_Report_Prescreen__c prescreen = [SELECT Id FROM Condition_Report_Prescreen__c][0];
        prescreen.Status__c = 'Closed';
        update prescreen;
        
        delete [select id from CR_Question__c];
        
        PrescreenEmailsScheduler scheduler = new PrescreenEmailsScheduler();
        Test.startTest();
        scheduler.executeScheduledLogic();
        Test.stopTest();
        
       	System.assertEquals(true, [SELECT Completed_Reviewed_No_Changes_Email__c FROM Condition_Report_Prescreen__c][0].Completed_Reviewed_No_Changes_Email__c);
    }

}