objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>ACV_inop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Integrated from Condition report answers when question #43 (Vehicle Inop - Does not move) is selected as TRUE</description>
        <label>ACV inop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <description>Set by Process Builder automation.</description>
        <label>Make</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vehicle_Make</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release_Pickup_Phrase__c</fullName>
        <description>Pickup_Phrase from auctions_attribute table</description>
        <label>Release Pickup Phrase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Inventory_Id__c</fullName>
        <description>Field populated through Inbound integration from the seller_inventory_id field found on the saved_auctions table in acv_prod</description>
        <label>Seller Inventory Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>This will be the same as Auction Number (Name), but is marked as an external ID for integration purposes.</description>
        <externalId>true</externalId>
        <label>Auction ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record for the buyer, person who will get delivery of vehicle</description>
        <label>Buyer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Buyer Dealership)</relationshipLabel>
        <relationshipName>Buyer_Transportation_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Buyer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buyer_Pickup_Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Buyer Pickup Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Buyer_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount charged to buyer for transportation service</description>
        <inlineHelpText>Price charged to customer for ACV arranged transportation of vehicle</inlineHelpText>
        <label>Buyer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Default_Delivery_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Delivery_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery City</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Delivery_Country__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Country</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Delivery_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Delivery_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Pickup_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pickup City</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Pickup_Country__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pickup Country</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Pickup_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pickup Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Pickup_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pickup State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Address_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delivery Address Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pickup_Address_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pickup Address Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pickup Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Pre_Promotion__c</fullName>
        <description>Price before promotion is applied to it.</description>
        <label>Price Pre Promotion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Release_Pickup_Phrase__c</fullName>
        <description>Pickup_Phrase from auctions_attribute table</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Release Pickup Phrase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Contact_Email__c</fullName>
        <description>This field is auto-populated via apex code to stamp the selling dealership&apos;s primary contact&apos;s email. Coed done by Manmeet Vasser</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Seller Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Seller_Contact_Phone__c</fullName>
        <formula>Seller_Contact__r.Phone</formula>
        <label>Seller Contact Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Inventory_Id__c</fullName>
        <formula>Auction_Number__r.Seller_Inventory_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Seller Inventory Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <formula>Seller_Dealership__r.Name</formula>
        <label>Seller Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Pick_Up_Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Seller Pick Up Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transportation_Notes__c</fullName>
        <description>Field to enter transportation notes on unwind case record</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Transportation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Is_Oversize__c</fullName>
        <formula>Vehicle__r.Vehicle_Is_Oversize__c</formula>
        <label>Vehicle Is Oversize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>Field used for integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Arbitration ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Transportation</fullName>
        <active>true</active>
        <businessProcess>Transportation Process</businessProcess>
        <description>Cases for handling transportation request</description>
        <label>Transportation</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>ACV_inop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACV inop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Is_Oversize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vehicle Is Oversize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>class_name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle ID</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>make__c</fullName>
        <description>The make (manufacturer) of the vehicle.</description>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>trim__c</fullName>
        <label>Trim</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/TransportationRequestCreateInvocable.cls
public class TransportationRequestCreateInvocable {
    
    private static string endpointURL = '/api/v1/transportation/create';

    @InvocableMethod 
    public static List<TransportationFlowResult> TransportationRequestCreate(List<Case> inputList){
        Case inputCase = inputList[0];
        Contact pickupContact;
        Contact deliveryContact;

        System.debug(inputCase.Seller_Contact__c);
        System.debug(inputCase.ContactId);
        if(inputCase.Seller_Contact__c != null){
            pickupContact = [Select id, Name, Email, Phone From Contact Where id = :inputCase.Seller_Contact__c];
        }
        if(inputCase.ContactId != null){
            deliveryContact = [Select id, Name, Email, Phone From Contact Where id = :inputCase.ContactId];
        }
        System.debug(pickupContact);
        System.debug(deliveryContact);

        if(inputCase.Auction_Number__c != null){
            Auction__c auctionData = [Select id, id__c, Release_Pickup_Phrase__c, vehicle_id__c, vehicle_id__r.vin__c, vehicle_id__r.year__c, vehicle_id__r.make__c, vehicle_id__r.model__c,
            vehicle_id__r.trim__c, vehicle_id__r.class_name__c, vehicle_id__r.Vehicle_Is_Oversize__c, ACV_inop__c, Seller_Dealership__r.Dealership_id__c, buyer_dealership__r.Dealership_Id__c,
            Seller_Dealership__r.Primary_Contact__r.Name, Seller_Dealership__r.Primary_Contact__r.Phone, Seller_Dealership__r.Primary_Contact__r.Email,  buyer_dealership__r.Primary_Contact__r.Name, 
            buyer_dealership__r.Primary_Contact__r.Phone, buyer_dealership__r.Primary_Contact__r.Email, Seller_Inventory_Id__c From Auction__c Where id = :inputCase.Auction_Number__c];
            TransportationRequestCreateObject trco = convertCaseToCalloutObject(inputCase, auctionData, pickupContact, DeliveryContact);
            List<TransportationFlowResult> result = runCalloutLogic(trco);
            return result;
            }
        else{
            Vehicle__c vehicleData = [Select Name, year__c, make__c, model__c, trim__c, class_name__c, Vehicle_Is_Oversize__c From vehicle__c Where id = :inputCase.vehicle__c];
            Account pickupDealer = [Select id, Name, Dealership_Id__c From Account where id = :inputCase.Seller_Dealership__c];
            Account deliveryDealer = [Select id, Name, Dealership_Id__c From Account where id = :inputCase.AccountId];
            TransportationRequestCreateObject trco = convertCaseToNonCaptiveCalloutObject(inputCase, vehicleData, pickupContact, DeliveryContact, pickupDealer, deliveryDealer);
            List<TransportationFlowResult> result = runCalloutLogic(trco);
            return result;
        }
        

    }
    private static List<TransportationFlowResult> runCalloutLogic(TransportationRequestCreateObject inputRequest){
            // List<TransportationFlowResult> newResult = new List<TransportationFlowResult>();
            // TransportationFlowResult r = new TransportationFlowResult();
            // r.resCode = '400';
            // r.legacyId = '123';
            // r.transpoGuid = 'guid-1234';
            // r.errorMessage = 'Zip Code is invalid';
            // newResult.add(r);
            // return newResult;
            // Response will have status as well, need to apply this to the case status 
            HttpRequest req = new HttpRequest();
            HttpResponse res = new HttpResponse();
            Http h = new Http();
            req.setMethod('POST');
            req.setEndpoint( 'callout:Salesforce_Gateway' + endpointURL );
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Authorization', '{!$Credential.Password}');
            req.setTimeout(120000);
            req.setBody(JSON.serialize(inputRequest));
            try{
                res = h.send(req);
            }
            catch(Exception e){
                sendHTTPLog(req,res, SplunkHelper.LOGLEVEL.ERROR, ACVUtility.currentLineNumber());
            }
            if(res.getStatusCode() >= 200 && res.getStatusCode() < 300){
                TransportationSuccessObject tso = TransportationSuccessObject.parse(res.getBody());

                sendHTTPLog(req,res, SplunkHelper.LOGLEVEL.INFO, ACVUtility.currentLineNumber());

                List<TransportationFlowResult> newResult = new List<TransportationFlowResult>();
                TransportationFlowResult r = new TransportationFlowResult();
                r.resCode = string.valueOf(res.getStatusCode());
                r.legacyId = string.valueOf(tso.data.acvLegacyTransportId);
                r.transpoGuid = tso.data.id;
                r.distance = tso.data.distance;
                System.debug(tso.data.status);
                if(tso.data.status == 'Ready-to-Post'){
                    r.status = 'Ready-to-Post';
                }
                else{
                    r.status = 'Awaiting Release';
                }
                System.debug(r);
                newResult.add(r);
                return newResult;
                // return new list<string>{String.valueOf(tso.data.acvLegacyTransportId),tso.data.id};
            }
            else{
                TransportationErrorObject teo = TransportationErrorObject.parse(res.getBody());
                
                sendHTTPLog(req,res, SplunkHelper.LOGLEVEL.ERROR, ACVUtility.currentLineNumber());

                List<TransportationFlowResult> newResult = new List<TransportationFlowResult>();
                TransportationFlowResult r = new TransportationFlowResult();
                r.resCode = string.valueOf(res.getStatusCode());
                r.errorMessage = teo.errors[0];
                newResult.add(r);
                return newResult;
            }
    }
    private static void sendHTTPLog(HttpRequest req, HttpResponse res, SplunkHelper.LOGLEVEL logLevel, Integer lineNumber){
        SplunkHelper.Log infoLog = new SplunkHelper.Log();
        infoLog.version = 'v1'; // We don't have versions yet
        infoLog.logLevel = LogLevel;
        infoLog.location = 'TransportationRequestCreateInvocable:' + lineNumber;
        infoLog.message = res.getStatus();
        infoLog.stackTrace = 'TransportationRequestCreateInvocable: '+lineNumber;
        infoLog.sfRecordId = UserInfo.getUserId();
        infoLog.componentName = 'TransportationRequestCreateInvocable';
        infoLog.sfObject = 'Case';
        infoLog.domainSet = new Set<SplunkHelper.DOMAIN>{ SplunkHelper.DOMAIN.POST_TRANSACTION};
        //SplunkHelper.buildandProcessLog( infoLog );
        SplunkHelper.buildAndProcessIntegrationLog(infoLog, req, res, SplunkHelper.INTEGRATION_DIRECTION.OUTBOUND );
    }

    private static TransportationRequestCreateObject convertCaseToCalloutObject(Case inputCase, Auction__c auctionData, Contact pickupContact, Contact deliveryContact){
        TransportationRequestCreateObject returnObject = new TransportationRequestCreateObject();

        returnObject.requestType = 'OUT_OF_APP';
        //REQ - not the case anymore
        // returnObject.acvLegacyTransportId;
        returnObject.acvAuctionId = auctionData.id__c;
        returnObject.notes = inputCase.Transportation_Notes__c;
        //REQ
        returnObject.priceCustomerPrePromotion = inputCase.Buyer_Price__c;
        returnObject.priceCustomerCharged = inputCase.Price_Pre_Promotion__c;
        //REQ
        returnObject.releaseSecretPhrase = auctionData.Release_Pickup_Phrase__c;
        returnObject.vehicle = new TransportationRequestCreateObject.vehicle();
        //REQ
        returnObject.vehicle.vin = auctionData.vehicle_id__r.vin__c;
        //REQ
        returnObject.vehicle.year = string.isNotBlank(auctionData.vehicle_id__r.year__c) ? integer.valueOf(auctionData.vehicle_id__r.year__c) : null;
        //REQ
        returnObject.vehicle.make = auctionData.vehicle_id__r.make__c;
        //REQ
        returnObject.vehicle.model = auctionData.vehicle_id__r.model__c;
        returnObject.vehicle.trim = auctionData.vehicle_id__r.trim__c;
        returnObject.vehicle.className = auctionData.vehicle_id__r.class_name__c;
        returnObject.vehicle.isOversize = auctionData.vehicle_id__r.Vehicle_Is_Oversize__c;
        returnObject.vehicle.isInoperable = auctionData.ACV_inop__c;
        
        returnObject.pickupLocation = new TransportationRequestCreateObject.pickupLocation();
        // REQ
        returnObject.pickupLocation.dealershipId = integer.valueOf(auctionData.Seller_Dealership__r.Dealership_id__c);
        //REQ
        returnObject.pickupLocation.addressName = inputCase.Pickup_Address_Name__c;
        //REQ
        returnObject.pickupLocation.addressLineOne = inputCase.Pickup_Address__c;
        // returnObject.addressLineTwo 
        // returnObject.addressLineThree 
        // returnObject.addressLineFour 
        //REQ
        returnObject.pickupLocation.addressCity = inputCase.Default_Pickup_City__c;
        //REQ
        returnObject.pickupLocation.addressRegion = inputCase.Default_Pickup_State__c;
        //REQ
        returnObject.pickupLocation.addressPostalCode = inputCase.Default_Pickup_Postal_Code__c;
        //REQ
        returnObject.pickupLocation.addressCountry = inputCase.Default_Pickup_Country__c;
        returnObject.pickupLocation.contactName = auctionData.Seller_Dealership__r.Primary_Contact__r.Name;
        returnObject.pickupLocation.contactPhone = auctionData.Seller_Dealership__r.Primary_Contact__r.Phone;
        returnObject.pickupLocation.contactEmail = auctionData.Seller_Dealership__r.Primary_Contact__r.Email;
        returnObject.pickupLocation.inventoryId = auctionData.Seller_Inventory_Id__c;
        returnObject.pickupLocation.notes = inputCase.Seller_Pick_Up_Notes__c;
        if(pickupContact != null){
            returnObject.pickupLocation.contactName = pickupContact.Name;        
            returnObject.pickupLocation.contactPhone = pickupContact.Phone;
            returnObject.pickupLocation.contactEmail = pickupContact.Email;
        }
        else{
            returnObject.pickupLocation.contactName = inputCase.Seller_Name__c;        
            returnObject.pickupLocation.contactPhone = inputCase.Seller_Contact_Phone__c;
            returnObject.pickupLocation.contactEmail = inputCase.Seller_Contact_Email__c;
        }

        returnObject.deliveryLocation = new TransportationRequestCreateObject.deliveryLocation();
        //REQ
        returnObject.deliveryLocation.dealershipId = integer.valueOf(auctionData.buyer_Dealership__r.Dealership_id__c);
        //REQ
        returnObject.deliveryLocation.addressName = inputCase.Delivery_Address_Name__c;
        //REQ
        returnObject.deliveryLocation.addressLineOne = inputCase.Default_Delivery_Address__c;
        // returnObject.addressLineTwo 
        // returnObject.addressLineThree 
        // returnObject.addressLineFour 
        //REQ
        returnObject.deliveryLocation.addressCity = inputCase.Default_Delivery_City__c;
        //REQ
        returnObject.deliveryLocation.addressRegion = inputCase.Default_Delivery_State__c;
        //REQ
        returnObject.deliveryLocation.addressPostalCode = inputCase.Default_Delivery_Postal_Code__c;
        //REQ
        returnObject.deliveryLocation.addressCountry = inputCase.Default_Delivery_Country__c;
        if(deliveryContact != null){
            returnObject.deliveryLocation.contactName = deliveryContact.Name;        
            returnObject.deliveryLocation.contactPhone = deliveryContact.Phone;
            returnObject.deliveryLocation.contactEmail = deliveryContact.Email;
        }
        else{
            returnObject.deliveryLocation.contactName = inputCase.Buyer_Name__c;        
            returnObject.deliveryLocation.contactPhone = inputCase.ContactPhone;
            returnObject.deliveryLocation.contactEmail = inputCase.ContactEmail;
        }

        //There wont be an inventory Id for the buyer since we have seller inventory id ONLY
        // returnObject.deliveryLocation.inventoryId = 
        returnObject.deliveryLocation.notes = inputCase.Buyer_Pickup_Notes__c;
        return returnObject;
    }
    private static TransportationRequestCreateObject convertCaseToNonCaptiveCalloutObject(Case inputCase, Vehicle__c vehicleData, Contact pickupContact, Contact deliveryContact, Account pickupDealer, Account deliveryDealer){
        TransportationRequestCreateObject returnObject = new TransportationRequestCreateObject();

        returnObject.requestType = 'NON_CAPTIVE';
        //REQ - not the case anymore
        // returnObject.acvLegacyTransportId;
        // returnObject.acvAuctionId = auctionData.id__c;
        returnObject.notes = inputCase.Transportation_Notes__c;
        //REQ
        returnObject.priceCustomerPrePromotion = inputCase.Buyer_Price__c;
        returnObject.priceCustomerCharged = inputCase.Price_Pre_Promotion__c;
        //REQ
        // returnObject.releaseSecretPhrase = auctionData.Release_Pickup_Phrase__c;
        returnObject.vehicle = new TransportationRequestCreateObject.vehicle();
        //REQ
        returnObject.vehicle.vin = vehicleData.Name;
        //REQ
        returnObject.vehicle.year = string.isNotBlank(vehicleData.year__c) ? integer.valueOf(vehicleData.year__c) : null;
        //REQ
        returnObject.vehicle.make = vehicleData.make__c;
        //REQ
        returnObject.vehicle.model = vehicleData.model__c;
        returnObject.vehicle.trim = vehicleData.trim__c;
        returnObject.vehicle.className = vehicleData.class_name__c;
        returnObject.vehicle.isOversize = vehicleData.Vehicle_Is_Oversize__c;
        returnObject.vehicle.isInoperable = inputCase.Inop__c;
        
        returnObject.pickupLocation = new TransportationRequestCreateObject.pickupLocation();
        // REQ
        returnObject.pickupLocation.dealershipId = integer.valueOf(pickupDealer.Dealership_id__c);
        //REQ
        returnObject.pickupLocation.addressName = inputCase.Pickup_Address_Name__c;
        //REQ
        returnObject.pickupLocation.addressLineOne = inputCase.Pickup_Address__c;
        // returnObject.addressLineTwo 
        // returnObject.addressLineThree 
        // returnObject.addressLineFour 
        //REQ
        returnObject.pickupLocation.addressCity = inputCase.Default_Pickup_City__c;
        //REQ
        returnObject.pickupLocation.addressRegion = inputCase.Default_Pickup_State__c;
        //REQ
        returnObject.pickupLocation.addressPostalCode = inputCase.Default_Pickup_Postal_Code__c;
        //REQ
        returnObject.pickupLocation.addressCountry = inputCase.Default_Pickup_Country__c;
        returnObject.pickupLocation.notes = inputCase.Seller_Pick_Up_Notes__c;
        if(pickupContact != null){
            returnObject.pickupLocation.contactName = pickupContact.Name;        
            returnObject.pickupLocation.contactPhone = pickupContact.Phone;
            returnObject.pickupLocation.contactEmail = pickupContact.Email;
        }
        else{
            returnObject.pickupLocation.contactName = inputCase.Seller_Name__c;        
            returnObject.pickupLocation.contactPhone = inputCase.Seller_Contact_Phone__c;
            returnObject.pickupLocation.contactEmail = inputCase.Seller_Contact_Email__c;
        }

        returnObject.deliveryLocation = new TransportationRequestCreateObject.deliveryLocation();
        //REQ
        returnObject.deliveryLocation.dealershipId = integer.valueOf(deliveryDealer.Dealership_id__c);
        //REQ
        returnObject.deliveryLocation.addressName = inputCase.Delivery_Address_Name__c;
        //REQ
        returnObject.deliveryLocation.addressLineOne = inputCase.Default_Delivery_Address__c;
        // returnObject.addressLineTwo 
        // returnObject.addressLineThree 
        // returnObject.addressLineFour 
        //REQ
        returnObject.deliveryLocation.addressCity = inputCase.Default_Delivery_City__c;
        //REQ
        returnObject.deliveryLocation.addressRegion = inputCase.Default_Delivery_State__c;
        //REQ
        returnObject.deliveryLocation.addressPostalCode = inputCase.Default_Delivery_Postal_Code__c;
        //REQ
        returnObject.deliveryLocation.addressCountry = inputCase.Default_Delivery_Country__c;
        if(deliveryContact != null){
            returnObject.deliveryLocation.contactName = deliveryContact.Name;        
            returnObject.deliveryLocation.contactPhone = deliveryContact.Phone;
            returnObject.deliveryLocation.contactEmail = deliveryContact.Email;
        }
        else{
            returnObject.deliveryLocation.contactName = inputCase.Buyer_Name__c;        
            returnObject.deliveryLocation.contactPhone = inputCase.ContactPhone;
            returnObject.deliveryLocation.contactEmail = inputCase.ContactEmail;
        }

        //There wont be an inventory Id for the buyer since we have seller inventory id ONLY
        // returnObject.deliveryLocation.inventoryId = 
        returnObject.deliveryLocation.notes = inputCase.Buyer_Pickup_Notes__c;
        return returnObject;
    }
    public class TransportationFlowResult{
        @invocableVariable
        public string resCode;
        @invocableVariable
        public string legacyId;
        @invocableVariable
        public string transpoGuid;
        @invocableVariable
        public string errorMessage;
        @invocableVariable
        public Integer distance;
        @invocableVariable
        public string status;   
    } 
}