objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealership_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Dealer ID from Tools</inlineHelpText>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IST_Account_Manager_Email__c</fullName>
        <description>Email of the IST Account Manager</description>
        <formula>Account.IST_Account_Owner__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IST Account Manager Email</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <formula>Account__r.Dealership_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IST_Account_Manager_Email__c</fullName>
        <description>IST Account Manager&apos;s email</description>
        <label>IST Account Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Email__c</fullName>
        <description>Field containing the primary contact&apos;s email for the related account.</description>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <label>Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Review</fullName>
                    <default>true</default>
                    <label>Ready for Review</label>
                </value>
                <value>
                    <fullName>Requires BDR</fullName>
                    <label>Requires IST</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Email__c</fullName>
        <label>TM Email</label>
        <type>Email</type>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Certificate_of_Insurance</fullName>
        <active>true</active>
        <description>Used by ACV Capital to capture information around the Dealer&apos;s Insurance Documents</description>
        <label>Certificate of Insurance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Exception__c.object
<CustomObject>
    <description>Details regarding exceptions that relate to custom integrations to Salesforce.</description>
    <fields>
        <fullName>Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a document is compliant or not.</description>
        <label>Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_ID__c</fullName>
        <description>The ACV Id of the dealership the document is associated with.</description>
        <label>Dealer ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_State_Dealer_Entered__c</fullName>
        <description>The state the document was issued by as entered by the dealer.</description>
        <label>Document State Dealer Entered</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_State_ML__c</fullName>
        <description>The state the document was issued by as entered by ML.</description>
        <label>Document State ML</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <description>The state the document was issued by.</description>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date_Dealer_Entered__c</fullName>
        <description>The date the document is set to expire as entered by the dealer.</description>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date Dealer Entered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date_ML__c</fullName>
        <description>The date the document is set to expire as entered by ML.</description>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date ML</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>The date the document is set to expire.</description>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IST_Account_Manager_Email__c</fullName>
        <description>Field containing the IST rep&apos;s email for the related account.</description>
        <label>IST Account Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>License_Number_Dealer_Entered__c</fullName>
        <description>The license number of the document as entered by the dealer.</description>
        <label>License Number Dealer Entered</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>License_Number_ML__c</fullName>
        <description>The license number of the document as entered by ML.</description>
        <label>License Number ML</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <description>The license number of the document.</description>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Manual_Validation_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If false, code will auto-convert Exception record to a Dealer Doc record.</description>
        <label>Manual Validation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Email__c</fullName>
        <description>Field containing the primary contact&apos;s email for the related account.</description>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Related_Account_Name__c</fullName>
        <description>Holds the name of the related account for use by the business document confirmation emails.</description>
        <label>Related Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Decision__c</fullName>
        <description>The outcome of the document review, selected after the review process is complete. This field will trigger different emails depending on the selection.</description>
        <label>Review Decision</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current and Compliant Document</fullName>
                </value>
                <value>
                    <fullName>Historical Document</fullName>
                </value>
                <value>
                    <fullName>Invalid Document</fullName>
                </value>
                <value>
                    <fullName>Poor Document Quality</fullName>
                </value>
                <value>
                    <fullName>Duplicate Document</fullName>
                </value>
                <value>
                    <fullName>Auto-Converted</fullName>
                </value>
                <value>
                    <fullName>Incomplete/Adjustment Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <description>The status of reviewing the document.</description>
        <label>Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Requires IST</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Processed by IST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Exception</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Email__c</fullName>
        <description>Field containing the TM&apos;s email for the related account.</description>
        <label>TM Email</label>
        <type>Email</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Certificate_of_Insurance</fullName>
        <active>true</active>
        <description>Used by ACV Capital to capture information around the Dealer&apos;s Insurance Documents</description>
        <label>Certificate of Insurance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses passed in from ML</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates passed in from ML</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <description>acv_prod id found on the users table used to identify internal users</description>
        <externalId>true</externalId>
        <inlineHelpText>This corresponds to the User&apos;s ACV Tools ID</inlineHelpText>
        <label>ACV User Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/State_Abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>VT</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

classes/ExceptionToDealerDocAutoConvert.cls
public without sharing class ExceptionToDealerDocAutoConvert extends TriggerInterface {
    public static final Id licenseId = Schema.SObjectType.Exception__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id resaleId = Schema.SObjectType.Exception__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();
    public static final Id certInsuranceId = Schema.SObjectType.Exception__c.getRecordTypeInfosByDeveloperName().get('Certificate_of_Insurance').getRecordTypeId();
    public static final Id docsLicenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id docsResaleId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();
    public static final Id docsCertInsuranceId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Certificate_of_Insurance').getRecordTypeId();
    public static Set<Id> types = new Set<Id>{licenseId, resaleId, certInsuranceId};
    public static final Set<String> revDecisions = new Set<String>{'Current and Compliant Document', 'Historical Document'};

    public override void beforeInsert(List<sObject> newList) { //NEED TO MAKE SURE CODE KNOWS WHAT TO DO IF THERE IS NO PRIMARY CONTACT (OR DO A DATALOAD)
        List<Exception__c> newEList = (List<Exception__c>)newList;
        List<Dealer_Docs__c> docList = new List<Dealer_Docs__c>();
        Set<String> dealerIds = new Set<String>();
        Map<String, Account> acctMap = new Map<String, Account>();
        for (Exception__c ex : newEList) {
            if(!String.isBlank(ex.Dealer_Id__c)) dealerIds.add(ex.Dealer_Id__c);
        }

        if(dealerIds.size() > 0)	{
            for (Account a : [SELECT Id, Dealership_Id__c, Name, IST_Account_Owner__r.Email, Owner.Email, Primary_Contact__r.Email FROM Account WHERE Dealership_Id__c IN :dealerIds]) {
                acctMap.put(a.Dealership_Id__c, a);
            }
        }
        
        for (Exception__c e : newEList) {
            e.IST_Account_Manager_Email__c = acctMap.get(e.Dealer_Id__c)?.IST_Account_Owner__r?.Email;
            e.TM_Email__c = acctMap.get(e.Dealer_Id__c)?.Owner?.Email;
            e.Primary_Contact_Email__c = acctMap.get(e.Dealer_Id__c)?.Primary_Contact__r?.Email;
            e.Related_Account_Name__c = acctMap.get(e.Dealer_Id__c)?.Name;

            if ((e.Manual_Validation_Required__c == false && e.RecordTypeId == licenseId) || (e.RecordTypeId == licenseId && e.Document_State_ML__c == e.Document_State_Dealer_Entered__c && e.Expiration_Date_ML__c == e.Expiration_Date_Dealer_Entered__c && e.License_Number_ML__c == e.License_Number_Dealer_Entered__c && e.Manual_Validation_Required__c == false)) {
                e.Document_State__c = e.Document_State_ML__c;
                e.Expiration_Date__c = e.Expiration_Date_ML__c;
                e.License_Number__c = e.License_Number_ML__c;

                //mark all licenses as compliant (or expired)
                //VT and AZ licenses will not be auto-converted as those need a little more attention
                if (e.Expiration_Date__c > System.Today() && (e.Document_State_ML__c != 'AZ' && e.Document_State_ML__c != 'VT')) {
                    e.Compliant__c = true;
                    e.Review_Status__c = 'Complete';
                    e.Status__c = 'Closed';
                    e.Review_Decision__c = 'Auto-Converted';
                    Dealer_Docs__c d = newLicense(e);
                    docList.add(d);
                }
                else if (e.Expiration_Date__c <= System.Today() && (e.Document_State_ML__c != 'AZ' && e.Document_State_ML__c != 'VT')) {
                    e.Review_Status__c = null;
                    e.Compliance_Issues__c = 'Document expired';
                    e.Status__c = 'Closed';
                    e.Review_Decision__c = 'Auto-Converted';
                    Dealer_Docs__c d = newLicense(e);
                    docList.add(d);
                }
                else if ((e.Expiration_Date__c == null) || (e.Document_State__c == 'AZ' || e.Document_State__c == 'VT')) {
                    e.Review_Status__c = 'Ready for Review';
                }
            }
        }
        insert docList;
    }

    public override void afterUpdate(Map<Id, sObject> oldMap, Map<Id, sObject> newMap) {
        Map<Id, Exception__c> newEMap = (Map<Id, Exception__c>)newMap;
        Map<Id, Exception__c> oldEMap = (Map<Id, Exception__c>)oldMap;
        List<Dealer_Docs__c> docList = new List<Dealer_Docs__c>();

        for (Exception__c e : newEMap.values()) {
            if ((e.Status__c == 'Closed' && oldEMap.get(e.Id).Status__c == 'Open') && (types.contains(e.RecordTypeId)) && (revDecisions.contains(e.Review_Decision__c))) {
                if (e.RecordTypeId == licenseId) {
                    Dealer_Docs__c d = newLicense(e);
                    docList.add(d);
                }
                else if (e.RecordTypeId == resaleId) {
                    Dealer_Docs__c d = newResale(e);
                    docList.add(d);
                }
                else if (e.RecordTypeId == certInsuranceId) {
                    Dealer_Docs__c d = newCertInsurance(e);
                    docList.add(d);
                }

            }
        }
        insert docList;
    }

    public static Dealer_Docs__c newLicense(Exception__c e) {
        Id ContactName = getContactName(e.Document_Created_By_Id__c);
        
        Dealer_Docs__c d = new Dealer_Docs__c(
        RecordTypeId = docsLicenseId,
        License_Number__c = e.License_Number__c,
        Document_State__c = e.Document_State__c,
        Expiration_Date__c = e.Expiration_Date__c,
        No_Expiration__c = e.No_Expiration__c,
        Compliant__c = e.Compliant__c,
        Compliance_Issues__c = e.Compliance_Issues__c,
        Document_Notes__c = e.Document_Notes__c,
        Extension_Granted__c = e.Extension_Granted__c,
        S3_Link__c = e.Images_Location__c, //S3_Link__c
        ML_Reviewed__c = true, //anything passing through this code has been reviewed by ML
        Primary_Contact_Email__c = e.Primary_Contact_Email__c,
        Document_Created_By__c = ContactName);
		
        d = getAccount(d, e);
        d.Document_Expired__c = docExpiredCheck(e.Expiration_Date__c);
        d.Review_Status__c = reviewStatus(e.Review_Status__c);
        if (d.Review_Status__c == 'Requires BDR') {
            d.IST_Account_Manager_Email__c = e.IST_Account_Manager_Email__c;
            d.TM_Email__c = e.TM_Email__c;
        }

        return d;
    }

    public static Dealer_Docs__c newResale(Exception__c e) {
        String ContactName = getContactName(e.Document_Created_By_Id__c);

        Dealer_Docs__c d = new Dealer_Docs__c(
        RecordTypeId = docsResaleId,
        Permit_Resale_Number__c = e.Permit_Resale_Number__c,
        Document_State__c = e.Document_State__c,
        Expiration_Date__c = e.Expiration_Date__c,
        No_Expiration__c = e.No_Expiration__c,
        AL_Sales_Tax__c = e.AL_Sales_Tax__c,
        MTC__c = e.MTC__c,
        Compliant__c = e.Compliant__c,
        Compliance_Issues__c = e.Compliance_Issues__c,
        Document_Notes__c = e.Document_Notes__c,
        Extension_Granted__c = e.Extension_Granted__c,
        S3_Link__c = e.Images_Location__c, //S3_Link__c
        ML_Reviewed__c = true, //anything passing through this code has been reviewed by ML
        Primary_Contact_Email__c = e.Primary_Contact_Email__c,
        Document_Created_By__c = ContactName);

        d = getAccount(d, e);
        d.Document_Expired__c = docExpiredCheck(e.Expiration_Date__c);
        d.Review_Status__c = reviewStatus(e.Review_Status__c);
        if (d.Review_Status__c == 'Requires BDR') {
            d.IST_Account_Manager_Email__c = e.IST_Account_Manager_Email__c;
            d.TM_Email__c = e.TM_Email__c;
        }

        return d;
    }

    public static Dealer_Docs__c newCertInsurance(Exception__c e) {
        String ContactName = getContactName(e.Document_Created_By_Id__c);
        
        Dealer_Docs__c d = new Dealer_Docs__c(
        RecordTypeId = docsCertInsuranceId,
        Insurance_Company_Name__c = e.Insurance_Company_Name__c,
        Inventory_Coverage_Amount__c = e.Inventory_Coverage_Amount__c,
        Document_State__c = e.Document_State__c,
        Expiration_Date__c = e.Expiration_Date__c,
        Compliant__c = e.Compliant__c,
        Compliance_Issues__c = e.Compliance_Issues__c,
        Document_Notes__c = e.Document_Notes__c,
        Extension_Granted__c = e.Extension_Granted__c,
        S3_Link__c = e.Images_Location__c, //S3_Link__c
        ML_Reviewed__c = true, //anything passing through this code has been reviewed by ML
        Primary_Contact_Email__c = e.Primary_Contact_Email__c,
        Document_Created_By__c = ContactName);

        d = getAccount(d, e);
        d.Document_Expired__c = docExpiredCheck(e.Expiration_Date__c);
        d.Review_Status__c = reviewStatus(e.Review_Status__c);
        if (d.Review_Status__c == 'Requires BDR') {
            d.IST_Account_Manager_Email__c = e.IST_Account_Manager_Email__c;
            d.TM_Email__c = e.TM_Email__c;
        }

        return d;
    }

    public static Dealer_Docs__c getAccount(Dealer_Docs__c d, Exception__c e) {
        Account a = new Account(Dealership_ID__c = e.Dealer_ID__c);
        d.Account__r = a;
        return d;
    }

    public static Boolean docExpiredCheck(Date da) {
        if (da <= System.Today()) {
            return true;
        }
        else {
            return false;
        }
    }

    public static String reviewStatus(String s) {
        if (s == 'Requires IST') {
            String st = 'Requires BDR';
            return st;
        }
        else {
            String st = s;
            return st;
        }
    }
    
    public static Id getContactName(String s){
        Id contactName;
        List<Contact> contactList = new List<Contact>();
        contactList = [select id, name from Contact where ID__c =:s];
        if(contactList.size()>0){
            contactName = contactList[0].id;
        }else{
            contactName = null;
        }
        
        return contactName;
    }
}