objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Dealer_Doc_Compliance__c</fullName>
        <label>Dealer Doc Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Out Of Compliance</fullName>
                    <default>true</default>
                    <label>Out Of Compliance</label>
                </value>
                <value>
                    <fullName>Compliant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Franchise</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Independent</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Independent - ACV Certified</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wholesaler</label>
                </value>
                <value>
                    <fullName>Dealer Group (Parent Account)</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Commercial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <description>The most recent resale number for the account.</description>
        <label>Permit/Resale Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Set_Active_Account_Check_Date__c</fullName>
        <description>This is the day that an Active account should be reviewed to see whether or not they have their dealer docs.</description>
        <label>Set Active Account Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>legal_name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dealer_Docs__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Docs</relationshipLabel>
        <relationshipName>Dealer_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_State__c</fullName>
        <label>Document State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>You must enter an expiration date. If no expiration date is listed, it is this far out: AL = 1yr, AZ = 4yrs, MI = 4yrs, ME = 3yrs, LA = 3yrs, NE = 3yrs, WA = 4yrs, FL = 1yr. Ex: Document state = AZ; signature date = 2/28/19; expiration date = 2/28/23.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>No_Expiration__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If a resale certificate does not have an expiration date (all states except AZ, MI, NE, WA and FL), you must check this box.</inlineHelpText>
        <label>No Expiration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit_Resale_Number__c</fullName>
        <label>Permit/Resale Number</label>
        <type>TextArea</type>
    </fields>
    <label>Dealer Doc</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Dealer Docs Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Docs</pluralLabel>
    <recordTypes>
        <fullName>Dealer_License</fullName>
        <active>true</active>
        <description>Record type for Dealer Licenses</description>
        <label>Dealer License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Resale_Certificate</fullName>
        <active>true</active>
        <description>Record type for Resale Certificates</description>
        <label>Resale Certificate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State_Abbreviations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NY</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

classes/VerifyAccountActiveStatusBatchTest.cls
@isTest
public class VerifyAccountActiveStatusBatchTest {
    public static final Id licenseId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Dealer_License').getRecordTypeId();
    public static final Id resaleId = Schema.SObjectType.Dealer_Docs__c.getRecordTypeInfosByDeveloperName().get('Resale_Certificate').getRecordTypeId();

    @isTest
    static void runTest() {
        //need today's date
        Date today = System.Today();
        Date future = System.Today().addMonths(5);
        //need some accounts
        List<Account> accountList = new List<Account>();
        //and two where Set_Active_Account_Check_Date__c is today (compliant)
        accountList.add(new Account(Name = 'Account1', legal_name__c='Account1', dealer_type__c='1',IST_Account_Owner__c = UserInfo.getUserId(), Dealer_Doc_Compliance__c = 'Compliant', Set_Active_Account_Check_Date__c = today));
        accountList.add(new Account(Name = 'Account2', legal_name__c='Account2', dealer_type__c='1',IST_Account_Owner__c = UserInfo.getUserId(), Dealer_Doc_Compliance__c = 'Compliant', Set_Active_Account_Check_Date__c = today));
        //make one with the field set to today but marked as not compliant
        accountList.add(new Account(Name = 'Account3', legal_name__c='Account3', dealer_type__c='1',IST_Account_Owner__c = UserInfo.getUserId(), Dealer_Doc_Compliance__c = 'Out Of Compliance', Set_Active_Account_Check_Date__c = today));
        //insert accounts
        insert accountList;
        //need to create some dealer docs that are linked to the accounts
        List<Dealer_Docs__c> docList = new List<Dealer_Docs__c>();
        //make a valid dealer doc in a special state for one of the accounts (license)
        docList.add(new Dealer_Docs__c(Account__c = accountList[0].Id, Expiration_Date__c = future, RecordTypeId = licenseId, Document_State__c = 'DE', License_Number__c = '33333', Compliant__c = true));
        //make a valid doc not in a special state for the second account (resale)
        docList.add(new Dealer_Docs__c(Account__c = accountList[1].Id, No_Expiration__c = true, RecordTypeId = resaleId, Document_State__c = 'NY', Permit_Resale_Number__c = '22222', Compliant__c = true));
        //insert docs
        insert docList;
        //need to re-set the Dealer_Doc_Compliance
        List<Account> forUpdate = [SELECT Id, Name, Dealer_Doc_Compliance__c, Set_Active_Account_Check_Date__c FROM Account];
        for (Account a : forUpdate) {
            if (a.Name == 'Account3') {
                a.Dealer_Doc_Compliance__c = 'Out Of Compliance'; //need to reset this because it will change when the docs are inserted
                //a.Set_Active_Account_Check_Date__c = today; //this will be set two weeks from now with the trigger so need to re-set
            }
            else if (a.Name == 'Account1' || a.Name == 'Account2') {
                a.Dealer_Doc_Compliance__c = 'Compliant'; //need to reset this because it will change when the docs are inserted
                //a.Set_Active_Account_Check_Date__c = today; //this will be set to two weeks from now with the trigger so need to re-set
            }
        }
        //update accounts
        update forUpdate;
        //and the date check fields because they will get changed when the docs are inserted/doc_compliance is updated
        List<Account> forUpdate2 = [SELECT Id, Name, Dealer_Doc_Compliance__c, Set_Active_Account_Check_Date__c FROM Account];
        System.debug(forUpdate2);
        for (Account ac : forUpdate2) {
            ac.Set_Active_Account_Check_Date__c = today; //again? what if above i only update the compliance, not the date so it's not as redundant?
        }
        //update again
        update forUpdate2; //this is dumb and i hate it
        //run batch
        Test.startTest();
            VerifyAccountActiveStatusBatch batch = new VerifyAccountActiveStatusBatch();
            Batch.executeScheduledLogic();
        Test.stopTest();
        //query
        List<Account> checkAccounts = [SELECT Id, Dealer_Doc_Compliance__c, Set_Active_Account_Check_Date__c FROM Account ORDER BY Name ASC];
        //system.asserts
        System.assertEquals('Compliant', checkAccounts[0].Dealer_Doc_Compliance__c); //should remain compliant because it has the correct docs
        System.assertEquals(null, checkAccounts[0].Set_Active_Account_Check_Date__c); //should null out when this runs through the batch
        System.assertEquals('Out Of Compliance', checkAccounts[1].Dealer_Doc_Compliance__c); //should be out of compliance because it doesn't have the right docs
        System.assertEquals(null, checkAccounts[1].Set_Active_Account_Check_Date__c); //should null out when this runs through the batch
        System.assertEquals('Out Of Compliance', checkAccounts[2].Dealer_Doc_Compliance__c); //should remain out of compliance
        System.assertEquals(null, checkAccounts[2].Set_Active_Account_Check_Date__c); //should null out when this runs through the batch
    }

    @isTest
    static void bulkTest() {
        Date today = System.Today();
        //create 200 accounts
        List<Account> bulkAccounts = new List<Account>();
        for (Integer i = 0; i < 50; i ++) {
            bulkAccounts.add(new Account(Name = 'Account' + i, IST_Account_Owner__c = UserInfo.getUserId(), Dealer_Doc_Compliance__c = 'Compliant', Dealer_Type__c = 'Independent', legal_name__c='Account '+i));
        }
        //insert
        insert bulkAccounts;
        //update the accounts to reset the Set_Active_Account_Check_Date
        List<Account> updateAccounts = [SELECT Id, Set_Active_Account_Check_Date__c FROM Account];
        for (Account a : updateAccounts) {
            a.Set_Active_Account_Check_Date__c = today;
        }
        update updateAccounts;
        //run batch
        Test.startTest();
            VerifyAccountActiveStatusBatch batch = new VerifyAccountActiveStatusBatch();
            Batch.executeScheduledLogic();
        Test.stopTest();
    }

    @isTest
    static void errorCheck() {
        //populate errorList
        VerifyAccountActiveStatusBatch.errorList.add('error');
        //run batch
        Test.startTest();
            VerifyAccountActiveStatusBatch batch = new VerifyAccountActiveStatusBatch();
            Batch.executeScheduledLogic();
        Test.stopTest();
    }
}