objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Auctions as Buyer</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winning_Bid_Price__c</fullName>
        <label>High Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>floor_price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Buyer_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record for the buyer, person who will get delivery of vehicle</description>
        <label>Buyer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Buyer Dealership)</relationshipLabel>
        <relationshipName>Buyer_Transportation_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <description>Field on unwind case layout to set a floor price</description>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incorrect_Vehicle_Information_on_Title__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of the Titles Problem set.</description>
        <inlineHelpText>Available options include: VIN and Year, Make, Model</inlineHelpText>
        <label>Incorrect Vehicle Information on Title</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Last_Updated__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title_Clerked_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Stamps the date that the Title Case status moved to Working</inlineHelpText>
        <label>Title Clerked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title_Problem_Subset__c</fullName>
        <description>This field is populated by the New QC flow and related to the QC object related to associated case record</description>
        <inlineHelpText>These are the problem subsets related to this case - to add additional problem subsets use the Report Problem button at the top of the page or reach out to titles.</inlineHelpText>
        <label>Title Problem Subset</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Address - Write over</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Branded on the Front of Title - Odom Discr.</label>
                </value>
                <value>
                    <fullName>Buyer Requested Duplicate - ACV at Fault</fullName>
                </value>
                <value>
                    <fullName>Buyer Requested Duplicate - Buyer at Fault</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                    <label>Damaged Title</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Dated Incorrectly on Reassignment</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Date - Write over</label>
                </value>
                <value>
                    <fullName>Dealer Stamp Used Instead of Notary</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Incorrect Name - Wrong Purchaser</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Mileage - Write over</label>
                </value>
                <value>
                    <fullName>Missing Death / Marriage / Divorce Certificate</fullName>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>Missing Lien Release</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Missing Notary</label>
                </value>
                <value>
                    <fullName>Missing One and the Same</fullName>
                </value>
                <value>
                    <fullName>Missing Owner POA</fullName>
                </value>
                <value>
                    <fullName>More Recently Issued Title</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Name - Write over</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Original Owner Missing Signature</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Reassigned to ACV - Wrong Purchaser</label>
                </value>
                <value>
                    <fullName>J</fullName>
                    <label>Reassignment not Included</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>Separate Reassignment Odom Discr.</label>
                </value>
                <value>
                    <fullName>Undisclosed application for title</fullName>
                </value>
                <value>
                    <fullName>Undisclosed Non-Titled Vehicle</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                    <label>Undisclosed Repossession Paperwork</label>
                </value>
                <value>
                    <fullName>Q</fullName>
                    <label>VIN Incorrect on Reassignment</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>VIN Incorrect on Title</label>
                </value>
                <value>
                    <fullName>P</fullName>
                    <label>Written Odom Discr.</label>
                </value>
                <value>
                    <fullName>S</fullName>
                    <label>Year, Make, or Model Incorrect on Reassignment</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Year, Make, or Model Incorrect on Title</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Buyer Signature Missing from Prior Reassignment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseTriggerFlag__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>CaseTriggerFlag</label>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DateStampCaseStatusChangeTest.cls
@isTest
public class DateStampCaseStatusChangeTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        insert new CaseTriggerFlag__c(Name='Default', Enabled__c = true);
        List<Account> accountList = New List<Account>();
        accountList.add( TestUtility.createAccount( '456' ) );
        accountList.add( TestUtility.createAccount( '123' ) );
        insert accountList;
        List<Contact> contactList = new List<Contact>();
        contactList.add( TestUtility.createContact( accountList[0] ) );
        contactList.add( TestUtility.createContact( accountList[1] ) );
        insert contactList;
        Vehicle__c newCar = TestUtility.createVehicle();
        newCar.vin__c = '1234567890102030';
        insert newCar;
        vehicle__c newCar1 = TestUtility.createVehicle();
        newCar.vin__c = '1234567890102031';
        insert newCar1;

        Auction__c newAuction = TestUtility.createAuction( accountList[0], contactList[0], newCar );
        newAuction.Status__c = 'Active'; 
        newAuction.end_time__c = System.Now();
        newAuction.Seller_Dealership__c = accountList[1].id;
        newAuction.Floor_Price__c = 500;
        newAuction.Winning_Bid_Price__c = 450;
        insert newAuction;
    }

    @isTest
    static void setReceived() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        User testUser = TestUtility.createUser();
        insert testUser;

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Received';
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
    }
    
    @isTest
    static void setWorking() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        User testUser = TestUtility.createUser();
        insert testUser;

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Working';
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
        System.assertEquals( Date.today(), titleCaseRec.Title_Clerked_Date__c, 'The Title Clerk Date was not correctly set' );
    }

    @isTest
    static void setProblem() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        User testUser = TestUtility.createSystemAdministratorUser();
        insert testUser;

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Problem';
            titleCaseRec.Title_Problem_Subset__c = 'O';
            titleCaseRec.Incorrect_Vehicle_Information_on_Title__c = TRUE;
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Was_Problem__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
        System.assertEquals( TRUE, titleCaseRec.Was_Problem__c, 'The Was Problem Checkbox was not correctly set' );
    }

    @isTest
    static void set48HourNotice() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        UserRole titleManagerRole = [ SELECT Id FROM UserRole WHERE DeveloperName = 'Titles_Manager' LIMIT 1];

        User testUser = TestUtility.createUser();
        testUser.UserRoleId = titleManagerRole.Id;
        insert testUser;

        System.runAs( testUser ) {
            titleCaseRec.Status = 'New';
            insert titleCaseRec;
            Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

            Test.startTest();

                titleCaseRec.Status = '48 Hour Notice';
                update titleCaseRec;

            Test.stopTest();
        }

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
    }

    @isTest
    static void setReturnToSeller() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        User testUser = TestUtility.createSystemAdministratorUser();
        insert testUser;

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Return to Seller';
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
    }

    @isTest
    static void setSent() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        //Profile userProfile = [ SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User testUser = TestUtility.createSystemAdministratorUser();
        

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Sent';
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
    }

    @isTest
    static void setTitleAtACVUnwound() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        User testUser = TestUtility.createUser();
        insert testUser;

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Title at ACV Unwound';
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
    }

    @isTest
    static void setClosedUnwound() {
        Auction__c testAuctRec = [ SELECT Id, buyer_dealership__c, buyer_contact__c FROM Auction__c LIMIT 1 ];
        Case titleCaseRec = TestUtility.createTitleCase( testAuctRec, new Account( Id = testAuctRec.buyer_dealership__c ), new Contact( Id = testAuctRec.buyer_contact__c ) );

        // Profile userProfile = [ SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User testUser = TestUtility.createSystemAdministratorUser();
        

        titleCaseRec.Status = 'New';
        insert titleCaseRec;
        Test.setCreatedDate( titleCaseRec.Id, Datetime.now().addDays( -7 ) );

        System.runAs( testUser ) {
            Group queueGroup = new Group(
                Type = 'Queue', Name = [ SELECT Value__c FROM Salesforce_Setting__mdt WHERE Label = 'Title Resolution Queue Name' LIMIT 1 ].Value__c
            );
            insert queueGroup;
            insert new QueuesObject(
                QueueId = queueGroup.Id, sObjectType = 'Case'
            );
        }

        Test.startTest();

        System.runAs( testUser ) {
            titleCaseRec.Status = 'Closed Unwound';
            update titleCaseRec;
        }

        Test.stopTest();

        titleCaseRec = [ SELECT Id, Status_Last_Updated__c, Title_Clerked_Date__c FROM Case WHERE Id = :titleCaseRec.Id LIMIT 1 ];
        System.assertEquals( Date.today(), titleCaseRec.Status_Last_Updated__c, 'The Status Last Updated Field was not correctly set' );
    }
}