objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>IST_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The is a lookup to the user table for tracking IST Owner on Accounts</description>
        <label>IST Account Rep</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The IST Rep must have the &quot;Inside Sales- Account Managers&quot; profile assigned on their user record</errorMessage>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00ej0000001AgjXAAS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Auction_Lights_Concatenation__c</fullName>
        <description>Populated via a workflow rule that generates a string based upon the independent auction light checkboxes. This field is then evaluated in the Auction Lights formula to return a user-friendly image showing the Auction Lights for an Auction.</description>
        <label>Auction Lights Concatenation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <description>Set by Process Builder automation.</description>
        <label>Make</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vehicle_Make</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winning_Bid_Price__c</fullName>
        <label>High Bid Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blue_light__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Blue Light</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>floor_price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>green_light__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Green Light</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>yellow_light__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Yellow Light</label>
        <type>Checkbox</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>make__c</fullName>
        <description>The make (manufacturer) of the vehicle.</description>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/AuctionLightsConcatenationUpdateTest.cls
@isTest
public class AuctionLightsConcatenationUpdateTest {
    @isTest
    static void runInsertTest() {
        //a seller account
        List<Account> accountList = new List<Account>();
        accountList.add(new Account(Name = 'seller', IST_Account_Owner__c = UserInfo.getUserId()));
        insert accountList;
        //a car
        Vehicle__c newCar = new Vehicle__c(Year__c = '2009', Make__c = 'test make', Model__c = 'test model', VIN__c = '1234567890102030');
        insert newCar;
        Vehicle__c car = [SELECT Id FROM Vehicle__c LIMIT 1];

        List<Auction__c> auctionList = new List<Auction__c>();
        //auction where all lights are true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = true, Yellow_Light__c = true, Blue_Light__c = true, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 500, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where green and yellow are true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = true, Yellow_Light__c = true, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 499, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where green and blue are true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = true, Yellow_Light__c = false, Blue_Light__c = true, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 498, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where yellow and blue are true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = true, Blue_Light__c = true, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 497, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where only green is true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = true, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 496, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where only yellow is true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = true, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 495, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where only blue is true
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = true, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 494, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        //auction where all lights are false
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 493, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        insert auctionList;

        //query
        List<Auction__c> auctions = [SELECT Id, Auction_Lights_Concatenation__c FROM Auction__c ORDER BY Floor_Price__c DESC];
        //system asserts
        System.assertEquals('gyb', auctions[0].Auction_Lights_Concatenation__c);
        System.assertEquals('gy', auctions[1].Auction_Lights_Concatenation__c);
        System.assertEquals('gb', auctions[2].Auction_Lights_Concatenation__c);
        System.assertEquals('yrb', auctions[3].Auction_Lights_Concatenation__c);
        System.assertEquals('g', auctions[4].Auction_Lights_Concatenation__c);
        System.assertEquals('yr', auctions[5].Auction_Lights_Concatenation__c);
        System.assertEquals('rb', auctions[6].Auction_Lights_Concatenation__c);
        System.assertEquals('r', auctions[7].Auction_Lights_Concatenation__c);
    }

    @isTest
    static void runUpdateTest() {
        //a seller account
        List<Account> accountList = new List<Account>();
        accountList.add(new Account(Name = 'seller', IST_Account_Owner__c = UserInfo.getUserId()));
        insert accountList;
        //a car
        Vehicle__c newCar = new Vehicle__c(Year__c = '2009', Make__c = 'test make', Model__c = 'test model', VIN__c = '1234567890102030');
        insert newCar;
        Vehicle__c car = [SELECT Id FROM Vehicle__c LIMIT 1];

        //insert auctions where all lights default to false
        List<Auction__c> auctionList = new List<Auction__c>();
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 500, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 499, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 498, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 497, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 496, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 495, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 494, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        auctionList.add(new Auction__c(Status__c = 'Active', Green_Light__c = false, Yellow_Light__c = false, Blue_Light__c = false, Seller_Dealership__c = accountList[0].Id, Floor_Price__c = 493, Winning_Bid_Price__c = 500, Vehicle_Id__c = car.Id));
        insert auctionList;

        //update them to have all different configurations
        //auction where all lights are true
        auctionList[0].Green_Light__c = true;
        auctionList[0].Yellow_Light__c = true;
        auctionList[0].Blue_Light__c = true;
        //auction where green and yellow are true
        auctionList[1].Green_Light__c = true;
        auctionList[1].Yellow_Light__c = true;
        //auction where green and blue are true
        auctionList[2].Green_Light__c = true;
        auctionList[2].Blue_Light__c = true;
        //auction where yellow and blue are true
        auctionList[3].Yellow_Light__c = true;
        auctionList[3].Blue_Light__c = true;
        //auction where only green is true
        auctionList[4].Green_Light__c = true;
        //auction where only yellow is true
        auctionList[5].Yellow_Light__c = true;
        //auction where only blue is true
        auctionList[6].Blue_Light__c = true;
        //auction where all lights are false - no need to change the last aution, it's already going to be false
        update auctionList;

        //query
        List<Auction__c> auctions = [SELECT Id, Auction_Lights_Concatenation__c FROM Auction__c ORDER BY Floor_Price__c DESC];
        //system asserts
        System.assertEquals('gyb', auctions[0].Auction_Lights_Concatenation__c);
        System.assertEquals('gy', auctions[1].Auction_Lights_Concatenation__c);
        System.assertEquals('gb', auctions[2].Auction_Lights_Concatenation__c);
        System.assertEquals('yrb', auctions[3].Auction_Lights_Concatenation__c);
        System.assertEquals('g', auctions[4].Auction_Lights_Concatenation__c);
        System.assertEquals('yr', auctions[5].Auction_Lights_Concatenation__c);
        System.assertEquals('rb', auctions[6].Auction_Lights_Concatenation__c);
        System.assertEquals('r', auctions[7].Auction_Lights_Concatenation__c);
    }
}