objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affiliation__c.object
<CustomObject>
    <description>A junction object allowing Contact to be related to many Accounts. The decision was made to create a custom object and not use AccountContactRelation object due to the latter&apos;s requirement of a direct/primary Account, which presented numerous integration challenges.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ACV Users</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Use this field to indicate whether the Affiliation is still active. It is best practice to not delete Affiliations, but mark them as Active or not appropriately.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Accounts</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>primary_contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Seller_Contact_Email__c</fullName>
        <description>This field is auto-populated via apex code to stamp the selling dealership&apos;s primary contact&apos;s email. Coed done by Manmeet Vasser</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Seller Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Title_Clerk_Email__c</fullName>
        <description>Populated via code to push the most recently created contact on the selling dealership&apos;s account that has a title of Title Clerk.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Seller Title Clerk Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetTitleContactEmailTest.cls
/**
 * @description https://acvauctions.atlassian.net/browse/TDO-292
 * 
 * @author Manmeet Vaseer
 * @date 09/03/2021
 * 
 */
@isTest
public class SetTitleContactEmailTest {
	@isTest
    static void testSellerContactEmailInsert()	{
        Test.startTest();
        String acctUniqueName = 'Test TitleStatusTransitionTriggerHandlerTest';
        Account newAcct = TestUtility.createAccount(acctUniqueName);
        SObject[] newObjs = new SObject[] {newAcct};
        insert newObjs;
        
        Contact newContact = TestUtility.createContact(newAcct);
        newContact.Active__c = true;
        newContact.Email = 'seller@dealership.com';

        Contact newPrimaryContact = TestUtility.createContact(newAcct);
        newPrimaryContact.Active__c = true;
        newPrimaryContact.Email = 'primary@dealership.com';

        newObjs = new SObject[] {newContact, newPrimaryContact};
        insert newObjs;
        
        Affiliation__c newAffiliation1 = new Affiliation__c(Account__c=newAcct.Id, Contact__c=newContact.Id, Primary_Contact__c=false);
        Affiliation__c newAffiliation2 = new Affiliation__c(Account__c=newAcct.Id, Contact__c=newPrimaryContact.Id, Primary_Contact__c=true);
        newObjs = new SObject[] {newAffiliation1, newAffiliation2};
        insert newObjs;
                
        Vehicle__c newVehicle = TestUtility.createVehicle();
        Auction__c newAuction = TestUtility.createAuction(newAcct, newContact, newVehicle);
        
        newObjs = new SObject[] {newVehicle, newAuction};
        insert newObjs;

		Case newTitleCase = TestUtility.createTitleCase(newAuction, newAcct, newContact);
        newTitleCase.Seller_Dealership__c = newAcct.Id;
        newTitleCase.Status = 'New';
        
        newObjs = new SObject[] {newTitleCase};
        insert newObjs;
        Test.stopTest();

        Case updatedCase = [SELECT Seller_Title_Clerk_Email__c, Seller_Contact_Email__c FROM CASE WHERE Id = :newTitleCase.Id];
        System.assertEquals(newPrimaryContact.Email, updatedCase.Seller_Contact_Email__c, 'Seller_Contact_Email__c should be populated by the trigger.');
    }

	@isTest
    static void testSellerContactEmailUpdate()	{
        Test.startTest();
        String acctUniqueName = 'Test TitleStatusTransitionTriggerHandlerTest';
        Account newAcct = TestUtility.createAccount(acctUniqueName);
        SObject[] newObjs = new SObject[] {newAcct};
        insert newObjs;
        
        Contact newContact = TestUtility.createContact(newAcct);
        newContact.Active__c = true;
        newContact.Email = 'seller@dealership.com';

        Contact newPrimaryContact = TestUtility.createContact(newAcct);
        newPrimaryContact.Active__c = true;
        newPrimaryContact.Email = 'primary@dealership.com';

        newObjs = new SObject[] {newContact, newPrimaryContact};
        insert newObjs;
        
        Affiliation__c newAffiliation1 = new Affiliation__c(Account__c=newAcct.Id, Contact__c=newContact.Id, Primary_Contact__c=false);
        Affiliation__c newAffiliation2 = new Affiliation__c(Account__c=newAcct.Id, Contact__c=newPrimaryContact.Id, Primary_Contact__c=true);
        newObjs = new SObject[] {newAffiliation1, newAffiliation2};
        insert newObjs;
                
        Vehicle__c newVehicle = TestUtility.createVehicle();
        Auction__c newAuction = TestUtility.createAuction(newAcct, newContact, newVehicle);
        
        newObjs = new SObject[] {newVehicle, newAuction};
        insert newObjs;

		Case newTitleCase = TestUtility.createTitleCase(newAuction, newAcct, newContact);
        newTitleCase.Seller_Dealership__c = newAcct.Id;
        newTitleCase.Status = 'New';
        
        newObjs = new SObject[] {newTitleCase};
        insert newObjs;
        Test.stopTest();

        Case updatedCase = [SELECT Seller_Title_Clerk_Email__c, Seller_Contact_Email__c FROM CASE WHERE Id = :newTitleCase.Id];
        System.assertEquals(newPrimaryContact.Email, updatedCase.Seller_Contact_Email__c, 'Seller_Contact_Email__c should be populated by the trigger.');
        
        // Now Update the primary contact
        newPrimaryContact.Email = 'primary2@dealership.com';
        update newPrimaryContact;
        update newTitleCase; // to invoke trigger

        updatedCase = [SELECT Seller_Title_Clerk_Email__c, Seller_Contact_Email__c FROM CASE WHERE Id = :newTitleCase.Id];
        System.assertEquals(newPrimaryContact.Email, updatedCase.Seller_Contact_Email__c, 'Seller_Contact_Email__c should be updated by the trigger.');

        // Now remove the primary contact from the Account/Affiliation
        newAffiliation1.Primary_Contact__c = true;
        newAffiliation2.Primary_Contact__c = false;
        newObjs = new SObject[] {newAffiliation1, newAffiliation2, newTitleCase};
        update newObjs;

        updatedCase = [SELECT Seller_Title_Clerk_Email__c, Seller_Contact_Email__c FROM CASE WHERE Id = :newTitleCase.Id];
        System.assertEquals(newContact.Email, updatedCase.Seller_Contact_Email__c, 'Seller_Contact_Email__c should be updated by the trigger.');        
  }    
}