objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Customer_Success_Advocate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Success Advocate - replacing the Title Consultant field</description>
        <inlineHelpText>Please reach out to the Customer Success Advocate for title statuses of “New” and “48 Hour Notice”. Customer Success Advocate has replaced the Title Consultant field.</inlineHelpText>
        <label>Customer Success Advocate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts73Aq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the Title Specialist that works with the Account</inlineHelpText>
        <label>Title Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Title_Information</fullName>
        <active>true</active>
        <businessProcess>Title Information Process</businessProcess>
        <description>Use this record type to process a title.</description>
        <label>Title Information</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Customer_Inquiry__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user assigned to this inquiry</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Inquiries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+Ops_Case__r.Auction_Number__c,  Ops_Case__r.Auction_Number__r.Name, &quot;_parent&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Related Customer Inquiries</relationshipLabel>
        <relationshipName>Related_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <description>The notes from the call.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <description>The subset of Call Bucket, further defines what the dealer is calling about.</description>
        <label>Call Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Call_Bucket__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Release Slip</fullName>
                </value>
                <value>
                    <fullName>Payment Not Selected</fullName>
                </value>
                <value>
                    <fullName>NSF</fullName>
                </value>
                <value>
                    <fullName>Buyer Payment Status</fullName>
                </value>
                <value>
                    <fullName>Seller Payment Status</fullName>
                </value>
                <value>
                    <fullName>Default Payment Update</fullName>
                </value>
                <value>
                    <fullName>ACV Capital</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Pickup Issue</fullName>
                </value>
                <value>
                    <fullName>Cancel Transport</fullName>
                </value>
                <value>
                    <fullName>Dealmaker</fullName>
                </value>
                <value>
                    <fullName>Make an Offer</fullName>
                </value>
                <value>
                    <fullName>False Proxy</fullName>
                </value>
                <value>
                    <fullName>Goodwill Request</fullName>
                </value>
                <value>
                    <fullName>Multi-Store Buyer</fullName>
                </value>
                <value>
                    <fullName>Ghost Bid</fullName>
                </value>
                <value>
                    <fullName>Account/Contact Update</fullName>
                </value>
                <value>
                    <fullName>User Login Support</fullName>
                </value>
                <value>
                    <fullName>Deactivation</fullName>
                </value>
                <value>
                    <fullName>Good Experience</fullName>
                </value>
                <value>
                    <fullName>Arbitration</fullName>
                </value>
                <value>
                    <fullName>Titles</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Unwind</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Valid Business Reason</fullName>
                </value>
                <value>
                    <fullName>Called No Answer, Try Again</fullName>
                </value>
                <value>
                    <fullName>App Education</fullName>
                </value>
                <value>
                    <fullName>Buyer Reported Problem</fullName>
                </value>
                <value>
                    <fullName>Buyer Title Status</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <formula>IF( ISBLANK(TEXT(Call_Type__c)) , HYPERLINK( &quot;/&quot; + Id,  &quot;Historic Record&quot;, &quot;_self&quot;), HYPERLINK( &quot;/&quot; + Id,  TEXT(Call_Type__c), &quot;_self&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Inquiry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>This is the external id for CI records coming from the Report a Problem process in tools. It is a concatenated id made up of the auction_issues table id and the auction_issues_note table id.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ops_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ops Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Related Support Cases</relationshipLabel>
        <relationshipName>Related_Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Displays which process a CI record was created by.</description>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>48 Hr Notice Tab</fullName>
                </value>
                <value>
                    <fullName>Log an Interaction</fullName>
                </value>
                <value>
                    <fullName>Report a Problem</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Should_Assign_To__c</fullName>
        <label>Should Assign To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Specialist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Inquiry</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Customer Inquiry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inquiry_Comment__c.object
<CustomObject>
    <description>Comments made related to each individual Inquiry record on a Support Case.</description>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related auction to the inquiry.</description>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Inquiry Comments</relationshipLabel>
        <relationshipName>Inquiry_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Inquiry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the Customer Inquiry record.</description>
        <label>Customer Inquiry</label>
        <referenceTo>Customer_Inquiry__c</referenceTo>
        <relationshipLabel>Inquiry Comments</relationshipLabel>
        <relationshipName>Inquiry_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inquiry_Notes__c</fullName>
        <description>Notes related to the Inquiry in the Customer Inquiry lookup field.</description>
        <label>Inquiry Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ops_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related ops case. ie: titles, arb, etc.</description>
        <label>Ops Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Inquiry Comments (Ops Case)</relationshipLabel>
        <relationshipName>Inquiry_Comments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inquiry Comment</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Inquiry Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiry Comments</pluralLabel>
    <recordTypes>
        <fullName>Inquiry_Comment</fullName>
        <active>true</active>
        <description>This record type is for the storing and displaying of Inquiry Comments.</description>
        <label>Inquiry Comment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomerInquiryReportAProblemHandler.cls
public with sharing class CustomerInquiryReportAProblemHandler extends TriggerInterface {
    public static final Id notesId = Schema.SObjectType.Inquiry_Comment__c.getRecordTypeInfosByDeveloperName().get('Inquiry_Comment').getRecordTypeId();
    public static final Set<String> specialistStatuses = new Set<String>{'Problem', 'Return to Seller', 'Closed Unwound', 'Returned to Seller Unwound', 'Title at ACV Unwound'};
    public static final Set<String> csAdvocateStatuses = new Set<String>{'Working', 'Received', 'New', '48 Hour Notice', 'Sent'};

    public override void beforeInsert(List<sObject> newList) {
        List<Customer_Inquiry__c> newCIList = (List<Customer_Inquiry__c>)newList;
        Map<String, Customer_Inquiry__c> rapCImap = new Map<String, Customer_Inquiry__c>();
        Map<String, Case> caseMap = new Map<String, Case>();
        Map<Id, Auction__c> aucMap = new Map<Id, Auction__c>();
        Set<String> acvAucIdSet = new Set<String>();

        for (Customer_Inquiry__c c : newCIList) {
            if (c.Origin__c == 'Report a Problem') {
                rapCImap.put(c.External_Id__c, c);
                acvAucIdSet.add(c.Auction__c);
            }
        }

        if (rapCImap.size() > 0) { 
            if (!acvAucIdSet.isEmpty()) {
                for (Case ca : [SELECT Id, Status, Auction_Number__c, CreatedDate FROM Case WHERE RecordType.DeveloperName = 'Title_Information' AND Auction_Number__c IN :acvAucIdSet]) {
                    if (!caseMap.containsKey(ca.Auction_Number__c)) {
                        caseMap.put(ca.Auction_Number__c, ca);
                    }
                    else if (ca.CreatedDate > caseMap.get(ca.Auction_Number__c).CreatedDate) {
                        caseMap.put(ca.Auction_Number__c, ca);
                    }
                }

                aucMap = new Map<Id, Auction__c>([SELECT Id, Seller_Dealership__r.Title_Specialist__c, Seller_Dealership__r.Customer_Success_Advocate__c FROM Auction__c WHERE Id IN :acvAucIdSet]);
            }

            for (Customer_Inquiry__c ci : rapCImap.values()) {
                Auction__c aucRec = aucMap.get(ci.Auction__c);
                Case caseRec = new Case();
                if (caseMap.containsKey(ci.Auction__c)) {
                    caseRec = caseMap.get(ci.Auction__c);
                }

                ci.Ops_Case__c = caseRec?.Id;

                // if (ci.Call_Type__c == 'Buyer Reported Problem') {
                //     if (aucRec?.Seller_Dealership__r?.Title_Specialist__c != null) {
                //         ci.Assigned_To__c = aucRec.Seller_Dealership__r.Title_Specialist__c;
                //     }
                //     else {
                //         ci.Should_Assign_To__c = 'Specialist';
                //     }
                // }
                // else if (caseMap.containsKey(ci.Auction__c)) {
                //     if (ci.Call_Type__c == 'Buyer Title Status' && specialistStatuses.contains(caseRec?.Status)) {
                //         if (aucRec?.Seller_Dealership__r?.Title_Specialist__c != null) {
                //             ci.Assigned_To__c = aucRec.Seller_Dealership__r.Title_Specialist__c;
                //         }
                //         else {
                //             ci.Should_Assign_To__c = 'Specialist';
                //         }
                //     }
                //     else if (ci.Call_Type__c == 'Buyer Title Status' && csAdvocateStatuses.contains(caseRec?.Status)) {
                //         if (aucRec?.Seller_Dealership__r?.Customer_Success_Advocate__c != null) {
                //             ci.Assigned_To__c = aucRec.Seller_Dealership__r.Customer_Success_Advocate__c;
                //         }
                //         else {
                //             ci.Should_Assign_To__c = 'Consultant';
                //         }
                //     }
                // }
            }
        }
    }

    public override void afterInsert(List<sObject> newList) {
        List<Customer_Inquiry__c> newCIList = (List<Customer_Inquiry__c>)newList;
        List<Inquiry_Comment__c> icList = new List<Inquiry_Comment__c>();
        for (Customer_Inquiry__c ci : newCIList) {
            if (ci.Origin__c == 'Report a Problem') {
                icList.add(new Inquiry_Comment__c(RecordTypeId = notesId, Customer_Inquiry__c = ci.Id, Inquiry_Notes__c = ci.Call_Notes__c));
            }
        }
        if (icList.size() > 0) {
            insert icList;
        }
    }
}