objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account Status related to the registration process. This field maps to Tools on the dealerships table</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0% complete</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>25% complete</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>50% complete</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>75% complete</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>100% complete</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the program is active or not.</description>
        <inlineHelpText>Used to indicate if the program is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to capture current status program.</description>
        <inlineHelpText>Used to capture current status program.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not eligible</fullName>
                </value>
                <value>
                    <fullName>In/under review by IST (use pre and post pending customer response)</fullName>
                </value>
                <value>
                    <fullName>Pending customer response (pending app completion) -In/under review by IST</fullName>
                </value>
                <value>
                    <fullName>Waiting on POA (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Verified by IST (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Under review by TM under review by RSD approved Rejected [with reasons] (do not call removes from eligibility)</fullName>
                </value>
                <value>
                    <fullName>TM will be reaching out to you soon Enrolled (start date)</fullName>
                </value>
                <value>
                    <fullName>Active (initiated at first sale)</fullName>
                </value>
                <value>
                    <fullName>Remove (for performance)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager_Email__c</fullName>
        <formula>Account__r.Field_Account_Manager__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Manager Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Manager_First_Name__c</fullName>
        <formula>Account__r.Field_Account_Manager__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Manager First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>To capture notes / comments related to the enrollment record</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>To capture notes / comments related to the enrollment record</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Has_Customer_Applied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Customer Applied?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invitation_Link_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invitation Link Expired?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invitation_Sent_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Invitation Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_Of_Days_Since_Invitation_Sent__c</fullName>
        <formula>TODAY() -  Invitation_Sent_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>No. Of Days Since Invitation Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Enrollments</relationshipLabel>
        <relationshipName>Program_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Not eligible</fullName>
                </value>
                <value>
                    <fullName>In/under review by IST (use pre and post pending customer response)</fullName>
                </value>
                <value>
                    <fullName>Pending customer response (pending app completion) -In/under review by IST</fullName>
                </value>
                <value>
                    <fullName>Waiting on POA (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Verified by IST (manually updated by IST)</fullName>
                </value>
                <value>
                    <fullName>Under review by TM under review by RSD approved Rejected [with reasons] (do not call removes from eligibility)</fullName>
                </value>
                <value>
                    <fullName>TM will be reaching out to you soon Enrolled (start date)</fullName>
                </value>
                <value>
                    <fullName>Active (initiated at first sale)</fullName>
                </value>
                <value>
                    <fullName>Remove (for performance)</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Rules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Program_Rule__c</fullName>
        <label>Program Rule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Rule__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Rule__c</referenceTo>
        <relationshipLabel>Rule Assignment</relationshipLabel>
        <relationshipName>Rule_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Rule Assignment</relationshipLabel>
        <relationshipName>Rule_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Assignment</label>
    <nameField>
        <displayFormat>RA{00000000}</displayFormat>
        <label>Rule Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DealerProgramApplicationController.cls
/******************************************************************************* 
@description : This Apex class is used as a controller for dealerProgramApplication LWC Component
@author Saisystems
*******************************************************************************/
global without sharing class DealerProgramApplicationController {
    
    /******************************************************************************* 
    @description : This function is used to get all the Files related to ProgramEnrollment
    @author Saisystems
    *******************************************************************************/
    @AuraEnabled
    public static List<ContentVersion> getContentDetails(String recordId) {
        List<ContentDocumentLink> contentDocumentList = [SELECT ContentDocumentId, LinkedEntityId 
                                                         FROM   ContentDocumentLink 
                                                         WHERE  LinkedEntityId =: recordId];
        Set<Id> contentDocumentId = new Set<Id>();
        
        for(ContentDocumentLink cdl : contentDocumentList){
            contentDocumentId.add(cdl.ContentDocumentId);
        }
        
        List<ContentVersion> contentVersionList = [SELECT Id, VersionData, FileType, Title, FileExtension,
                                                   ContentDocument.CreatedBy.Name, ContentDocument.ContentSize,
                                                   CreatedDate, ContentDocumentId, ContentDocument.FileType
                                                   FROM   ContentVersion 
                                                   WHERE  ContentDocumentId IN : contentDocumentId];
        return contentVersionList;
        //return JSON.serialize(contentVersionList);
    }
    
    /******************************************************************************* 
    @description : This function is used to get the details of Program And the ContactRecord Details
    @author Saisystems
    *******************************************************************************/
    @AuraEnabled(cacheable=true)
    public static ProgramAndContactDetails getProgramAndContactDetails(String programId, String accountId, 
                                                                       String primaryContactId, String recordId){
		system.debug('@@@@programId----'+programId);
        system.debug('@@@@accountId----'+accountId);
        system.debug('@@@@primaryContactId----'+primaryContactId);
        Boolean isLinkExpired = false;
		List<ContentVersion> contentVersionList = new List<ContentVersion>();
        Program__c programRecord = null;
        Contact contactRecord = null;
        Program_Enrollment__c programEnrollment = null;                                                                   
        List<Rule_Assignment__c> programRuleAssignments = null;
        List<ProgramRuleAssignmentAndAcceptance> ProgramRuleAssignmentAndAcceptanceList = new List<ProgramRuleAssignmentAndAcceptance>();
        if(!String.isBlank(programId)){
            //String programName = '%'+programId+'%';
            programRecord = [SELECT Id, Name, Active__c  
                             FROM Program__c
                             WHERE Id =: programId
                             ];
            programEnrollment = [SELECT Id, Name, Invitation_Sent_Date__c, No_Of_Days_Since_Invitation_Sent__c, Invitation_Link_Expired__c,
                                 Account_Manager_First_Name__c, Account_Manager_Email__c, Has_Customer_Applied__c
                             FROM Program_Enrollment__c
                             WHERE Id =: recordId
                             ];
            system.debug('@@@@programEnrollment----'+programEnrollment);
            if(programEnrollment != null && programEnrollment.No_Of_Days_Since_Invitation_Sent__c >= 15 ){	
                //programEnrollment.Invitation_Link_Expired__c = true;
                //update programEnrollment;
                isLinkExpired = true;
                updateEnrolmentRecord(programEnrollment.Id);
            }
            programRuleAssignments = [SELECT Id, Name, Program_Rule__c, Program__c, Program_Rule__r.Name, Program_Rule__r.Description__c
                                        FROM Rule_Assignment__c 
                                        WHERE Program__c =: programId
                                        ]; 
            if(!programRuleAssignments.isEmpty()){                
                for(Rule_Assignment__c ruleAssignmentRecord : programRuleAssignments){
                    ProgramRuleAssignmentAndAcceptance programRuleAssignmentAndAcceptanceRecord = new ProgramRuleAssignmentAndAcceptance(false, ruleAssignmentRecord);
                    ProgramRuleAssignmentAndAcceptanceList.add(programRuleAssignmentAndAcceptanceRecord);
                }    
            }                                                                      
        }
        if(!String.isBlank(primaryContactId)){
            contactRecord = [SELECT Id, Name, Account.Name, Title, Phone, Email, Account.Website 
                            FROM Contact
                            WHERE Id =: primaryContactId LIMIT 1
                            ];
        }
        if(!String.isBlank(recordId)){
            List<ContentDocumentLink> contentDocumentList = [SELECT ContentDocumentId, LinkedEntityId 
                                                            FROM   ContentDocumentLink 
                                                            WHERE  LinkedEntityId =: recordId];
            Set<Id> contentDocumentId = new Set<Id>();
            for(ContentDocumentLink cdl : contentDocumentList){
            	contentDocumentId.add(cdl.ContentDocumentId);
            }
            contentVersionList = [SELECT Id, VersionData, FileType, Title, FileExtension,
                                                        ContentDocument.CreatedBy.Name, ContentDocument.ContentSize,
                                                        CreatedDate, ContentDocumentId, ContentDocument.FileType
                                                        FROM   ContentVersion 
                                                        WHERE  ContentDocumentId IN : contentDocumentId];
        }
        system.debug('@@@@programRecord----'+programRecord);
        system.debug('@@@@contactRecord----'+contactRecord);
        return new ProgramAndContactDetails(isLinkExpired, programRecord, contactRecord, ProgramRuleAssignmentAndAcceptanceList, contentVersionList, programEnrollment);
    }
    /*
    @AuraEnabled(cacheable=true)
    public static Contact getContactCustom(String accountId) {
        if(!String.isBlank(accountId)){
            system.debug('@@@@accountId----'+accountId);
            system.debug('@@@@Inside getContact Method----');
            system.debug('@@@@contactRecord----'+[SELECT Id, Name, Account.Name, Title, Phone, Email, Account.Website 
                                                  FROM Contact
                                                  WHERE AccountId =: accountId LIMIT 1]);
            return [
                SELECT Id, Name, Account.Name, Title, Phone, Email, Account.Website 
                FROM Contact
                WHERE AccountId =: accountId LIMIT 1
            ];
        }
        return null;
    }*/
    
    @AuraEnabled
    public static boolean submitApplication(String parentId){
        system.debug('@@@@parentId----'+parentId);
        Program_Enrollment__c programEnrollmentToUpdate;
        if(!String.isEmpty(parentId)){
        	programEnrollmentToUpdate = 
                [SELECT Id, Status__c, Name, Has_Customer_Applied__c 
                FROM Program_Enrollment__c 
                WHERE Id =: parentId];
            //Desicuss the status value with Matt 
            programEnrollmentToUpdate.Status__c = 'TM will be reaching out to you soon Enrolled (start date)';
            programEnrollmentToUpdate.Has_Customer_Applied__c = true;
            update programEnrollmentToUpdate;
        }    
        return true;       
    }
    
    @future
    public static void updateEnrolmentRecord(String recordId)
    {   
         Program_Enrollment__c programEnrollment = [SELECT Id, Name, Invitation_Sent_Date__c, No_Of_Days_Since_Invitation_Sent__c, Invitation_Link_Expired__c    
                             FROM Program_Enrollment__c
                             WHERE Id =: recordId
                             ];
        programEnrollment.Invitation_Link_Expired__c = true;
        update programEnrollment;
    }
    
    /******************************************************************************* 
    @description : Wrapper class used to hold the details of Program and Contact Details
    @author Saisystems
    *******************************************************************************/
    public class ProgramAndContactDetails{
        @AuraEnabled
        Public Boolean isLinkExpired;
        @AuraEnabled
        Public Program__c programRecord;
        @AuraEnabled
        Public Program_Enrollment__c programEnrollmentRecord;
        @AuraEnabled
        Public Contact contactRecord;
        @AuraEnabled
        Public List<ProgramRuleAssignmentAndAcceptance> programRuleAssignmentAndAcceptanceList;
        @AuraEnabled 
        public List<ContentVersion> contentVersionList;
        
        ProgramAndContactDetails(Boolean isLinkExpired, Program__c programRecord, Contact contactRecord, List<ProgramRuleAssignmentAndAcceptance> programRuleAssignmentAndAcceptanceList, 
                                 List<ContentVersion> contentVersionList, Program_Enrollment__c programEnrollmentRecord){
                                     this.isLinkExpired = isLinkExpired;
                                     this.programRecord = programRecord;
                                     this.contactRecord = contactRecord;
                                     this.programRuleAssignmentAndAcceptanceList = programRuleAssignmentAndAcceptanceList;
                                     this.contentVersionList = contentVersionList;
                                     this.programEnrollmentRecord = programEnrollmentRecord;
                                 }
    }
    
    /******************************************************************************* 
    @description : Wrapper class used to hold the Program Rule Assignment and the rule Acceptance
    @author Saisystems
    *******************************************************************************/
    public class ProgramRuleAssignmentAndAcceptance{
        @AuraEnabled
        Public Boolean ruleAcceptance;
        @AuraEnabled
        Public Rule_Assignment__c programRuleAssignment;
        
        ProgramRuleAssignmentAndAcceptance(Boolean ruleAcceptance, Rule_Assignment__c programRuleAssignment){
            this.ruleAcceptance = ruleAcceptance;
            this.programRuleAssignment = programRuleAssignment;
        }
    }
}