objects/Account.object
<CustomObject
     >
    <fields>
        <fullName>Legal_State__c</fullName>
        <label>Legal State</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field can be deprecated once the ACV-to-SFDC integration unmaps this from the integration.</description>
        <label>Title Absent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Due_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Title Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CalculateTitleDueDateCaseTest.cls
/**
 * @description https://acvauctions.atlassian.net/browse/TDO-26 requirements.
 * 
 * @author Amul
 * @date 05/10/2021
 * 
 * @history 06/09/2021 Manmeet Vaseer - Added logic to handle Legal vs Billing state.
 * 
 */
@isTest
public class CalculateTitleDueDateCaseTest {
    @TestSetup static void createData(){
        Test.startTest();    
        Account actObj = TestUtility.createAccount();
        actObj.BillingState='CA';
        insert actObj;  

        Contact contactObj = TestUtility.createContact(actObj);
        insert contactObj;
        Vehicle__c vehicleObj = TestUtility.createVehicle();
        Insert vehicleObj;
        Auction__c auctionObj = TestUtility.createAuction(actObj, contactObj, vehicleObj);
        auctionObj.end_time__c= system.today();
        insert auctionObj;
        Test.stopTest();
    }

    @isTest
    static void testTitleAttachedChangeAndStatusClose() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];        
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
        
        Case testCase = TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase.Title_Attached__c = true;
        testCase.Seller_Dealership__c = acctObj.Id;
        testCase.Status = 'Working';
        
        /*
         * This should invoke CaseCalculateTitleDueDate handler in the Case trigger,
         * which will use related Account to check if the Legal/Billing State has changed and
         * then populate the value of Title Due Date field in Case.
         */ 
        insert testCase;
        
		testCase = [Select id,Title_Due_Date__c, Title_Attached__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(44), testCase.Title_Due_Date__c);

        testCase.Status = 'Closed Unwound';
        update testCase;

		testCase = [Select id,Title_Due_Date__c, Title_Attached__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(44), testCase.Title_Due_Date__c);
        
        testCase.Title_Attached__c = false;
        update testCase;
        
		testCase = [Select id,Title_Due_Date__c, Title_Attached__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(44), testCase.Title_Due_Date__c);            
    }  
    
    @isTest
    static void testTitleAttachedChange() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];        
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
        
        Case testCase = TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase.Title_Attached__c = true;
        testCase.Seller_Dealership__c = acctObj.Id;        
        
        /*
         * This should invoke CaseCalculateTitleDueDate handler in the Case trigger,
         * which will use related Account to check if the Legal/Billing State has changed and
         * then populate the value of Title Due Date field in Case.
         */ 
        insert testCase;
        
		testCase = [Select id,Title_Due_Date__c, Title_Attached__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(44), testCase.Title_Due_Date__c);
        
        /*
         * This should invoke CaseCalculateTitleDueDate handler in the Account trigger,
         * which will update the Title Due Date field in related Cases.
         */ 
        acctObj.BillingState = 'FL';
        update acctObj;

		testCase = [Select id,Title_Due_Date__c, Title_Attached__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(29), testCase.Title_Due_Date__c);    
        
        testCase.Title_Attached__c = false;
        update testCase;
        
		testCase = [Select id,Title_Due_Date__c, Title_Attached__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(6), testCase.Title_Due_Date__c);            
    }  

    @isTest
    static void testOtherStateTitleAttachedTrueLegalState() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];        
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
        acctObj.Legal_State__c = 'FL';
        update acctObj;
        
        Case testCase = TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase.Title_Attached__c = true;
        testCase.Seller_Dealership__c = acctObj.Id;
        
        Test.startTest();
        insert testCase;
        Test.stopTest();
        
		testCase = [Select id,Title_Due_Date__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(29), testCase.Title_Due_Date__c);
    }  

    @isTest
    static void testCaliforniaTitleAttachedTrueLegalState() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];        
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
        acctObj.Legal_State__c = 'CA';
        acctObj.BillingState='FL';
        update acctObj;
        
        Case testCase = TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase.Title_Attached__c = true;
        testCase.Seller_Dealership__c = acctObj.Id;
        
        Test.startTest();
        insert testCase;
        Test.stopTest();
        
		testCase = [Select id,Title_Due_Date__c from Case where id=:testCase.ID];
		System.assert(testCase.Title_Due_Date__c!=null); 
        System.assertEquals(system.today().addDays(44), testCase.Title_Due_Date__c);
    }  
    
    @isTest
    static void testCaliforniaTitleAttachedFalse() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
        Case testCase = TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase.Title_Attached__c = false;
        testCase.Seller_Dealership__c = acctObj.Id;
        
        Test.startTest();
        insert testCase;
        Test.stopTest();
        
		testCase = [Select id,Title_Due_Date__c from Case where id=:testCase.ID];
		system.assert(testCase.Title_Due_Date__c!=null); 
        system.assert(testCase.Title_Due_Date__c == system.today().addDays(6));
    }  
    
    @isTest
    static void testOtherStateTitleAttachedFalse() {
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
        update new account(id=conObj.AccountId,BillingState = 'FL');
        
        Case testCase1 = TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase1.Title_Attached__c = false;
        testCase1.Seller_Dealership__c = acctObj.Id;
  		
        Test.startTest();
        insert testCase1;
        Test.stopTest();
        
        testCase1 = [Select id,Title_Due_Date__c from Case where id=:testCase1.ID];
		system.assert(testCase1.Title_Due_Date__c!=null); 
        system.assert(testCase1.Title_Due_Date__c == system.today().addDays(6)); 
    }  
    
    @isTest
    static void testCaliforniaTitleAttachedTrue() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];

        Case testCase1 =TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase1.Title_Attached__c = true;
        testCase1.Seller_Dealership__c = acctObj.Id;
        
        Test.startTest();
        insert testCase1;
        Test.stopTest();
        
        testCase1 = [Select id,Title_Due_Date__c from Case where id=:testCase1.ID];
        system.assert(testCase1.Title_Due_Date__c!=null); 
        system.assert(testCase1.Title_Due_Date__c == system.today().addDays(44));
    }  
    
    @isTest
    static void testOtherStateTitleAttachedTrue() {
        
        Auction__c auctionObj = [SELECT id,vehicle_id__c FROM Auction__c LIMIT 1];
        Contact conObj = [SELECT id,AccountId FROM Contact LIMIT 1];
        Account acctObj = [SELECT id,BillingState, Legal_State__c FROM Account WHERE Id = :conObj.AccountId];
		update new account(id=conObj.AccountId,BillingState = 'FL');
        Case testCase1 =TestUtility.createTitleCase(auctionObj, acctObj, conObj);
        testCase1.Title_Attached__c = true;
        testCase1.Seller_Dealership__c = acctObj.Id;
        
        Test.startTest();
        insert testCase1;
        Test.stopTest();
        
        testCase1 = [Select id,Title_Due_Date__c from Case where id=:testCase1.ID];
		system.assert(testCase1.Title_Due_Date__c!=null); 
        system.assert(testCase1.Title_Due_Date__c == system.today().addDays(29)); 
    } 

}