objects/AssociatedLocation.object
<CustomObject>
    <fields>
        <fullName>Auto_Inc_Id__c</fullName>
        <description>Auto Increment Id used to generate Org address Ids</description>
        <label>Auto Inc Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Organization_Address_Id__c</fullName>
        <description>This field is the unique Id between the Organizaition and the Address associated with it, along with the unique Address type</description>
        <externalId>true</externalId>
        <label>Organization Address Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssociatedLocationUniqueIdGeneration.cls
public class AssociatedLocationUniqueIdGeneration extends TriggerInterface {

    @TestVisible Private Static Boolean throwError = false;

    public override void afterInsert(List<sObject> objectList) {
    
        List<AssociatedLocation> newAssociatedLocations = (List<AssociatedLocation>) objectList;
        Map<id, String> idMap = new Map<id, String>();
        List<AssociatedLocation> updateList = new List<AssociatedLocation>();
        for(AssociatedLocation newAssLocs : newAssociatedLocations){
            idMap.put(newAssLocs.id, newAssLocs.Auto_Inc_Id__c);
        }
        List<AssociatedLocation> assLocLst = new List<AssociatedLocation>([Select id, Auto_Inc_Id__c, Organization_Address_Id__c
        From AssociatedLocation Where id IN: newAssociatedLocations]);

            for ( AssociatedLocation newAssLoc : assLocLst ) {
                if (newAssLoc.Organization_Address_Id__c == null) {
                    newAssLoc.Organization_Address_Id__c = integer.valueof(idMap.get(newAssLoc.id));
                    updateList.add(newAssLoc);
                }
            }
            try{
                if(!updateList.isempty()){
                    if(throwError) Decimal i = 1/0;
                    update updateList;
                }
            }
            catch(Exception e){
                IdentityHelper.makeApexLog(acvutility.currentLineNumber(), 
                    'AssociatedLocationUniqueIdGeneration: Get AssociatedLocation Id failure: '+e.getStackTraceString(), 
                    SplunkHelper.LOGLEVEL.ERROR, 'AssociatedLocationUniqueIdGeneration', 
                    e.getMessage(), 
                    'AssociatedLocation');
                throw new CustomException(e);

            }
    }
}