objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Vehicle_Make__c</fullName>
        <label>Vehicle Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <label>Vehicle Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Year__c</fullName>
        <label>Vehicle Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payment_method__c</fullName>
        <description>Integrated field.</description>
        <label>Buyer Payment Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payment_status__c</fullName>
        <description>Integrated field.</description>
        <label>Buyer Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Deposited</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>hold_on_file</fullName>
                    <label>Hold On File</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>payment_pending</fullName>
                    <label>Payment Pending</label>
                </value>
                <value>
                    <fullName>payment_returned</fullName>
                    <label>Payment Returned</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Recorded</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>refund_pending</fullName>
                    <label>Refund Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>ta_hold</fullName>
                    <label>TA Hold</label>
                </value>
                <value>
                    <fullName>ta_on_file</fullName>
                    <label>TA On File</label>
                </value>
                <value>
                    <fullName>to_be_floored</fullName>
                    <label>To Be Floored</label>
                </value>
                <value>
                    <fullName>to_be_picked_up</fullName>
                    <label>To Be Picked Up</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Age_in_Days__c</fullName>
        <formula>(NOW() -CreatedDate )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age in Days</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auction_Number_Case__c</fullName>
        <formula>Auction_Number__r.id__c</formula>
        <label>Auction Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_Name__c</fullName>
        <formula>Account.Name</formula>
        <label>Buyer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Auction_Number__r.payment_method__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buyer Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>TEXT(Auction_Number__r.payment_status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buyer Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Name__c</fullName>
        <formula>Seller_Dealership__r.Name</formula>
        <label>Seller Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field can be deprecated once the ACV-to-SFDC integration unmaps this from the integration.</description>
        <label>Title Absent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Make__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vehicle Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Year__c</fullName>
        <label>Vehicle Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/SearchAllTitlesApexHandler.cls
public with sharing class SearchAllTitlesApexHandler {
    @AuraEnabled(cacheable=true)
    public static List<Case> getTitles(String searchTerm){
        if (String.isNotEmpty(searchTerm) && searchTerm.length() > 1) {
            searchTerm += '*';

            List<List<sObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING 
                                                Case (Id, Title_Attached__c, Status, CaseNumber, Auction_Number_Case__c, Auction_Number__r.Name, Auction_Number__c, Vehicle__c, Vehicle__r.Name, Vehicle_Make__c, Vehicle_Model__c, Vehicle_Year__c, Seller_Name__c, Buyer_Name__c, Age_in_Days__c, Payment_Method__c, Payment_Status__c
                                                WHERE Status IN ('New', '48 Hour Notice', 'Problem') AND RecordType.Name = 'Title Information' AND Age_in_Days__c < 50.0 ORDER BY Age_in_Days__c DESC)];

            List<Case> results = new List<Case>();
            Case [] titles = ((List<Case>) searchResults[0]);
            return titles;
        } 
        else {
            return [SELECT Id, Title_Attached__c, Status, CaseNumber, Auction_Number_Case__c, Auction_Number__r.Name, Auction_Number__c, Vehicle__c, Vehicle__r.Name, Vehicle_Make__c, Vehicle_Model__c, Vehicle_Year__c, Seller_Name__c, Buyer_Name__c, Age_in_Days__c, Payment_Method__c, Payment_Status__c
                FROM Case
                WHERE Status IN ('New', '48 Hour Notice', 'Problem')
                AND RecordType.Name = 'Title Information'
                AND Age_in_Days__c < 50.0
                ORDER BY Age_in_Days__c DESC LIMIT 100];
        }
    }
}
//AND Age_in_Days__c > 3.0
//AND Age_in_Days__c < 30.0