objects/Auction__c.object
<CustomObject>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number_Searchable__c</fullName>
        <description>This field is filled by a workflow. It was created to provide a searchable Auction Number field since the Lookup and Formula Auction Number fields are not.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Auction Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <description>The Batch Id generated by the Titles Cron when a title is sent to the entitled-beta inbox from a user scanning it. It uses the current time, user, scanner, and current date. Primarily used to mass assign titles to a specific user.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Inbound Batch Id</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Location__c</fullName>
        <description>Location of Title Image</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Image Location</label>
        <length>1028</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title_Received_Date__c</fullName>
        <description>Date title was received from the Seller</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date title was received from the Seller</inlineHelpText>
        <label>Title Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title_Scanned_Time__c</fullName>
        <description>Time at which the Title was scanned</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title Scanned Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title_Scanner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Title Scanner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <label>Title State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Title_Information</fullName>
        <active>true</active>
        <businessProcess>Title Information Process</businessProcess>
        <description>Use this record type to process a title.</description>
        <label>Title Information</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/TitlesReceivedAPI.cls
@RestResource(urlMapping='/TitlesReceived/*')
global class TitlesReceivedAPI {
    
    private static Case auctionCase;
    private static User runningUser;

    @HTTPPost
    global static void validateParams(String auctionNumber, String userEmail, Datetime timeStamp, String s3url, String batchId, String titleStateFullname) {
        TitlesAutomationAPI automation = new TitlesAutomationAPI();
        try {
            RestRequest req = RestContext.request;
            RestResponse res = RestContext.response;
            s3url = String.isNotBlank(s3url) ? s3url : null;
            batchId = String.isNotBlank(batchId) ? batchId : null;

            // Set Return to be in JSON
            res.addHeader('Content-Type', 'application/json');
            final Id TITLE_CASE_RT = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get( 'Title_Information' ).getRecordTypeId();

            if (String.isBlank(userEmail)) {
                throw new BadRequestException('A userEmail parameter is required and cannot be left blank');
            }

            //Get user Id
            List<User> userLst = [SELECT Id, Name FROM User WHERE Email = :userEmail];

            if ( userLst.isEmpty() ) {
                runningUser = null;
                throw new ConflictException('The provided userEmail, ' + userEmail + ' could not be matched to a user in Salesforce');
            } else {
                runningUser = userLst[0];
            }

            if ( String.isBlank(auctionNumber) ) {
                throw new BadRequestException('The auctionNumber parameter is required and cannot be left blank');
            }

            // Query for the Associated Title Case
            List<Case> associatedCaseLst = [SELECT Id, Status, Auction_Number__r.Id
                                            FROM Case
                                            WHERE Auction_Number_Searchable__c = :auctionNumber
                                            AND RecordTypeId = :TITLE_CASE_RT];

            if ( associatedCaseLst.isEmpty() ) {
                throw new ConflictException('There was an issue trying to retrieve a case with the given auction number. This could be due to ' +
                                            'the record lacking the proper recordtype, not being open in the system, or because the auction number isn\'t accurate');
            } else if( associatedCaseLst.size() > 1 ) {
                throw new ConflictException('When attempting to retrieve a single case with the given auction number, ' +
                                            associatedCaseLst.size() + ' cases were located instead');
            } else if( associatedCaseLst.size() == 1 && associatedCaseLst[0].Status != 'New') {
                auctionCase = associatedCaseLst[0];
                throw new ConflictException('The case status is "' + associatedCaseLst[0].Status +'" instead of "New"');
            }

            auctionCase = associatedCaseLst[0];
            auctionCase.Title_Scanner__c = runningUser.Id;
            auctionCase.Status = 'Received';
            auctionCase.Image_Location__c = s3url;
            auctionCase.Title_Scanned_Time__c = timeStamp;
            auctionCase.Title_Received_Date__c = Date.today();
            auctionCase.Batch_Id__c = batchId;
            FieldHistoryProcess.overwriteUserId = runningUser.Id;
            auctionCase.Title_State__c = titleStateFullname;
            update auctionCase;

            processResponse(200, new APIResponse(auctionNumber, userEmail, 'Success', s3url), auctionCase.Id);
        } catch( BadRequestException exc ) {
            processResponse(400, new APIResponse(auctionNumber, userEmail, exc.getMessage(), s3url), null);
        } catch( ConflictException exc ) {
            processResponse(409, new APIResponse(auctionNumber, userEmail, exc.getMessage() ,s3url), null);
            if (auctionCase != null) {
                TitlesAutomationAPI.insertExc( 'Auction Number: ' + auctionNumber + '. ' + exc.getMessage() , auctionCase, runningUser, s3url, batchId, 'Inbound', titleStateFullname );
            }
        } catch( ValidationException exc ) {
            processResponse(500, new APIResponse(auctionNumber, userEmail, exc.getMessage() ,s3url), auctionCase.Id);
        }catch( Exception exc) {
            processResponse(500, new APIResponse(auctionNumber, userEmail, (exc.getMessage() + ' ' + exc.getStackTraceString()), s3url), null);
            TitlesAutomationAPI.insertExc( exc.getMessage(), auctionCase, runningUser, s3url, batchId, 'Inbound', titleStateFullname );
        }
    }

    
    private static void processResponse(Integer statusCode, TitlesReceivedAPI.APIResponse apiResponse, String caseId) {
        RestResponse response = RestContext.response;
        response.statusCode = statusCode;
        response.responseBody = Blob.valueOf( JSON.serialize(apiResponse));
    }

    global class APIResponse{
        public OriginalRequest originalRequest;
        public String returnMessage;

        public APIResponse(String auctionNumber, String userEmail, String message, String s3url) {
            this.originalRequest = new originalRequest(auctionNumber, userEmail, s3url);
            this.returnMessage = message;
        }
    }
    global class OriginalRequest {
        public String auctionNumber;
        public String userEmail;
        public String s3url;
        public OriginalRequest( String auctionNumber, String userEmail, String s3url ) {
            this.auctionNumber = auctionNumber;
            this.userEmail = userEmail;
            this.s3url = s3url;
        }
    }
    private class BadRequestException extends Exception{}
    private class ConflictException extends Exception{}
    private class ValidationException extends Exception{}
}