objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/CaliforniaBadgeLogic.cls
/**
 * Trigger Class to check for Major Account Badge Eligiblity
 * @author James Andre LaCour
 * @since Aug 10th, 2021
 */
public class CaliforniaBadgeLogic extends BadgeBannerInterface {
    /**
     * String containing the 2 character abbrivation for California
     */
    private final String CALIFORNIA_ABBRIEVATION = 'CA'; 
    /**
     * String Containing the name of California
     */
    private final String CALIFORNIA_NAME = 'California';
    /**
     * returns true or false based on if the Account is from California
     * @param badgeDeveloperName - developer name of the custom metadata that drives this badge
     * @param recordId - recordId the LWC is running on
     * @return  `Boolean` - whether or not recordId has this badge
     */
    public override Boolean checkLogic( String badgeDeveloperName, Id recordId ){
        String thisAccountState = '';
        // California Logic -  If the BillingState on Account = CA or California
        switch on badgeDeveloperName {
            when 'California_Seller_Case'{
                List<Case> cseList = [ SELECT Id, Seller_Dealership__c, Seller_Dealership__r.BillingState FROM Case WHERE Id = :recordId LIMIT 1 ];
                if( !cseList.isEmpty() ) thisAccountState = cseList[0].Seller_Dealership__r?.BillingState;
            }
            when 'California_Seller_Auction'{
                List<Auction__c> auctionList = [ SELECT Id, Seller_Dealership__c, Seller_Dealership__r.BillingState FROM Auction__c WHERE Id = :recordId LIMIT 1 ];
                if( !auctionList.isEmpty() ) thisAccountState = auctionList[0].Seller_Dealership__r?.BillingState;
            }
        }
        return thisAccountState.equalsIgnoreCase(CALIFORNIA_ABBRIEVATION) || thisAccountState.equalsIgnoreCase(CALIFORNIA_NAME);
    }
}