objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EngineAudioPlayerComponent.cls
public class EngineAudioPlayerComponent {
    
    @AuraEnabled(cacheable=true)
    public static string getAudioLink(String caseId){
      List<Case> caseList = [select id, Auction_Number__r.vehicle_id__r.Vin__c from case where id = :caseId];
      Case currentCase = new Case();
      if(caseList.size() == 1){
          currentCase = caseList[0];
      }

      return callOutToAudioLink(currentCase.Auction_Number__r.vehicle_id__r.Vin__c);
    }

    public static String callOutToAudioLink(String Vin){
        Http h = new Http();

        HttpRequest req = new HttpRequest();
        req.setEndPoint('https://ent-micro-audio-prod.acvauctions.com/audio/vin/'+Vin+'/');
        req.setMethod('GET');
        req.setHeader('Authorization','-1:14f1b7dda4a834c711c52a72b003f744');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept','application/json');
        req.setHeader('X-Frame-Options','SAMEORIGIN');
        req.setTimeout(60000);

        HttpResponse res = h.send(req);

        if(res.getStatusCode() == 200){
            system.debug(res.getBody());
            EngineAudioParser eap = EngineAudioParser.parse(res.getBody());
            return eap.data.audio_files[0].Link;
        }
        else{
            system.debug('error from Audio End Point');
            throw new CustomException('Issue Getting Audio: '+res.getStatusCode()+' '+res.getStatus());   
        }
    }
}