objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ACV_Titles_External_ID__c</fullName>
        <description>external id to identify title cases</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Titles External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Buyer_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record for the buyer, person who will get delivery of vehicle</description>
        <label>Buyer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Buyer Dealership)</relationshipLabel>
        <relationshipName>Buyer_Transportation_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Title_Information</fullName>
        <active>true</active>
        <businessProcess>Title Information Process</businessProcess>
        <description>Use this record type to process a title.</description>
        <label>Title Information</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WisconsinBadgeLogicTest.cls
/**
 * Test Class for WisconsinBadgeLogic
 * @author James Andre LaCour
 * @since Aug 12th, 2021
 */
@isTest
public class WisconsinBadgeLogicTest {
    /********************Test Data Setup*************************/
    /**
     * Creates Data needed for Test Methods
     * @return void
     */
    @TestSetup
    public static void makeData(){
        Account acct = TestUtility.createAccount('Test Dealership');
        acct.BillingState = 'WI';
        insert acct;
        Contact con = TestUtility.createContact(acct);
        insert con;
        Vehicle__c veh = TestUtility.createVehicle();
        insert veh;
        Auction__c auc = TestUtility.createAuction(acct, con, veh);
        auc.Buyer_Dealership__c = acct.Id;
        auc.Seller_Dealership__c = acct.Id;
        insert auc;
        Case cse = TestUtility.createCase(auc, veh, acct, con);
        cse.Type = 'Titles';
        cse.AccountId = acct.Id;
        cse.Seller_Dealership__c = acct.Id;
        cse.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Title_Information').getRecordTypeId();
        cse.ACV_Titles_External_ID__c = '12345';
        insert cse;
    }
    /********************Test Methods****************************/
    /**
     * Test the WI badge on the Account record
     * @return void
     */
    public static testMethod void accountTest(){
        List<Account> acctList = [ SELECT Id FROM Account LIMIT 1 ];
        System.assertEquals( 1, acctList.size() );
        Test.startTest();
            Boolean eligilbeBadge = new WisconsinBadgeLogic().checkLogic( 'Wisconsin_Account', acctList[0].Id );
        Test.stopTest();
        System.assertEquals( true, eligilbeBadge );
    }
    /**
     * Test the WI Badge on the case record
     * @return void
     */
    public static testMethod void caseTest(){
        List<Case> caseList = [ SELECT Id FROM Case LIMIT 1 ];
        System.assertEquals( 1, caseList.size() );
        Test.startTest();
            Boolean eligilbeBadge = new WisconsinBadgeLogic().checkLogic( 'Wisconsin_Case', caseList[0].Id );
        Test.stopTest();
        System.assertEquals( true, eligilbeBadge );
    }
    /**
     * Test the WI badge on the Auction record for Seller and Buyer Dealership
     * @return void
     */
    public static testMethod void auctionTest(){
        List<Auction__c> aucList = [ SELECT Id FROM Auction__c LIMIT 1 ];
        System.assertEquals( 1, aucList.size() );
        Test.startTest();
            Boolean eligilbeBadgeSeller = new WisconsinBadgeLogic().checkLogic( 'Wisconsin_Auction_Seller', aucList[0].Id );
            Boolean eligilbeBadgeBuyer = new WisconsinBadgeLogic().checkLogic( 'Wisconsin_Auction_Buyer', aucList[0].Id );
        Test.stopTest();
        System.assertEquals( true, eligilbeBadgeSeller );
        System.assertEquals( true, eligilbeBadgeBuyer );
    }
}