objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>payment_method__c</fullName>
        <description>Integrated field.</description>
        <label>Buyer Payment Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payment_status__c</fullName>
        <description>Integrated field.</description>
        <label>Buyer Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Deposited</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>hold_on_file</fullName>
                    <label>Hold On File</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>payment_pending</fullName>
                    <label>Payment Pending</label>
                </value>
                <value>
                    <fullName>payment_returned</fullName>
                    <label>Payment Returned</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Recorded</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>refund_pending</fullName>
                    <label>Refund Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>ta_hold</fullName>
                    <label>TA Hold</label>
                </value>
                <value>
                    <fullName>ta_on_file</fullName>
                    <label>TA On File</label>
                </value>
                <value>
                    <fullName>to_be_floored</fullName>
                    <label>To Be Floored</label>
                </value>
                <value>
                    <fullName>to_be_picked_up</fullName>
                    <label>To Be Picked Up</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hold_For_Payment__c</fullName>
        <description>Developed as part of the Digital Titles process in response to COVID19 State Closures</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Hold For Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Auction_Number__r.payment_method__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buyer Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>TEXT(Auction_Number__r.payment_status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buyer Payment Status</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Title_Information</fullName>
        <active>true</active>
        <businessProcess>Title Information Process</businessProcess>
        <description>Use this record type to process a title.</description>
        <label>Title Information</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/TitleCheckForAuctionPayment.cls
public class TitleCheckForAuctionPayment extends TriggerInterface{
    
    public override void afterUpdate(Map<Id,Sobject> oldMap, Map<Id,sObject> newMap){
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Title_Information').getRecordTypeId();
        Map<Id, Auction__c> newAuctionMap = (Map<Id, Auction__c>)newMap;
        Map<Id, Auction__c> oldAuctionMap = (Map<Id, Auction__c>)oldMap;
        List<Case> caseUpdateList = new List<Case>();

        List<Id> auctionIdList = new List<Id>();
        for(Auction__c a :newAuctionMap.values()){
            // Compare Payment Status and ensure auction is paid for
            if(a.payment_status__c != oldAuctionMap.get(a.id).payment_status__c && TitlesShippingAutomation.isPaidFor(a.payment_status__c, a.payment_method__c)){
                auctionIdList.add(a.id);
            }
        }

        if(auctionIdList.size() > 0){
            // Clear the Hold for Payment field
            for(Case c :[select id, Hold_For_Payment__c from Case where Auction_Number__c in :auctionIdList AND recordTypeId = :recordTypeId AND Hold_For_Payment__c != null]){
                c.Hold_For_Payment__c = null;
                caseUpdateList.add(c);
            }
        }

        if(caseUpdateList.size() > 0){
            update caseUpdateList;
        }
    }
}