objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>buyer_dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate the buying dealer at auction.</description>
        <label>Buyer Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>High Bid at Auction</relationshipLabel>
        <relationshipName>BuyerAuctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auction_Relaunch_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Auction ID for the relaunched auction</description>
        <label>Auction Relaunch ID</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases (Auction Relaunch ID)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/AccountMergeDependentRecordCheck.cls
public with sharing class AccountMergeDependentRecordCheck {
    

    public static Boolean AccountMergeDependentRecordCheck(Account Acc) {

        Boolean auctionFound = false;
        Boolean caseFound = false;
        if(Acc.Auctions__r.size() > 0 || Acc.BuyerAuctions__r.size() > 0){
            auctionFound = true;
        }
        if(Acc.Cases.size() > 0 || Acc.Cases1__r.size() > 0){
            caseFound = true;
        }
        if(auctionFound || caseFound){
            return true;
        }
        return false; 
    }
}