objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by Integration to indicate who provided the vehicle for the auction</description>
        <label>Seller Dealership</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Launched at Auction</relationshipLabel>
        <relationshipName>Auctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Seller_Dealership__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Title_Clerk_Email__c</fullName>
        <description>Populated via code to push the most recently created contact on the selling dealership&apos;s account that has a title of Title Clerk.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Seller Title Clerk Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Title_Picklist__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Title Clerk</fullName>
                </value>
                <value>
                    <fullName>Used Car Manager</fullName>
                </value>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Selling Rep</fullName>
                </value>
                <value>
                    <fullName>Buying Rep</fullName>
                </value>
                <value>
                    <fullName>Transport Manager</fullName>
                </value>
                <value>
                    <fullName>TrueFrame Billing Contact</fullName>
                </value>
                <value>
                    <fullName>TF Report Contact</fullName>
                </value>
                <value>
                    <fullName>Lotsweep Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dealership_Contact</fullName>
        <active>true</active>
        <description>This Contact record is for Dealership contacts that do not have login access to the acv app</description>
        <label>Dealership Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/updateSellerTitleClerkEmailTest.cls
@isTest
public class updateSellerTitleClerkEmailTest {
    public static  Id conDealershipRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Dealership_Contact').getRecordTypeId();

        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
       Account accRec = TestUtility.createAccount('Acc Test');
        insert accRec ;
        
        Contact conRec1 = TestUtility.createContact(accRec);
        insert conRec1;
        
        Vehicle__c vehcRec = TestUtility.createVehicle();
        insert vehcRec;
        
        Auction__c auctionRec = TestUtility.createAuction(accRec,conRec1, vehcRec);
        insert auctionRec;
        
         Case titleInfoCaseRec = TestUtility.createTitleCase(auctionRec,accRec,conRec1);
        titleInfoCaseRec.Seller_Dealership__c = accRec.Id;
        titleInfoCaseRec.Status = 'New';
        insert titleInfoCaseRec;
         
    }
    
    @isTest
    static void testAfterInsert(){
      
        Account accrec = [select id from Account Limit 1];
        
        Contact conRec = TestUtility.createContact(accRec);
        conRec.Title_Picklist__c = 'Title Clerk';
        conRec.RecordTypeId = conDealershipRecTypeId;
        insert conRec;
         
        
        Case caseRec = [Select Id,Seller_Title_Clerk_Email__c,Seller_Dealership__c from Case Limit 1];
        system.assertEquals(caseRec.Seller_Title_Clerk_Email__c, conRec.Email);
        system.assertEquals(caseRec.Seller_Dealership__c, conRec.AccountId);
    }
    @isTest
    static void testNegativeAfterInsert(){
        
        Account accrec = [select id from Account Limit 1];
        Contact conRec = TestUtility.createContact(accRec);
        conRec.Title_Picklist__c = 'Accounting';
        conRec.RecordTypeId = conDealershipRecTypeId;
        insert conRec;
         
        
        Case caseRec = [Select Id,Seller_Title_Clerk_Email__c,Seller_Dealership__c from Case Limit 1];
        system.assertNotEquals(caseRec.Seller_Title_Clerk_Email__c, conRec.Email);
        system.assertEquals(caseRec.Seller_Dealership__c, conRec.AccountId);
    }
     @isTest
    static void testAfterUpdate(){
        
     
        Account accrec = [select id from Account Limit 1];

        
        Contact conRec = TestUtility.createContact(accRec);
        conRec.Title_Picklist__c = 'Accounting';
        conRec.RecordTypeId = conDealershipRecTypeId;
        insert conRec;
        
        conRec.Title_Picklist__c = 'Title Clerk';
        update conRec;
        
        Case caseRec = [Select Id,Seller_Title_Clerk_Email__c,Seller_Dealership__c from Case Limit 1];
        system.assertEquals(caseRec.Seller_Title_Clerk_Email__c, conRec.Email);
        system.assertEquals(caseRec.Seller_Dealership__c, conRec.AccountId);
    }
     @isTest
    static void testNegativeAfterUpdate(){
        
       
       Account accrec = [select id from Account Limit 1];
        
        Contact conRec = TestUtility.createContact(accRec);
        conRec.Title_Picklist__c = 'Title Clerk';
        conRec.RecordTypeId = conDealershipRecTypeId;
        insert conRec;
         
        conRec.Title_Picklist__c = 'Accounting';
        update conRec;
        
        Case caseRec = [Select Id,Seller_Title_Clerk_Email__c,Seller_Dealership__c from Case Limit 1];
        system.assertNotEquals(caseRec.Seller_Title_Clerk_Email__c, conRec.Email);
        system.assertEquals(caseRec.Seller_Dealership__c, conRec.AccountId);
    }
}