objects/Auction__c.object
<CustomObject>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>First_Arbitration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is checked if this arbitration case is the first such case related to the associated dealer.</description>
        <inlineHelpText>This is checked automatically if this arbitration case is the first such case related to the associated dealer.</inlineHelpText>
        <label>First Arbitration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetFirstArbitrationTest.cls
@isTest
public class SetFirstArbitrationTest {
    
    @isTest
    static void testSetFirstArb(){ 
        Account a = TestUtility.createAccount();
        insert a;
        Contact c = TestUtility.createContact(a);
        insert c;
        Vehicle__c v = TestUtility.createVehicle();
        insert v;
        Auction__c au = TestUtility.createAuction(v);
        insert au;

        Test.startTest();
        Case firstArbCase = TestUtility.createCase(au,v,a,c);
        firstArbCase.Description='first';
        insert firstArbCase;

        Case titleCase = TestUtility.createTitleCase(au, a, c);
        insert titleCase;

        Case secondArbCase = TestUtility.createCase(au,v,a,c);
        secondArbCase.Description='second';
        insert secondArbCase;
        Test.stopTest();

        List<Case> arbCases = [SELECT Id, First_Arbitration__c, Description FROM Case];
        for(Case cs : arbCases){
            if(cs.Description == 'first'){
                System.assertEquals(true,cs.First_Arbitration__c,'First Arbitration should set to true when first arb logged on account');
            }
            else if(cs.Description == 'second') {
                System.assertEquals(false,cs.First_Arbitration__c,'First Arbitration should remain false when not first arb logged on account');
            }
            else {
                // assert title case is not changed
                System.assertEquals(false,cs.First_Arbitration__c,'First Arbitration should not be set on a title case');
            }
        }
    }
}