objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>awaiting_acceptance</fullName>
                    <label>Awaiting Acceptance</label>
                </value>
                <value>
                    <fullName>counter_accepted</fullName>
                    <label>Counter Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_accepted</fullName>
                    <label>Counter Original Accepted</label>
                </value>
                <value>
                    <fullName>counter_original_declined</fullName>
                    <label>Counter Original Declined</label>
                </value>
                <value>
                    <fullName>counter_sent</fullName>
                    <label>Counter Sent</label>
                </value>
                <value>
                    <fullName>ended_accepted</fullName>
                    <label>Ended Accepted</label>
                </value>
                <value>
                    <fullName>ended_declined</fullName>
                    <label>Ended Declined</label>
                </value>
                <value>
                    <fullName>ended_killed</fullName>
                    <label>Ended Killed</label>
                </value>
                <value>
                    <fullName>ended_nobid</fullName>
                    <label>Ended No Bid</label>
                </value>
                <value>
                    <fullName>ended_unwound</fullName>
                    <label>Ended Unwound</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>staging</fullName>
                </value>
                <value>
                    <fullName>Preview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Auctions</relationshipLabel>
        <relationshipName>VehicleAuction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>VIN__c</fullName>
        <formula>Vehicle__r.vin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vehicle_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate a vehicle to a condition report review case record</description>
        <label>VIN</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (VIN)</relationshipLabel>
        <relationshipName>VehicleCRR</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Arbitration_Claim</fullName>
        <active>true</active>
        <businessProcess>Arbitration Claim Process</businessProcess>
        <description>Use this record type to process an arbitration claim.</description>
        <label>Arbitration Claim</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Condition_Report_Prescreen__c.object
<CustomObject>
    <fields>
        <fullName>Previous_Auction_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current VIN has been sold in an auction on our platform before.</description>
        <label>Previous Auction Run</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previously_Arbitrated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current VIN has been arbitrated on our platform before.</description>
        <label>Previously Arbitrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <formula>Vehicle__r.id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Report Prescreen</relationshipLabel>
        <relationshipName>Condition_Report_Prescreen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vin__c</fullName>
        <formula>IF( OR(ISBLANK(Condition_Report__c),ISBLANK(Condition_Report__r.VIN__c)),  Inspection_Data_VIN__c , Condition_Report__r.VIN__c)</formula>
        <label>Vin #</label>
        <type>Text</type>
    </fields>
    <label>Condition Report Prescreen</label>
    <nameField>
        <displayFormat>CRR-{0000000}</displayFormat>
        <label>Condition Report Prescreen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Report Prescreen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VehicleSoldOrArbedPreviously.cls
public class VehicleSoldOrArbedPreviously extends TriggerInterface {
    public override void beforeInsert(List<sObject> newList) {
        List<Condition_Report_Prescreen__c> newPreList = (List<Condition_Report_Prescreen__c>)newList;
        Map<String, Case> arbCaseMap = new Map<String, Case>();
        Map<String, Auction__c> auctionsMap = new Map<String, Auction__c>();
        Set<String> vinSet = new Set<String>();
        for (Condition_Report_Prescreen__c c : newPreList) {
            if (c.Vin__c != null) {
                vinSet.add(c.Vin__c);
            }
        }

        if (!vinSet.isEmpty()) {
            auctionsMap = queryAuctions(vinSet, auctionsMap);
            if (!auctionsMap.isEmpty()) { //if there are no auctions, no need to look for arbs, saves a query and a loop. also don't need to assess the checkboxes because they would be false
                arbCaseMap = queryCases(vinSet, arbCaseMap);
                assessCheckboxes(auctionsMap, arbCaseMap, newPreList);
            }
        }
    }

    public static Map<String, Auction__c> queryAuctions(Set<String> vinSet, Map<String, Auction__c> auctionsMap) {
        List<Auction__c> auctions = [SELECT Id, Vehicle_Id__r.Vin__c FROM Auction__c WHERE Vehicle_Id__r.Vin__c IN :vinSet];
        if (!auctions.isEmpty()) {
            for (Auction__c a : auctions) {
                if (auctionsMap.get(a.Vehicle_Id__r.Vin__c) == null) {
                    auctionsMap.put(a.Vehicle_Id__r.Vin__c, a);
                } //if the vin is already mapped to an auction, i don't need to do anything else
            }
        }
        return auctionsMap;
    }

    public static Map<String, Case> queryCases(Set<String> vinSet, Map<String, Case> arbCaseMap) {
        List<Case> arbCases = [SELECT Id, Vehicle__r.Vin__c FROM Case WHERE RecordType.DeveloperName = 'Arbitration_Claim' AND Vehicle__r.Vin__c IN :vinSet];
        if (!arbCases.isEmpty()) {
            for (Case c : arbCases) {
                if (arbCaseMap.get(c.Vehicle__r.Vin__c) == null) {
                    arbCaseMap.put(c.Vehicle__r.Vin__c, c);
                } //if the vin is already mapped to a case, i don't need to do anything else
            }
        }
        return arbCaseMap;
    }

    public static List<Condition_Report_Prescreen__c> assessCheckboxes(Map<String, Auction__c> auctionsMap, Map<String, Case> arbCaseMap, List<Condition_Report_Prescreen__c> crpList) {
        List<Condition_Report_Prescreen__c> returnList = new List<Condition_Report_Prescreen__c>();
        if ((auctionsMap != null && arbCaseMap != null) && (!auctionsMap.isEmpty() || !arbCaseMap.isEmpty())) {
            for (Condition_Report_Prescreen__c p : crpList) {
                Boolean crChanged = false;
                if (p.Status__c != 'Closed') {
                    if (auctionsMap.get(p.Vin__c) != null && auctionsMap.get(p.Vin__c).Vehicle_Id__r.Vin__c != null) {
                        p.Previous_Auction_Run__c = true;
                        crChanged = true;
                    }
                    if (arbCaseMap.get(p.Vin__c) != null && arbCaseMap.get(p.Vin__c).Vehicle__r.Vin__c != null) {
                        p.Previously_Arbitrated__c = true;
                        crChanged = true;
                    }
                    if(crChanged){
                        returnList.add(p);
                    }
                }
            }
        }
        return returnList;
    }
}