objects/Auction__c.object
<CustomObject>
    <fields>
        <fullName>end_time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>payment_method__c</fullName>
        <description>Integrated field.</description>
        <label>Buyer Payment Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payment_status__c</fullName>
        <description>Integrated field.</description>
        <label>Buyer Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Deposited</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>hold_on_file</fullName>
                    <label>Hold On File</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>payment_pending</fullName>
                    <label>Payment Pending</label>
                </value>
                <value>
                    <fullName>payment_returned</fullName>
                    <label>Payment Returned</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Recorded</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>refund_pending</fullName>
                    <label>Refund Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>ta_hold</fullName>
                    <label>TA Hold</label>
                </value>
                <value>
                    <fullName>ta_on_file</fullName>
                    <label>TA On File</label>
                </value>
                <value>
                    <fullName>to_be_floored</fullName>
                    <label>To Be Floored</label>
                </value>
                <value>
                    <fullName>to_be_picked_up</fullName>
                    <label>To Be Picked Up</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Odometer_Reading__c</fullName>
        <description>Odometer Reading written by a flow, with information pulled from the vehicle record</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Odometer Reading</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>Auction_Number__r.payment_method__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buyer Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <formula>TEXT(Auction_Number__r.payment_status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buyer Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (as Seller)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Display_Related_Fields__mdt.object
<CustomObject>
    <description>Settings for Display Related Fields LWC.</description>
    <label>Display Related Fields Setting</label>
    <pluralLabel>Display Related Fields Settings</pluralLabel>
</CustomObject>

objects/Quality_Control__c.object
<CustomObject>
    <fields>
        <fullName>Auction__c</fullName>
        <formula>Case__r.Auction_Number_Case__c</formula>
        <label>Auction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Quality Control</relationshipLabel>
        <relationshipName>Quality_Control</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quality Control</label>
    <nameField>
        <displayFormat>QC-{000000}</displayFormat>
        <label>QC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DisplayRelatedFieldsControllerTest.cls
/**
 * @description A supporting component that is used by DisplayRelatedFields LWC. 
 * 				DisplayRelatedFields LWC is used to display related fields in the specified order.
 * 				Requirements: https://acvauctions.atlassian.net/browse/TDO-473
 * 
 *              It is using 'Unit_Tests' record in Display_Related_Fields__mdt Custom Metadata.
 * 
 * @author Manmeet Vaseer
 * @date 09/24/2021
 * 
 */
@isTest
public class DisplayRelatedFieldsControllerTest {

    @isTest
    static void testGetFieldLabelValuePairs()	{
        Test.startTest();
                
        String acctUniqueName = 'Test EasyPostControllerTest';
        Account newAcct = TestUtility.createAccount(acctUniqueName);        
        Contact newContact = TestUtility.createContact(newAcct);
        Vehicle__c newVehicle = TestUtility.createVehicle();
        
        Auction__c newAuction = TestUtility.createAuction(newAcct, newContact, newVehicle);
        newAuction.end_time__c = System.today();
        newAuction.Payment_Status__c='Paid';
        newAuction.Payment_Method__c = 'adi';

        SObject[] newObjs = new SObject[] {newAcct, newContact, newVehicle, newAuction};
        insert newObjs;
        
		Case newTitleCase = TestUtility.createTitleCase(newAuction, newAcct, newContact);
        newTitleCase.Odometer_Reading__c = '123467';
        newTitleCase.AccountId = newAcct.Id;
		newTitleCase.Seller_Contact__c = newContact.Id;
        newTitleCase.Status = 'New';
        
        newObjs = new SObject[] {newTitleCase};
        insert newObjs;
        
        Quality_Control__c qc = new Quality_Control__c();
        qc.Case__c = newTitleCase.Id;
        insert qc;

        Test.stopTest();
        
        String recId = qc.Id;
        String metadataTypeRecName='Unit_Tests';
        String json = DisplayRelatedFieldsController.getFieldLabelValuePairs(recId, metadataTypeRecName);
        System.assert(!String.isBlank(json));
        
        List<DisplayRelatedFieldsController.Payload> fieldLableValuePairs = (List<DisplayRelatedFieldsController.Payload>)System.JSON.deserialize(json, List<DisplayRelatedFieldsController.Payload>.class);
        System.assertEquals(21, fieldLableValuePairs.size(), 'Total number of Label=Value pairs are incorrect.');
        Integer totalProcessed = 0;
        for(DisplayRelatedFieldsController.Payload pl : fieldLableValuePairs)	{
            if(pl.label == 'Odometer') {
                System.assertEquals(newTitleCase.Odometer_Reading__c, pl.value);
                totalProcessed = totalProcessed + 1;
            }
            else if(pl.label == 'Payment Status') {
                System.assertEquals(newAuction.Payment_Status__c, pl.value);
                totalProcessed = totalProcessed + 1;
            }
            else if(pl.label == 'Payment Method') {
                System.assertEquals(newAuction.Payment_Method__c, pl.value);
                totalProcessed = totalProcessed + 1;
            }
            else if(pl.label == 'Buyer Billing Street') {
                System.assertEquals(newAcct.BillingStreet, pl.value);
                totalProcessed = totalProcessed + 1;
            }
            else if(pl.label == 'Seller Contact Name') {
                System.assertEquals(newContact.firstName + ' ' + newContact.lastName, pl.value);
                totalProcessed = totalProcessed + 1;
            }
        }

        System.assertEquals(5, totalProcessed, 'Incorrect number of totalProcessed values.');        
    }
}