objects/Auction__c.object
<CustomObject>
    <label>Auction</label>
    <nameField>
        <label>Auction Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Arb_Close_Date_for_Titles__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Arb Close Date for Titles</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Should be automatically populated by entering the Auction relationship - either via API integration or by a Process Builder.</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Arbitration_Claim</fullName>
        <active>true</active>
        <businessProcess>Arbitration Claim Process</businessProcess>
        <description>Use this record type to process an arbitration claim.</description>
        <label>Arbitration Claim</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ArbitrationCasetitleCloseDateHandlerTest.cls
@isTest
public class ArbitrationCasetitleCloseDateHandlerTest {
    @isTest
    static void testAfterUpdate(){
    
        Account accRec = TestUtility.createAccount('Acc Test');
        insert accRec ;
        
        Contact conRec = TestUtility.createContact(accRec);
        insert conRec;
        
        Vehicle__c vehcRec = TestUtility.createVehicle();
        insert vehcRec;
        
        Auction__c auctionRec = TestUtility.createAuction(accRec,conRec, vehcRec);
        insert auctionRec;
        
        Case titleInfoCaseRec = TestUtility.createTitleCase(auctionRec,accRec,conRec);
        insert titleInfoCaseRec;
        
      //  Id arbrecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Arbitration_Claim').getRecordTypeId();
        Case arbCaseRec = TestUtility.createCase(auctionRec,vehcRec,accRec,conRec);
      //  arbCaseRec.RecordTypeId = arbrecordTypeId;
        insert arbCaseRec;
        
        arbCaseRec.Status = 'Closed';
        update arbCaseRec;
        
        system.assertEquals(arbCaseRec.Auction_Number__c, titleInfoCaseRec.Auction_Number__c);
        system.assertEquals(arbCaseRec.ClosedDate, titleInfoCaseRec.Arb_Close_Date_for_Titles__c);
    }
}