objects/Case.object
<CustomObject>
    <fields>
        <fullName>Arb_Close_Date_for_Titles__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Arb Close Date for Titles</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Auction_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auction Number</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Arbitration_Claim</fullName>
        <active>true</active>
        <businessProcess>Arbitration Claim Process</businessProcess>
        <description>Use this record type to process an arbitration claim.</description>
        <label>Arbitration Claim</label>
    </recordTypes>
    <recordTypes>
        <fullName>Title_Information</fullName>
        <active>true</active>
        <businessProcess>Title Information Process</businessProcess>
        <description>Use this record type to process a title.</description>
        <label>Title Information</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/ArbitrationCasetitleCloseDateHandler.cls
public class ArbitrationCasetitleCloseDateHandler extends TriggerInterface {
    
    /* This method is used to update "Arb Close Date for Titles" field on Titile Information Case when 
		its associated Auction Number's Arbitration Claim Case record is Closed. */
    public override void afterUpdate(Map<Id,SObject> oldMap, Map<Id,SObject> newMap){
        
        Map<Id,Case> caseIdToNewCase = (Map<Id,Case>)newMap;
        Map<Id,Case> caseIdToOldCase = (Map<Id,Case>)oldMap;
        Map<Id, Datetime> auctionIdToCloseDate = new Map<Id, Datetime>();
        List<Case> casesToUpdate = new List<Case>();
        Id arbrecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Arbitration_Claim').getRecordTypeId();
        Id titleRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Title_Information').getRecordTypeId();
        
        
        for(Case caseRec : caseIdToNewCase.values()){
            if(caseRec.RecordTypeId == arbrecordTypeId &&
               caseRec.Status != caseIdToOldCase.get(caseRec.Id).Status &&
               (caseRec.Status.contains('Closed') || caseRec.Status.contains('Not Arbitration')) &&
               caseRec.Auction_Number__c != NULL &&
               caseRec.ClosedDate != NULL)
            {
                auctionIdToCloseDate.put(caseRec.Auction_Number__c ,caseRec.ClosedDate);
            }
        }
        if(!auctionIdToCloseDate.isEmpty()){
            for(Case tfCase : [Select Id,
                               Status,
                               Auction_Number__c,
                               Arb_Close_Date_for_Titles__c 
                               FROM Case 
                               WHERE RecordTypeId =: titleRecordTypeId 
                               AND Auction_Number__c IN :auctionIdToCloseDate.keySet()]
                
               ){
                   if(auctionIdToCloseDate.containsKey(tfCase.Auction_Number__c)){
                       tfCase.Arb_Close_Date_for_Titles__c = auctionIdToCloseDate.get(tfCase.Auction_Number__c);
                       casesToUpdate.add(tfCase);
                   }
               }
        }
        if(!casesToUpdate.isEmpty()){
            update casesToUpdate;
        }
    }
}