objects/Case.object
<CustomObject>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <description>The Batch Id generated by the Titles Cron when a title is sent to the entitled-beta inbox from a user scanning it. It uses the current time, user, scanner, and current date. Primarily used to mass assign titles to a specific user.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Inbound Batch Id</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Location__c</fullName>
        <description>Location of Title Image</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Image Location</label>
        <length>1028</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Exception__c.object
<CustomObject>
    <description>Details regarding exceptions that relate to custom integrations to Salesforce.</description>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <description>The Batch Id generated when the Title was scanned. Combination of the user id in the Titles CRON, the scanner Id, current date, and current time</description>
        <label>Batch Id</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Images_Location__c</fullName>
        <description>S3 Bucket Folder location for JPEG images</description>
        <label>Images Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case that this Exception relates to</description>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Exceptions</relationshipLabel>
        <relationshipName>Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CopyBatchIdFromExceptionToCase.cls
public class CopyBatchIdFromExceptionToCase extends TriggerInterface{
    
    public override void beforeUpdate(Map<Id, SObject> oldMap,Map<Id, SObject> newMap){
        Map<Id, Exception__c> newEMap = (Map<Id,Exception__c>)newMap;
        Map<Id, Exception__c> oldEMap = (Map<Id,Exception__c>)oldMap;
        List<Case> caseUpdateList = new List<Case>();

        for(Exception__c e :newEMap.values()){
            if(e.Related_Case__c != oldEMap.get(e.id).Related_Case__c && (e.Batch_Id__c != null || e.Images_Location__c != null)){
                if(e.Related_Case__c != null){
                    caseUpdateList.add(new Case(Id = e.Related_Case__c, Batch_Id__c = e.Batch_Id__c, Image_Location__c = e.Images_Location__c));
                }
                //handle someone screwing up and putting in the wrong case, then going back to correct it
                if(oldEMap.get(e.id).Related_Case__c != null){
                    caseUpdateList.add(new Case(Id = oldEMap.get(e.id).Related_Case__c, Batch_Id__c = null));
                }
            }
        }

        if(caseUpdateList.size() > 0){
            update caseUpdateList;
        }
    }

    /** beforeInsert
     *  Update the Batch Id of the Related Case if the Batch Id is present on the Exception
     */
    public override void beforeInsert(List<SObject> newList){
        List<Exception__c> excList = (List<Exception__c>)newList;
        List<Case> caseUpdateList = new List<Case>();

        for (Exception__c exc : excList) {
            if (exc.Related_Case__c != null && (exc.Batch_Id__c != null || exc.Images_Location__c != null)) {
                caseUpdateList.add(new Case(Id = exc.Related_Case__c, Batch_Id__c = exc.Batch_Id__c, Image_Location__c = exc.Images_Location__c));
            }
        }

        if (caseUpdateList.size() > 0) {
            update caseUpdateList;
        }
    }
}