objects/Case.object
<CustomObject>
    <fields>
        <fullName>ACV_Titles_External_ID__c</fullName>
        <description>external id to identify title cases</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Titles External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Damaged_Title__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of the Title problems set.</description>
        <label>Damaged Title</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Incorrect_Vehicle_Information_on_Title__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of the Titles Problem set.</description>
        <inlineHelpText>Available options include: VIN and Year, Make, Model</inlineHelpText>
        <label>Incorrect Vehicle Information on Title</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Missing_Notary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Missing Notary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Missing_Signature__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Available options include: Original Owner and Seller</inlineHelpText>
        <label>Missing Signature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Odometer_Discrepancy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Available options include: Branded on the Front, Written and Separate Reassignment</description>
        <inlineHelpText>Available options include: Branded on the Front, Written and Separate Reassignment</inlineHelpText>
        <label>Odometer Discrepancy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reassigned_to_Wrong_Purchaser__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of the Titles problems set.</description>
        <inlineHelpText>Available options include: Reassigned to ACV, Incorrect Address and Incorrect Name</inlineHelpText>
        <label>Reassigned to Wrong Purchaser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reassignment_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of the Titles problems set.</description>
        <inlineHelpText>Available options include: Wrong VIN on Reassignment, Not Included, Dated Incorrectly and Buyer Signature Missing From Prior Reassignment</inlineHelpText>
        <label>Reassignment Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Problem_Subset__c</fullName>
        <description>This field is populated by the New QC flow and related to the QC object related to associated case record</description>
        <inlineHelpText>These are the problem subsets related to this case - to add additional problem subsets use the Report Problem button at the top of the page or reach out to titles.</inlineHelpText>
        <label>Title Problem Subset</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <label>Address - Write over</label>
                </value>
                <value>
                    <fullName>B</fullName>
                    <label>Branded on the Front of Title - Odom Discr.</label>
                </value>
                <value>
                    <fullName>Buyer Requested Duplicate - ACV at Fault</fullName>
                </value>
                <value>
                    <fullName>Buyer Requested Duplicate - Buyer at Fault</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                    <label>Damaged Title</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Dated Incorrectly on Reassignment</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Date - Write over</label>
                </value>
                <value>
                    <fullName>Dealer Stamp Used Instead of Notary</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                    <label>Incorrect Name - Wrong Purchaser</label>
                </value>
                <value>
                    <fullName>H</fullName>
                    <label>Mileage - Write over</label>
                </value>
                <value>
                    <fullName>Missing Death / Marriage / Divorce Certificate</fullName>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>Missing Lien Release</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>Missing Notary</label>
                </value>
                <value>
                    <fullName>Missing One and the Same</fullName>
                </value>
                <value>
                    <fullName>Missing Owner POA</fullName>
                </value>
                <value>
                    <fullName>More Recently Issued Title</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Name - Write over</label>
                </value>
                <value>
                    <fullName>K</fullName>
                    <label>Original Owner Missing Signature</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Reassigned to ACV - Wrong Purchaser</label>
                </value>
                <value>
                    <fullName>J</fullName>
                    <label>Reassignment not Included</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>Separate Reassignment Odom Discr.</label>
                </value>
                <value>
                    <fullName>Undisclosed application for title</fullName>
                </value>
                <value>
                    <fullName>Undisclosed Non-Titled Vehicle</fullName>
                </value>
                <value>
                    <fullName>W</fullName>
                    <label>Undisclosed Repossession Paperwork</label>
                </value>
                <value>
                    <fullName>Q</fullName>
                    <label>VIN Incorrect on Reassignment</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>VIN Incorrect on Title</label>
                </value>
                <value>
                    <fullName>P</fullName>
                    <label>Written Odom Discr.</label>
                </value>
                <value>
                    <fullName>S</fullName>
                    <label>Year, Make, or Model Incorrect on Reassignment</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Year, Make, or Model Incorrect on Title</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Buyer Signature Missing from Prior Reassignment</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>Seller Missing Signature &amp; Missing ACV POA</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Incorrect Address on Reassignment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Write_Overs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of the Titles problem set.</description>
        <inlineHelpText>Available options include: Name, Address, Date and Mileage</inlineHelpText>
        <label>Write-Overs</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/TitleCaseFieldValidationTest.cls
// TODO: Remove this class along with TitleCaseFieldValidation (trigger handler)
@isTest
public class TitleCaseFieldValidationTest {
    @isTest
    static void bogus(){
    }
    
    /*
    @isTest
    static void insertTestCase1() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase1 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = false, Missing_Notary__c = true, ACV_Titles_External_ID__c='123');

        System.runAs( u ) {
            try {
                insert testCase1;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Incorrect Vehicle Information on Title to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void insertTestCase2() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase2 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'B', Odometer_Discrepancy__c = false, Missing_Notary__c = true, ACV_Titles_External_ID__c='124');
    
        System.runAs( u ) {
            try {
                insert testCase2;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Odometer Discrepancy to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void insertTestCase3() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase3 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'M', Missing_Signature__c = false, Missing_Notary__c = true, ACV_Titles_External_ID__c='125');
        
        System.runAs( u ) {
            try {
                insert testCase3;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Missing Signature to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void insertTestCase4() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase4 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'E', Reassignment_Error__c = false, Missing_Notary__c = true, ACV_Titles_External_ID__c='126');
        
        System.runAs( u ) {
            try {
                insert testCase4;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Reassignment Errors to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void insertTestCase5() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase5 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'D', Write_Overs__c = false, Missing_Notary__c = true, ACV_Titles_External_ID__c='127');
       
        System.runAs( u ) {
            try {
                insert testCase5;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Write-Overs to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void insertTestCase6() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase6 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'G', Reassigned_To_Wrong_Purchaser__c = false, Missing_Notary__c = true, ACV_Titles_External_ID__c='128');
        
        System.runAs( u ) {
            try {
                insert testCase6;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Reassigned to Wrong Purchaser to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void insertTestCase7() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase7 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Damaged_Title__c = true, ACV_Titles_External_ID__c='129');
        
        System.runAs( u ) {
            try {
                insert testCase7;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Please fill out the Title Problem Subset values related to your Primary Problem checkboxes' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }
       

    @isTest
    static void updateTestCase1() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase1 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='129');
        insert testCase1;
        testCase1.Title_Problem_Subset__c = 'B';

        System.runAs( u ) {
            try {
                update testCase1;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Odometer Discrepancy to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void updateTestCase2() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase2 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='131');
        insert testCase2;
        testCase2.Title_Problem_Subset__c = 'K';

        System.runAs( u ) {
            try {
                update testCase2;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Missing Signature to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void updateTestCase3() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase3 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='132');
        insert testCase3;
        testCase3.Title_Problem_Subset__c = 'Q';

        System.runAs( u ) {
            try {
                update testCase3;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Reassignment Errors to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void updateTestCase4() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase4 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='133');
        insert testCase4;
        testCase4.Title_Problem_Subset__c = 'I';

        System.runAs( u ) {
            try {
                update testCase4;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Write-Overs to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }

    @isTest
    static void updateTestCase5() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase5 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='134');
        insert testCase5;
        testCase5.Title_Problem_Subset__c = 'F';

        System.runAs( u ) {
            try {
                update testCase5;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Reassignment Errors to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }
       @isTest
    static void updateTestCase6() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase6 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='135');
        insert testCase6;
        testCase6.Title_Problem_Subset__c = 'U';

        System.runAs( u ) {
            try {
                update testCase6;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains('Your Title Problem Subset values require Missing Lien release to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }
      @isTest
    static void updateTestCase7() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase7 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='136');
        insert testCase7;
        testCase7.Title_Problem_Subset__c = 'V';

        System.runAs( u ) {
            try {
                update testCase7;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset values require Damaged Title to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }
     @isTest
    static void updateTestCase8() {
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [ SELECT Id FROM Profile WHERE Name='Standard User' ];
        User u = new User(
            Alias = 'standt', Email='standarduser@testorg.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/New_York',
            UserName=uniqueUserName
        );

        Id titlesRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Case testCase8 = new Case(recordTypeId = titlesRecordType, Status = 'Problem', Origin = 'Phone', Title_Problem_Subset__c = 'O', Incorrect_Vehicle_Information_on_Title__c = true, ACV_Titles_External_ID__c='137');
        insert testCase8;
        testCase8.Title_Problem_Subset__c = 'W';

        System.runAs( u ) {
            try {
                update testCase8;
                system.assert( false, 'This message indicates an error was not thrown when expected!' );
            } catch(exception e) {
                system.assert( 
                    e.getMessage().contains( 'Your Title Problem Subset Values require Listing Error to be selected.' ), 
                    'The error message thrown was unexpected: ' + e.getMessage()
                );
            }
        }
    }
*/
}