objects/Case.object
<CustomObject>
    <fields>
        <fullName>ACV_Titles_External_ID__c</fullName>
        <description>external id to identify title cases</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Titles External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case_guid__c</fullName>
        <description>GUID generated in Salesforce to identify this unique Case Record across Datahub systems</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Case guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>Field used for integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Arbitration ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Unwind</fullName>
        <active>true</active>
        <businessProcess>Unwind Process</businessProcess>
        <description>Record type to process unwinds</description>
        <label>Unwind</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Complaint__c.object
<CustomObject>
    <description>A child object of Case to be used in arbitration claims process to log the complaints that accompany a claim.</description>
    <fields>
        <fullName>arbitration_id__c</fullName>
        <description>Stores the reference to the Arbitration case.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>The external ID for this complaint from ACV DB.</description>
        <externalId>true</externalId>
        <label>id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>valid__c</fullName>
        <description>Field used by Resolution Validation Rule.  Field is required in order to resolve complaint</description>
        <inlineHelpText>Field is required in order to resolve complaint</inlineHelpText>
        <label>Valid</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>AC-{0000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Resolution__c.object
<CustomObject>
    <description>An object for use in the Arbitration Claims process to identify the resolution of a claim.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount should be entered for all valid complaint resolutions with the exception of &quot;ACV to Re-List&quot;</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Field will be set by Process Builder that makes a direct reference between a Resolution record and a its Parent Complaint&apos;s Case record. Assists in rolling up data for reporting purposes.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <description>A field to identify the arbitration administrator&apos;s resolution decision.</description>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>ACV Credit Assigned</fullName>
                </value>
                <value>
                    <fullName>ACV Issue Check</fullName>
                </value>
                <value>
                    <fullName>ACV To Re-List</fullName>
                </value>
                <value>
                    <fullName>Seller Issue Check</fullName>
                </value>
                <value>
                    <fullName>Unwound Back To Seller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>complaint_id__c</fullName>
        <description>Stores a reference to the parent Complaint that a Resolution is for.</description>
        <label>Complaint</label>
        <referenceTo>Complaint__c</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>External Id for this resolution from ACV DB.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resolution</label>
    <nameField>
        <displayFormat>ACR-{0000000}</displayFormat>
        <label>Resolution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resolutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

classes/CaseGuidGenerationTest.cls
@istest
public with sharing class CaseGuidGenerationTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Id arbrecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Arbitration Claim').getRecordTypeId();
        Id titleRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Title Information').getRecordTypeId();
        Id unwindRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Unwind').getRecordTypeId();


        Account a = new Account(Name='test account');
        insert a;
        Contact c = new Contact(FirstName = 'test', LastName='Contact', AccountId = a.id);
        insert c;
        Case ca = new Case(AccountId = a.id, ContactId = c.id, id__c = '1', RecordTypeId = arbrecordTypeId);
        insert ca;
        Case ca2 = new Case(AccountId = a.id, ContactId = c.id, id__c = '2', ACV_Titles_External_ID__c = '123', RecordTypeId = titlerecordTypeId);
        insert ca2;
        Case ca3 = new Case(AccountId = a.id, ContactId = c.id, id__c = '3', RecordTypeId = unwindrecordTypeId);
        insert ca3;
        Complaint__c com = new Complaint__c(arbitration_id__c = ca.id, valid__c = 'yes');
        insert com;
        Resolution__c r = new Resolution__c(Case__c = ca.id, complaint_id__c = com.id,amount__c = 600.00);
        insert r;
    }
    public static testMethod void TestCaseGuidGenerationUponInsert(){
        Case newCas = [SELECT ID, Case_guid__c FROM Case Where id__c = '1'];
        System.Debug([SELECT ID, Case_guid__c FROM Case Where id__c = '1']);
        System.assert(newCas.Case_guid__c != null, 'Guid null when it shouldnt be');      
    }
    public static testMethod void TestCaseGuidGenerationUponUpdate(){
        Case newCase = [SELECT ID, Case_guid__c FROM Case Where id__c = '2'];
        newCase.Case_guid__c = null;
        update newCase;
        newCase = [SELECT ID, Case_guid__c, id__c FROM Case Where id__c = '2' LIMIT 1];
        System.assert(newCase.Case_guid__c != null, 'Guid null when it shouldnt be');      
    }
    public static testMethod void TestBADCaseGuidGenerationUponInsert(){
        Case newCa = [SELECT ID, Case_guid__c FROM Case Where id__c = '3'];
        System.Debug([SELECT ID, Case_guid__c FROM Case Where id__c = '3']);
        System.assertEquals(null, newCa.Case_guid__c);     
    }
    public static testMethod void TestCaseGuidUponUpdate(){
        Case oldCase = [SELECT id__c, ID, Case_guid__c FROM Case Where id__c = '2'];        
        update oldCase;
        Case updatedCase = [SELECT id__c, ID, Case_guid__c FROM Case Where id__c = '2' LIMIT 1];        
        System.assert(oldCase.Case_guid__c == updatedCase.Case_guid__c, 'Guid is not the same after update');      
    }
}