objects/Case.object
<CustomObject>
    <fields>
        <fullName>id__c</fullName>
        <description>Field used for integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Arbitration ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Complaint__c.object
<CustomObject>
    <description>A child object of Case to be used in arbitration claims process to log the complaints that accompany a claim.</description>
    <fields>
        <fullName>arbitration_id__c</fullName>
        <description>Stores the reference to the Arbitration case.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>The external ID for this complaint from ACV DB.</description>
        <externalId>true</externalId>
        <label>id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>valid__c</fullName>
        <description>Field used by Resolution Validation Rule.  Field is required in order to resolve complaint</description>
        <inlineHelpText>Field is required in order to resolve complaint</inlineHelpText>
        <label>Valid</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <displayFormat>AC-{0000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Resolution__c.object
<CustomObject>
    <description>An object for use in the Arbitration Claims process to identify the resolution of a claim.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount should be entered for all valid complaint resolutions with the exception of &quot;ACV to Re-List&quot;</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Field will be set by Process Builder that makes a direct reference between a Resolution record and a its Parent Complaint&apos;s Case record. Assists in rolling up data for reporting purposes.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <description>A field to identify the arbitration administrator&apos;s resolution decision.</description>
        <label>Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>ACV Credit Assigned</fullName>
                </value>
                <value>
                    <fullName>ACV Issue Check</fullName>
                </value>
                <value>
                    <fullName>ACV To Re-List</fullName>
                </value>
                <value>
                    <fullName>Seller Issue Check</fullName>
                </value>
                <value>
                    <fullName>Unwound Back To Seller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_guid__c</fullName>
        <description>GUID generated in Salesforce to identify this unique Resolution Record across Datahub systems</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Resolution guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>complaint_id__c</fullName>
        <description>Stores a reference to the parent Complaint that a Resolution is for.</description>
        <label>Complaint</label>
        <referenceTo>Complaint__c</referenceTo>
        <relationshipLabel>Resolutions</relationshipLabel>
        <relationshipName>Resolutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <description>External Id for this resolution from ACV DB.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resolution</label>
    <nameField>
        <displayFormat>ACR-{0000000}</displayFormat>
        <label>Resolution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resolutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerHandler__mdt.object
<CustomObject>
    <label>TriggerHandler</label>
    <pluralLabel>TriggerHandlers</pluralLabel>
</CustomObject>

classes/ResolutionGuidGenerationTest.cls
@istest
public with sharing class ResolutionGuidGenerationTest {
        @TestSetup
    static void makeData() {
        TriggerFramework.mockMetaData = new List<TriggerHandler__mdt>();
        Account a = new Account(Name='test account');
        insert a;
        Contact c = new Contact(FirstName = 'test', LastName='Contact', AccountId = a.id);
        insert c;
        Case ca = new Case(AccountId = a.id, ContactId = c.id);
        insert ca;
        Complaint__c com = new Complaint__c(arbitration_id__c = ca.id, valid__c = 'yes');
        insert com;
        Resolution__c r = new Resolution__c(Case__c = ca.id, complaint_id__c = com.id,amount__c = 600.00, id__c = '1');
        insert r;
        Resolution__c r2 = new Resolution__c(Case__c = ca.id, complaint_id__c = com.id,amount__c = 666.00, id__c = '2');
        insert r2;
    }
    public static testMethod void TestResolutionGuidGenerationUponInsert(){
        Resolution__c newRes = new Resolution__c();
        newRes = [SELECT ID, Resolution_guid__c FROM Resolution__c Where id__c = '1'];
        System.Debug([SELECT ID, Resolution_guid__c FROM Resolution__c Where id__c = '1']);
        System.assert(newRes.Resolution_guid__c != null, 'Guid null when it shouldnt be');      
    }
    public static testMethod void TestResolutionGuidGenerationUponUpdate(){
        Resolution__c newReso = new Resolution__c();
        newReso = [SELECT ID, Resolution_guid__c, amount__c FROM Resolution__c Where id__c = '2'];
        newReso.Resolution_guid__c = null;
        update newReso;
        newReso = [SELECT ID, Resolution_guid__c, amount__c, id__c FROM Resolution__c Where id__c = '2' LIMIT 1];
        System.assert(newReso.Resolution_guid__c != null, 'Guid null when it shouldnt be');      
    }
}