objects/Condition_Report__c.object
<CustomObject>
    <description>This object receives fields from the condition_report, condition_report_document and saved_auctions tables in ACV Tools.</description>
    <fields>
        <fullName>Inspection_Guid__c</fullName>
        <description>Inspection Guid generated for SIA records</description>
        <label>Inspection Guid</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report</label>
    <nameField>
        <label>Condition Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Report_Prescreen__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Report</label>
        <referenceTo>Condition_Report__c</referenceTo>
        <relationshipName>Condition_Report_Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inspection_Id__c</fullName>
        <description>Inspection GUID</description>
        <externalId>true</externalId>
        <label>Inspection Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Report Prescreen</relationshipLabel>
        <relationshipName>Condition_Report_Prescreen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report Prescreen</label>
    <nameField>
        <displayFormat>CRR-{0000000}</displayFormat>
        <label>Condition Report Prescreen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Report Prescreen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LinkCRToPrescreen.cls
public class LinkCRToPrescreen extends TriggerInterface{
    
    public override void afterInsert(Map<Id, SObject> newMap){
        Map<Id, Condition_Report__c> tempCrMap = (Map<Id, Condition_Report__c>)newMap;
        Map<String, Condition_Report__c> newCrMap = new Map<String, Condition_Report__c>();

        for(Condition_Report__c cr :tempCrMap.values()){
            if(!String.isBlank(cr.Inspection_Guid__c)){
                newCrMap.put(cr.Inspection_Guid__c, cr);
            }
        }

        List<Condition_Report_Prescreen__c> prescreenUpdateList = new List<Condition_Report_Prescreen__c>();

        for(Condition_Report_Prescreen__c crp :[SELECT ID, Vehicle__c, Condition_Report__c,Inspection_Id__c FROM Condition_Report_Prescreen__c WHERE Inspection_Id__c IN :newCrMap.keySet()]){
            if(newCrMap.get(crp.Inspection_Id__c) != null){
                if(!String.isBlank(newCrMap.get(crp.Inspection_Id__c).Vehicle__c)){
                    crp.Vehicle__c = newCrMap.get(crp.Inspection_Id__c).Vehicle__c;
                }
                
                crp.Condition_Report__c = newCrMap.get(crp.Inspection_Id__c).Id;
                prescreenUpdateList.add(crp);
            }
        }

        if(prescreenUpdateList.size() > 0){
            update prescreenUpdateList;
        }
    }
}