objects/Condition_Report__c.object
<CustomObject>
    <description>This object receives fields from the condition_report, condition_report_document and saved_auctions tables in ACV Tools.</description>
    <fields>
        <fullName>Awaiting_Floor_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CR has been reviewed and Floor price has been populated with &lt;20 value or +999999</description>
        <label>Awaiting Floor Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CR_Doc_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>condition_report_document.launchable</description>
        <label>CR Doc Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CR_in_review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked once CR Doc complete but floor price is null</description>
        <label>CR in review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <label>Floor Price</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <description>saved_auctions.vin</description>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report</label>
    <nameField>
        <label>Condition Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssignmentManagerVehicleUpdate.cls
public class AssignmentManagerVehicleUpdate extends TriggerInterface{

    private final static String STANDARD_INSPECTION = 'Standard Inspection';

    // public override void afterInsert(Map<Id, SObject> newMap){
    //     System.Debug(Trigger.newMap);
    //     System.debug(Trigger.oldMap);
    //     updateRelatedVehicleAndEvent(newMap.values());
    //     checkForReadyToLaunch(newMap.values(), null, FALSE);//(Map<Id, sObject>)new Map<Id,Condition_Report__c>(), FALSE);
    // }

    // public override void afterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap){
    //     checkForReadyToLaunch(newMap.values(), oldMap, TRUE);
    // }

    // public static void updateRelatedVehicleAndEvent(List<sObject> triggerNew){
    //     List<Condition_Report__c> crList = (List<Condition_Report__c>)triggerNew;

    //     Map<String,Condition_Report__c> vinIdSet = new Map<String,Condition_Report__c>();
    //     for(Condition_Report__c cr :crList){
    //         system.debug(cr);
    //         if(!String.isBlank(cr.VIN__c)){
    //             vinIdSet.put(cr.VIN__c.toUpperCase(), cr);
    //         }
    //     }

    //     List<WorkOrderLineItem> vinUpdateList = new List<WorkOrderLineItem>();
    //     for(WorkOrderLineItem v :[SELECT Id, Status, VIN__c, Vehicle__c FROM WorkOrderLineItem WHERE VIN__c IN :vinIdSet.keySet() AND Status = 'New' AND WorkType.Name = :STANDARD_INSPECTION]){
    //         if(!String.isBlank(v.VIN__c)){
    //             v.Status = 'In Progress';
    //             v.Vehicle__c = vinIdSet.get(v.VIN__c.toUpperCase()).Vehicle__c;
    //             vinUpdateList.add(v);
    //         }
    //     }

    //     if(vinUpdateList.size() > 0){
    //         update vinUpdateList;
    //     }
    // }

    // public static void checkForReadyToLaunch(List<sObject> newList, Map<Id, sObject> oldMap, Boolean isUpdate){
    //     //List<sObject> triggerNew
    //     List<Condition_Report__c> crList = (List<Condition_Report__c>)newList;
    //     Map<Id, Condition_Report__c> oldCRMap = (Map<Id, Condition_Report__c>)oldMap;

    //     Map<String, Condition_Report__c> vinToCr = new Map<String, Condition_Report__c>();
    //     Map<String, Condition_Report__c> oldVinMap = new Map<String, Condition_Report__c>();
    //     if (isUpdate) {
    //         for(Condition_Report__c cr :crList){
    //             if(!String.isBlank(cr.VIN__c)){
    //                 vinToCr.put(cr.VIN__c.toUpperCase(), cr);
    //                 oldVinMap.put(cr.VIN__c.toUpperCase(), oldCRMap.get(cr.Id)); //???
    //             }
    //         }
    //     }
    //     else {
    //         for (Condition_Report__c cr : crList) {
    //             if(!String.isBlank(cr.VIN__c)){
    //                 vinToCr.put(cr.VIN__c.toUpperCase(), cr);
    //             }
    //         }
    //     }

    //     //Map<Id, Condition_Report__c> newCRMap = (Map<Id, Condition_Report__c>)newMap;
    //     //Map<Id, Condition_Report__c> oldCRMap = (Map<Id, Condition_Report__c>)oldMap;

    //     List<WorkOrderLineItem> vinUpdateList = new List<WorkOrderLineItem>();
    //     for(WorkOrderLineItem v :[SELECT Id, Status, Vin__c FROM WorkOrderLineItem WHERE Vin__c IN :vinToCr.keyset() AND WorkType.Name = :STANDARD_INSPECTION]){
    //         Boolean touched = false;
    //         if(!String.isBlank(v.VIN__c)){
    //             if (isUpdate && oldVinMap.get(v.VIN__c.toUpperCase()) != null) {
    //                 if(oldVinMap.get(v.VIN__c.toUpperCase()).CR_Doc_Complete__c != vinToCr.get(v.VIN__c.toUpperCase()).CR_Doc_Complete__c){
    //                     v.Status = 'Inspected';
    //                     touched = true;
    //                 }
    //                 else if(oldVinMap.get(v.VIN__c.toUpperCase()).CR_in_Review__c != vinToCr.get(v.VIN__c.toUpperCase()).CR_in_Review__c){
    //                     v.Status = 'Internal Review';
    //                     touched = true;
    //                 }
    //                 else if(oldVinMap.get(v.VIN__c.toUpperCase()).Awaiting_Floor_Price__c != vinToCr.get(v.VIN__c.toUpperCase()).Awaiting_Floor_Price__c){
    //                     v.Status = 'Awaiting Floor Price';
    //                     touched = true;
    //                 }
    //                 else if((oldVinMap.get(v.VIN__c.toUpperCase()).Floor_Price__c != vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c) && (vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c > 20 || vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c != 999999)){ //vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c != null &&
    //                     v.Status = 'Ready To Launch';
    //                     touched = true;
    //                 }
    //             }
    //             else if(vinToCr.get(v.VIN__c.toUpperCase()) != null) {
    //                 if (vinToCr.get(v.VIN__c.toUpperCase()).CR_Doc_Complete__c) {
    //                     v.Status = 'Inspected';
    //                     touched = true;
    //                 }
    //                 else if (vinToCr.get(v.VIN__c.toUpperCase()).CR_in_Review__c) {
    //                     v.Status = 'Internal Review';
    //                     touched = true;
    //                 }
    //                 else if (vinToCr.get(v.VIN__c.toUpperCase()).Awaiting_Floor_Price__c) {
    //                     v.Status = 'Awaiting Floor Price';
    //                     touched = true;
    //                 }
    //                 else if (vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c != null && (vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c > 20 || vinToCr.get(v.VIN__c.toUpperCase()).Floor_Price__c != 999999)) {
    //                     v.Status = 'Ready To Launch';
    //                     touched = true;
    //                 }
    //             }
    //         }
    //         if(touched){
    //             vinUpdateList.add(v);
    //         }
    //     }

    //     if(vinUpdateList.size() > 0){
    //         system.debug(vinUpdateList);
    //         update vinUpdateList;
    //     }
    // }


}