objects/Condition_Report_Prescreen__c.object
<CustomObject>
    <fields>
        <fullName>CR_Review_Timeout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is checked if 30 minutes has elapsed since creation and no review has been completed.</description>
        <label>CR Review Timeout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CR_Update_by_pre_Screener__c</fullName>
        <description>Changes made to the CR by Pre-Screener field needs to be filled out to close the case. There is also a validation rule to verify this is filled in before closing the record.</description>
        <label>CR Update by pre-Screener</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Condition Report Prescreen</label>
    <nameField>
        <displayFormat>CRR-{0000000}</displayFormat>
        <label>Condition Report Prescreen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Report Prescreen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Prescreen_Reason__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report_Prescreen__c</fullName>
        <label>Condition Report Prescreen</label>
        <referenceTo>Condition_Report_Prescreen__c</referenceTo>
        <relationshipLabel>Prescreen Reasons</relationshipLabel>
        <relationshipName>Prescreen_Reasons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prescreen Reason</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Prescreen Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescreen Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Prescreen_Reasons__mdt.object
<CustomObject>
    <fields>
        <fullName>Include_For_Time_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include For Time Out</label>
        <type>Checkbox</type>
    </fields>
    <label>Prescreen Reasons</label>
    <pluralLabel>Prescreen Reasons</pluralLabel>
</CustomObject>

classes/PrescreenClosingScheduler.cls
global class PrescreenClosingScheduler extends SchedulingInterface{

    private static final String ARB_GUARD_PRESCREEN_REASON_NAME = 'Arb Guard';
    private static final String AMP_ML_PRESCREEN_REASON_NAME = 'AMP ML';
    private static final String PRESCREEN_STATUS_NEW = 'New';
    private static final String PRESCREEN_STATUS_CLOSED = 'Closed';
    private static final String PRESCREEN_CLOSING_SCHEDULER = 'PrescreenClosingScheduler';

    public override void executeScheduledLogic(){
        System.enqueueJob(new PrescreenClosingSchedulerQueuable());
    }

    public class PrescreenClosingSchedulerQueuable implements Queueable{
		
		public void execute(QueueableContext context) {
            System.debug('PrescreenClosingScheduler start');

            List<Prescreen_Reasons__mdt> allowedReasons = [SELECT MasterLabel FROM Prescreen_Reasons__mdt WHERE Include_For_Time_Out__c = TRUE];
            
            Set<String> reasonNames = new Set<String>();
            for(Prescreen_Reasons__mdt reason : allowedReasons){ reasonNames.add(reason.MasterLabel); }

            List<Condition_Report_Prescreen__c> prescreensToClose = new  List<Condition_Report_Prescreen__c>();

            List<Condition_Report_Prescreen__c> existingPrescreens = [SELECT Id, OwnerId, CreatedDate,
                                                                            (select Id, Name from Prescreen_Reasons__r where Name IN: reasonNames) 
                                                                    FROM  Condition_Report_Prescreen__c 
                                                                    WHERE Status__c =: PRESCREEN_STATUS_NEW
                                                                    FOR UPDATE];

            Datetime now = Datetime.now();

            for(Condition_Report_Prescreen__c prescreen : existingPrescreens){
                Datetime creationDate = prescreen.CreatedDate;

                Decimal minutesBetween = Integer.valueOf((now.getTime() - creationDate.getTime())/(1000*60));

                if(minutesBetween >= 60 || (minutesBetween >= 30 && prescreen.Prescreen_Reasons__r.isEmpty()) ){
                    prescreensToClose.add(prescreen);
                }
            }

            for(Condition_Report_Prescreen__c prescreen: prescreensToClose){ 
                prescreen.Status__c = PRESCREEN_STATUS_CLOSED; 
                prescreen.CR_Update_by_pre_Screener__c = PRESCREEN_CLOSING_SCHEDULER;
                prescreen.CR_Review_Timeout__c = true;
            }
            
            if(!prescreensToClose.isEmpty()){ Database.update(prescreensToClose,false); }
            System.debug('PrescreenClosingScheduler end');
		}
        
        
        
	}
}