objects/Condition_Report__c.object
<CustomObject>
    <description>This object receives fields from the condition_report, condition_report_document and saved_auctions tables in ACV Tools.</description>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <label>Floor Price</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Reports</relationshipLabel>
        <relationshipName>Condition_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report</label>
    <nameField>
        <label>Condition Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Report_Prescreen__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Report</label>
        <referenceTo>Condition_Report__c</referenceTo>
        <relationshipName>Condition_Report_Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Report Prescreen</relationshipLabel>
        <relationshipName>Condition_Report_Prescreen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition Report Prescreen</label>
    <nameField>
        <displayFormat>CRR-{0000000}</displayFormat>
        <label>Condition Report Prescreen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Report Prescreen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/createPrescreenForDuplicateCR.cls
public class createPrescreenForDuplicateCR extends ClassInterface{
    
    public override List<SObject> handle(List<SObject> objList){
        return (List<SObject>)getCRsThatHaveSiblings((List<Condition_Report__c>)objList);
    }

    public List<Condition_Report__c> getCRsThatHaveSiblings(List<Condition_Report__c> crList){
        Map<Id, Condition_Report__c> vinIdtoCrMap = new Map<Id,Condition_Report__c>();
        List<Condition_Report__c> returnList = new List<Condition_Report__c>();
        List<Id> crIdList = new List<Id>();
        for(Condition_Report__c cr :crList){
                vinIdtoCrMap.put(cr.vehicle__c,cr);
                crIdList.add(cr.id);
        }
        if(vinIdtoCrMap.keySet().size() > 0){
            Map<Id,Condition_Report__c> crMap = new Map<Id,Condition_Report__c>(crList);
            //Filter Sub Query on CR Prescreen to not look at CR Ids in the CR List that we get passed
            for(vehicle__c v :[select id, (Select Id from Condition_Reports__r where Floor_Price__c > 0 AND createddate != TODAY AND ID NOT IN :crMap.keySet()), (select id from Condition_Report_Prescreen__r where Condition_Report__c IN :crIdList) from Vehicle__c where ID in :vinIdtoCrMap.keySet()]){
                if(v.Condition_Reports__r.size() > 0 && v.Condition_Report_Prescreen__r.size() == 0){
                    returnList.add(vinIdtoCrMap.get(v.id));
                }
            }
        }
        return returnList;
    }
}