objects/Condition_Report_Prescreen__c.object
<CustomObject>
    <fields>
        <fullName>Age_in_Minutes__c</fullName>
        <formula>if( NOT(ISPICKVAL(Status__c, &apos;Closed&apos;)) , 
if((NOW() - CreatedDate)*24*60 &lt;= 10, IMAGE(&quot;/resource/Green_Status_light&quot;,TEXT(NOW() - CreatedDate),32,32), 
if((NOW() - CreatedDate)*24*60 &gt; 10 &amp;&amp; (NOW() - CreatedDate)*24*60 &lt;= 15, IMAGE(&quot;/resource/Yellow_Status_Light&quot;,TEXT(NOW() - CreatedDate),32,32), 
if((NOW() - CreatedDate)*24*60 &gt; 15, IMAGE(&quot;/resource/Red_Status_Light&quot;,TEXT(NOW() - CreatedDate),32,32),null))), 

if(( Closed_Date__c - CreatedDate)*24*60 &lt;= 10, IMAGE(&quot;/resource/Green_Status_light&quot;,TEXT(Closed_Date__c - CreatedDate),32,32), 
if((Closed_Date__c - CreatedDate)*24*60 &gt; 10 &amp;&amp; (Closed_Date__c - CreatedDate)*24*60 &lt;= 15, IMAGE(&quot;/resource/Yellow_Status_Light&quot;,TEXT(Closed_Date__c - CreatedDate),32,32), 
if((Closed_Date__c - CreatedDate)*24*60 &gt; 15, IMAGE(&quot;/resource/Red_Status_Light&quot;,TEXT(Closed_Date__c - CreatedDate),32,32),null))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age in Minutes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_To_CR__c</fullName>
        <formula>IF( ISBLANK( Inspection_Id__c ),
HYPERLINK(&apos;https://app.acvauctions.com/saved/&apos;+Condition_Report__r.ACV_Saved_Auction_Id__c, Condition_Report__r.ACV_Saved_Auction_Id__c),
HYPERLINK(&apos;https://inspection-viewer.internal.acvauctions.com/inspections/&apos;+Inspection_Id__c, Inspection_Id__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Link To CR</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VCI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VCI</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Condition_Report_Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Condition Report Prescreen</relationshipLabel>
        <relationshipName>Condition_Report_Prescreen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vin__c</fullName>
        <formula>IF( OR(ISBLANK(Condition_Report__c),ISBLANK(Condition_Report__r.VIN__c)),  Inspection_Data_VIN__c , Condition_Report__r.VIN__c)</formula>
        <label>Vin #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>IF( OR(ISBLANK(Vehicle__c)),  Inspection_Data_Year__c , Text(Vehicle__r.Year__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Condition Report Prescreen</label>
    <nameField>
        <displayFormat>CRR-{0000000}</displayFormat>
        <label>Condition Report Prescreen Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Report Prescreen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CR_Review_Trigger__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prescreen_Reason__c</fullName>
        <label>Prescreen Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CR Review Trigger</label>
    <pluralLabel>CR Review Triggers</pluralLabel>
</CustomObject>

objects/Prescreen_Reason__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Report_Prescreen__c</fullName>
        <label>Condition Report Prescreen</label>
        <referenceTo>Condition_Report_Prescreen__c</referenceTo>
        <relationshipLabel>Prescreen Reasons</relationshipLabel>
        <relationshipName>Prescreen_Reasons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prescreen Reason</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Prescreen Reason Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescreen Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vin__c</fullName>
        <description>data to be replicated into the Vehicle VIN field</description>
        <externalId>true</externalId>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle VIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Year.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <customValue>
        <fullName>1992</fullName>
    </customValue>
    <customValue>
        <fullName>1991</fullName>
    </customValue>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

classes/CRQueueController.cls
public class CRQueueController {
    /**
     * getPrescreens Only meant to get the Prescreens where the owner is the 'CR Queue'
     * @return   return List<Condition_Report_Prescreen__c>
     */
    @AuraEnabled(cacheable = false)
    public static List<Condition_Report_Prescreen__c> getPrescreens(){
        return [Select Id, Name, Vehicle__r.VIN__c, Vehicle__c, Vehicle__r.Year__c,Link_To_CR__c, Age_in_Minutes__c, VIN__c, vci__r.Name, (Select Id, Name from Prescreen_Reasons__r) from Condition_Report_Prescreen__c where Status__c = 'New'];
    }

    
    /**
     * getCRReasons get all review trigger metadata records and get the prescreen reasons from them
     * @return   retruns a set of picklists to ensure we have single of each value
     */
    @AuraEnabled
    public static String getCRReasons(){
        Set<LWCUtility.picklist> reasonList = new Set<LWCUtility.picklist>();
        Set<String> reasonStringSet = new Set<String>();
        //List<CR_Review_Trigger__mdt> ruleList = [select id, Prescreen_Reason__c from CR_Review_Trigger__mdt];
        for(CR_Review_Trigger__mdt rule :[select id, Prescreen_Reason__c from CR_Review_Trigger__mdt where Active__c = True]){
            if(!String.isBlank(rule.Prescreen_Reason__c)){
                reasonStringSet.add(rule.Prescreen_Reason__c);
            }
        }
        for(String s :reasonStringSet){
            reasonList.add(new LWCUtility.picklist(s,s));
        }

        return JSON.serialize(reasonList);
        //return new List<LWCUtility.picklist>(reasonList);
    }
}