objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IST_Account_Manager_Email__c</fullName>
        <description>Email of the IST Account Manager</description>
        <formula>Account.IST_Account_Owner__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IST Account Manager Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Convert_Status__c</fullName>
        <formula>TEXT(Account.Lead_Convert_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Convert Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating if this Contact was created from a Lead</description>
        <label>Lead Created Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Policy_Email_Status__c</fullName>
        <description>This field is used for scheduling policy email with a delay.</description>
        <label>Policy Email Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Policy Email Not Sent</fullName>
                </value>
                <value>
                    <fullName>Send Policy Email</fullName>
                </value>
                <value>
                    <fullName>Policy Email Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SendDelayedPolicyEmailSchedulable.cls
/**
 * Schedulable class to send policy email upon custom lead conversion with a delay.
 * @author Jyothsna P
 * @since 09/24/21
 */
public class SendDelayedPolicyEmailSchedulable extends SchedulingInterface {

    private final Id acvuserRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('ACV User').getRecordTypeId();

    public SendDelayedPolicyEmailSchedulable(){
    }

    public override void executeScheduledLogic(){

        // Select contacts converted from org leads with 'Policy Email Sent' equal to 'false' 
        List<Contact> cList = [ SELECT Id, IST_Account_Manager_Email__c FROM Contact WHERE Lead_Convert_Status__c != '' 
                                and Lead_Created_Contact__c= true and RecordTypeid=:acvuserRecordTypeId and Policy_Email_Status__c='Policy Email Not Sent'];

        // update "Send Policy Email" to true. This is used in 'Organization Lead Converted Policy Email With Delay' work flow rule.                       
        for( Contact c : cList){  
            c.Policy_Email_Status__c= 'Send Policy Email';
        }

        update cList;
    }

}