objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Guid__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealership_Contact_Id__c</fullName>
        <description>Indicates the unique Dealership Contact Id for this Contact record. This field will be populated only for the Dealership Contact Record types</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Dealership Contact Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Used by Integration</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ACV Contact ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <description>acv_prod id found on the users table used to identify internal users</description>
        <externalId>true</externalId>
        <inlineHelpText>This corresponds to the User&apos;s ACV Tools ID</inlineHelpText>
        <label>ACV User Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContactGuidGeneration.cls
public class ContactGuidGeneration extends TriggerInterface {
    //TODO: Use utility method for recordType checks

    Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dealership Contact').getRecordTypeId();
    Id acvuserRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('ACV User').getRecordTypeId();

    public override void beforeInsert(List<sObject> objectList) {
    
        List<Contact> newContacts = (List<Contact>) objectList;
        
            for ( Contact newCon : newContacts ) {
                if (string.isBlank(newCon.Contact_Guid__c	) && (newCon.RecordTypeId == contactRecordTypeId ||  newCon.RecordTypeId == acvuserRecordTypeId) 
                && (newCon.Id__c != null || newCon.Dealership_Contact_Id__c != null)) {
                    newCon.Contact_Guid__c = ACVUtility.NewGuid();
                }
            }
    }
    public override void beforeUpdate(List<Sobject> oldList, List<Sobject> newlist){

        List<Contact> newConList = (List<Contact>)newlist;
        
            for ( Contact newCon : newConList ) {
                if (string.isBlank(newCon.Contact_Guid__c	) && (newCon.RecordTypeId == contactRecordTypeId ||  newCon.RecordTypeId == acvuserRecordTypeId) 
                && (newCon.Id__c != null || newCon.Dealership_Contact_Id__c != null)) {
                    newCon.Contact_Guid__c = ACVUtility.NewGuid(); 
                }
            }
    }
}