objects/Data_Schedule__c.object
<CustomObject>
    <description>Object that uses the trigger to create and delete cron apex jobs for the recurring data generator</description>
    <fields>
        <fullName>Day__c</fullName>
        <description>Day that the data generation should occur</description>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>How often does the data batch run</description>
        <label>Frequency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Horizon_Length__c</fullName>
        <description>How many x in the future to generate data</description>
        <label>Horizon Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Horizon_Type__c</fullName>
        <description>Number of &quot;type&quot; in the future</description>
        <label>Horizon Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Weeks</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Schedule</label>
    <nameField>
        <displayFormat>Sch{000}</displayFormat>
        <label>Data Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Day__c</fullName>
        <description>When Every is 1, select what day of the week for the occurrence</description>
        <label>Day of the Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>weekday</fullName>
                </value>
                <value>
                    <fullName>weekend day</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Every__c</fullName>
        <description>Space between the frequency. Every # frequency.</description>
        <label>Every</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Farthest_Date_Generated__c</fullName>
        <description>This field marks the date of the work order/service appointment that is scheduled the farthest into the future.</description>
        <inlineHelpText>The farthest date in the future that work is scheduled for.</inlineHelpText>
        <label>Farthest Date Generated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency that the event occurs</description>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The revolving appointment that this occurrence appears on</description>
        <label>Revolving Appointment</label>
        <referenceTo>Timeline__c</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <label>Week Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>first</fullName>
                </value>
                <value>
                    <fullName>second</fullName>
                </value>
                <value>
                    <fullName>third</fullName>
                </value>
                <value>
                    <fullName>fourth</fullName>
                </value>
                <value>
                    <fullName>fifth</fullName>
                </value>
                <value>
                    <fullName>last</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timeline__c.object
<CustomObject>
    <description>Object for defining a time period for creating recurring records</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date that the timeline ends. This can be left null for an indefinite timeline</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farthest_Date_Generated__c</fullName>
        <description>This is the date farthest in the future that any work order or service appointment generated by this revolving appointment has been scheduled</description>
        <inlineHelpText>Farthest date in the future a work order or service appointment has been scheduled from this revolving appointment.</inlineHelpText>
        <label>Farthest Date Generated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Day that the timeline begins</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Revolving Appointment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revolving Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RevolvingUtility.cls
public class RevolvingUtility {


    public static final Datetime NOW = (Datetime) System.today();
    public static final String DAY_OF_THE_WEEK = NOW.format('EEEE');
    public static final String DAY_OF_THE_MONTH = NOW.format('d');

    public static final String DATA_FREQUENCY_DAILY   = 'Daily';
    public static final String DATA_FREQUENCY_WEEKLY  = 'Weekly';
    public static final String DATA_FREQUENCY_MONTHLY = 'Monthly';

    public static final String DATA_HORIZON_DAYS   = 'Days';
    public static final String DATA_HORIZON_WEEKS  = 'Weeks';
    public static final String DATA_HORIZON_MONTHS = 'Months';

    public static Boolean isDaily(Data_Schedule__c schedule) {
        if(schedule.Frequency__c != null){
            return (schedule.Frequency__c == DATA_FREQUENCY_DAILY);
        }
        return null;
    }

    public static Boolean isWeeklyToday(Data_Schedule__c schedule) {
        if(schedule.Frequency__c != null && schedule.Day__c != null){
            return ((schedule.Frequency__c == DATA_FREQUENCY_WEEKLY) && (DAY_OF_THE_WEEK == schedule.Day__c));
        }
        return null;
    }

    public static Boolean isMonthlyToday(Data_Schedule__c schedule) {
        if(schedule.Frequency__c != null && schedule.Day__c != null){
            return ((schedule.Frequency__c == DATA_FREQUENCY_MONTHLY) && (DAY_OF_THE_MONTH == schedule.Day__c));
        }
        return null;
    }

    public static Date horizonDate(Date start, Data_Schedule__c schedule){
        Date horizon;
        if(schedule.Horizon_Length__c != null){
            if(schedule.Horizon_Type__c != null && schedule.Horizon_Type__c == DATA_HORIZON_DAYS){
                horizon = start.addDays(Integer.valueOf(schedule.Horizon_Length__c));
            }
            else if(schedule.Horizon_Type__c != null && schedule.Horizon_Type__c == DATA_HORIZON_WEEKS){
                horizon = start.addDays(Integer.valueOf(schedule.Horizon_Length__c)*7);
            }
            else if(schedule.Horizon_Type__c != null && schedule.Horizon_Type__c == DATA_HORIZON_MONTHS){
                horizon = start.addMonths(Integer.valueOf(schedule.Horizon_Length__c));
            }
        }
        return horizon;
    }

    public static List<String> processSaveResults(List<Database.SaveResult> results){
        //Id not accessible when insert fails
        List<String> errorMessages = new List<String>();

        if(results.size() > 0){

            Id resultId;
            String sObjName;
            Boolean recordInfoSet = false;
    
            for(Database.SaveResult result : results) {

                if(!recordInfoSet && result.getId() != null){
                    resultId = result.getId();
                    resultId.getSObjectType().getDescribe().getName();
                    recordInfoSet = true;
                }

                if(result.getErrors().size() > 0) {
                    String error = 'Error(s)';
                    if(recordInfoSet){
                        error += 'from ' + sObjName + ': ' + result.getId();
                    }
                    for(Database.Error err : result.getErrors()){
                        error += '\n<br>    --Error Message: ' + err.getMessage();
                        error += '\n<br>    ----Status Code: ' + err.getStatusCode();
                        error += '\n<br>    -Related Fields: ' + err.getFields();
                    }
                    errorMessages.add(error);
                }
            }
        }
        return errorMessages;
    }
    public static Set<Id> errorIdSet(List<Database.SaveResult> results){
        Set<Id> errorIds = new Set<Id>();
        if(results.size() > 0){
            for(Database.SaveResult result : results){
                if(result.getErrors().size() > 0){
                    errorIds.add(result.getId());
                }
            }
        }
        return errorIds;
    }

    public static List<String> processDeleteResults(List<Database.DeleteResult> results){
        List<String> errorMessages = new List<String>();
        if(results.size() > 0){
            Id resultId = results[0].getId();
            String sObjName = resultId.getSObjectType().getDescribe().getName();
    
            for(Database.DeleteResult result : results) {
                if(result.getErrors().size() > 0) {
                    String error = '<br>Error(s) from ' + sObjName + ': ' + result.getId();
                    for(Database.Error err : result.getErrors()){
                        error += '\n<br>    --Error Message: ' + err.getMessage();
                        error += '\n<br>    ----Status Code: ' + err.getStatusCode();
                        error += '\n<br>    -Related Fields: ' + err.getFields();
                    }
                    errorMessages.add(error);
                }
            }
        }
        return errorMessages;
    }
    public static Set<Id> errorIdSet(List<Database.DeleteResult> results){
        Set<Id> errorIds = new Set<Id>();
        if(results.size() > 0){
            for(Database.DeleteResult result : results){
                if(result.getErrors().size() > 0){
                    errorIds.add(result.getId());
                }
            }
        }
        return errorIds;
    }

    public static List<Date> getDatesFromOccurence(Occurrence__c occ, Date endDate){
        //endDate being how far into the future we are generating data for, will be determined by the batch
        List<Date> generationDates = new List<Date>();
        Date actualGenerationEndDate = (occ.Timeline__r.End_Date__c != null && occ.Timeline__r.End_Date__c < endDate) ? occ.Timeline__r.End_Date__c : endDate;
        Date startDate = (occ.Timeline__r.Start_Date__c > occ.Farthest_Date_Generated__c.date()) ? occ.Timeline__r.Start_Date__c : occ.Farthest_Date_Generated__c.date();
        if (occ.Frequency__c == DATA_FREQUENCY_WEEKLY){
            //do weekly generation
            String days = occ.Day__c;
            for (String day : days.split(';')){
                generationDates.addAll(tracDateUtils.getWeeklyEveryDayBetween(day, (Integer)occ.Every__c,startDate,actualGenerationEndDate));
            }
        }else if (occ.Frequency__c == DATA_FREQUENCY_MONTHLY){
            String days = occ.Day__c;
            if (occ.Week_Number__c == null){
                for (String day : days.split(';')){
                    generationDates.addAll(tracDateUtils.getMonthlyOnDay(Integer.valueOf(day) ,(Integer)occ.Every__c,startDate,actualGenerationEndDate));
                }
            }else{
                generationDates.addAll(tracDateUtils.getMonthlyEach(occ.Week_Number__c ,days,(Integer)occ.Every__c,startDate,actualGenerationEndDate));
            }
        }else if (occ.Frequency__c == DATA_FREQUENCY_DAILY){
            generationDates.addAll(tracDateUtils.getDailyEveryDayBetween((Integer) occ.Every__c,startDate,actualGenerationEndDate));
        }
        return generationDates;
    }
}