objects/Data_Schedule__c.object
<CustomObject>
    <description>Object that uses the trigger to create and delete cron apex jobs for the recurring data generator</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Schedule that is active. Only one record can be active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <description>Controls how many Occurrence records are processed in the batch at a time</description>
        <label>Batch Size</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>Day that the data generation should occur</description>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>How often does the data batch run</description>
        <label>Frequency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Run_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to invoke the batch to run</description>
        <inlineHelpText>Set to true and save to run the batch. Use sparingly!!!</inlineHelpText>
        <label>Run Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Data Schedule</label>
    <nameField>
        <displayFormat>Sch{000}</displayFormat>
        <label>Data Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/tracDataScheduleHandlerTest.cls
/**
 * @description ${DESCRIPTION}
 * @name tracDataScheduleHandlerTest
 * @author Daniel Labonte, Traction on Demand
 * @date 2019-09-05
 */

@IsTest
private class tracDataScheduleHandlerTest {
    @IsTest
    static void testBehavior() {
        Data_Schedule__c ds = new Data_Schedule__c();
        ds.Frequency__c = 'Monthly';
        ds.Day__c = '5';
        ds.Active__c = true;
        ds.Batch_Size__c = 50;
        insert ds;
    }

    @IsTest
    static void testUpdate() {
        insert new List<WorkType>{
                new WorkType(Name = tracConstants.WORKTYPE_DEALER_STANDARD_INSPECTION,EstimatedDuration = 60)
        };

        Data_Schedule__c ds = new Data_Schedule__c();
        ds.Frequency__c = 'Monthly';
        ds.Day__c = '5';
        ds.Active__c = true;
        ds.Batch_Size__c = 50;
        insert ds;

        ds.Active__c = true;
        ds.Run_Batch__c = true;
        update ds;

        Data_Schedule__c updatedDataSchedule = [SELECT Run_Batch__c FROM Data_Schedule__c WHERE Id = :ds.Id];
        System.assert(updatedDataSchedule.Run_Batch__c, 'Deprecated Flag was reset');
    }

    @IsTest
    static void testUndelete() {
        Data_Schedule__c ds = new Data_Schedule__c();
        ds.Frequency__c = tracConstants.DATA_FREQUENCY_DAILY;
        ds.Active__c = true;
        ds.Batch_Size__c = 50;
        insert ds;

        delete ds;

        undelete ds;
        Data_Schedule__c updatedDataSchedule = [SELECT Id, Active__c FROM Data_Schedule__c WHERE Id = :ds.Id];
        System.assert(!updatedDataSchedule.Active__c);
    }
}