objects/Group__c.object
<CustomObject>
    <label>Organization Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Group_Affiliation__c.object
<CustomObject>
    <description>Junction object between the many to many relationship of the Account and Group objects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Associated Account for this Group Affiliation</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organization Group Affiliations</relationshipLabel>
        <relationshipName>Group_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>Relationship between this junction object and the Group object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Group_Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Affiliation__c</fullName>
        <description>Field used to prevent duplication by concatenating the Ids of the Group and Account associated with this Affiliation</description>
        <label>Unique Affiliation</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Organization Group Affiliation</label>
    <nameField>
        <displayFormat>GA-{00000}</displayFormat>
        <label>Group Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Group Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GroupAffiliationUniqueIdGeneration.cls
public class GroupAffiliationUniqueIdGeneration extends TriggerInterface {

    public override void beforeInsert(List<sObject> objectList) {
    
        List<Group_Affiliation__c> newGrpAff = (List<Group_Affiliation__c>) objectList;

            for ( Group_Affiliation__c newGaf : newGrpAff ) {
                //Upon Creation of GroupAffiliation Record, if unique id is blank then populate it with the unique GroupId_AccountId combination
                if (string.isBlank(newGaf.Unique_Affiliation__c )) {
                        newGaf.Unique_Affiliation__c = newGaf.Group__c + '_' + newGaf.Account__c;
                }

            }
    }
    public override void beforeUpdate(Map<Id, Sobject> oldMap, Map<Id, Sobject> newMap){

        Map<Id, Group_Affiliation__c> newGrpAffMap = (Map<Id, Group_Affiliation__c>)newMap;
        Map<Id, Group_Affiliation__c> oldGrpAffMap = (Map<Id, Group_Affiliation__c>)oldMap;
        
            for ( Group_Affiliation__c newGaf : newGrpAffMap.values() ) {
                //Upon update of GroupAffiliation Record, if unique id is blank OR the Account record has been changed 
                //then "attempt" to populate it with the unique GroupId_AccountId combination
                //This will trigger validation rule 'Cant_Change_Account_Group_Combination'
                if (string.isBlank(newGaf.Unique_Affiliation__c ) || 
                    oldGrpAffMap.get(newGaf.id).Account__c != newGaf.Account__c) {
                        newGaf.Unique_Affiliation__c = newGaf.Group__c + '_' + newGaf.Account__c;
                }
            }
    }
}