objects/maps__ShapeLayer__c.object
<CustomObject>
    <fields>
        <fullName>ACV_Territory_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ACV Territory ID</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Guid__c</fullName>
        <description>Unique guid for this Territory record</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Territory Guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>maps__ShapeLayer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shape Layer</label>
        <referenceTo>maps__ShapeLayer__c</referenceTo>
        <relationshipLabel>Shape Layers</relationshipLabel>
        <relationshipName>ShapeLayers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Maps Shape Layer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maps Shape Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TerritoryGuidGenerationTest.cls
@isTest
public class TerritoryGuidGenerationTest {
    @testSetup
    Static void createTestData(){
        maps__ShapeLayer__c a = new maps__ShapeLayer__c(ACV_Territory_ID__c='1', Name='Test Name');
        insert a;
        maps__ShapeLayer__c a1 = new maps__ShapeLayer__c(ACV_Territory_ID__c='2', Name='Test Name 2');
        insert a1;
    }
    public static testMethod void TestTerrGuidGenerationUponInsert(){
        maps__ShapeLayer__c newTerr = new maps__ShapeLayer__c();
        newTerr = [SELECT ID, ACV_Territory_ID__c, Territory_Guid__c FROM maps__ShapeLayer__c Where ACV_Territory_ID__c = '1'];
        System.assert(newTerr.Territory_Guid__c != null, 'Guid null when it shouldnt be');      
    }
    public static testMethod void TestResolutionGuidGenerationUponUpdate(){
        maps__ShapeLayer__c newTerr = new maps__ShapeLayer__c();
        newTerr = [SELECT ID, ACV_Territory_ID__c, Territory_Guid__c FROM maps__ShapeLayer__c Where ACV_Territory_ID__c = '2'];
        newTerr.Territory_Guid__c = null;
        update newTerr;
        newTerr = [SELECT ID, ACV_Territory_ID__c, Territory_Guid__c FROM maps__ShapeLayer__c Where ACV_Territory_ID__c = '2'];
        System.assert(newTerr.Territory_Guid__c != null, 'Guid null when it shouldnt be');      
    }
    public static testMethod void TestResolutionGuidGenerationDoesNotChange(){
        maps__ShapeLayer__c newTerr = new maps__ShapeLayer__c();
        newTerr = [SELECT ID, ACV_Territory_ID__c, Territory_Guid__c FROM maps__ShapeLayer__c Where ACV_Territory_ID__c = '1'];
        update newTerr;
        maps__ShapeLayer__c newTerr1 = new maps__ShapeLayer__c();
        newTerr1 = [SELECT ID, ACV_Territory_ID__c, Territory_Guid__c FROM maps__ShapeLayer__c Where ACV_Territory_ID__c = '1'];
        System.assert(newTerr.Territory_Guid__c == newTerr1.Territory_Guid__c, 'Guid changed when it shouldnt have');      
    }
}