objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Timeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The revolving appointment that this occurrence appears on</description>
        <label>Revolving Appointment</label>
        <referenceTo>Timeline__c</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timeline__c.object
<CustomObject>
    <description>Object for defining a time period for creating recurring records</description>
    <fields>
        <fullName>Service_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service resource to be assigned to the generated service appointments/work orders</description>
        <label>Service Resource</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Revolving Appointments</relationshipLabel>
        <relationshipName>Revolving_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revolving Appointment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revolving Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Occurrence record from the revolving appointment generator that generated this work order record</description>
        <label>Occurrence</label>
        <referenceTo>Occurrence__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CleanUpExcessRevApptResourcePrefBatch.cls
global class CleanUpExcessRevApptResourcePrefBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start( Database.BatchableContext BC ) {      
        String query = 'SELECT Id, Status,';
        query += ' Occurrence__c, Occurrence__r.Timeline__c, Occurrence__r.Timeline__r.Service_Resource__c,';
        query += '  ( SELECT Id, RelatedRecordId, ServiceResourceId FROM ResourcePreferences )';
        query += ' FROM WorkOrder';
        query += ' WHERE StatusCategory in (\'New\') AND Occurrence__c != null';
        return Database.getQueryLocator( query );
    }

    global void execute(Database.BatchableContext BC, List<WorkOrder> scope) { 
        List<ResourcePreference> deleteRecLst = new List<ResourcePreference>();
        for ( WorkOrder woRec : scope ) {
            if ( woRec.Occurrence__c != null && woRec.Occurrence__r.Timeline__c != null &&  woRec.Occurrence__r.Timeline__r.Service_Resource__c != null ) {
                // If a Service Resource Exists on the Work Order, continue
                for ( ResourcePreference rpRec : woRec.ResourcePreferences ) {
                    if ( rpRec.ServiceResourceId != woRec.Occurrence__r.Timeline__r.Service_Resource__c ) {
                        deleteRecLst.add( rpRec );
                    }
                }
            }
        }

        if ( !deleteRecLst.isEmpty() ) { delete deleteRecLst; }
    }

    global void finish( Database.BatchableContext BC ) {
        // Don't do anything
    }
}