objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Cleanup_Marker__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field becomes checked if fields are changed on this record that would cause incorrect work to be scheduled.</description>
        <inlineHelpText>Read Only field marking if the cleanup batch will pick up this record</inlineHelpText>
        <label>Cleanup Marker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>When Every is 1, select what day of the week for the occurrence</description>
        <label>Day of the Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>weekday</fullName>
                </value>
                <value>
                    <fullName>weekend day</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End time of the occurrence</description>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time of the occurrence</description>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChangedOccurenceRecord.cls
public class ChangedOccurenceRecord extends TriggerInterface {
    // public override void beforeUpdate( Map<Id, SObject> oldMap, Map<Id, SObject> newMap ) {
    //     for ( Occurrence__c occurRec : (List<Occurrence__c>) newMap.values() ) {
    //         Occurrence__c oldOccurRec = (Occurrence__c) oldMap.get( occurRec.Id );
    //         if ( occurRec.Day__c != oldOccurRec.Day__c ||
    //             occurRec.Start_Time__c != oldOccurRec.Start_Time__c ||
    //             occurRec.End_Time__c != oldOccurRec.End_Time__c ) {
    //                 occurRec.Cleanup_Marker__c = TRUE;
    //         }
    //     }
    // }
}