objects/Occurrence__c.object
<CustomObject>
    <description>Defines a repeatable date</description>
    <fields>
        <fullName>Cleanup_Marker__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field becomes checked if fields are changed on this record that would cause incorrect work to be scheduled.</description>
        <inlineHelpText>Read Only field marking if the cleanup batch will pick up this record</inlineHelpText>
        <label>Cleanup Marker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>When Every is 1, select what day of the week for the occurrence</description>
        <label>Day of the Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>weekday</fullName>
                </value>
                <value>
                    <fullName>weekend day</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End time of the occurrence</description>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Every__c</fullName>
        <description>Space between the frequency. Every # frequency.</description>
        <label>Every</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether this Occurrence is still active</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time of the occurrence</description>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <label>Week Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>first</fullName>
                </value>
                <value>
                    <fullName>second</fullName>
                </value>
                <value>
                    <fullName>third</fullName>
                </value>
                <value>
                    <fullName>fourth</fullName>
                </value>
                <value>
                    <fullName>fifth</fullName>
                </value>
                <value>
                    <fullName>last</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>OC-{0000000}</displayFormat>
        <label>Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OccurrenceBatchMarker.cls
public with sharing class OccurrenceBatchMarker extends TriggerInterface{

    // private final static List<String> OCCURRENCE_CLEANUP_FIELDS = new List<String> {'Start_Time__c', 'Day__c', 'End_Time__c', 'Is_Active__c', 'Week_Number__c', 'Every__c'};

    // public override void beforeUpdate(Map<Id, sObject> oldMap, Map<Id, sObject> newMap){
    //     Map<Id, Occurrence__c> oldOccurrences = (Map<Id, Occurrence__c>)oldMap;
    //     Map<Id, Occurrence__c> newOccurrences = (Map<Id, Occurrence__c>)newMap;
    //     markCleanup(newOccurrences, oldOccurrences);
    // }

    // private void markCleanup(Map<Id,Occurrence__c> newOccurrences, Map<Id,Occurrence__c> oldOccurrences){
    //     Occurrence__c oldOcc;

    //     for(Occurrence__c newOcc : newOccurrences.values()){
    //         if(oldOccurrences.get(newOcc.id) != null){
    //             oldOcc = oldOccurrences.get(newOcc.id);

    //             for(String field : OCCURRENCE_CLEANUP_FIELDS){
    //                 if(newOcc.get(field) != oldOcc.get(field)){
    //                         newOcc.Cleanup_Marker__c = true;
    //                         break;
    //                 }
    //             }
    //         }
    //     }
    // }
}