objects/Recommended_Price__c.object
<CustomObject>
    <description>A child object of Vehicles, to be used as a tool for repricing vehicles that have failed an auction.</description>
    <fields>
        <fullName>Pricing_Status__c</fullName>
        <description>Defines whether a Recommended Price is active or expired.</description>
        <label>Pricing Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommended_Price_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox field that gets marked as &apos;True&apos;, when the &quot;Pricing Status&quot; field is set to &apos;Active&apos;. Set via workflow rule.</description>
        <label>Recommended Price Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Recommended Price</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Recommended Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommended Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RecPriceUpdateActive.cls
public without sharing class RecPriceUpdateActive extends TriggerInterface {
    public override void beforeUpdate(List<sObject> oldList, List<sObject> newList) {
        List<Recommended_Price__c> oldRecPrices = (List<Recommended_Price__c>)oldList;
        List<Recommended_Price__c> newRecPrices = (List<Recommended_Price__c>)newList;

        Map<Id, Recommended_Price__c> oldMap = new Map<Id, Recommended_Price__c>();

        for (Recommended_Price__c orp : oldRecPrices) {
            //creating a map
            oldMap.put(orp.Id, orp);
        }

        for (Recommended_Price__c nrp : newRecPrices) {
            if(nrp.Pricing_Status__c == 'Active' && oldMap.get(nrp.Id).Pricing_Status__c == 'Expired') {
                nrp.Recommended_Price_Active__c = true;
            } else if (nrp.Pricing_Status__c == 'Expired' && oldMap.get(nrp.Id).Pricing_Status__c == 'Active') {
                nrp.Recommended_Price_Active__c = false;
            }
        }
    }
}