objects/S3_Reference__c.object
<CustomObject>
    <description>This links a S3 URL with an External Guid (that is generated in Salesforce)</description>
    <fields>
        <fullName>External_Record_Guid__c</fullName>
        <description>This is an external id to link to the MySQL database generated in Salesforce</description>
        <externalId>true</externalId>
        <label>External Record Guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>S3 Reference</label>
    <nameField>
        <label>S3 Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>S3 References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/S3ReferenceTriggerTest.cls
@isTest
public class S3ReferenceTriggerTest {

    @isTest
    static void generateGuidOnInsert(){
    	S3_Reference__c ref = new S3_reference__c(name = 'No Guid');
        insert ref;
        List<S3_reference__c> refLIst = [SELECT id, name, External_Record_Guid__c FROM S3_reference__c WHERE name = 'No Guid'];
        System.assert(refList[0].External_Record_Guid__c != null, 'a guid was not generated for the s3_reference__c');
    }

    @isTest
    static void maintainGuidOnInsert(){
        String guid = ACVUtility.newGuid();
    	S3_Reference__c ref = new S3_reference__c(name = 'No Guid', External_Record_Guid__c = guid);
        insert ref;
       	List<S3_reference__c> refList = [SELECT id, name, External_Record_Guid__c FROM S3_reference__c WHERE External_Record_Guid__c = :guid];
        System.assert(refList.size() > 0, 'Could not find s3_reference_c with correct guid');
    }
}