objects/Salesforce_Setting__mdt.object
<CustomObject>
    <description>This holds small Custom Metadata values that we wish are configurable but are not enough to have its own Custom Metadata Type.</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>value that will be used in Apex or wherever this metadata record is used</description>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>Salesforce Setting</label>
    <pluralLabel>Salesforce Settings</pluralLabel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>External_Record_guid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Record guid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Launch_Term_Details__c</fullName>
        <description>Stores the additional information on the Account&apos;s Vehicle Launch Terms especially when it is set to Future Date/Time, Run List or Other.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provide additional information on the Vehicle Launch Terms especially when it is set to Future Date/Time, Run List or Other.</inlineHelpText>
        <label>Launch Term Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Revolving Term</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle_Launch_Terms__c</fullName>
        <description>Used to capture launch terms as agreed to with the TM/RSD.</description>
        <inlineHelpText>Captures the launch terms as agreed to with the TM/RSD. If Future Date/Time, Run List or Other is selected, please fill in the Launch Term Details</inlineHelpText>
        <label>Vehicle Launch Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>After each vehicle</fullName>
                </value>
                <value>
                    <fullName>End of Visit/After Prescreen</fullName>
                </value>
                <value>
                    <fullName>Future Date/Time</fullName>
                </value>
                <value>
                    <fullName>Run List</fullName>
                </value>
                <value>
                    <fullName>No Reserve</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Add_to_Run_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add to Run List?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Inspected__c</fullName>
        <label>Date Inspected</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dealer_Contact__c</fullName>
        <label>Dealer Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealership_Name__c</fullName>
        <label>Dealership Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Invoice_Id__c</fullName>
        <label>External Invoice Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Record_guid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Record guid</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Floor_Price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Job_Notes__c</fullName>
        <label>Job Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Revolving Term</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reserve_Price__c</fullName>
        <description>A location for the reserve price to be entered by IST for inspectors to use through fsl. This field is required by the assignmentManagerCreateWorkLines code pieces.</description>
        <label>Reserve Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Residential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stock_Number__c</fullName>
        <label>Stock Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Status__c</fullName>
        <label>Title Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_with_Dealer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title with Dealer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transport_Status__c</fullName>
        <label>Transport Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transport Arranged</fullName>
                </value>
                <value>
                    <fullName>Unit Delivered</fullName>
                </value>
                <value>
                    <fullName>Unit in Transit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FSLExpirationBatch.cls
global class FSLExpirationBatch extends SchedulingInterface implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {

    // Query Vars
    final static String TRUEFRAME_METADATA_NAME = 'Trueframe - FSL Expiration Batch Length';
    final static String TRUEFRAME_WORKTYPE_NAME = 'True 360';
    final static Salesforce_Setting__mdt TRUEFRAME_METADATA = [ SELECT Id, Value__c FROM Salesforce_Setting__mdt WHERE Label = :TRUEFRAME_METADATA_NAME LIMIT 1 ];
    final public static WorkType TRUEFRAME_360_WT = [ SELECT Id FROM WorkType WHERE Name = :TRUEFRAME_WORKTYPE_NAME ];
    final static String STATUS_CHECK = 'New';

    // Execute Vars
    final static String EXPIRED_STATUS = 'Expired';

    // Stateful Var for Logging Splunk in Finish Method
    global BatchUtilityClass.BatchReturn returnInfo = new BatchUtilityClass.BatchReturn( FALSE );

    public static DateTime timeNow {
        get {
            if ( timeNow == null ) {
                Integer dateRange = ( Integer.valueOf( TRUEFRAME_METADATA.Value__c ) ) * -1; // negate the value for query
                timeNow = System.now().addDays( dateRange );
            }
            return timeNow;
        }
        set;
    }
    
    global Database.QueryLocator start( Database.BatchableContext BC ) {
        String query;
        try {
            final Id TRUEFRAME_360_WTID = TRUEFRAME_360_WT.Id;
            DateTime currentTime = timeNow;

            query = 'SELECT Id';
            query += ' FROM WorkOrderLineItem';
            query += ' WHERE CreatedDate <= :currentTime AND WorkTypeId = :TRUEFRAME_360_WTID AND Status = :STATUS_CHECK';
        } catch ( exception e ) {
            // Splunk Log
            createErrorLog(e);
        }

        return Database.getQueryLocator( query );
    }

    global void execute( Database.BatchableContext BC, List<sObject> scope ) {
        Set<String> errorStrSet = new Set<String>();

        SavePoint dbSave = Database.setSavePoint();
        Set<Id> scopeIdSet = new Set<Id>();
        for ( SObject scopeRec : scope ) {
            scopeIdSet.add( scopeRec.Id );
        }

        // Get updated fields, as some records might have already been processed in previous methods
        List<WorkOrderLineItem> woliLst = [ SELECT Id, Status, WorkOrderId, WorkOrder.Status 
                                            FROM WorkOrderLineItem WHERE Id IN :scopeIdSet AND Status != :EXPIRED_STATUS 
                                            AND WorkOrder.Status != :EXPIRED_STATUS AND Status = 'New'
                                            AND WorkType.Id = :TRUEFRAME_360_WT.Id AND CreatedDate <= :timeNow ];                                  
        BatchUtilityClass.BatchReturn loggingInfo = new BatchUtilityClass.BatchReturn( FALSE );

        if ( woliLst != null && !woliLst.isEmpty() ) {
            Set<String> successfulSet = new Set<String>();

            Set<Id> woIdSet = new Set<Id>();
            Map<Id, WorkOrder> expiredWOMap = new Map<Id, WorkOrder>();
            for ( WorkOrderLineItem woli : woliLst ) {
                // Status is New, Parent has yet to be processed
                woli.Status = EXPIRED_STATUS;
                
                if ( expiredWOMap.get( woli.WorkOrderId ) == null ) {
                    expiredWOMap.put( 
                        woli.WorkOrderId,
                        new WorkOrder(
                            Id = woli.WorkOrderId,
                            Status = EXPIRED_STATUS
                        )
                    );
                }

                // Add Parent to ferry child records later
                woIdSet.add( woli.WorkOrderId );
            }
            List<Database.UpsertResult> dbResultLst = Database.upsert( woliLst, FALSE );

            Boolean rollbackCheck = FALSE; 
            Set<Id> woCheckIdSet = new Set<Id>();
            for ( Integer index = 0; index < woliLst.size(); index++ ) {
                Database.UpsertResult dbResult = dbResultLst[index];
                WorkOrderLineItem woliRec = woliLst[index];

                if ( dbResult.isSuccess() ) {
                    woCheckIdSet.add( woliRec.WorkOrderId );
                    successfulSet.add( woliRec.Id );
                } else {
                    loggingInfo.errorReturnLst.add( JSON.serialize( woliRec ) );
                    loggingInfo.errorMessageLst.add( dbResult.getErrors()[0].message );
                    rollbackCheck = TRUE;
                }
            }

            dbResultLst = Database.upsert( expiredWOMap.values(), FALSE );
       
            for ( Integer index = 0; index < expiredWOMap.size(); index++ ) {
                Database.UpsertResult dbResult = dbResultLst[index];
                WorkOrder woRec = expiredWOMap.values()[index];

                if ( dbResult.isSuccess() ) {
                    successfulSet.add( woRec.Id );
                } else {
                    loggingInfo.errorReturnLst.add( JSON.serialize( woRec.Id ) );
                    loggingInfo.errorMessageLst.add( dbResult.getErrors()[0].message );
                    rollbackCheck = TRUE;
                }
            }

            if ( rollbackCheck ) {
                Database.rollback( dbSave ); 
            }       

            if ( woCheckIdSet != null && !woCheckIdSet.isEmpty() ) {
                BatchUtilityClass.BatchReturn returnCheck = cloneLineItemsOnExpiredWOs( woCheckIdSet );

                if ( returnCheck.successfulReturnSet.isEmpty() ) {
                    returnCheck.successfulReturnSet = successfulSet;
                }
                loggingInfo.combine( returnCheck );       

                if ( loggingInfo.hasErrors || returnInfo.hasErrors ) {
                    Database.rollback( dbSave );
                }
            } else { // Add Return records from above if we're not calling the clone method
                returnInfo.successfulReturnSet = successfulSet;
            }          

            returnInfo.combine( loggingInfo );                  
        }
    }

    global void finish( Database.BatchableContext BC ) {
        // Splunk Log
        BatchUtilityClass.createBatchLog( 
            returnInfo, BC.getJobId(), 'FSLExpirationBatch', ACVUtility.currentLineNumber(), 
            'FSLExpirationBatch:' + ACVUtility.currentLineNumber(), new Set<String>{ 'WorkOrder', 'WorkOrderLineItem' }
        );
    }

    public override void executeScheduledLogic() {
        FSLExpirationBatch fslEBatch = new FSLExpirationBatch();
        Database.executeBatch( fslEBatch, 200 );
    }

    global static BatchUtilityClass.BatchReturn cloneLineItemsOnExpiredWOs( Set<Id> woIdSet ) {
        BatchUtilityClass.BatchReturn returnInfo = new BatchUtilityClass.BatchReturn( FALSE );

        // These are for error returns
        List<Id> oldWOLst = new List<Id>();
        List<Id> oldWOLILst = new List<Id>();

        if ( woIdSet != null && !woIdSet.isEmpty() ) {

            List<WorkOrderLineItem> woliLst = [ SELECT Id, WorkOrderId, Stock_Number__c, Origin__c, Street, City, State, PostalCode, Country, vin__c, 
                                                year__c, make__c, model__c, color__c, Reserve_Price__c, Title_Status__c, Title_with_Dealer__c, 
                                                Dealer_Contact__c, Residential__c, Add_To_Run_List__c, Floor_Price__c, Date_Inspected__c, WorkTypeId, WorkType.Name, 
                                                External_Record_guid__c, Due_Date__c, Status, Transport_Status__c, Job_Notes__c, Dealership_Name__c, Earliest_Start_Date__c, External_Invoice_Id__c
                                                FROM WorkOrderLineItem WHERE WorkOrderId IN :woIdSet AND Status = :STATUS_CHECK ];
            // Organize Results
            Map<Id, List<WorkOrderLineItem>> woToLineItemMap = new Map<Id, List<WorkOrderLineItem>>();
            for ( WorkOrderLineItem woli : woliLst ) {
                if ( woToLineItemMap.get( woli.WorkOrderId ) == null ) {
                    woToLineItemMap.put( woli.WorkOrderId, new List<WorkOrderLineItem>() );
                }
                woToLineItemMap.get( woli.WorkOrderId ).add( woli );
            }       

            List<WorkOrder> woRecLst = [ SELECT Id, AccountId, ServiceTerritoryId, Priority, WorkTypeId, Origin__c, Duration, 
                                        DurationType, Street, City, PostalCode, State, Country, Subject, Description, 
                                        Launch_Term_Details__c, Vehicle_Launch_Terms__c
                                        FROM WorkOrder WHERE Id IN :woToLineItemMap.keyset() ];
            // Make new Work Order first, then make line items for each
            List<WorkOrder> clonedWOLst = new List<WorkOrder>();
            for ( WorkOrder woRec : woRecLst ) {
                WorkOrder newWORec = woRec.clone( FALSE, TRUE, TRUE, FALSE );
                oldWOLst.add( woRec.Id );
                clonedWOLst.add( newWORec );
            }

            List<Database.SaveResult> dbResultLst = Database.insert( clonedWOLst, FALSE );   
            Map<Id, Id> expiredWOIdMap = new Map<Id, Id>();
            for ( Integer index = 0; index < clonedWOLst.size(); index++ ) {
                // clonedWOLst is made one to one from woRecLst, so order is guaranteed
                Database.SaveResult dbResult = dbResultLst[index];
                WorkOrder clonedWO = clonedWOLst[index];
                WorkOrder expiredWO = woRecLst[index];

                if ( dbResult.isSuccess() ) {
                    expiredWOIdMap.put( expiredWO.Id, clonedWO.Id );
                } else { 
                    // Add for Error Logging in Splunk
                    returnInfo.hasErrors = TRUE;
                    returnInfo.errorReturnLst.add( JSON.serialize( clonedWOLst[index] ) );
                    returnInfo.errorMessageLst.add( dbResult.getErrors()[0].getMessage() );
                }
            }

            if ( expiredWOIdMap != null && !expiredWOIdMap.isEmpty() ) {
                List<WorkOrderLineItem> clonedWOLILst = new List<WorkOrderLineItem>();
                List<WorkOrderLineItem> deleteWOLILst = new List<WorkOrderLineItem>();

                for ( Id expiredWOId : woToLineItemMap.keyset() ) {
                    if ( expiredWOIdMap.get( expiredWOId ) != null ) {
                        Id newClonedWoId = expiredWOIdMap.get( expiredWOId );
                        // Clone Line Item                 
                        for ( WorkOrderLineItem woliToClone : woToLineItemMap.get( expiredWOId ) ) {
                            WorkOrderLineItem clonedWOLI = woliToClone.clone( FALSE, TRUE, TRUE, FALSE );
                            clonedWOLI.WorkOrderId = newClonedWoId;
                            clonedWOLILst.add( clonedWOLI );

                            oldWOLILst.add( woliToClone.Id );
                            
                            deleteWOLILst.add( woliToClone );
                        }
                    }
                }           

                // Get rid of dupes
                try {
                    delete deleteWOLILst;
                } catch ( exception e ) {
                    returnInfo.hasErrors = TRUE;
                    createErrorLog( e );
                }

                List<Database.SaveResult> dbResultLst2 = Database.insert( clonedWOLILst, FALSE );             

                Set<String> returnWOLIIdSet = new Set<String>();
                for ( Integer index = 0; index < clonedWOLILst.size(); index++ ) {
                    // clonedWOLst is made one to one from woRecLst, so order is guaranteed
                    Database.SaveResult dbResult = dbResultLst2[index];
                    WorkOrderLineItem clonedWOLI = clonedWOLILst[index];
    
                    if ( dbResult.isSuccess() ) {
                        returnWOLIIdSet.add( clonedWOLI.Id );
                    } else { 
                        // Add for Error Logging in Splunk
                        returnInfo.hasErrors = TRUE;
                        returnInfo.errorReturnLst.add( JSON.serialize( clonedWOLILst[index] ) );
                        returnInfo.errorMessageLst.add( dbResult.getErrors()[0].getMessage() );
                    }
                }

                returnInfo.successfulReturnSet = returnWOLIIdSet;
            }
        }

        return returnInfo;
    }

    global static void createErrorLog( Exception e ) {
        SplunkHelper.Log infoLog = new SplunkHelper.Log();
        infoLog.version = 'v1'; // We don't have versions yet
        infoLog.logLevel = SplunkHelper.LOGLEVEL.ERROR;
        infoLog.location = 'FSLExpirationBatch:' + e.getLineNumber();
        infoLog.message = e.getMessage();
        infoLog.stackTrace = e.getStackTraceString();
        infoLog.sfRecordId = UserInfo.getUserId();
        infoLog.componentName = 'FSLExpirationBatch';
        infoLog.sfObject = 'WorkOrder, WorkOrderLineItem';
        infoLog.domainSet = new Set<SplunkHelper.DOMAIN>{ SplunkHelper.DOMAIN.SALES };
        
        SplunkHelper.buildandProcessLog( infoLog );
    }
}