objects/Salesforce_Setting__mdt.object
<CustomObject>
    <description>This holds small Custom Metadata values that we wish are configurable but are not enough to have its own Custom Metadata Type.</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>value that will be used in Apex or wherever this metadata record is used</description>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>Salesforce Setting</label>
    <pluralLabel>Salesforce Settings</pluralLabel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Inspection_Number_of_Vehicles__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used to capture the number of vehicles to be inspected while on-site.  Populated in advance if known and/or updated by VCI on-site (for Standard Inspection, Sirius XM, and True 360).</description>
        <inlineHelpText>Populated in advance if known - to be validated by VCI on-site.  Should be updated when Work Order Line Items are added/deleted (for Standard Inspection, Sirius XM, and True 360).</inlineHelpText>
        <label>Inspection - Number of Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateServiceAppointment.cls
public class CreateServiceAppointment extends TriggerInterface {
    
    public static boolean skipAppointmentCreation = FALSE;
    private final static String saStatus = 'New';
    private static Integer dateRange {
        get { 
            if ( dateRange == null ) {
                for ( Salesforce_Setting__mdt rec : [ SELECT Value__c FROM Salesforce_Setting__mdt WHERE DeveloperName = 'Default_Service_Appointment_Range' LIMIT 1 ] ) {
                    dateRange = Integer.valueOf( rec.Value__c );
                }
            }
            return dateRange;
        }
        set;
    } 

    public override void afterInsert( Map<Id, SObject> newMap ) {
        if ( !CreateServiceAppointment.skipAppointmentCreation ) {
            List<ServiceAppointment> createSALst = new List<ServiceAppointment>();

            DateTime currentDT = DateTime.now();
            for ( WorkOrder woRec : [ SELECT Id, WorkTypeId, Inspection_Number_Of_Vehicles__c, ServiceTerritoryId, AccountId, Duration, DurationType, Account.Name, OwnerId, Subject, Description, Street, City, PostalCode, State, Country FROM WorkOrder WHERE Id IN :newMap.keySet() FOR REFERENCE ] ) {
                createSALst.add( 
                    ServiceAppointmentUtility.createAppointmentFromWorkOrder( woRec, saStatus, currentDT, currentDT.addDays( dateRange ) )
                );
            }
            insert createSALst;
        }
    }
}