objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Cannot_Complete_Reason__c</fullName>
        <description>Picklist for selection why a service appointment is being given a status of &apos;Cannot Complete&apos;</description>
        <label>Cannot Complete Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insufficient time to complete</fullName>
                </value>
                <value>
                    <fullName>Dealer Uncooperative</fullName>
                </value>
                <value>
                    <fullName>Safety Hazard</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Auction uncooperative</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Contact not available</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - In service or body shop</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Incorrect contact listed</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Moved to another location</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Unable to locate keys</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Unable to locate vehicle</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Unit sold</fullName>
                </value>
                <value>
                    <fullName>Dry Run Auction  - Vehicle will not start</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Contact not available</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Dealer uncooperative</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Incorrect contact listed</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Moved to another location</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Unable to locate vehicle</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Unit sold</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer  - Vehicle will not start</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer -Unable to access vehicle at storage facility</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- In service or body shop</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- No start/ No jump</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- Purchasing</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- Unable to locate keys</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- Vehicle moved to auto auction</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- Vehicle not at location</fullName>
                </value>
                <value>
                    <fullName>Dry Run Dealer- Vehicle not at storage location</fullName>
                </value>
                <value>
                    <fullName>Dry Run Home  - Address incomplete/incorrect</fullName>
                </value>
                <value>
                    <fullName>Dry Run Home  - Lessee not available</fullName>
                </value>
                <value>
                    <fullName>Dry Run Home  - No answer to calls</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dry_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dry Run</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Pinned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pinned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <description>Work Type Unique ID for the Work Order linked to this Service Appointment.</description>
        <formula>Work_Order__r.WorkType.Work_Type_Unique_ID__c</formula>
        <label>Work Type Unique ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>Work_Type_Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Work Type Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DryRunFromServiceAppointmentCtlrTest.cls
/**
 * @description       : Test class for DryRunFromServiceAppointmentController
 * @author            : v-dchaves@acvauctions.com
 * @group             : Scheduling
 * @last modified on  : 05-13-2022
 * @last modified by  : v-dchaves@acvauctions.com
**/
@IsTest
public with sharing class DryRunFromServiceAppointmentCtlrTest {
    @TestSetup
    static Void makeData(){
        FSLTestUtility.createAllStructureWithParentST( 'Buffalo', '14209' );
        Account acc = TestUtility.createAccount();
        insert acc;

        WorkType dealerWorkType = [SELECT Id, EstimatedDuration, DurationType FROM WorkType WHERE Work_Type_Unique_ID__c = 'dealer'];

        WorkOrder workOrder = new WorkOrder(AccountId = acc.Id,
                                            ServiceTerritoryId = [ SELECT Id FROM ServiceTerritory LIMIT 1 ].Id,
                                            WorkTypeId = dealerWorkType.Id,
                                            Status = 'New',
                                            Priority = 'Low');
        insert workOrder;

        ServiceAppointment serviceAppointment = new ServiceAppointment(DueDate = system.today().addDays(21),
                                                                       FSL__Pinned__c = false,
                                                                       Subject = workOrder.Subject,
                                                                       Work_Order__c = workOrder.Id,
                                                                       ParentRecordId = workOrder.Id,
                                                                       Status = 'Dispatched',
                                                                       ServiceTerritoryId = [ SELECT Id FROM ServiceTerritory LIMIT 1 ].Id,
                                                                       EarliestStartTime = DateTime.now().addDays(-25),
                                                                       SchedStartTime = DateTime.now().addDays(1),
                                                                       SchedEndTime = DateTime.now().addHours(25),
                                                                       Dry_Run__c = false,
                                                                       Cannot_Complete_Reason__c = 'Other',
                                                                       ActualStartTime = DateTime.now().addDays(1),
                                                                       ActualEndTime = DateTime.now().addDays(1).addHours(2));
        insert serviceAppointment;

        FSL.GlobalAPIS.addStatusTransition('Dispatched', 'Completed');
    }

    @IsTest
    public static Void generalTest(){
        ServiceAppointment serviceAppointment = [SELECT Id FROM ServiceAppointment LIMIT 1];

        // test getServiceAppointment method
        String jsonResponse = DryRunFromServiceAppointmentController.getServiceAppointment(serviceAppointment.Id);

        Map<String, String> response = (Map<String, String>) JSON.deserialize(jsonResponse, Map<String, String>.class);
        System.assertEquals(response.get('Status'), 'SUCCESS', 'Status: ' + response.get('Status'));

        DryRunFromServiceAppointmentController.ServiceAppointmentWrapper wrapperObj = (DryRunFromServiceAppointmentController.ServiceAppointmentWrapper) JSON.deserialize(response.get('Record'), DryRunFromServiceAppointmentController.ServiceAppointmentWrapper.class);
        System.assertEquals(wrapperObj.recordId, serviceAppointment.Id);
        System.assertEquals(wrapperObj.dryRun, false);
        System.assertEquals(wrapperObj.cannotCompleteReason, 'Other');

        // test markAsDryRun method
        wrapperObj.cannotCompleteReason = 'Insufficient time to complete';
        jsonResponse = DryRunFromServiceAppointmentController.markAsDryRun(JSON.serialize(wrapperObj));

        serviceAppointment = [SELECT Id, Dry_Run__c, Cannot_Complete_Reason__c, Status, Work_Order__r.Status FROM ServiceAppointment WHERE Id = :wrapperObj.recordId];
        System.assertEquals(serviceAppointment.Dry_Run__c, true);
        System.assertEquals(serviceAppointment.Cannot_Complete_Reason__c, 'Insufficient time to complete');
        System.assertEquals(serviceAppointment.Status, 'Completed');
        System.assertEquals(serviceAppointment.Work_Order__r.Status, 'Completed');
    }

    @IsTest
    public static Void errorTest(){
        String jsonResponse = DryRunFromServiceAppointmentController.getServiceAppointment('NOT_AN_ID');

        Map<String, String> response = (Map<String, String>) JSON.deserialize(jsonResponse, Map<String, String>.class);
        System.assertEquals(response.get('Status'), 'ERROR', 'Status: ' + response.get('Status'));

        jsonResponse = DryRunFromServiceAppointmentController.markAsDryRun('NOT_A_JSON');
        
        response = (Map<String, String>) JSON.deserialize(jsonResponse, Map<String, String>.class);
        System.assertEquals(response.get('Status'), 'ERROR', 'Status: ' + response.get('Status'));
    }
}