objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceAppointmentAccountLookup.cls
public class ServiceAppointmentAccountLookup extends TriggerInterface {
    public override void beforeInsert(List<SObject> newMap) {
        List<ServiceAppointment> saList = (List<ServiceAppointment>)newMap;
        Set<Id> woSet = new SEt<Id>();
        for (ServiceAppointment sa : saList){
            if(sa.ParentRecordId != null){
                woSet.add(sa.ParentRecordId);
            }
        }

        Map<Id, WorkOrder> woMap = new Map<Id, WorkOrder>([SELECT AccountId FROM WorkORder WHERE id in :woSEt]);
        for(ServiceAppointment sa : saList){
            if(sa.AccountId != null){
                sa.Account__c = sa.AccountId;
            }
            else if (sa.Work_Order__r.AccountId != null){
                sa.Account__c = sa.Work_Order__r.AccountId;
            }
            else if (sa.ParentRecordId != null && woMap.get(sa.ParentRecordId) != null && woMap.get(sa.ParentRecordId).AccountID != null){
                sa.Account__c = woMap.get(sa.ParentRecordId).AccountId;
            }
        }
        
    }
}