objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FSL__GanttLabel__c</fullName>
        <label>Gantt Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Inspection_Number_of_Vehicles__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used to capture the number of vehicles to be inspected while on-site.  Populated in advance if known and/or updated by VCI on-site (for Standard Inspection, Sirius XM, and True 360).</description>
        <inlineHelpText>Populated in advance if known - to be validated by VCI on-site.  Should be updated when Work Order Line Items are added/deleted (for Standard Inspection, Sirius XM, and True 360).</inlineHelpText>
        <label>Inspection - Number of Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceAppointmentUtility.cls
public class ServiceAppointmentUtility {

    public static ServiceAppointment createAppointmentFromWorkOrder( WorkOrder woRec, String status, DateTime startDT, DateTime dueDT ) {
        return createAppointmentFromWorkOrder( woRec, status, startDT, dueDT, new Map<String,ServiceAppointment>() );
    }

    public static ServiceAppointment createAppointmentFromWorkOrder( WorkOrder woRec, String status, DateTime startDT, DateTime dueDT, Map<String,ServiceAppointment> saOverrideMap ) {

        ServiceAppointment sa = new ServiceAppointment();

        sa.ServiceTerritoryId = woRec?.ServiceTerritoryId;
        sa.ParentRecordId = woRec?.Id;
        sa.Work_Order__c = woRec?.Id;
        sa.Status = status;
        //Account__c = woRec.AccountId;
        sa.EarliestStartTime = startDT;
        sa.DueDate = dueDT;
        sa.Duration = FSLWorkProcessUtility.getNumberOfMinutes( woRec.WorkTypeId, woRec.Inspection_Number_of_Vehicles__c != null ? Integer.valueOf( woRec.Inspection_Number_of_Vehicles__c ) : null );
        sa.DurationType = woRec?.DurationType;
        sa.FSL__GanttLabel__c = woRec?.Account?.Name;
        sa.OwnerId = woRec?.OwnerId?.getSObjectType() == Schema.User.SObjectType ? woRec?.OwnerId : UserInfo.getUserId();
        sa.Subject = woRec?.Subject;
        sa.Description = woRec?.Description;
        sa.Street = woRec?.Street;
        sa.City = woRec?.City;
        sa.PostalCode = woRec?.PostalCode;
        sa.State = woRec?.State;
        sa.Country = woRec?.Country;


        if( saOverrideMap.containsKey( woRec.Service_Appt_Map_Id__c ) ){
            Map<String, Object> values = saOverrideMap.get( woRec.Service_Appt_Map_Id__c ).getPopulatedFieldsAsMap();
            for(String fieldName : values.keySet() ){
                sa.put(fieldName,values.get(fieldName));
            }
        }
        return sa;
    }
}